### ISSUE TITLE
https://www.lootlinks.xyz

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#100]
### Domain

https://www.lootlinks.xyz

### Link

https://www.lootlinks.xyz/D9ZQ

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
![image](https://user-images.githubusercontent.com/81463636/134613027-ec78d153-8543-461c-bae8-cd6f0d37c356.png)
