### ISSUE TITLE
Chrome deletes fastforward on its own

### ISSUE THREAD

**Issue by AviJamal** [FastForwardTeam/FastForward#1000]
### Body

as said above the browser remove the extension on its own what to do

### Version

 0.2224

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

no

**Comment by ghost** [comment]
It shouldn't, if you're deleting the folder where FastForward is held, you're going to delete the extension; Chrome checks whether the folder is there every time it boots up, so if you delete the folder, the extension goes.
