### ISSUE TITLE
Bypass not working in https://egao.in/ 

### ISSUE THREAD

**Issue by harudrive** [FastForwardTeam/FastForward#1002]
### Domain

https://doroni.me/anime/aktivitas-dewa-di-dunia-tanpa-dewa/episode-8

### Link

https://egao.in/?id=eyJpdiI6IlJYR2kxNmFvNDZIQXdwejUxQkk1YWc9PSIsInZhbHVlIjoiTEw1ZXo0dk9pc1Z1Nlp0YUxyZEtiQT09IiwibWFjIjoiYTk4MzMyOGYyMmZlOTFiY2ZkOGJiMjE5MzYwMzRmM2UwZmM1MjM4OGZhZTg3OTJiNzZiOTI0MzZiNWNmNmZjYSIsInRhZyI6IiJ9

### Version

0.0.8

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

they added hCaptcha

![image](https://github.com/FastForwardTeam/FastForward/assets/95627509/afc474a3-8980-40f4-8fa8-126fe9beec80)

**Comment by ghost** [comment]
We cannot skip hCaptcha, you will have to manually do it yourself.
