### ISSUE TITLE
https://terabox.fun/ Broken Bypass

### ISSUE THREAD

**Issue by dzayeate** [FastForwardTeam/FastForward#1004]
### Domain

https://terabox.fun/

### Link

https://terabox.fun/sl/2njYb3ciP7

### Version

 0.2256

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/50524722/19cc7c04-8b43-4b2d-a82e-aa2689926548)

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.

**Comment by chayleaf** [comment]
could this be reopened now?
