### ISSUE TITLE
Fc-lc.com

### ISSUE THREAD

**Issue by vjrmy** [FastForwardTeam/FastForward#1005]
### Domain

https://fc-lc.com

### Link

https://fc-lc.com/TeXoB

### Version

0.2249

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

i dont know this is broken bypass or this url maybe not include in fastforward. Please fix it or add it to rules.

**Comment by 0xc60f** [comment]
Fixed in the Mv3 version.
