### ISSUE TITLE
Need to reinstall everytime to use on Edge

### ISSUE THREAD

**Issue by Grohax** [FastForwardTeam/FastForward#1008]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/126134/wingssims/1

### Version

Version 0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

The plugin simply doesn't do anything. I need to go to the store, uninstall and install it again in order to work. When I reinstall, it works perfectly. It happens everytime I close the browser.

**Comment by eks28** [comment]
Same here Needs to be fixed

**Comment by Mordius** [comment]
Same problem here, I've noticed when you go to extension config page it's stuck in "Downloading bypass definitions"

![image](https://github.com/FastForwardTeam/FastForward/assets/48067152/27ef25ab-19be-4948-9e1d-ec19a155a046)

**Comment by N4than007** [comment]
Same here

**Comment by Strat00s** [comment]
I am not the only one 🙌
I also have the "downloading bypass definitions" problem

**Comment by ghost** [comment]
Make sure you follow the instructions exactly on [our installation page](https://fastforward.team/instructions).
