### ISSUE TITLE
FastForward not working

### ISSUE THREAD

**Issue by nickogaldame97** [FastForwardTeam/FastForward#1009]
### Body

A day ago the program worked perfectly and now that I use it again it stopped working.
It doesn't even give me the reports that the page cannot be skipped

### Version

0.2256

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

.

**Comment by vivek-kumar-poddar** [comment]
Yup... works 100% on Firefox and even on Brave. On Google Chrome, however, it just doesn't work. To make it work, I have to remove and reinstall the extension EVERYTIME I open the browser. YES EVERYTIME!

**Comment by Xcczs** [comment]
For me it doesn't even work on brave

**Comment by ghost** [comment]
Make sure you follow the instructions exactly on [our installation page](https://fastforward.team/instructions).

**Comment by Xcczs** [comment]
bruh we're not that dumb, the extension just doesn't work
