### ISSUE TITLE
Bypass does not work on Linkperisi.com

### ISSUE THREAD

**Issue by gulsoy83** [FastForwardTeam/FastForward#1013]
### Domain

https://linkperisi.com

### Link

https://linkperisi.com/go/5zwee1

### Version

0.2237

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/46426033/e063af37-5b0a-41ab-b7ab-2bb90698bb80)

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.
