### ISSUE TITLE
Bypass does not work on https://www.tonanmedia.my.id/

### ISSUE THREAD

**Issue by harudrive** [FastForwardTeam/FastForward#1018]
### Domain

https://extonan.id/mashle-episode-10/

### Link

https://www.tonanmedia.my.id/2023/06/novel-visual-dari-aniplex-atri-my-dear.html#?o=a9cd467778cdf081ca8833d7fc54f751c0a8131214d5fb043892f0fc74bf12b10c30af9ed7606054b436663a218f82eb93bc59bebd90e24199774107407d07d9eadd6bb016ece92de809c000b590eb384444296334470528b3228854bac181513698e88eb9e6c4f0efe55804ff81ae8b7da5d994f4bc3688

### Version

0.0.8

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/95627509/6671dd89-c3ce-4bb5-a5d1-55f5af26df9f)

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.
