### ISSUE TITLE
Linkvertise detecting ublock origin and bypass not working

### ISSUE THREAD

**Issue by john482847573** [FastForwardTeam/FastForward#1020]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/157244/auhm-v3418?o=sharing

### Version

Version 0.2237 · Development Mode

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/92234562/8d9e933c-06ef-4fb8-acf5-850eb3c1d23f)

**Comment by ghost** [comment]
This is a uBlock problem, try updating your filters.
