### ISSUE TITLE
Add-on is being removed every time Chrome is closed

### ISSUE THREAD

**Issue by dmitriy1980** [FastForwardTeam/FastForward#1021]
### Body

I install the extension in Chrome based on instructions specified at https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#chromium-based-browsers-chrome-kiwi-opera-opera-gx-vivaldi-brave-etc. Specifically download zip file and then import in the Extensions area of Chrome. However, it appears I can no longer see the this specific extension after I re-open Chrome.

### Version

0.2262

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

N/A

**Comment by mooms06** [comment]
Chrome is very bad anyway, use Vivaldi or Firefox.

**Comment by dmitriy1980** [comment]
Thanks for a reply. Any relevant response to an issue at hand?

**Comment by mooms06** [comment]
Yes, it was already answered, see the closed issues.
