### ISSUE TITLE
The Extension download link did not work

### ISSUE THREAD

**Issue by furkan-izgi** [FastForwardTeam/FastForward#1022]
### Body

Hello, your manually download link is not working:

https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/FastForward_chromium.zip

### Version

Lastest

### What browsers are you seeing the problem on?

Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/76229401/24f9f733-da96-459e-8907-0adca03034f9)

**Comment by ghost** [comment]
It's back up now, but nightly isn't the most reliable so we will fork our own instance.
