### ISSUE TITLE
non stop DOWNLOADING BYPASS DEFINITIONS...

### ISSUE THREAD

**Issue by kyawzinthet** [FastForwardTeam/FastForward#1024]
### Body

Bypassing stopped and auto updating sometimes

can be fixed that error by 

> Reloading fastforward.zip and
> Extensions Update 

![Screenshot_2023-06-22-19-06-52-380_com kiwibrowser browser-edit](https://github.com/FastForwardTeam/FastForward/assets/78093225/f8a6bec3-5b18-40c2-84a4-c4a6c9d06ed3)

### Version

Version 0.2262

### What browsers are you seeing the problem on?

Other

### What OS are you seeing the problem on?

Android

### Anything else?

![Screenshot_2023-06-22-19-03-06-135_com kiwibrowser browser-edit](https://github.com/FastForwardTeam/FastForward/assets/78093225/5f3d6d4f-347b-4d35-ad9a-02cc5aab6b12)

**Comment by Strat00s** [comment]
same here on edge

**Comment by InfinityCg** [comment]
Same issue, it does not download the definitions and just stays on "Downloading bypass definitions"

**Comment by viveksh1** [comment]
Same on Vivaldi (chromium based)

**Comment by DineshSolanki** [comment]
check https://github.com/FastForwardTeam/FastForward/releases/tag/0.2237 , it won't be fixed for these releases.

**Comment by dhana-exe** [comment]
somehow i had the solution....
on me... i download the lastest file

and extract it until the last zip files

my zip file name is FastForward_chromium_0.2268.zip
and all i do is drag and drop it to extension page...

and works....
now if you not delete that files... all times you open browser the extension will be working fine....
