### ISSUE TITLE
Google Bard - Black Page Issue

### ISSUE THREAD

**Issue by L0garithmic** [FastForwardTeam/FastForward#1025]
### Domain

https://bard.google.com/

### Link

https://bard.google.com/

### Version

0.2237

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Bard becomes a black page with a white border. This is not functional as I use bard frequently.

**Comment by panckreous** [comment]
same on macos. the screen is all white for me, but I'm assuming that's just system or app light vs dark modes.

**Comment by sylvesterroos** [comment]
Same here on Linux. White screen on light mode, black screen with white border on dark mode.

**Comment by ZeroCool22** [comment]
Same here, it totally broke bard.google.com

https://github.com/FastForwardTeam/FastForward/assets/13344308/93eec1f4-e03d-4c88-b120-55d146c7ec0d

Some ETA for the fix?
It's really annoying....

**Comment by dmitriy1980** [comment]
@ZeroCool22 I noticed you have an older version. I tried on my side and it was working correctly. Try getting a newer version that's been available for a while.

**Comment by ZeroCool22** [comment]
> @ZeroCool22 I noticed you have an older version. I tried on my side and it was working correctly. Try getting a newer version that's been available for a while.

When i click the button to search for updates, it tell me i'm on the last one: **Versión 0.2039 · Definiciones de evasión 1f41318**

I must install it manually?

**Comment by ZeroCool22** [comment]
> @ZeroCool22 I noticed you have an older version. I tried on my side and it was working correctly. Try getting a newer version that's been available for a while.

![Screenshot_2](https://github.com/FastForwardTeam/FastForward/assets/13344308/4f026a9b-446b-4e58-bd85-f14448b8bc45)

Just installed the last one, still same problem.

**Comment by dmitriy1980** [comment]
I'm on 0.2262

**Comment by CRiS-SVRS** [comment]
can't install that version on firefox stable

**Comment by ZeroCool22** [comment]
> can't install that version on firefox stable

Pfff...

**Comment by ZeroCool22** [comment]
> I'm on 0.2262

And how the hell i get that version for firefox stable?

**Comment by CRiS-SVRS** [comment]
following this 
https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#firefox-based-browsers-firefox-waterfox-pale-moon-librewolf-etc
only on nightly or developer versions of firefox

**Comment by jed84** [comment]
> @ZeroCool22 I noticed you have an older version. I tried on my side and it was working correctly. Try getting a newer version that's been available for a while.

Still broken on 0.2237

**Comment by ghost** [comment]
This will be fixed in the Mv3 extension as you can whitelist sites.

**Comment by ZeroCool22** [comment]
> This will be fixed in the Mv3 extension as you can whitelist sites.

And when we can expect that version to comes out?

**Comment by ghost** [comment]
> > This will be fixed in the Mv3 extension as you can whitelist sites.
> 
> And when we can expect that version to comes out?

It'll be published in a couple of weeks as the extension is done, but we're just cleaning up code. After that, it's in Google and Mozilla's court.
