### ISSUE TITLE
FastForward on LibreWolf not saving custom bypasses

### ISSUE THREAD

**Issue by YTG1234** [FastForwardTeam/FastForward#1030]
### Body

Custom bypasses are not saved at all, not even during the session.

Steps to replicate:
1. Open the extension settings
2. Write a custom bypass
3. Observe that it doesn't work
4. Refresh the page / close and reopen the extension settings
5. Observe that the bypass is gone

My first thought was that this must be a LibreWolf issue, what with all of its security measures. Other extensions, however, can save their settings perfectly fine; this is unique to FastForward.

### Version

0.2237

### What browsers are you seeing the problem on?

Other

### What OS are you seeing the problem on?

MacOS

### Anything else?

https://github.com/FastForwardTeam/FastForward/assets/54103478/ec0e5ca6-0ba7-459c-aaf6-e085d8b8d312

(Screen recorder didn't record the extension popup)

**Comment by AppleMangoOrange** [comment]
Same for me on Firefox, running POP!_OS. This is a big issue considering it doesn't work with most websites that Universal Bypass did.

**Comment by ghost** [comment]
@princessmortix think you could help? I remember one of the devs (possibly you?) mentioning how to fix this.

**Comment by lostdusty** [comment]
No, I don't, but the user should unfocus from the text input, and wait at least 1s for it to be saved.
