### ISSUE TITLE
https://mediafile.cc not working

### ISSUE THREAD

**Issue by itsdaffxter** [FastForwardTeam/FastForward#1031]
### Domain

https://mediafile.cc

### Link

https://mediafile.cc

### Version

Version 0.2237

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/105346673/13187373-0765-4202-b88d-54f2627f0e0e)

**Comment by DineshSolanki** [comment]
please provide a testlink

**Comment by sokkycakes** [comment]
I can leave a link:
https://mediafile.cc/2312211ae98ae661
