### ISSUE TITLE
PlayPaste

### ISSUE THREAD

**Issue by Crosus97** [FastForwardTeam/FastForward#1032]
### Domain

https://playpaste.com/

### Link

https://playpaste.com/pivi/?v=jU

### Version

0.2262

### What browsers are you seeing the problem on?

Chrome, Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

https://pivigames.blog/project-zomboid-ultima-version-online-hamachi-tunngle/

This is the root of the links

**Comment by DineshSolanki** [comment]
what is there to bypass, there's only 1 captcha
