### ISSUE TITLE
Can't bypass https://web1s.info

### ISSUE THREAD

**Issue by hotboylong1234** [FastForwardTeam/FastForward#1034]
### Domain

https://web1s.info/

### Link

https://web1s.info/S2wKBJJMhN/ (NSFW)

### Version

0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/51923264/ed091ee8-cc20-475d-b769-cf718a8b16cd)

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.

**Comment by mastercho** [comment]
> We are not accepting new bypasses now, check #656 for more details.

Does still not accepting new bypasses? As these links with web1s are pretty annoying
