### ISSUE TITLE
Elsticsearch doesn't load when the extension is enabled

### ISSUE THREAD

**Issue by Nezz** [FastForwardTeam/FastForward#1036]
### Body

This was already reported in #669 but was not reproduced.

Reproduction steps:
1. Open https://demo.elastic.co/app/dashboards#/view/welcome_dashboard
2. Reject cookie banner. If you see only a blurred picture then the cookie banner is blocked by a content blocker that you should disable.

I believe this is caused by the strict content security policy that the website tries to enforce.

### Version

0.2237

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/431167/b2f289fd-e235-43e8-8c34-388132b90afb)

**Comment by ghost** [comment]
You'll be able to whitelist sites in our Mv3 extension, which will be submitted to web stores in the next 2 weeks. That should fix this error.
