### ISSUE TITLE
broken bypass

### ISSUE THREAD

**Issue by ExGuestCJ** [FastForwardTeam/FastForward#1037]
### Domain

filecrypt.co

### Link

https://filecrypt.co/Container/920AF807FB.html

### Version

 0.2262 

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

None

### Anything else?

i wanted to download final fantasy 7

**Comment by ghost** [comment]
We are not accepting new bypasses now, check #656 for more details.
