### ISSUE TITLE
LinkVertise Not Working

### ISSUE THREAD

**Issue by DarkDreamEXIST** [FastForwardTeam/FastForward#1039]
### Domain

linkvertise.com

### Link

https://linkvertise.com/152666/fluxus-windows-check-1/1

### Version

0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

When I go to fastforward site it says Downloading bypass definitions... and doesn't download

**Comment by ghost** [comment]
Known issue, we are working on a fix.
