### ISSUE TITLE
https://pingit.im

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#104]
### Domain

https://pingit.im

### Link

https://pingit.im/4Sewd

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
This one would be really annoying without the extension

~~Should work~~ @kammychan has a better solution below
```
domainBypass("noweconomy.live", () => {
    ensureDomLoaded(() => {
        ifElement("a#surl1", a => {
		safelyNavigate(a.href)
        })
		ifElement("button.btn-main.get-link", b => {
		b.click()
		
    })
})
})
```

**Comment by kammychan** [comment]
Below one is working too

```
domainBypass("noweconomy.live",()=>{
	ifElement("form",form=>form.submit())
	ifElement("#surl1",a=>a.click())
})
```

Fixed formatting -@NotAProton

**Comment by NotAProton** [comment]
@kammychan Could you make a PR?
