### ISSUE TITLE
FastForward

### ISSUE THREAD

**Issue by ErkanGuner** [FastForwardTeam/FastForward#1040]
### Body

Kısa link siteleri için yapılan bir uzantı ama hem Edge hem de Chrome uygulamasında çalışmıyor. Mylink adlı kısa link sitesini geçemiyorum. BYPASS TANIMLARI İNDİRİLİYOR şeklinde uyarı çıkıyor.
![ScreenHunter_8](https://github.com/FastForwardTeam/FastForward/assets/127676143/ec7d69dd-d999-444f-ae7b-c70e2be1adb7)

### Version

0.2262

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![ScreenHunter_8](https://github.com/FastForwardTeam/FastForward/assets/127676143/695dd254-467a-49de-8d8c-0dfbb57b5b04)

**Comment by DogancanYr** [comment]
Bu ekran açıkken kapat tarayıcıyı sonra bu ekrana tekrar gel ve 3-4 kez tekrar et .

**Comment by ghost** [comment]
[Kurulum sayfamızdaki](https://fastforward.team/instructions) yönergeleri tam olarak izlediğinizden emin olun.
Kötü çeviri için üzgünüm, Türkçe bilmiyorum ama İngilizce bilmediğinize saygı duymak istedim.
