### ISSUE TITLE
Bluemediafile

### ISSUE THREAD

**Issue by Darkasus999** [FastForwardTeam/FastForward#1041]
### Domain

https://bluemediafile.sbs/

### Link

https://bluemediafile.sbs/url-generator-1.php?url=SDUS9bRvhba8BF9dQAj5cgIzeg4+4r9hpGtYJn0s4Kwtvb6uOzeLgbYwfW9y0s5afDD5E0lCVLwSMo4Ub9c9/6OkLKOdprACYqHFSdDReqQ

### Version

0.2268 412fdd8

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Bluemediafile.com was renamed to Bluemediafile.sbs and probably works a bit differently.

**Comment by ghost** [comment]
I've been trying to work on this, but Mv3 security is blocking the bypass that worked fine on Mv2, so I'll need to come up with a workaround.
