### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by Ketarmin** [FastForwardTeam/FastForward#1042]
### Body

The linked Discord link is invalid, i unfortunately cant join your discord

### Version

latest

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

None

### Anything else?

The linked Discord link is invalid, i unfortunately cant join your discord

**Comment by ghost** [comment]
Link worked for me, try again or use Server Discovery in Discord to join the server.
