### ISSUE TITLE
not working after restart browser

### ISSUE THREAD

**Issue by dhana-exe** [FastForwardTeam/FastForward#1044]
### Body

Hello anyone... well the addons didn't works like what i think on my browser and laptop
can someone help me?

issue is
when i extract all files to the folder like the tutorial
all works fine 
UNTIL
i close the browser and re open it
when i reopen it... all addons works but the system (bypassing) didn't

earlier the addons is works but after somehow restart the browser they didn't
any solution for this?

### Version

lastest

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/29838157/51efd42c-7157-4de8-b57c-56fa01399742)

**Comment by dhana-exe** [comment]
yeah somehow this is works and not works
idk what happen

**Comment by dhana-exe** [comment]
now i should drag and drop the addons on chrome to make it works when i turn on my laptop

**Comment by ghost** [comment]
Make sure you follow the instructions exactly on [our installation page](https://fastforward.team/instructions).

**Comment by dhana-exe** [comment]
i already do that.... thats why i reporting it to here.....
on my laptop they not works after restarting or after i turn on the laptop again

**Comment by AliahX** [comment]
This is the stuck on downloading bypass definition glitch. we have a fix for it on our [discord server](https://discord.com/invite/RSAf7b5njt)

[https://discord.com/channels/876622516607656006/885806363064827924/1134376414712442911](https://discord.com/channels/876622516607656006/885806363064827924/1134376414712442911)

**Comment by dhana-exe** [comment]
> This is the stuck on downloading bypass definition glitch. we have a fix for it on our [discord server](https://discord.com/invite/RSAf7b5njt)

yeeep thanks for this....
