### ISSUE TITLE
FastForward Randomly Installing (NOT INSTALLED PREVIOUSLY AT ALL)

### ISSUE THREAD

**Issue by XM0ni** [FastForwardTeam/FastForward#1049]
### Body

I just woke up today and saw that fastforward was installed on my browser. I did not install fastforward at ANY point in the past, I never even knew about it until I got the window popup when I woke up

### Version

MV3

### What browsers are you seeing the problem on?

Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/141153087/01f7c574-3bfd-4501-95ca-4830c66fc346)
![image](https://github.com/FastForwardTeam/FastForward/assets/141153087/22b627b3-3ac0-4fc4-916d-b725c53fca83)
![image](https://github.com/FastForwardTeam/FastForward/assets/141153087/0cd515f9-fa73-4bc9-a580-6e848af92123)
Occurred between 12 AM to 9 AM EST

**Comment by gabrielmdu** [comment]
The same happened to me a few minutes ago. Windows 11 and Chrome.

**Comment by mannin1337** [comment]
same with me, went out to eat and when I got back it was installed
is this caused by a virus?
