### ISSUE TITLE
https://dutchycorp.ovh

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#105]
### Domain

https://dutchycorp.ovh

### Link

https://dutchycorp.ovh/sl/DmtIL8Om

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://dutchycorp.space/sl/MOnhlcs1
https://dutchycorp.space/sh/1WYEdTE8
https://dutchycorp.space/sh/MhrePrz
https://dutchycorp.ovh/sh/8WqnnHG6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Done, the second link in the chain needs crowd bypass tho
```
domainBypass("dutchycorp.space", () => {
    ensureDomLoaded(() => {
        ifElement("div#cl1", d => {
		safelyNavigate(d.getElementsByTagName("a")[0].href)
    })
})
})
```

**Comment by NotAProton** [comment]
Fixed, thanks for the report
