### ISSUE TITLE
Linkvertise isnt working

### ISSUE THREAD

**Issue by HimeSpider** [FastForwardTeam/FastForward#1050]
### Domain

Linkvertise.com

### Link

https://linkvertise.com/253297/4632/dynamic?link_origin=adfly&r=aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tLz9idzM2bnRpOXd4OXQ5aDk%3D&o=sharing

### Version

0.2262

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I have tried it multiple times. It worked at first. But the last couple of times I opened it it didn't load it at all

**Comment by lostdusty** [comment]
Duplicate of #963.
