### ISSUE TITLE
Not working on this website

### ISSUE THREAD

**Issue by thuypoi** [FastForwardTeam/FastForward#1055]
### Domain

https://mneylink.com/

### Link

https://mneylink.com/

### Version

Version 0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

edge

**Comment by SleepingPig35** [comment]
Could you please give an example link? Thanks.

**Comment by thuypoi** [comment]
IS Here
https://mneylink.com/lSHlAw
pls
