### ISSUE TITLE
https://1shortlink.com/

### ISSUE THREAD

**Issue by baidu01gc** [FastForwardTeam/FastForward#1057]
### Domain

https://1shortlink.com/

### Link

https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9qYXZnZy5tZS8xc2p1cy8=&type=2

### Version

Version 0.2279-Mv3

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

it was able to bypass before this new version

**Comment by ghost** [comment]
I probably haven't gotten around to making a Mv3 bypass for this, I'll add it ASAP. Keep in mind that even when I finish, it'll be absent for a couple of weeks as I'm trying to push around 30-40 new bypasses with every update to the web stores.
