### ISSUE TITLE
No description of options

### ISSUE THREAD

**Issue by rugabunda** [FastForwardTeam/FastForward#1059]
### Body

Ridiculous 

![image](https://github.com/FastForwardTeam/FastForward/assets/38260267/46763fcd-abf2-4158-afa0-9476cb846d11)

### Version

not sure

### What browsers are you seeing the problem on?

Other

### What OS are you seeing the problem on?

Other

### Anything else?

What do these options do? there is no explanation that I can find anywhere; should be in the wiki; please consider explaining them; like what is 'the destination of a tracker'? and why is it disabled by default

**Comment by NotAProton** [comment]
Destination of a tracker is the website it leads to like if clicking on t.co/xyz takes you to google.com then google.com is the destination of the tracker. By default the extension shows a preview of the link you are about to be redirected to, if you don't want that then check the "Instantly take me to the destination..." option

**Comment by rugabunda** [comment]
Thank you NotAProton. Is apimon.de a proxy for untangling redirects? 

And does blocking ip loggers if they can't be bypassed break the bypass altogether?

**Comment by NotAProton** [comment]
apimon.de is now discontinued (see #784)

Yes, blocking IP loggers blocks sites like https://grabify.link completely.

**Comment by rugabunda** [comment]
Thank you.
