### ISSUE TITLE
https://sl.mcmfaucets.xyz

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#106]
### Domain

https://sl.mcmfaucets.xyz

### Link

https://sl.mcmfaucets.xyz/short/2WLAZvit

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Fixed, thanks for the report
