### ISSUE TITLE
linkvertise not working in new version

### ISSUE THREAD

**Issue by ElMakis** [FastForwardTeam/FastForward#1061]
### Domain

https://linkvertise.com

### Link

https://linkvertise.com/887199/zf8/1

### Version

0.2279-Mv3

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge, Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

linkvertise not working in new version

**Comment by NotAProton** [comment]
This is intentional.

**Comment by Unknown78** [comment]
@NotAProton On this manifest v3, where is the "Custom bypasses" box to add the linkvertise bypass manually as per instruction in [INSTALLING.MD](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md)?

**Comment by NotAProton** [comment]
Google's MV3 guidelines prohibit the extension from running any code that is not packed with the extension so we had to remove that feature.

**Comment by Unknown78** [comment]
@NotAProton Is there an easy way for end user to modify the extension to add the custom bypass? Load unpacked MV3 perhaps?

**Comment by NotAProton** [comment]
That's a good idea, I'll open an issue for that. For now you can stick to mv2 version.
