### ISSUE TITLE
https://marocclickers.xyz

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#107]
### Domain

https://marocclickers.xyz

### Link

https://marocclickers.xyz/page1-html/#/Xh0ASjnm

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Where are you even getting so many from??

**Comment by oq1u7o5f14** [comment]
Hello, Mr.NotAProton.
I apologize for sending you so many requests at once.
I've been compiling a list of which sites I can't bypass for some time now, and this is the number I've received.
I'm not very good at English, so I apologize if this is not correct.

**Comment by NotAProton** [comment]
Nah, no need to apologize.
By all means, please continue submitting this list of yours.
>I'm not very good at English, so I apologize if this is not correct.

nevermind English is not my first language as well
