### ISSUE TITLE
works before update, Not working anymore

### ISSUE THREAD

**Issue by CocoKKH** [FastForwardTeam/FastForward#1071]
### Domain

https://www.wts.pw

### Link

https://www.wts.pw/full/?api=c459ca2d2ff7da18fec24ab01fb49d529ca0dc99&url=aHR0cHM6Ly9sLmhzdi5teS5pZC8xMTovW0xFTkRSSVZFXSUyMFRlbXBsZSUyMC0lMjAwNiUyMFsxMDgwcCUyMEhFVkNdW0R1YWxzdWJzXS5ta3Y=&type=2

### Version

0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

works before update, Not working anymore...

**Comment by Asrum** [comment]
> ### Domain
> https://www.wts.pw
> 
> ### Link
> https://www.wts.pw/full/?api=c459ca2d2ff7da18fec24ab01fb49d529ca0dc99&url=aHR0cHM6Ly9sLmhzdi5teS5pZC8xMTovW0xFTkRSSVZFXSUyMFRlbXBsZSUyMC0lMjAwNiUyMFsxMDgwcCUyMEhFVkNdW0R1YWxzdWJzXS5ta3Y=&type=2
> 
> ### Version
> 0.2279-Mv3
> 
> ### What browsers are you seeing the problem on?
> Microsoft Edge
> 
> ### What OS are you seeing the problem on?
> Windows
> 
> ### Anything else?
> works before update, Not working anymore...
