### ISSUE TITLE
add linkperisi.com

### ISSUE THREAD

**Issue by therabug** [FastForwardTeam/FastForward#1073]
### Domain

https://linkperisi.com

### Link

https://linkperisi.com/go/bgslb4

### Version

0.2277

### What browsers are you seeing the problem on?

Other

### What OS are you seeing the problem on?

Android

### Anything else?

pls add linkperisi.com

**Comment by uurcan7** [comment]
0.2279-Mv3 
msedge and kiwi same

**Comment by Asrum** [comment]
> ### Domain
> https://linkperisi.com
> 
> ### Link
> https://linkperisi.com/go/bgslb4
> 
> ### Version
> 0.2277
> 
> ### What browsers are you seeing the problem on?
> Other
> 
> ### What OS are you seeing the problem on?
> Android
> 
> ### Anything else?
> pls add linkperisi.com

Ok!
Fate me stands, ALL rigth chartenm Tanks.

**Comment by Sertinel** [comment]
Hit. System is not working.
