### ISSUE TITLE
FastForward not working at all in Chrome

### ISSUE THREAD

**Issue by Blurge16** [FastForwardTeam/FastForward#1074]
### Domain

https://nude-leaks24.com/

### Link

https://nude-leaks24.com/s?cK5l;NSFW

### Version

0.2279-Mv3

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

These folllowing domains don't work either:
locconnect.com
linkvertise.com
locconn.com
![FastForward](https://github.com/FastForwardTeam/FastForward/assets/23457641/584dc75b-3450-4d8b-8caf-43e9250967d3)

**Comment by driedpampas** [comment]
the firefox mv3 version instantly sent me to a pastelink.net which I believe is the target

**Comment by lostdusty** [comment]
Duplicate of #963.
