### ISSUE TITLE
[request] blitly.io

### ISSUE THREAD

**Issue by QuangLocIsME** [FastForwardTeam/FastForward#1075]
### Domain

blitly.io

### Link

blitly.io

### Version

lastest verison ( google web store )

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

not workking !

**Comment by lostdusty** [comment]
We need an example link.

**Comment by toyboatcash** [comment]
> We need an example link.

hi i did not post this but found some links from https://urlscan.io/domain/blitly.io https://blitly.io/OeH1J_K and [blitly.io/Obsfivj] and blitly.io/OOCTROh
