### ISSUE TITLE
FastForward is no longer bypassing, linkvertise.com

### ISSUE THREAD

**Issue by FerGarrix** [FastForwardTeam/FastForward#1077]
### Domain

https://linkvertise.com

### Link

https://linkvertise.com//253297/7840/dynamic?link_origin=adfly&r=aHR0cDovL3d3dy5saW5rYnVja3MuY29tL2xqUmM%3D&o=sharing

### Version

Versión 0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/142575047/3b96afa1-3330-4489-8466-0ea27bb86c3b)

**Comment by lostdusty** [comment]
Duplicate of #963.
