### ISSUE TITLE
up-4ever.net website not bypass

### ISSUE THREAD

**Issue by Crukk11** [FastForwardTeam/FastForward#1080]
### Domain

https://www.up-4ever.net/

### Link

https://www.up-4ever.net/yux5f8pjpmtt

### Version

 0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/64012867/de1f31bd-cd7a-4dbe-ac36-1b0a7a37d9f5)
it not bypass countdown

**Comment by FoxVukOff** [comment]
Oh...
