### ISSUE TITLE
[request] megawarez.org

### ISSUE THREAD

**Issue by walismar** [FastForwardTeam/FastForward#1081]
### Domain

https://www.megawarez.org/el-adobe-photoshop-cc-ultima-version-descargar/

### Link

https://yogablogfit.com/yoga-for-a-healthy-checkup-3-poses-to-help-you-prepare-for-preventive-health-checkup/

### Version

13.15.2

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

This website shares movies, programs, etc. In the first step one must wait a while to give me the button to download, to give me opens a window with another button and instructions, to click it opens a page with gogle and a search, we must open the page that tell us, wait a while and click on advertising, then it gives me the link to the shortener, but are shorteners in quotes, to display advertising, but without many who use, before if I jumped but had the generic as they now have these custom I stay in the infinite loop ... Is it possible to skip them? or how could I do to add each one to the list and help.

**Comment by lostdusty** [comment]
Could you give us a screen recording of the issue?

**Comment by lostdusty** [comment]
Duplicate of #930.
