### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FerGarrix** [FastForwardTeam/FastForward#1082]
### Domain

https://wordcounter.icu

### Link

https://wordcounter.icu/erHk4

### Version

Versión 0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/142575047/be2a89be-2b2c-4939-9533-73a68f3fbf8f)

**Comment by lostdusty** [comment]
There is no error. You need to manually bypass this website, so others can bypass it too (as read on the pop-up). This happens because the website uses crowdbypass.

Also is this really FastForward?

**Comment by undeadjess** [comment]
you seem to be using something called Streamus ByPasser. this is not made by us, but is based off Fastforwards code. we would be more than happy to help you if you [installed the official version of Fastforward](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md)
