### ISSUE TITLE
Not Bypass

### ISSUE THREAD

**Issue by jagiex212** [FastForwardTeam/FastForward#1083]
### Domain

https://enit.in

### Link

https://enit.in/i4X4JoVba

### Version

Version 0.2279-Mv3

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/142865940/119e13c0-b368-448b-af97-ed2d9fd905a7)

**Comment by lostdusty** [comment]
There is no error. You need to manually bypass this website, so others can bypass it too (as read on the pop-up). This happens because the website uses crowdbypass.

Also is this really FastForward?
