### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FerGarrix** [FastForwardTeam/FastForward#1085]
### Domain

https://oko.sh

### Link

https://oko.sh/NaufragoHD1080p

### Version

Versión 0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/142575047/73cc98ed-cde0-4050-bde3-47a05789cf13)

**Comment by lostdusty** [comment]
There is no error. You need to manually bypass this website, so others can bypass it too (as read on the pop-up). This happens because the website uses crowdbypass.

Also is this really FastForward?
