### ISSUE TITLE
Random webpage opening

### ISSUE THREAD

**Issue by streetlegithub** [FastForwardTeam/FastForward#1088]
### Body

Around 20% of the time when I close edge the page to edit settings for the extension pops up. Very annoying

### Version

0.2279-Mv3

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/88948099/3604d5d5-cdaa-4d55-8d33-ddf8dfc13daf)

**Comment by NotAProton** [comment]
It's probably related to this https://github.com/FastForwardTeam/FastForward/pull/921/files#diff-25daee2bd4a749c171c5bd0b87567f3fe306a1fdacb2a6d6785a3e1e6fd065f9R15 
I'll investigate

**Comment by rlnt** [comment]
Yeah, it's really annoying that it happens every time. Not only that page but for me, it's also opening the "Welcome" and "Thanks for installing" page whenever I open Edge.

**Comment by DSGriff** [comment]
Just thought I'd add, the same thing happens on Chrome as well.

**Comment by NotAProton** [comment]
fixed by https://github.com/FastForwardTeam/FastForward/commit/03ffd999705f477e3296749878d17731746c792e
