### ISSUE TITLE
Settings, Custom Bypass don't save

### ISSUE THREAD

**Issue by aChr0me** [FastForwardTeam/FastForward#1089]
### Body

I'm using the Mullvad Browser. Basically a mix of Firefox and TOR if I understand correctly.

The issue seems to be persistent and isn't solved by different methods of installation, etc.

The crowd bypass button doesn't want to check, as the check simply disappears after a refresh.

Same goes for anything in the Custom Bypass Field, and the second delays for the default options.

### Version

0.2237

### What browsers are you seeing the problem on?

Other

### What OS are you seeing the problem on?

Windows

### Anything else?

The fields that I have talked about: 

Take me to destinations after second(s).
Crowd Bypass
Open crowd-sourced destinations in a new tab after second(s).
Close tab containing the crowd-sourced destination after second(s) of visiting it.

Custom Bypasses

**Comment by lostdusty** [comment]
We don't support custom bypasses anymore since the MV3 version is out.
