### ISSUE TITLE
https://clickscoin.com

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#109]
### Domain

https://clickscoin.com

### Link

https://clickscoin.com/short/w61rD

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Done.
```
domainBypass(/clickscoin\.com|dogeclick\.net/, () => {
	ensureDomLoaded(() => {
	awaitElement("button#mdt", a => {
		a.click()
	})
})
})

```

smaller:

`domainBypass(/clickscoin\.com|dogeclick\.net/, () => awaitElement("button#mdt", a => a.click()))`

**Comment by NotAProton** [comment]
Fixed, thanks for the report
