### ISSUE TITLE
add 1short.info

### ISSUE THREAD

**Issue by MasterStupid** [FastForwardTeam/FastForward#1091]
### Domain

1short.info

### Link

1short.info

### Version

0.2279-Mv3

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I want to bypass this link

**Comment by Asrum** [comment]
> ### Domain
> 1short.info
> 
> ### Link
> 1short.info
> 
> ### Version
> 0.2279-Mv3
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### What OS are you seeing the problem on?
> Windows
> 
> ### Anything else?
> I want to bypass this link
