### ISSUE TITLE
Config page pops up every time Edge updates

### ISSUE THREAD

**Issue by AkazaRenn** [FastForwardTeam/FastForward#1099]
### Body

This page: extension://ldcclmkclhomnpcnccgbgleikchbnecl/html/options.html, version 0.2279, installed from Edge Extension store: https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by NotAProton** [comment]
Duplicate of #1088
