### ISSUE TITLE
Bard is still not working on firefox

### ISSUE THREAD

**Issue by MauroAce** [FastForwardTeam/FastForward#1102]
### Domain

bard.google.com

### Link

https://bard.google.com/?hl=es_419

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

I know there was a pull before but its still not working :(
![imagen](https://github.com/FastForwardTeam/FastForward/assets/89175228/98e724a7-e1c7-4cbc-8ebc-0131084483a5)
it just loads like that, i have the extension on edge and it loads normally.

**Comment by lostdusty** [comment]
Are you using the MV3 extension?

**Comment by MauroAce** [comment]
no, im not
i only have this extensions, when i disable the ad block it still doesn't work
![imagen](https://github.com/FastForwardTeam/FastForward/assets/89175228/51808f2b-8d20-4bf6-be80-357947e30177)

**Comment by undeadjess** [comment]
could you please try turning all of them off except Fastforward using the switches in the Firefox extension manager, then try again?

**Comment by AndusDEV** [comment]
I can confirm it's FastForward's fault. I have the same problem

**Comment by driedpampas** [comment]
Same issue with Firefox 117.0.1 on Fedora 38, extension v0.2237

**Comment by driedpampas** [comment]
This problem is still present in the MV3 version (and might impact ChatGPT as well)

**Comment by Cohinem** [comment]
I also have this problem.

**Comment by driedpampas** [comment]
Apparently it actually works in the MV3 version, I had a version I used for testing MV3 installed and Bard loads just fine.

**Comment by lostdusty** [comment]
![image](https://github.com/FastForwardTeam/FastForward/assets/47502554/23d4dad7-f3d6-4560-bc9f-6ef4a5c241f8)

Just confirmed: Bard works on MV3
