### ISSUE TITLE
filedm and linkvertise doesnt work

### ISSUE THREAD

**Issue by Stanislavuu** [FastForwardTeam/FastForward#1105]
### Domain

https://filedm.com/

### Link

https://filedm.com/Ijn6h

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by driedpampas** [comment]
I know linkvertise is not in the chrome version, it's the reason it was removed from the chrome web store.
>Q: Can I manually setup the Linkvertise bypass?
>A: Yes! Go to the Fastforward settings, look for "Custom Bypass" and [paste this code snippet](https://raw.githubusercontent.com/FastForwardTeam/FastForward/main/src/linkvertise.js) on the end of the box.

**Comment by driedpampas** [comment]
Also, that filedm link has nothing to bypass it's just a download button for a program (definitely malware will scan it with virustotal)
![image](https://github.com/FastForwardTeam/FastForward/assets/76390419/0a80745c-fe6f-48dd-b35a-5d8981a900df)

**Comment by JeanTheFungle** [comment]
how do i skip ?

**Comment by lostdusty** [comment]
Couldn't reproduce this issue, and about linkvertise we already know about it.
