### ISSUE TITLE
fx-22

### ISSUE THREAD

**Issue by MohamedAliClai** [FastForwardTeam/FastForward#1109]
### Link

https://fx-22.com/5-tips-for-choosing-the-right-brokerage-account-in-2023/

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
From where did you get redirected to this website, because I don't think it has anything to do with bypassing link shorteners.

**Comment by lostdusty** [comment]
This seems to be a link protector (used in pirated websites for indexing pirated videos or similar), I'd like to know where did you get this link from, so we can look futher on this issue.
