### ISSUE TITLE
https://pentafaucet.com/

### ISSUE THREAD

**Issue by jadreas** [FastForwardTeam/FastForward#111]
### Domain

https://pentafaucet.com/

### Link

https://pentafaucet.com/f/GTWOo2SkEZ

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://pentafaucet.com/f/GTWOo2SkEZ

https://pentafaucet.com/f/r5-aE6yQOB

https://pentafaucet.com/s/yjMlGRuSyl

https://pentafaucet.com/f/eVzIUGC1WH

https://pentafaucet.com/f/mfid-HvbPi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
![image](https://user-images.githubusercontent.com/81463636/134612931-bffe2e1c-e314-41cf-843f-d0186b735fd2.png)

**Comment by reashetyrr** [comment]
i get a 404 on all links
