### ISSUE TITLE
[New bypass] mneylink.com

### ISSUE THREAD

**Issue by SinestreaOwO** [FastForwardTeam/FastForward#1110]
### Link

https://mneylink.com/ROOOTFULL14T9

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
To get the whole picture I'm trying to do what they say to see how they generate the code, but I can't even access that social(.)bet website
![image](https://github.com/FastForwardTeam/FastForward/assets/76390419/91b93486-9c0f-48b9-8a19-1b127812c5e0)
