### ISSUE TITLE
[Bug] Failed to load extension

### ISSUE THREAD

**Issue by SasanSistan** [FastForwardTeam/FastForward#1114]
### Body

Hello. This warning is given in the Chrome browser during installation. What is the problem?

![Untitled](https://github.com/FastForwardTeam/FastForward/assets/93873747/1a64c63f-6303-469c-b679-530a93975288)

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
download the chromium package, unzip it twice and load it as unpacked see if it still errors

[package-githubactions](https://github.com/driedpampas/FastForward-Firefox/actions/runs/6240439129)

**Comment by SasanSistan** [comment]
I did it, it gives the same warning

**Comment by SasanSistan** [comment]
> download the chromium package, unzip it twice and load it as unpacked see if it still errors
> 
> [package-githubactions](https://github.com/driedpampas/FastForward-Firefox/actions/runs/6240439129)

tnx.

**Comment by driedpampas** [comment]
if it worked close the issue and wait for pr #1108 to be merged

**Comment by lostdusty** [comment]
You can also install it from the CWS.

Looks like this was solved.
