### ISSUE TITLE
https://getitall.top/

### ISSUE THREAD

**Issue by jadreas** [FastForwardTeam/FastForward#112]
### Domain

https://getitall.top/

### Link

https://getitall.top/f/BAPmCTcrFQ

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://getitall.top/f/BAPmCTcrFQ

https://getitall.top/f/EaL6LOU_qe

https://getitall.top/f/kpDf6nxaWf

https://getitall.top/f/WYwTWHdakG

https://getitall.top/f/JOuRCyuO37

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
thi is kinda sketchy... when you click the button then next it queries: https://sl.lindernman.xyz/s/next
