### ISSUE TITLE
Work.ink

### ISSUE THREAD

**Issue by DogancanYr** [FastForwardTeam/FastForward#1124]
### Link

https://work.ink/1QUd/lmvaukj0

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

Nothing is happening .

![image](https://github.com/FastForwardTeam/FastForward/assets/90002969/a65beb78-a33c-44c4-8dab-667671192b17)

**Comment by lostdusty** [comment]
Duplicate of #967.
