### ISSUE TITLE
clictune.com bypass not working

### ISSUE THREAD

**Issue by grandpa1946** [FastForwardTeam/FastForward#1127]
### Link

https://www.dlink2.net/ix7b

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by escape0707** [comment]
Still able to reproduce.

**Comment by driedpampas** [comment]
it was fixed in #1169 so you'll have to wait for the ext to be updated in the store or you can grab the chromium package from the latest pr and load it unpacked (and don't forget to ONLY have ONE FastForward installed)

**Comment by escape0707** [comment]
Thanks for the reply! Then I assume this issue can be closed.

**Comment by driedpampas** [comment]
of course! if you want to, go ahead and close it

**Comment by escape0707** [comment]
Well, I'm not the author of this issue. I'm but merely a subscriber XD.

**Comment by grandpa1946** [comment]
> it was fixed in #1169 so you'll have to wait for the ext to be updated in the store or you can grab the chromium package from the latest pr and load it unpacked (and don't forget to ONLY have ONE FastForward installed)

alright!
