### ISSUE TITLE
https://hitbits.io/

### ISSUE THREAD

**Issue by jadreas** [FastForwardTeam/FastForward#113]
### Domain

https://hitbits.io/

### Link

https://hitbits.io/slk/f/KSMJspPUik

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://hitbits.io/slk/f/KSMJspPUik

https://hitbits.io/slk/f/_pNMqGIOMn

https://hitbits.io/slk/f/4UY1gd_oOO

https://hitbits.io/slk/f/d6ddAzniXD

https://hitbits.io/slk/f/yqXjjN4v1C

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Looks like it'll need crowdbypass
