### ISSUE TITLE
No bypasses working anymore

### ISSUE THREAD

**Issue by BrightDarknessXX** [FastForwardTeam/FastForward#1135]
Version: 0.2310
Latest update: September 30, 2023
Firefox Version: 118.0.1 x64

No bypasses are working anymore. It seems to do absolutely nothing anymore.

**Comment by BrightDarknessXX** [comment]
I disabled all plug-ins and extensions, still not working.

**Comment by driedpampas** [comment]
#1130

**Comment by undeadjess** [comment]
we are aware of issues in the latest Firefox version, please see #1130
