### ISSUE TITLE
https://bstlar.com

### ISSUE THREAD

**Issue by Domm5** [FastForwardTeam/FastForward#1136]
### Link

https://bstlar.com

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
please update the issue to include a link as an example, not just the domain.tld

**Comment by ItsProfessional** [comment]
why does this dumb stale bot even exist? just because not many people are interested in this issue, doesn't mean that it's no longer an issue.

**Comment by 0xliam627** [comment]
Dear @Domm5,
> Your problem has been solved! https://github.com/FastForwardTeam/FastForward/commit/89fb43ce12718b3d83edb0eb5abec4c683c16925
