### ISSUE TITLE
[Bug] KNOWN ISSUE, WINDOWS DEFENDER FALSE POSITIVE

### ISSUE THREAD

**Issue by BlackWolfWoof** [FastForwardTeam/FastForward#1138]
# Update:
Windows defender no longer triggers on it 01.10.2023 10:37 Europe/Berlin

### Body

As mentioned by the developer on [Discord](https://discord.gg/RSAf7b5njt), this seems to be a false positive. It is being investigated now.
Just leaving this here so if whoever looks for an answer of why windows defender triggered knows what happened. Stay patient in the mean time and maybe check discord for any statements or updates from the developer 👍
*Jess is the developer*
![image](https://github.com/FastForwardTeam/FastForward/assets/29355595/3334c6b8-0d02-4b43-9c43-645123ba8f67)

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by AliahX** [comment]
Heres a virustotal link of the fastforward extension file right after I downloaded it from the webstore. https://www.virustotal.com/gui/file/47f55b85df67bd317bc3d85f0d676e6e8b011b3c90262d9e651458ac9b9e9a7a
Just in case anyone was worried that it wasn't a false positive

**Comment by LoboRundas** [comment]
Hello, this happened to me at first, glad to know it was a false positive. Thing is, I restarted my PC after windows defender asked me to, reinstalled the extension, and then it prompted me again, but about a "Phonzy.b!ml" trojan instead (but the action windows defender took was, again deleting Fast Forward). Might it be that Windows Defender mistook the two, or do I have a bigger problem on my hands?

**Comment by lostdusty** [comment]
![Screenshot_2023-09-30-08-42-28-898_com android chrome-edit](https://github.com/FastForwardTeam/FastForward/assets/47502554/93320d16-67ef-42d7-a790-def574274581)
I've submitted the extension to WDSI as a false positive, hopefully they will fix this soon :)

**Comment by stefanorossiti** [comment]
same for me, just now

![image](https://github.com/FastForwardTeam/FastForward/assets/25284995/abdd6081-2fe3-43ac-bad3-a2c441224d9f)

https://www.virustotal.com/gui/file/a7fb4d988fcb568428918536ed62ee703f93373c41d3438c48e8d729190e0adc

**Comment by ghost** [comment]
Wasn't able to recreate this false positive with Firefox Developer Edition, but was able to recreate the false positive in a VM. Possibly something in Dev. Edition doesn't cause this false flag?

**Comment by stefanorossiti** [comment]
> Wasn't able to recreate this false positive with Firefox Developer Edition, but was able to recreate the false positive in a VM. Possibly something in Dev. Edition doesn't cause this false flag?

I have this problem in dev edition.
My laptop doesn't seems to care tho, similar setup, win 11, firefox dev edition + account synch on extensions.

**Comment by thakyZ** [comment]
I had this problem in Waterfox. Now 13 hours later I noticed the plugin got re-added, and now Windows Defender doesn't care. Even manually scanned the whole `%USERPROFILE%/AppData` folder, the Temp folder (for updates) and the profiles folder of Waterfox.

**Comment by lostdusty** [comment]
Microsoft removed it! If anyone still have this issue, please run this 3 commands, using an elevated cmd:
1. `cd c:\Program Files\Windows Defender`
2. `MpCmdRun.exe -removedefinitions -dynamicsignatures`
3. `MpCmdRun.exe -SignatureUpdate`
