### ISSUE TITLE
sub2unlock.com not working in MV3

### ISSUE THREAD

**Issue by vlOd2** [FastForwardTeam/FastForward#1150]
### Link

https://sub2unlock.com/mQHKF

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

[The example link](https://sub2unlock.com/mQHKF) from https://fastforward.team/example-links (page found in the FAQ) isn't bypassed correctly.

You have to actually click on "Subscribe" and "Like" and then click unlock twice to get to the destination

**Comment by driedpampas** [comment]
@vlOd2 please enable this permission
![Screenshot from 2023-10-05 13-51-41](https://github.com/FastForwardTeam/FastForward/assets/76390419/09dabc11-db42-4681-af55-1a480d0c0810)
