### ISSUE TITLE
Darkibox

### ISSUE THREAD

**Issue by Bubucho** [FastForwardTeam/FastForward#1151]
### Link

https://darkibox.com/vam1e5e8yo1hz.html

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
![image](https://github.com/FastForwardTeam/FastForward/assets/76390419/83218273-9a79-4e9e-bfa1-73cf7730e8e3)
