### ISSUE TITLE
Can you please bypass this website? "https://ouo.io/"

### ISSUE THREAD

**Issue by advthankyou** [FastForwardTeam/FastForward#1152]
ouo.io used to be bypassed previously but since a few days it's not being bypassed.

**Comment by driedpampas** [comment]
It seems to work for me I just have to press the "I'm a human" button.
What browser are you using?

**Comment by advthankyou** [comment]
firefox

**Comment by driedpampas** [comment]
@advthankyou please enable this permission
![Screenshot from 2023-10-05 13-51-41](https://github.com/FastForwardTeam/FastForward/assets/76390419/09dabc11-db42-4681-af55-1a480d0c0810)

**Comment by advthankyou** [comment]
![image](https://github.com/FastForwardTeam/FastForward/assets/147034291/a022b9d7-ecef-4139-a2d0-31b5a7c459fc)
thank you and are these setting okay?

**Comment by driedpampas** [comment]
yes (and it's instant if it's 0 seconds :sparkles: ), although you might want to change crowd-sourced destinations settings if you go over this :arrow_down: 
![image](https://github.com/FastForwardTeam/FastForward/assets/76390419/d9bcd7be-d16a-46c8-851f-0497347f9a64)

**Comment by advthankyou** [comment]
thanks for the help!

**Comment by driedpampas** [comment]
of course! (and if there's no more questions you can close the issue :smiley: )
