### ISSUE TITLE
ouo.io is not by passing[Bug] 

### ISSUE THREAD

**Issue by Ateeb91** [FastForwardTeam/FastForward#1153]
### Body

ouo.io is not working in latest update of extension in firefox also please add option to add more websites to bypass.

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
@Ateeb91 please enable this permission
![Screenshot from 2023-10-05 13-51-41](https://github.com/FastForwardTeam/FastForward/assets/76390419/09dabc11-db42-4681-af55-1a480d0c0810)

**Comment by lostdusty** [comment]
This issue is fixed by enabling the permission on the comment above. A fix has been pushed to Firefox AMO already.

**Comment by Ateeb91** [comment]
Will check and let you know soon.

**Comment by Ateeb91** [comment]
Still issue won't resolve.
[image: image.png]

[image: image.png]

**Comment by driedpampas** [comment]
we can't see the images, please use links or log into github and upload them in a comment

**Comment by Ateeb91** [comment]
I hope now images are clear, check email attachments.

**Comment by driedpampas** [comment]
There are no attachments, I believe GitHub removed them before forwarding
the email to this issue's participants, upload the images to Imgur, IBB.co
or whatever service you use and leave us some links

**Comment by Ateeb91** [comment]
![image](https://github.com/FastForwardTeam/FastForward/assets/25129966/71c06d5c-6416-4789-a23f-a7758c008b81)
![image2](https://github.com/FastForwardTeam/FastForward/assets/25129966/192aa6e0-6d96-4233-a515-3a63f97e3461)

**Comment by driedpampas** [comment]
huh, send me a screenshot of the extensions options page

**Comment by Ateeb91** [comment]
Option page screeshot.
![Screenshot 2023-10-08 043725](https://github.com/FastForwardTeam/FastForward/assets/25129966/7e4e1246-2f81-4cfc-9295-31f424791b3f)

**Comment by driedpampas** [comment]
it says undefined so it's the broken one you have to wait for Mozilla to update in AMO (or install manually on nightly or dev)

**Comment by Ateeb91** [comment]
link for manual installation?

**Comment by lostdusty** [comment]
https://github.com/FastForwardTeam/FastForward/blob/main/docs/INSTALLING.md

**Comment by Ateeb91** [comment]
Thank u so much it's working now
