### ISSUE TITLE
Bypass needed for https://ify.ac

### ISSUE THREAD

**Issue by ENC4YP7ED** [FastForwardTeam/FastForward#1155]
### Link

https://ify.ac/cXr

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/70538228/4ab98752-5611-4c24-a3ce-bce9c136038c)

**Comment by driedpampas** [comment]
try again and use the link in the screenshot as an example

**Comment by driedpampas** [comment]
also this looks like one of those websites so i don't think it's anything to do with bypassing

**Comment by ENC4YP7ED** [comment]
Updated the Link

**Comment by driedpampas** [comment]
oh i think it's somewhat simple

**Comment by ENC4YP7ED** [comment]
sounds good

**Comment by driedpampas** [comment]
https://github.com/driedpampas/FastForward-Firefox/actions/runs/6431692447

**Comment by driedpampas** [comment]
choose the package respective of your browser and load it
(heads up: if you're on firefox stable or beta, you'll need to change the contact email in the manifest.json file and upload it to addons as self distributed to install it)

**Comment by driedpampas** [comment]
also ill finish this bypass and pr it after all the mv2 bypasses are ported to mv3 so you'll have to reinstall the ext every update (so ill keep the linkify branch on my repo and update it whenever origin gets an update)

**Comment by rofdsfdsff** [comment]
ify.ac bypass
It may not work
as it was created in chatgpt

```
domainBypass("ify.ac", () => {
    ensureDomLoaded(() => {
        // Код, который нужно выполнить после загрузки DOM
    });

    // Функция для проверки ссылок на странице и перехода на страницу без рекламы
    const bypassAdLinks = () => {
        const adLink = document.querySelector("a[href^='https://ify.ac/get/']");
        if (adLink) {
            safelyNavigate(adLink.href);
        } else {
            console.log("Ссылка без рекламы не найдена.");
        }
    };

    // Проверка ссылок на странице сразу при загрузке
    bypassAdLinks();

    // Проверка ссылок при каждом изменении URL (например, при переходе на новую страницу)
    window.addEventListener("hashchange", bypassAdLinks);
    window.addEventListener("popstate", bypassAdLinks);
});

```
