### ISSUE TITLE
https://ez4mods.com/

### ISSUE THREAD

**Issue by gevin456** [FastForwardTeam/FastForward#1156]
### Link

https://ez4mods.com/

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

https://ez4mods.com/viber-messenger-mod-patched-unlocked/

**Comment by driedpampas** [comment]
ez4mods isn't the site that needs to be bypassed, it just has the download buttons that in this case redirected to 
![image](https://github.com/FastForwardTeam/FastForward/assets/76390419/0d9bfe40-afd9-447e-82b6-4c66a1eb429b)
so please edit the issue to reflect that (oh and mv2 is expired)
