### ISSUE TITLE
https://go.paid4link.com

### ISSUE THREAD

**Issue by Kutang81** [FastForwardTeam/FastForward#1158]
### Link

https://go.paid4link.com/QvKbs8np NSFW

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by tilsgee** [comment]
in the meantime, use script from bloggerpemula while waiting for the update

**Comment by Kutang81** [comment]
ty
