### ISSUE TITLE
https://linkpoi.me/tWT2KzN3

### ISSUE THREAD

**Issue by dhana-exe** [FastForwardTeam/FastForward#116]
### Domain

https://linkpoi.me/

### Link

https://linkpoi.me/tWT2KzN3

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #36

Closing
