### ISSUE TITLE
Low res "Get Add-on" icon in Readme

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#1160]
### Discussed in https://github.com/FastForwardTeam/FastForward/discussions/1159

<div type='discussions-op-text'>

<sup>Originally posted by **SecretX33** October  9, 2023</sup>
I'm wondering if this project would be interested in using high-quality versions of the "Get Add-on" icons for [Chrome](https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png) and [Firefox](https://user-images.githubusercontent.com/585534/107280546-7b9b2a00-6a26-11eb-8f9f-f95932f4bfec.png).

If you are, I can create a pull request (PR) to update the README.md file with these icons. Specifically, for the Chrome icon, I have both a square version (basically the HQ version of the current one used by the project), and a custom variant with rounded corners, which closely resembles the Firefox icon. I'm curious to know if the project would prefer using this rounded-corner variant, as I find it more visually appealing, personally. 😄</div>

**Comment by NotAProton** [comment]
@SecretX33 can you upload the images here?

**Comment by SecretX33** [comment]
Sure, here's the images, directly from one of my repos:

- [Firefox](https://github.com/SecretX33/pjo-to-anki/blob/master/docs/icons/get_extension_firefox.png)
- [Chrome (square)](https://github.com/SecretX33/pjo-to-anki/blob/master/docs/icons/get_extension_chrome_square_corners.png)
- [Chrome (round)](https://github.com/SecretX33/pjo-to-anki/blob/master/docs/icons/get_extension_chrome.png)

Also, see this [README](https://github.com/SecretX33/pjo-to-anki) to see how the round icon looks like.

**Comment by lostdusty** [comment]
Feel free to add your PR.

**Comment by NotAProton** [comment]
#1180
