### ISSUE TITLE
ouo.io, mentioned before: https://github.com/FastForwardTeam/FastForward/issues/861

### ISSUE THREAD

**Issue by grandpa1946** [FastForwardTeam/FastForward#1165]
### Link

https://ouo.io/jTIroo

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by grandpa1946** [comment]
nothing happens when opening the link btw (as if ff isn't installed)

**Comment by NotAProton** [comment]
Manifest v2 is not actively supported by us. Please switch to the MV3 version: 
https://github.com/FastForwardTeam/FastForward/blob/main/docs/INSTALLING.md#installing-from-web-stores

**Comment by grandpa1946** [comment]
@NotAProton the mv3 extension also doesn't work btw
