### ISSUE TITLE
https://www.clictune.com/ix7b

### ISSUE THREAD

**Issue by Veki34** [FastForwardTeam/FastForward#1168]
Link:
https://www.clictune.com/ix7b
Version:
Manifest-v3
What browser(s) are you seeing the problem on?
Librewolf.
What platform are you seeing the problem on?
Windows.

**Comment by Veki34** [comment]
label:Broken-Bypass

**Comment by Veki34** [comment]
Broken-bypass

**Comment by Veki34** [comment]
https://github.com/FastForwardTeam/FastForward/labels/Broken-bypass

**Comment by driedpampas** [comment]
clictune bypass fixed in #1169

**Comment by Veki34** [comment]
Ok, how can I download the fix?

**Comment by driedpampas** [comment]
you'll have to wait for the ext to be updated in the AMO or if on firefox dev or nightly you can grab the firefox package from the latest pr (and don't forget to set xpinstall.signatures.required to false in about:config)

**Comment by Veki34** [comment]
Roger,then I will keep this issue open till the extension includes the fix.

**Comment by Veki34** [comment]
Also, I will open one more issue for another bypass. How can I add an label to it?

**Comment by lostdusty** [comment]
Using the right template
