### ISSUE TITLE
https://tii.la bypass

### ISSUE THREAD

**Issue by Zeroxsho** [FastForwardTeam/FastForward#1170]
### Link

https://tii.la

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Pls add this site

**Comment by driedpampas** [comment]
please provide an example link

**Comment by Zeroxsho** [comment]
Here https://tii.la/LhsXGpMS
