### ISSUE TITLE
same for me, just now

### ISSUE THREAD

**Issue by Asrum** [FastForwardTeam/FastForward#1171]
same for me, just now

![image](https://github.com/FastForwardTeam/FastForward/assets/25284995/abdd6081-2fe3-43ac-bad3-a2c441224d9f)

https://www.virustotal.com/gui/file/a7fb4d988fcb568428918536ed62ee703f93373c41d3438c48e8d729190e0adc

_Originally posted by @stefanorossiti in https://github.com/FastForwardTeam/FastForward/issues/1138#issuecomment-1741769545_

**Comment by driedpampas** [comment]
Microsoft has removed the false positive from FastForward. If Windows Defender is still getting a bit quirky for you, run these commands in an elevated CMD.

1. `cd c:\Program Files\Windows Defender`
2. `MpCmdRun.exe -removedefinitions -dynamicsignatures`
3. `MpCmdRun.exe -SignatureUpdate`
