### ISSUE TITLE
FastForward isnt bypassing Linkvertise

### ISSUE THREAD

**Issue by Resimaa** [FastForwardTeam/FastForward#1173]
Am trying to bypass this site but its not working.
It worked the last time i used this extension like 2 months ago but idk what going on.
pls help.
Here is the link (its for a Fluxus key):
https://linkvertise.com/152666/fluxus-windows-check-1/1

**Comment by driedpampas** [comment]
The linkvertise bypass is broken and there is friction with individuals related to linkvertise at the moment, so it won't be fixed rn (at least officially :eyes: ).

**Comment by Resimaa** [comment]
OH thank you!
(and how would i do it un-officially? 👀)

**Comment by driedpampas** [comment]
i  think you can bypass linkveritse with adsbypasser or if yyou have ublock there was a list that made it harmless just a continue button (i was talking about making an unofficial fix :sparkles: :eyes: )

**Comment by lostdusty** [comment]
Linkvertise bypass is working here.
Also, open this issue using the right issue template.
