### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by grandpa1946** [FastForwardTeam/FastForward#1178]
### Body
improve backwards compatibility by omitting the upstreamcommit etc from backgroud.js in mv2 version, because the mv3 version uses totally different scripts and maybe load it locally? the last files are already saved to the disk...

<details>
<summary>original content:</summary>

add injection_script.js to main branch improve backwards compatibility with mv2 extension
i can't figure out to copy the injection_script.js from mv2 branch to main, but please add this, because 180 websites still aren't bypassed in mv3 vs mv2... 
What i mean is, mv2 uses the main branch with jsdelivr.net, but need to use the mv2 branch.

</details>

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment]
This is intentional and was decided after months of discussion among all the project members. See #658 .

**Comment by grandpa1946** [comment]
so how do i get mv2 extension working?

**Comment by NotAProton** [comment]
https://github.com/FastForwardTeam/FastForward/releases/tag/manifest-v2-release
