### ISSUE TITLE
[Bug] Changelog link broken 404

### ISSUE THREAD

**Issue by nigiriemoji** [FastForwardTeam/FastForward#1179]
### Body

https://fastforward.team/changelog

This link is the Changelog link, it's broken

![image](https://github.com/FastForwardTeam/FastForward/assets/53108354/5b52f4fb-dd51-4c3a-b6b5-c9643d15d833)
![image](https://github.com/FastForwardTeam/FastForward/assets/53108354/05f4e524-f171-4f4a-87c3-c03df66fc055)

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by lostdusty** [comment]
This is known, we didn't make any changelog yet.
