### ISSUE TITLE
ShareUs.io

### ISSUE THREAD

**Issue by HASNAINGAMERYT** [FastForwardTeam/FastForward#1188]
### Link

https://api.shareus.io/direct_link?api_key=Mv2E5zRYgqgW5VmVOvbpjy0cxZ92&pages=3&link=https://link.tnshort.net/DL8ro

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Phone (Android)

### (Optional) Anything else?

Ye

**Comment by UltraBlackLinux** [comment]
Ugh I think that is just a trap for people like you, because for me, it just redirects to the same website over and over again.

What a disgusting redirector though

**Comment by HASNAINGAMERYT** [comment]
But did you make a bypass for it, or it's just a messed up redirector?

**Comment by UltraBlackLinux** [comment]
I said I don't think you can even get past that. It seems to be an infinite loop

**Comment by HASNAINGAMERYT** [comment]
Okay
