### ISSUE TITLE
Tracker bypass not working on Firefox

### ISSUE THREAD

**Issue by seatwiggy** [FastForwardTeam/FastForward#1190]
### Link

https://goo.gl/BW1RV3

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

I tried to follow this link and was taken to the FastForward You aren't supposed to be here page.
https://goo.gl/XXZddT This link doesn't work either.

**Comment by NotAProton** [comment]
Works fine for me. Can you attach a screen recording?

**Comment by seatwiggy** [comment]
https://github.com/FastForwardTeam/FastForward/assets/93173836/ff3bf9eb-fcc1-463d-b53a-f2e75a6f6c6a

**Comment by NotAProton** [comment]
Have you enabled this permission https://github.com/FastForwardTeam/FastForward/issues/1150#issuecomment-1748963835

**Comment by seatwiggy** [comment]
That was enabled. I turned it off and back on just for kicks and it works now. I'm not sure if that's why. I have restarted Firefox and my computer a couple times since then. Thanks for the help anyway

**Comment by Asrum** [comment]
> Have you enabled this permission [#1150 (comment)](https://github.com/FastForwardTeam/FastForward/issues/1150#issuecomment-1748963835)
