### ISSUE TITLE
linkspy.cc bypass seemingly not working

### ISSUE THREAD

**Issue by BaconGod512** [FastForwardTeam/FastForward#1195]
### Link

linkspy.cc

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
please provide an example link not just domain.tld

**Comment by BaconGod512** [comment]
> please provide an example link not just domain.tld

Apologies, https://l4s.cc/J1xx
