### ISSUE TITLE
It says error when trying to bypass

### ISSUE THREAD

**Issue by Scrollerium** [FastForwardTeam/FastForward#1196]
### Link

https://direct-link.net/414421/acds

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Phone (Android)

### Anything else?

It says error

**Comment by hyrumpro** [comment]
Same to me, LinkVertise bypass its not working

https://linkvertise.com/984673/correoelectronic/1

**Comment by driedpampas** [comment]
linvertise is known to be broken
