### ISSUE TITLE
Example bypass links doesn't work

### ISSUE THREAD

**Issue by MikaelaMuller** [FastForwardTeam/FastForward#1197]
### Link

https://sub2unlock.com/mQHKF https://www.dlink2.net/ix7b https://letsboost.net/LrkkHQ https://ouo.press/o4Fbxg

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Phone (Android)

### Anything else?

https://github.com/FastForwardTeam/FastForward/assets/91151184/8023ff31-c139-4fae-8aa3-9bc7b49abd42

Note: bypass delay set to 0
![Screenshot_20231021-222046_Fennec](https://github.com/FastForwardTeam/FastForward/assets/91151184/2071ad7c-482c-43a3-a282-64a09e4f2288)

**Comment by MikaelaMuller** [comment]
![Screenshot_20231021-222529_Fennec](https://github.com/FastForwardTeam/FastForward/assets/91151184/9f8ec895-7cfc-4bb6-aaaf-115b55a5df5f)
![Screenshot_20231021-222532_Fennec](https://github.com/FastForwardTeam/FastForward/assets/91151184/f9caac33-bda4-402c-a6f7-71b091f6d9fd)

Settings and version

**Comment by driedpampas** [comment]
it doesn't work on firefox android :sob:

**Comment by stekzero** [comment]
> it doesn't work on firefox android :sob: 

Why? What happen?

**Comment by driedpampas** [comment]
I believe it's simply because it's incompatible (and might also have sth to
do with manifest v3)

**Comment by Legonzaur** [comment]
Using Firefox on desktop, it doesn't works either for any of the links in #223

**Comment by Aridow** [comment]
Except sub2unlock, no links in example page work on Firefox desktop.
