### ISSUE TITLE
cuty.io

### ISSUE THREAD

**Issue by julianmekato** [FastForwardTeam/FastForward#1198]
### Link

https://cuty.io/YlSN

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by AndnixSH** [comment]
Don't stale

Another link `https://cuty.io/LegendYt4k2`

**Comment by AahirKzz** [comment]
Why no one replying to any thread
