### ISSUE TITLE
Newegg and Gamestop product links from PCPartPicker infinite loop

### ISSUE THREAD

**Issue by robmonte** [FastForwardTeam/FastForward#1210]
### Link

https://pcpartpicker.com/mr/newegg/3hyH99

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

Not sure if I'm submitting this correctly.

The Newegg one I provided is an example, but if looking at an item like https://pcpartpicker.com/product/3hyH99/amd-ryzen-7-7800x3d-42-ghz-8-core-processor-100-100000910wof
you'll see some of the same format do work and others don't.

Best Buy or BHPhotoVideo work, but Newegg and Gamestop are stuck in the infinite loop.

**Comment by Shahnewaz1996** [comment]
Seems to be broken for all Newegg links generated by PcPartPicker.

Here's another one: [Lian Li SP 750 W 80+ Gold Certified Fully Modular SFX Power Supply](https://ca.pcpartpicker.com/mr/neweggca/3ZzhP6)

![Snipaste_2023-11-12_16-52-27](https://github.com/FastForwardTeam/FastForward/assets/34409006/267428e1-433a-418f-aff9-6bafb59f1b83)
