### ISSUE TITLE
https://exey.io

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#123]
### Domain

https://exey.io

### Link

https://exey.io/kueqv8

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #117 

Fixed in https://github.com/FastForwardTeam/FastForward/commit/a53f1cf03f4fde3c0ee6d9a95ae028d70695fdf6
