### ISSUE TITLE
https://musicc.xyz/ Bypass

### ISSUE THREAD

**Issue by simonapostolovski** [FastForwardTeam/FastForward#1234]
### Link

https://musicc.xyz/4js5

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

The green button after 15 seconds directly navigates to the link (didnt notice anything suspicious)

**Comment by not-varram** [comment]
note for later: just trigger hidden form and take the destination URL from that and redirect

**Comment by 0xliam627** [comment]
The website you provided is no longer accessible
![image](https://github.com/user-attachments/assets/e49b4b5e-bd0d-4178-802d-1f56e351ae01)
