### ISSUE TITLE
yoshare.net

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#124]
### Domain

Yoshare.net

### Link

https://yoshare.net/frag-pro-shooter-mod-apk/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Original link: https://droplink.co/n6DkNLH6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
```js
// place in ensureDomLoaded
domainBypass(/yoshare\.net/, () =>{ 
    ifElement("input.btn.btn-primary", a => a.click()) 
    
    ifElement("button#btn6", b => b.click())
    
})
```

second step needs crowd bypass

**Comment by NotAProton** [comment]
Fixed, thanks for the report
