### ISSUE TITLE
https://www.gositestat.com

### ISSUE THREAD

**Issue by Helmasko** [FastForwardTeam/FastForward#125]
### Domain

https://www.gositestat.com

### Link

https://doodrive.com/f/9znjvy

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
only a verify button nothing else

**Comment by Vojtak42** [comment]
Same problem.
