### ISSUE TITLE
FastForward - Discord

### ISSUE THREAD

**Issue by lokibh** [FastForwardTeam/FastForward#1253]
Hi,

Im not able to enter FastFord on Discord
i dont understand why...

Possible for someone to look into it please...

User name
crypto.hunter

Thanks

**Comment by kiraio-moe** [comment]
Here: https://discord.gg/PbZ2d4Gf

**Comment by lokibh** [comment]
Still not able to go in...
Am i banned or locked out?? no idea but it seems like it...
Im sure i never done or said anything wrong....
:(
