### ISSUE TITLE
you aren't supposed to be here error

### ISSUE THREAD

**Issue by Arvindrox** [FastForwardTeam/FastForward#1255]
### Link

linegee.net/GL0sa

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

![Uploading error.png…]()

**Comment by GJJellyfish** [comment]
I keep getting this on Librewolf as well.
