### ISSUE TITLE
Request Support For cutt.us

### ISSUE THREAD

**Issue by Davenchy** [FastForwardTeam/FastForward#1256]
### Link

https://cutt.us

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment]
Please provide an example link

**Comment by Davenchy** [comment]
I created this one ([https://cutt.us/lCsZC](https://cutt.us/lCsZC)) because I lost the URL I wanted to pass before.
Somehow, it is working for me and doesn't require bypassing.
