### ISSUE TITLE
loot-links

### ISSUE THREAD

**Issue by onixiya1337** [FastForwardTeam/FastForward#1274]
### Link

https://loot-links.com/s?fk9o

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

It should be really easy to make a bypass for it. Here's a part of its source code:
![20231207_103657](https://github.com/FastForwardTeam/FastForward/assets/47077455/78e89eb4-0a42-4804-9ed3-25b1851f3016)

**Comment by jonahd123** [comment]
THIS IS A FAST BYPASS
open console and type "PUBLISHER_LINK"

**Comment by RealPacket** [comment]
Deobfuscator used: https://deobfuscate.relative.im/
I did some processing on one of the scripts (it creates the `PUBLISHER_LINK` variable in the window), and here's the result:
https://gist.github.com/RealPacket/ddfbf2126dcea0274b6040b867219f67

**Comment by RealPacket** [comment]
works! right now: https://loot-links.com/s?fIjL -> https://www.mediafire.com/file/u09lk2fa7vtirdc/Codex_new_one.apk/file
![image](https://github.com/FastForwardTeam/FastForward/assets/107498533/835005dd-6001-4e10-83df-65fb0c0a0b96)

**Comment by RealPacket** [comment]
I'm going to try and make a PR to fix loot links support.

**Comment by RealPacket** [comment]
> I'm going to try and make a PR to fix loot links support.

I'm late... https://github.com/FastForwardTeam/FastForward/pull/1333

**Comment by NotAProton** [comment]
Fixed by #1333
