### ISSUE TITLE
Stuck bypassing bit.ly, cannot whitelist

### ISSUE THREAD

**Issue by paulo27ms** [FastForwardTeam/FastForward#1275]
### Link

https://bit.ly/test

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

In a loop:
![image](https://github.com/FastForwardTeam/FastForward/assets/13546823/f738b5a3-f233-4549-a7f0-d3b0e15ce576)

Tried the following whitelists, does not prevent the bypasser from getting stuck:
bit.ly
bit.*
*.bit.*

**Comment by kiraio-moe** [comment]
It's work on Chrome in the latest commit.
The final destination is this: https://en.wikipedia.org/wiki/Chris_Messina_(open-source_advocate)

Have you allowed all FF permission?
Try this: [FastForward_chromium_0.2366.zip](https://github.com/FastForwardTeam/FastForward/files/13610269/FastForward_chromium_0.2366.zip)

**Comment by paulo27ms** [comment]
Sorry, this is actually on v3.
I saw the other issue, this is on Chrome v120 (v119 yesterday, same issue), all permissions have been granted.

I loaded the version you provided, same results.

Disabling "Bypass trackers" let me access.

**Comment by Soromeister** [comment]
> Disabling "Bypass trackers" let me access.

Confirmed that this `workaround` fixes the issue for now.

**Comment by herrblitzkrieg** [comment]
Same issue here on Firefox v121.0 (64-bit).

**Comment by phucho0237** [comment]
Same issue on Chrome 120.0.6099.130 (64-bit)
