### ISSUE TITLE
programasvirtualespc.net bypass

### ISSUE THREAD

**Issue by Antonio1k** [FastForwardTeam/FastForward#1278]
### Link

https://www.programasvirtualespc.net/out/?aHR0cDovL3Bhc3RlcHZwLm9yZy8/dj0zOA==

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

https://www.programasvirtualespc.net/out/?aHR0cDovL3Bhc3RlcHZwLm9yZy8/dj0zOA==
https://onlypc.net/out#!WVVoU01HTkViM1pNTTBKb1l6TlNiR05JV25kTWJUbDVXbms0TDJScU1IcFBRVDA5
this website should be added, its being used as part of a quite complex link protector chain that makes you go to google.com and click the first result (usually being one of the same site they redirect you to)

**Comment by not-varram** [comment]
just fyi but the ending of the URL is the base64 encoded version of the destination URL: aHR0cDovL3Bhc3RlcHZwLm9yZy8/dj0zOA== when base64 decoded gives us: http://pastepvp.org/?v=38. so to bypass this all a dev has to do is to base64 decode the ending for the said URL and then redirect.
