### ISSUE TITLE
https://gplinks.co

### ISSUE THREAD

**Issue by LeibelRyan** [FastForwardTeam/FastForward#128]
### Domain

https://gplinks.co

### Link

https://gplinks.co/cEMUmA

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
```js
//place in ensureDomLoaded

	//Gplinks.co domains
	domainBypass("mynewsmedia.co", () => {    
	    awaitElement('a#btn6', b => {
	       safelyNavigate(b.href)
	    })
	    ifElement("button.close.close-btn-open-window", a => {
	        a.click()
	    })
	})
```

second step needs crowdBypass

**Comment by NotAProton** [comment]
Fixed, thanks for the report
