### ISSUE TITLE
Link not bypassing

### ISSUE THREAD

**Issue by AlguemDaRua** [FastForwardTeam/FastForward#1281]
### Link

https://l4s.cc/bIJi

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Was trying to download assassins creed 3 on ovagames and this is what happened

**Comment by kraivux** [comment]
So, had a problem with the l4s.cc domain and I've figured out it's using https:// instead of extension:// once I correct it (manually) it operates as I'd expect it to.
