### ISSUE TITLE
please bypass linkloot

### ISSUE THREAD

**Issue by GGLOLGGTAKE** [FastForwardTeam/FastForward#1293]
### Link

https://linksloot.net/s?dCQN

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by GGLOLGGTAKE** [comment]
please bypass linkloot!

**Comment by 0xliam627** [comment]
Dear @GGLOLGGTAKE ,
> Your problem has been solved! https://github.com/FastForwardTeam/FastForward/commit/275bafda84d259fc86498bbf08a15edfa0450cac
