### ISSUE TITLE
problem diverting cuty.io shortener

### ISSUE THREAD

**Issue by Fer120396** [FastForwardTeam/FastForward#1295]
Good creators of FastForward, I found with the cuty.io shortener that even the extension cannot be skipped. If you would be so kind as to make the extension skip this shortener since many of the programs I use are with this shortener, I would greatly appreciate it.
![Captura de pantalla 2023-12-23 022829](https://github.com/FastForwardTeam/FastForward/assets/109110448/d2a6ab9b-7808-4fad-8e81-4d74a93eaa93)

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) use este
