### ISSUE TITLE
Tracker Bypass not working

### ISSUE THREAD

**Issue by IsaiahBloyer** [FastForwardTeam/FastForward#1297]
### Link

https://bit.ly/3TGoW1Z

### Version

Manifest-v2

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

https://zipline.temper.live/u/8o4nNl.png <- error message
https://zipline.temper.live/u/aqjBZu.png <- fastfoward options

**Comment by NotAProton** [comment]
can you re-upload the screenshots? The host seems to be down

**Comment by accidental-expert** [comment]
bitly isn't working for me either, it just goes to the error page for this extension.

**Comment by IsaiahBloyer** [comment]
Yeah I had to transfer the domain to another registrar. Tonight or tomorrow I’ll reupload them to imgurOn Dec 30, 2023, at 9:58 AM, NotAProton ***@***.***> wrote:﻿
can you re-upload the screenshots? The host seems to be down

**Comment by Asrum** [comment]
> ### Link
> https://bit.ly/3TGoW1Z
> 
> ### Version
> Manifest-v2
> 
> ### What browser(s) are you using?
> Firefox browsers
> 
> ### What platform are you using?
> Computer (Windows, Linux, MacOS)
> 
> ### (Optional) Anything else?
> https://zipline.temper.live/u/8o4nNl.png <- error message https://zipline.temper.live/u/aqjBZu.png <- fastfoward options

Automático frawser

**Comment by IsaiahBloyer** [comment]
Here they are, both of them in 1. I just used all the default settings but it was unable to bypass the bitly. Turning off recommended helped https://imgur.com/a/Mptx9Tm

**Comment by NotAProton** [comment]
Unshorten.me now requires users to login to resolve trackers. Please turn off bypass trackers while we look for an alternative.

**Comment by privacyguy123** [comment]
Sorry for the duplicate issue - is there any movement on this one? It used to work.

I see this in an infinite loop with "undefined" in the Console.
![image](https://github.com/FastForwardTeam/FastForward/assets/50337995/b401414e-418e-4d6e-bb56-01f511ab6295)

**Comment by NotAProton** [comment]
> is there any movement on this one? It used to work.

It used to work because unshorten.me didn't require users to login for 10requests/hr. I'm working on an implementation hosted by FastForward. In the meantime if you have an alternative reply to this issue
