### ISSUE TITLE
autoclaim.in

### ISSUE THREAD

**Issue by zaquelgih** [FastForwardTeam/FastForward#130]
### Domain

~tei.ai~  autoclaim.in

### Link

https://tei.ai/zro5A?utm_source=AutoClaim.in

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

The tei.ai bypass works, autoclaim.in is broken

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloggerpemula** [comment]
turn off fastforward when you visit this site is the easy way

**Comment by NotAProton** [comment]
I'll remove the bypass for now

**Comment by kevin01523** [comment]
It works for me though it bypasses the captcha since tei.ai is loan2host now not the old ckk.ai or tei.aibut with it being removed it kinda switched to crowdbypass

**Comment by NotAProton** [comment]
thanks to setteメガイラ(megaera) on discord for noticing that the tei.ai bypass works, autoclaim.in is broken.

**Comment by kevin01523** [comment]
> thanks to setteメガイラ(megaera) on discord for noticing that the tei.ai bypass works, autoclaim.in is broken.

Btw im sette 🤣
