### ISSUE TITLE
Re-crie a acessibilidade de autenticação . bitly isn't working for me either, it just goes to the error page for this extension.

### ISSUE THREAD

**Issue by Asrum** [FastForwardTeam/FastForward#1302]
bitly isn't working for me either, it just goes to the error page for this extension.

_Originally posted by @matt-derrick in https://github.com/FastForwardTeam/FastForward/issues/1297#issuecomment-1872628443_

**Comment by Asrum** [comment]
Por favor. Refazer ascessibilidade de autenticação.

**Comment by NotAProton** [comment]
Duplicate
