### ISSUE TITLE
link-to.net isn't working

### ISSUE THREAD

**Issue by sminato27** [FastForwardTeam/FastForward#1308]
### Link

https://link-to.net/623961/529.833070924929/dynamic?r=aHR0cHM6Ly9icm90aGVycGFyYWRpc2Uub25saW5lL25lQ1NFaW1Bb2E=

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by 0xliam627** [comment]
Dupe #1419
