### ISSUE TITLE
problem bypassing bit.ly

### ISSUE THREAD

**Issue by parsapoorsh** [FastForwardTeam/FastForward#1311]
### Link

https://bit.ly/cloud-arch-patterns

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

when i click on that link, it takes me to:
https://fastforward.team/bypassed?type=tracker&url=https://bit.ly/cloud-arch-patterns

**Comment by phucho0237** [comment]
Same problem

**Comment by Unknown78** [comment]
Confirmed on Mv3 FastForward 0.2369
The [Last Mv2 Releases (FastForward 0.2286)](https://github.com/FastForwardTeam/FastForward/releases/tag/manifest-v2-release) is working fine with this.

**Comment by NotAProton** [comment]
Duplicate of #1297
