### ISSUE TITLE
https://www.up-4ever.net/

### ISSUE THREAD

**Issue by Pix-10** [FastForwardTeam/FastForward#1315]
### Link

https://www.up-4ever.net/12azg7arnhhj

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by Asrum** [comment]
________________________________
De: Pix-10 ***@***.***>
Enviado: quarta-feira, 10 de janeiro de 2024 09:26
Para: FastForwardTeam/FastForward ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [FastForwardTeam/FastForward] https://www.up-4ever.net/ (Issue #1315)


Link

https://www.up-4ever.net/12azg7arnhhj

Version

Manifest-v3

What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

What platform are you using?

Computer (Windows, Linux, MacOS)

(Optional) Anything else?

No response
