### ISSUE TITLE
shrinkme

### ISSUE THREAD

**Issue by jorgecotrinax1** [FastForwardTeam/FastForward#1320]
### Link

https://shrinkme.org/P0m56xWH

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

use a link chain: shrinkme > c-lc.xyz > digitalmarktrend > link

**Comment by 0xliam627** [comment]
Dupe #1226
