### ISSUE TITLE
Add New Bypass to oko.sh

### ISSUE THREAD

**Issue by kedaitinh12** [FastForwardTeam/FastForward#1323]
### Link

https://oko.sh/YXu7D

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by Infinitay** [comment]
The bypass wasn't working for me either, but it seems like it's not implemented despite the bypassed site list saying it is. https://github.com/FastForwardTeam/FastForward/blob/main/docs/Bypassed.md
