### ISSUE TITLE
Broken bit.ly

### ISSUE THREAD

**Issue by DorkYBru** [FastForwardTeam/FastForward#1325]
### Link

https://bit.ly/3tKYoSI

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment]
Duplicate of #1297
