### ISSUE TITLE
Discord's shortened link dis.gd is broken?

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#1327]
### Link

https://dis.gd/request

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by ghost** [comment]
(please change label to New-bypass)

**Comment by NotAProton** [comment]
Duplicate of #1297
