### ISSUE TITLE
Add a new bypass to loot-links.com

### ISSUE THREAD

**Issue by kedaitinh12** [FastForwardTeam/FastForward#1329]
### Link

https://loot-links.com/s?fkxm

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by 0xliam627** [comment]
Dear @kedaitinh12,
> Your problem has been solved! https://github.com/FastForwardTeam/FastForward/commit/15c2b048ac051bfe9528c3011a2103939957d393
