### ISSUE TITLE
[Bug] Fastforward broke on a bit.ly link

### ISSUE THREAD

**Issue by 2meito** [FastForwardTeam/FastForward#1331]
### Body

I tried to go to this link:
- https://bit.ly/NCH_GBVSR

and fastforward redirected to this page:
- https://fastforward.team/bypassed?type=tracker&url=https://bit.ly/NCH_GBVSR

which said
- "You aren't supposed to be here. Please open an issue on github to report this error."

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by movieslol** [comment]
yeah same here, looks like its broken

**Comment by marcostudios** [comment]
same, was about to report this

**Comment by NotAProton** [comment]
Duplicate of #1297
