### ISSUE TITLE
Not bypassing Nexus Mods countdown

### ISSUE THREAD

**Issue by Porkemon211** [FastForwardTeam/FastForward#1332]
### Link

https://www.nexusmods.com

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

Was working 1 month ago but now it wont work anymore also tried v3 but still nothing

**Comment by Solganis** [comment]
How does bypass working in abandoned 2 years ago Universal Bypass and not now?
