### ISSUE TITLE
[Bug] It says ''You aren't supposed to be here''

### ISSUE THREAD

**Issue by yagizracist** [FastForwardTeam/FastForward#1335]
### Body

https://www.ovagames.com/224736-elden-ring-deluxe-edition-multi14-elamigos.html 
Im trying the Google Drive link and it just says me what it says on the title and that i should report it on github.

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by kevin01523** [comment]
yeah the redirection is broken but you get the correct link just need to url decode it
