### ISSUE TITLE
Link in YouTube description

### ISSUE THREAD

**Issue by NeoNyaa** [FastForwardTeam/FastForward#1339]
### Link

https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbHU3WEZxODF5YlhueGNhNkFOSWZKQ29ZUUtEUXxBQ3Jtc0ttS1RUYk9CMGh4YXhRUVNpdk56cVcxT0gyeEU3OTFETjMwWEE4dnRxMlNaTVRWWUtXeTk0RU1la1d3THl1Wi1UR0M3SVNjWnhmb3NaZzhRYVU0cHMwMXN6X2VjX3hqd0VkWUFveFUxMGJkYnFrWFRZNA&q=http%3A%2F%2Fbit.ly%2Fdisciplerecs&v=Rj9_wFB_b88

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

All I can really say is I was on youtube and clicked a link in the description of a youtube video and instead of going where I wanted I was taken to the FastForward error page instead.  

![image](https://github.com/FastForwardTeam/FastForward/assets/56982408/1d35da59-264d-4ebf-891b-4402ec7c11f9)  

The URL bar has the contents of: `https://fastforward.team/bypassed?type=tracker&url=http://bit.ly/disciplerecs`  

And I'm unsure of if its any help but here is the YouTube video with the link I tried bypassing: `https://www.youtube.com/watch?v=Rj9_wFB_b88`
The specific link is their "SPOTIFY" link.

**Comment by NeoNyaa** [comment]
I may have been a dummy and misunderstood the information I was given and as such may have provided invalid information. The actual link that may have been failing could be `http://bit.ly/disciplerecs`.

**Comment by NotAProton** [comment]
Duplicate of #1297
