### ISSUE TITLE
[Bug] FastForward breaks portal.azure.com

### ISSUE THREAD

**Issue by foxt** [FastForwardTeam/FastForward#1340]
### Body

If you try to launch portal.azure.com with FastForward enabled the page will not load.

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by foxt** [comment]
https://github.com/FastForwardTeam/FastForward/assets/12257112/dbd7a762-fc24-4ae8-bcd7-03808b28dca4

**Comment by NotAProton** [comment]
Can you reproduce this on chrome?
