### ISSUE TITLE
ouo.io not bypassing

### ISSUE THREAD

**Issue by BrightDarknessXX** [FastForwardTeam/FastForward#1343]
### Link

https://ouo.io/o4Fbxg

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by BrightDarknessXX** [comment]
Version 0.2334-Mv3

**Comment by NotAProton** [comment]
Duplicate of #1343

**Comment by BrightDarknessXX** [comment]
What do you mean "marked this as a duplicate of #1343"? This is #1343.

**Comment by NotAProton** [comment]
Oh sorry I meant #1197

**Comment by detyso** [comment]
> ### Link
> https://ouo.io/o4Fbxg
> 
> ### Version
> Manifest-v3
> 
> ### What browser(s) are you seeing the problem on?
> Firefox browsers
> 
> ### What platform are you seeing the problem on?
> Computer (Windows, Linux, MacOS)
> 
> ### Anything else?
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated > _No response_
