### ISSUE TITLE
bstlar.com can't not bypass

### ISSUE THREAD

**Issue by TheWeaknd** [FastForwardTeam/FastForward#1345]
### Link

https://bstlar.com/2Fd/waiobp

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by 0xliam627** [comment]
Dupe #1136
