### ISSUE TITLE
https://linkspy.cc/tr/aHR0cHM6Ly9jbGlja3NmbHkuY29tL2Z1bGw/YXBpPWNhMDNkN2Q1YzBjODgzMzViMGY5YmVmZDkyMWQ5YWYxMWZmZmM4OTEmdXJsPWFIUjBjSE02THk5M2QzY3VabWxzWldOeWVYQjBMbU5qTDBOdmJuUmhhVzVsY2k5RlFrTTVSRE5GUkVZNUxtaDBiV3c9JnR5cGU9Mg=

### ISSUE THREAD

**Issue by expandhorizon** [FastForwardTeam/FastForward#1352]
### Link

https://linkspy.cc/tr/aHR0cHM6Ly9jbGlja3NmbHkuY29tL2Z1bGw/YXBpPWNhMDNkN2Q1YzBjODgzMzViMGY5YmVmZDkyMWQ5YWYxMWZmZmM4OTEmdXJsPWFIUjBjSE02THk5M2QzY3VabWxzWldOeWVYQjBMbU5qTDBOdmJuUmhhVzVsY2k5RlFrTTVSRE5GUkVZNUxtaDBiV3c9JnR5cGU9Mg==

### Version

Manifest-v2

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by Rust1667** [comment]
I solved it with this userscript 
https://greasyfork.org/en/scripts/487038-linkspy-concatenated-with-clicksfly-com-bypass
Not sure yet how to add these to FF
