### ISSUE TITLE
please bypass "peeplink"

### ISSUE THREAD

**Issue by triplesixxxxxxx** [FastForwardTeam/FastForward#1357]
### Link

http://peeplink.in

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
