### ISSUE TITLE
[Bug] Universal Bypass breaks Google Gemini

### ISSUE THREAD

**Issue by arantius** [FastForwardTeam/FastForward#1375]
### Body

1. Install Universal Bypass (in Firefox) (I have Version 13.15.2.1)
2. Navigate to https://gemini.google.com/

App fails to load, console logs lots of CSP failures.  Disable add-on, navigate again, app loads.

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by NotAProton** [comment]
The version on the Mozilla store (0.2334-Mv3) has a whitelist feature. Older versions are not supported

**Comment by arantius** [comment]
Oh, it's not "the version" it's a completely separate extension now?  I didn't know.  I've just had it installed for a while and it .. hasn't update for a while, and I guess now I know why?
