### ISSUE TITLE
No current bypass for ps4linux.com

### ISSUE THREAD

**Issue by hanakomisa** [FastForwardTeam/FastForward#1389]
### Link

https://ps4linux.com/s/z1fh5

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by Rust1667** [comment]
this userscript solves it:
```
// ==UserScript==
// @name        ps4linux.com
// @match       https://ps4linux.com/s/*
// @run-at      document-start
// ==/UserScript==
document.addEventListener('DOMContentLoaded', function() {
  window.location.assign(document.querySelector('#skipaft > a:nth-child(1)').href)
});
```

**Comment by hanakomisa** [comment]
Absolute time saver, thank you! I'm not sure if I should close this issue though. I'll leave it to the discretion of the FF team or if there are suggestions to do so.

**Comment by 0xliam627** [comment]
Dear @hanakomisa ,
> Your problem has been solved! https://github.com/FastForwardTeam/FastForward/commit/326389a33720e1323e3b1e874ec96db9f2d27ea8

**Comment by hanakomisa** [comment]
Legend, thank you!
