### ISSUE TITLE
1fichier.com

### ISSUE THREAD

**Issue by OrangeBull89** [FastForwardTeam/FastForward#1402]
### Link

https://1fichier.com/

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Phone (Android)

### (Optional) Anything else?

This is one of the major websites I encounter, the ip address tracking sucks, even when I use a vpn and get around it, it makes the download soooo slow.

**Comment by detyso** [comment]
Pay for debrid
