### ISSUE TITLE
dl.freetutsdownload.net

### ISSUE THREAD

**Issue by Cyberavater** [FastForwardTeam/FastForward#141]
### Domain

dl.freetutsdownload.net

### Link

https://dl.freetutsdownload.net/redirect-to/?url=https%3A%2F%2F1fichier.com%2F%3Fe80a5jyx32fm6dojyesp

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Place in ensureDomLoaded

```js
domainBypass("dl.freetutsdownload.net", () => {
	ifElement("h3", a => {
		b = a.getElementsByTagName('strong')[0].innerHTML
		safelyNavigate(b)
	})
})
```

**Comment by NotAProton** [comment]
Fixed, thanks for the report
