### ISSUE TITLE
https://paster.so/

### ISSUE THREAD

**Issue by apacalay** [FastForwardTeam/FastForward#1412]
### Link

https://paster.so/sV7jU

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this
