### ISSUE TITLE
bit.ly not working

### ISSUE THREAD

**Issue by mateushonorato** [FastForwardTeam/FastForward#1413]
### Link

https://bit.ly/StarioLauncher

### Version

Manifest-v2

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by 0xliam627** [comment]
Dupe #1364
