### ISSUE TITLE
[Bug] Settings page not working on Arc Browser

### ISSUE THREAD

**Issue by As2Bax** [FastForwardTeam/FastForward#1414]
### Body

I have no idea what manifest version it could be because it's so broken I can't tell

![image](https://github.com/FastForwardTeam/FastForward/assets/111764732/57021acc-6837-4f43-832c-6f3509ee0c08)

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by 0xliam627** [comment]
![image](https://github.com/user-attachments/assets/a8eaa770-1665-418e-9e80-60d38e38c116)
Dear @As2Bax 
> I tried it on Arc Browser and didn't see the error you mentioned
