### ISSUE TITLE
 this project is no longer updated Use this Script instead (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated)

### ISSUE THREAD

**Issue by detyso** [FastForwardTeam/FastForward#1418]
### Body

https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
This person is doing a good job for the community. 

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated

**Comment by 0xliam627** [comment]
Thank you, it's not a problem.
