### ISSUE TITLE
https://linkvertise.com

### ISSUE THREAD

**Issue by graperovsky** [FastForwardTeam/FastForward#1419]

**Comment by marcussacana** [comment]
Same here, not working

**Comment by fakhamatia** [comment]
Same here, not working

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by Cuteistfox** [comment]
> (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

Can confirm it works, if you dont want to add random userscripts, you can just type it into [Bypass.city](http://bypass.city)

**Comment by detyso** [comment]
Bypass city supports less websites rather than the amoni one they update every week or so

**Comment by fakhamatia** [comment]
> > (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this
> 
> Can confirm it works, if you dont want to add random userscripts, you can just type it into [Bypass.city](http://bypass.city)

Error
Failed to fetch
Why ?

**Comment by detyso** [comment]
what u mean just use the codeberg site

**Comment by 0xliam627** [comment]
Dear @graperovsky,
> Your problem has been solved! https://github.com/FastForwardTeam/FastForward/commit/31bd3b0193e06b73d8c777d640b0970175bac816
