### ISSUE TITLE
ty.gl (Trendyol Shopping Company) & adj.st (Adjust Ads)

### ISSUE THREAD

**Issue by ramazansancar** [FastForwardTeam/FastForward#1420]
### Link

https://ty.gl/010524_wp_saat

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

This link is generally used for influencer ad tracking. And it was created to earn commission for the link owner. When the link is entered, it shows the page with the relevant product or product list. He includes this in the link he directs. The `adjust_redirect` parameter value contains the link to be navigated.

**Comment by detyso** [comment]
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
use this

**Comment by ramazansancar** [comment]
I couldn't see adj.st here. Maybe it needs to be added with contribution. @detyso

**Comment by detyso** [comment]
If it’s an faucet site he doesn’t do those only content sharing where u got that link

**Comment by ramazansancar** [comment]
What is this repo for? @detyso

**Comment by driedpampas** [comment]
The link provided redirects me to a random shopping website:
https://www.trendyol.com/sr?wc=34&qt=kol+saati&st=kol+saati&prc=0-350&os=1&sst=MOST_FAVOURITE&adjust_t=h9ybh70_d50mvs0&adjust_adgroup=story&adjust_campaign=instagram&adjust_creative=010524_wp_saat&adjust_tracker_limit=999999999

**Comment by detyso** [comment]
You have a virus on ur pc then the link I share is open and you can also google it just by searching codeberg bypass shortlink

**Comment by ramazansancar** [comment]
Yes, a structure that cleans the affiliate links and directs them as a clean link is required here. @driedpampas
