### ISSUE TITLE
app.hb.biz (Hepsiburada Shopping Company) & adj.st (Adjust Ads)

### ISSUE THREAD

**Issue by ramazansancar** [FastForwardTeam/FastForward#1421]
### Link

https://app.hb.biz/LggnIdudwRX7

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

This link is generally used for influencer ad tracking. And it was created to earn commission for the link owner. When the link is entered, it shows the page with the relevant product or product list. He includes this in the link he directs. The adjust_redirect parameter value contains the link to be navigated.

When https://github.com/FastForwardTeam/FastForward/issues/1420 is done it can simply cover this as well.

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by ramazansancar** [comment]
What is this repo for? @detyso

**Comment by detyso** [comment]
It’s to skip the short links it autoclicks and skips the timer it was just made this year in january by amoni for movies or series ddl sites
