### ISSUE TITLE
spotify.link

### ISSUE THREAD

**Issue by ramazansancar** [FastForwardTeam/FastForward#1423]
### Link

https://spotify.link/Q4ysHiRssJb

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers, Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by 0xliam627** [comment]
Dear @ramazansancar,
> Thanks for your opinion but I think https://spotify.link/ is just a shortened link that doesn't need to be passed!
