### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by zinhtet96930** [FastForwardTeam/FastForward#1425]
### Link

https://shrinkme.us/DeepNude_Access_key

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Phone (Android)

### (Optional) Anything else?

[](url)https://shrinkme.us/DeepNude_Access_key

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by 0xliam627** [comment]
Dupe #1226
