### ISSUE TITLE
[Bug] You aren't supposed to be here: buff.ly

### ISSUE THREAD

**Issue by RozvM** [FastForwardTeam/FastForward#1426]
### Body

When trying to access [https://buff.ly/3woJOlc](https://buff.ly/3woJOlc), I get this error message: 
![image](https://github.com/FastForwardTeam/FastForward/assets/74600479/71ef3e59-a981-406e-b91f-aa8784eb429e)

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
Can you use this  fast forward won’t get updates (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated)
