### ISSUE TITLE
Add bypass for www.jdoqocy.com links

### ISSUE THREAD

**Issue by vacero** [FastForwardTeam/FastForward#1427]
### Link

https://www.jdoqocy.com/click-6305441-13212017?URL=https%3A%2F%2Fwww.fanatical.com%2Fdlc%2Fhouse-flipper-garden-dlc

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Seems like the bypass could be easy to implement, as the target URL is in a query param

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by driedpampas** [comment]
Weird, when I click on the link provided, it sends me straight to the target page (fanatical.com)
