### ISSUE TITLE
[Bug] Redirecting to original link loop

### ISSUE THREAD

**Issue by pnxl** [FastForwardTeam/FastForward#1428]
### Body

When FastForward fails to bypass a tracker it tries to redirect to original link...
Only to try to bypass it, again... and again... and again... and again... you get the idea.

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

I've found this problem with multiple links, here's one of them: https://click.linksynergy.com/deeplink?id=9e1vMmumXG0

**Comment by pnxl** [comment]
Sorry seems like the link is broken, here's the original one i got from a site: https://click.linksynergy.com/deeplink?id=9e1vMmumXG0&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Fp%2F1AY-000V-000C0%3FDescription%3Dsurface%2520pro%2520X%26cm_re%3Dsurface_pro%2520X-_-1AY-000V-000C0-_-Product%26quicklink%3Dtrue

Seems like FastForward removes the `murl` search query so the LinkSynergy doesn't know where to redirect

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this

**Comment by the-r3dacted** [comment]
This is the bug I have. The linked bypass all shortlinks debloated works fine.
