### ISSUE TITLE
Clictune[dot]com bypass failed

### ISSUE THREAD

**Issue by TheEpicness9000** [FastForwardTeam/FastForward#1429]
### Link

Clictune.com and Ouo.io

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

This is especially poignant considering clictune[dot]com is one of the [example bypasses](https://fastforward.team/example-links). This is likely because it became dlink4[dot]com.
EDIT: Ouo.io also failed.

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this
