### ISSUE TITLE
Cannot bypass 'web1s.asia' 

### ISSUE THREAD

**Issue by Woeml** [FastForwardTeam/FastForward#1430]
### Link

https://web1s.asia/rJx4OtBCGR/

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
> ### Link
> https://web1s.asia/rJx4OtBCGR/
> 
> ### Version
> Manifest-v3
> 
> ### What browser(s) are you using?
> Chrome browsers (includes brave, edge, opera, etc)
> 
> ### What platform are you using?
> Computer (Windows, Linux, MacOS)
> 
> ### (Optional) Anything else?
> _No response_

Use this script 
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
