### ISSUE TITLE
[Bug] Crowd bypass to empty URL breaks the flow.

### ISSUE THREAD

**Issue by Prototyped** [FastForwardTeam/FastForward#1431]
### Body

An attempt to bypass https://tii.la/7Tn2w?src=PSA gets me an empty crowd bypass.

![image](https://github.com/FastForwardTeam/FastForward/assets/5622474/b4ef2c9f-da50-4dc7-8773-6f12d5504353)

My settings:

![image](https://github.com/FastForwardTeam/FastForward/assets/5622474/5d09feaa-5216-431d-9e26-3370d87a8181)

Oddly enough, disabling crowd bypass actually redirects correctly to the destination -- but only after the whole wait. (But I had to wait the whole wait for the crowd bypass too.)

![image](https://github.com/FastForwardTeam/FastForward/assets/5622474/1913dc95-1a43-4a90-81f8-afbfc8cb56f9)

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by Prototyped** [comment]
FWIW I see this behavior not just for tii.la links but also others as well. In fact I don't think I've seen crowd bypass work under the guise of FastForward -- the last time I saw it work was when the extension was still called Universal Bypass.

**Comment by detyso** [comment]
(https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated) Use this
