### ISSUE TITLE
Broken Bypass https://lowcygier.pl > https://click.linksynergy.com

### ISSUE THREAD

**Issue by jed84** [FastForwardTeam/FastForward#1433]
### Link

https://lowcygier.pl/r/28e67635134e2caea6f42f03de962c5a3741f264/?utm_term=single&utm_source=post-478961

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

![obraz](https://github.com/FastForwardTeam/FastForward/assets/47121522/5528bc07-b0a8-4545-86a4-1b9d1c320947)

**Comment by detyso** [comment]
> ### Link
> https://lowcygier.pl/r/28e67635134e2caea6f42f03de962c5a3741f264/?utm_term=single&utm_source=post-478961
> 
> ### Version
> Manifest-v2
> 
> ### What browser(s) are you seeing the problem on?
> Firefox browsers
> 
> ### What platform are you seeing the problem on?
> Computer (Windows, Linux, MacOS)
> 
> ### Anything else?
> ![obraz](https://private-user-images.githubusercontent.com/47121522/335681807-5528bc07-b0a8-4545-86a4-1b9d1c320947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDg2MzEsIm5iZiI6MTcxODc0ODMzMSwicGF0aCI6Ii80NzEyMTUyMi8zMzU2ODE4MDctNTUyOGJjMDctYjBhOC00NTQ1LTg2YTQtMWI5ZDFjMzIwOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDIyMDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNjc3ZGY5ZjEwY2VhOGNmYzc1YmY1OWI0ZmExZjc3NGM3ZDA4NjMwYjEwY2UyYmViMDI0M2U4MzAzOThjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PsW5F0Gj974GvYgrGVwHZsh-voO_eB18A_2Kk3V4xHQ)

Use this script instead 

https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
