### ISSUE TITLE
This website isn't bypassed. Please add bypass for this asap. It takes too long to go through this website to get our required file.

### ISSUE THREAD

**Issue by Sonibros** [FastForwardTeam/FastForward#1434]
### Link

https://lksfy.com/59EhFF

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
> ### Link
> https://lksfy.com/59EhFF
> 
> ### Version
> Manifest-v3
> 
> ### What browser(s) are you using?
> Chrome browsers (includes brave, edge, opera, etc)
> 
> ### What platform are you using?
> Computer (Windows, Linux, MacOS)
> 
> ### (Optional) Anything else?
> _No response_

Use this script fast forward won’t get update’s anymore 
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
