### ISSUE TITLE
tii.la links bypass

### ISSUE THREAD

**Issue by tfaqar** [FastForwardTeam/FastForward#1435]
### Link

https://tii.la/RDn1

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Phone (Android)

**Comment by detyso** [comment]
> ### Link
> https://tii.la/RDn1
> 
> ### Version
> Manifest-v2
> 
> ### What browser(s) are you using?
> Chrome browsers (includes brave, edge, opera, etc)
> 
> ### What platform are you using?
> Phone (Android)
> 
> ### (Optional) Anything else?
> _No response_

Use this script instead 
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
