### ISSUE TITLE
ViralFeed

### ISSUE THREAD

**Issue by trisout78** [FastForwardTeam/FastForward#1436]
### Link

https://viralfeed.xyz

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
> ### Link
> https://viralfeed.xyz
> 
> ### Version
> Manifest-v3
> 
> ### What browser(s) are you using?
> Chrome browsers (includes brave, edge, opera, etc)
> 
> ### What platform are you using?
> Computer (Windows, Linux, MacOS)
> 
> ### (Optional) Anything else?
> _No response_
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
