### ISSUE TITLE
agregar por favor, gracias

### ISSUE THREAD

**Issue by nrgl2002** [FastForwardTeam/FastForward#1439]
### Link

https://xpshort.com/bfPlXsZR

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

### Anything else?

se podra agregar a la base gracias!!!

**Comment by detyso** [comment]
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/ Utilize este script fast forward ya no actualizan @nrgl2002
