### ISSUE TITLE
how file dm can't be fastforward but when i check it still say can bypass?

### ISSUE THREAD

**Issue by vthiep2412** [FastForwardTeam/FastForward#1440]

**Comment by driedpampas** [comment]
The bypass might need updates since filedm could have introduced breaking changes to the shortener and how it could be bypassed.

**Comment by detyso** [comment]
> The bypass might need updates since filedm could have introduced breaking changes to the shortener and how it could be bypassed.
Use this fast forward is a dead project no more updates it says on there
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/
