### ISSUE TITLE
Bypass curseforge linkouts

### ISSUE THREAD

**Issue by 500-internal-server-error** [FastForwardTeam/FastForward#1441]
### Link

https://www.curseforge.com/linkout?remoteUrl=https://bit.ly/PatreonXaero96

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Seems like a similar extension did this bypass already a few years ago, maybe [their work](https://gitlab.com/ClearURLs/ClearUrls/-/issues/241) could be reused here too.

**Comment by detyso** [comment]
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
