### ISSUE TITLE
Support for HotLink.cc

### ISSUE THREAD

**Issue by fakhamatia** [FastForwardTeam/FastForward#1442]
### Link

https://hotlink.cc

### Version

Manifest-v3

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

**Comment by detyso** [comment]
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated

**Comment by driedpampas** [comment]
Provide a proper example link.

**Comment by fakhamatia** [comment]
> Provide a proper example link.

[https://hotlink.cc/OXESAVETZU0X/AmericanFiction.zip.html](https://hotlink.cc/OXESAVETZU0X/AmericanFiction.zip.html)
