### ISSUE TITLE
Optimize Bypass Time for Loot-links Without Parameter r

### ISSUE THREAD

**Issue by 0xliam627** [FastForwardTeam/FastForward#1445]
# Issue:
When dealing with loot-links that lack the **r** parameter (e.g., https://linksloot.net/s?dCQN), the bypass process typically takes around 60 seconds to complete. This delay negatively impacts the efficiency and user experience.

# Objective:
Implement a solution to reduce the bypass time for loot-links without the **r** parameter, aiming to make the process faster and more efficient.

# Steps to Reproduce:

- Go to the link: https://linksloot.net/s?dCQN
- Observe the time taken for the process to complete (approximately 60 seconds).
**Expected Outcome:** The bypass time should be significantly reduced, ideally to under 10 seconds.

Example loot-link without the `r` parameter: https://linksloot.net/s?dCQN

### Version

Manifest-v3

### What browser(s) are you seeing the problem on?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by driedpampas** [comment]
Can't reproduce this. Navigating to the link, it complains about adblock being enabled (even with extension disabled) then I get sent to a FF extension page as it should.
![image](https://github.com/user-attachments/assets/2caeb02e-add2-47d9-bbfc-05a936716b45)

**Comment by 0xliam627** [comment]
> Can't reproduce this. Navigating to the link, it complains about adblock being enabled (even with extension disabled) then I get sent to a FF extension page as it should. ![image](https://private-user-images.githubusercontent.com/76390419/353035375-2caeb02e-add2-47d9-bbfc-05a936716b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTQ1NjYsIm5iZiI6MTcyMjI1NDI2NiwicGF0aCI6Ii83NjM5MDQxOS8zNTMwMzUzNzUtMmNhZWIwMmUtYWRkMi00N2Q5LWJiZmMtMDVhOTM2NzE2YjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDExNTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MWM4Mjk0MzE2MmU2Y2QyMjk0NWIzYjVlYjIwMzgzYTYyN2UzNmFhMGNhZGZkOGZhODdjYmRiNjc4YzRiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gdTvGGqjfa8IiaIhhjGURU8Oi0p_cntCX0eISQbKYiY)

This problem refers to a very long bypass time, not to the bypass not working

**Comment by driedpampas** [comment]
I only have to wait about 3-4 seconds on average before seeing the extension page.

**Comment by ghost** [comment]
This extension doesnt work on have of the sites for me

**Comment by 0xliam627** [comment]
@theregularshow Can you provide the link?

**Comment by mohaounsy-cmyk** [comment]
https://links.lootlabs.gg/s?fJjn&data=ropKerF1C%2BDVFRHtlJ4B3stRPx3lFEDYB2oDjB3ThPQBq9LuSb2fb%2FStLDwx3eHaxZF7jN3bCFg0IH%2FbAExgtk2gpdPvUctud5lQa99BVjHxbl0OxjRX0DefmsxdJ%2BnxcPB4yBcux6MxNwivcI%2FB%2B05vMA4wHniykqcuCo8oqCVAaEoDxI0WRDYNF7dXHlJXR%2BcUJYxhGDuNs2rNKgtMMxjlGtblw0IFwF3okRgU7dscVCGiOMkvNJ%2FJX30JHCGqJOup5RIIUR10SXvHu4BVxiqpPnhsH4OOTx1G71TzwV936%2FtZQt5g7xC6t0hprhWQ75T6vGURT9a0ts1F%2F4Xyt3N48YWaJjZ8ete4M22w0mniLtxDSl6lQw3D%2B4oLkVq2UOyo9EnFStYwUzCi67G9mAfW9o31TwHWNuhz4eEwqN5GJNFBqXoGTLOor5RkWJsFRDUeJCXNtzwP3qQ3%2F80H4SElIaIsbsJgnetzrc%2BmcjS9K73sRnTdk%2BrIf0da%2B3upK2SCoa%2Bt2joTaZNtbs0LINBRZziFeQacrZHVEql%2FVKHBZ3y8aopz9%2Blusx5JxUlwq7HnxYZn9vp6%2FjcgY4vQzVKSiBVcU6oE66RubBJFM%2BY5eGS65qpUDCHO47b98CWy9W1QtpfBSA%2FQltIvokCPVZxnjnx2IslfW%2FFz9rDqvOzPCdS5f9p5IqEtGPd4VXO%2FYnyagRTzw4k8OXxdGtM4RjCHp66z7o60oSr6VUhdQ6wBynJxDYt92Tt%2FNJtSOCNr
