### ISSUE TITLE
AdMaven links (mostly for NSFW)

### ISSUE THREAD

**Issue by Rust1667** [FastForwardTeam/FastForward#1446]
### Link

https://kmendation.com/s?DtIj

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

In case this helps:
- currently existing bypass for this is only bypass.city or userscripts that redirect there
- Also, there are some uBlock Origin filters that sort of work for Firefox (but the domain names need to be updated): https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-9392257
- these links are commonly used in telegram groups (like https://t.me/leakedmegas, https://t.me/onlyfansleaks420, https://t.me/onlyfansxmega1, ...) to link to mega folders with NSFW stuff from onlyfans 
- this issue https://github.com/FastForwardTeam/FastForward/issues/1370 is for the same thing

**Comment by 0xliam627** [comment]
Dupe #1370
