### ISSUE TITLE
Necesito agregar unos acortadores para poder saltarlos 

### ISSUE THREAD

**Issue by Anonimus5jt** [FastForwardTeam/FastForward#1454]
me ayudan necesito saltar algunos acortadores de url como estos

https://shrinkme.dev/ORGmfJ1
https://tii.la/l2Ktv
https://tmearn.net/link/lUSaFM

porfavor avisenme si se puede ya que estoy tratando de saltarlos pero no me dejan

**Comment by detyso** [comment]
Busca en codeberg esta ahi como no sabes
