### ISSUE TITLE
Not bypassing linkvertise links

### ISSUE THREAD

**Issue by fullbr1nger** [FastForwardTeam/FastForward#1455]
Browser: Vivaldi, LibreWolf

Example link: https://linkvertise.com/451994/amdy1?o=sharing

**Comment by 0xliam627** [comment]
Are you using Manifest V2 or Manifest V3?

**Comment by fullbr1nger** [comment]
In the extensions settings menu it says: 0.2383-Mv3, i think its Manifest V3

**Comment by 0xliam627** [comment]
Your problem has been solved on commit https://github.com/FastForwardTeam/FastForward/commit/31bd3b0193e06b73d8c777d640b0970175bac816
