### ISSUE TITLE
Boostellar

### ISSUE THREAD

**Issue by Beanerism** [FastForwardTeam/FastForward#1461]
### Link

https://bstlar.com/

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

I was able to bypass this website before but now it doesn't

**Comment by 0xliam627** [comment]
Manifest-v2 is deprecated, now only Manifest-v3 remains

**Comment by Beanerism** [comment]
> Manifest-v2 is deprecated, now only Manifest-v3 remains

How do I "get" v3?
