### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by A6tzz** [FastForwardTeam/FastForward#1464]
https://loot-link.com/s?c56dbf87&data=FvC8CevZd3UHGx6Y2T0z9m5jqCd9RgWPQNjBb%2BJ94D726Un6Hqdm6LN5HQcHVthYU8BGsr36Lc8ryqhCqfR0Mw%3D%3D

**Comment by quangpao** [comment]
Loot-link is no longer work. Facing the same issue. 😭
