### ISSUE TITLE
New bypass request

### ISSUE THREAD

**Issue by waveware4ai** [FastForwardTeam/FastForward#1468]
### Link

https://ouo.press/3aFFzA

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

No response

**Comment by 0xliam627** [comment]
Manifest-v2 is deprecated, now only Manifest-v3 remains
