### ISSUE TITLE
aylink.co bypass req

### ISSUE THREAD

**Issue by Raidware** [FastForwardTeam/FastForward#1469]
### Link

aylink.co

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

pls add this website

**Comment by 0xliam627** [comment]
Manifest-v2 is deprecated, now only Manifest-v3 remains

**Comment by Raidware** [comment]
> Manifest-v2 is deprecated, now only Manifest-v3 remains

in result of?
