### ISSUE TITLE
Mobi2c.com is not bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#147]
### Domain

Mobi2c.com

### Link

https://mobi2c.com/oppo-find-x2-pro-phone-review/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogachenkove** [comment]
From which site (full URL) did you get to the site `https://mobi2c.com/oppo-find-x2-pro-phone-review/` ?

**Comment by Vojtak42** [comment]
sorry, solved, I had old definitions

**Comment by Bhadu29** [comment]
mobi2c still not bypass.


i got this shortner link from movies website that name is psarips
