### ISSUE TITLE
https://1short.info

### ISSUE THREAD

**Issue by longvuu** [FastForwardTeam/FastForward#1477]
### Link

https://1short.info

### Version

Manifest-v2

### What browser(s) are you using?

Chrome browsers (includes brave, edge, opera, etc)

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Link
https://1short.info

Version
Manifest-v2

What browser(s) are you using?
Chrome browsers (includes brave, edge, opera, etc)

What platform are you using?
Computer (Windows, Linux, MacOS)

(Optional) Anything else?

**Comment by 0xliam627** [comment]
Manifest-v2 is deprecated, now only Manifest-v3 remains
