### ISSUE TITLE
https://af.gog.com

### ISSUE THREAD

**Issue by Patrxgt** [FastForwardTeam/FastForward#1478]
### Link

https://af.gog.com/game/tropico_4?as=1721879312

### Version

Manifest-v3

### What browser(s) are you using?

Firefox browsers

### What platform are you using?

Computer (Windows, Linux, MacOS)

### (Optional) Anything else?

Data about this redirect collected by uBlock Origin:
without parameters = https://track.adtraction.com/t/t
a = 1578845458
as = 1721879312
t = 2
tk = 1
url = https://www.gog.com/game/tropico_4

**Comment by 0xliam627** [comment]
huh? As far as I can see, https://af.gog.com/game/tropico_4?as=1721879312 is a place to buy

**Comment by Patrxgt** [comment]
But it's an affiliate link that sometimes closes the whole tab after clicking on it in Firefox when using uBO.
