### ISSUE TITLE
FastForward Breaks google gemini

### ISSUE THREAD

**Issue by PeriodicOccupancy** [FastForwardTeam/FastForward#1481]
Using FastForward makes the gemini webapp unusable. not sure why, but disabling the extension allows gemini to work as normal.

**Comment by 0xliam627** [comment]
Can u give proofs?

**Comment by PeriodicOccupancy** [comment]
I'd have to reinstall the extension, but I can give you a screenshot of the webpage saying gemini is unavailable and another without the extension where it works.

**Comment by PeriodicOccupancy** [comment]
![image](https://github.com/user-attachments/assets/087833a6-ebef-40b8-84d5-0a52b7b85ab4)

![image](https://github.com/user-attachments/assets/4c034adf-468f-4d88-963c-66cb02d1ca99)

Only change between these two is I disabled FastForward, issue was bugging me for a month before I decided to disable extensions one by one and FastForward was the culprit

![image](https://github.com/user-attachments/assets/67032091-f416-4463-9a1b-3800b255050e)
Here's the options I have in the extension, Custom Bypasses are untouched, Thought about checking if writing a bypass to ignore gemini.google would work but haven't had the time to look into it.
