### ISSUE TITLE
go.netfile.cc

### ISSUE THREAD

**Issue by ahmed98Osama** [FastForwardTeam/FastForward#149]
### Domain

go.netfile.cc

### Link

https://go.netfile.cc/MxAu

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #117 

Fixed in https://github.com/FastForwardTeam/FastForward/commit/a53f1cf03f4fde3c0ee6d9a95ae028d70695fdf6
