### ISSUE TITLE
Bypass not working for Linkspy

### ISSUE THREAD

**Issue by Bruhgherstein** [FastForwardTeam/FastForward#1503]
### Link

https://linkspy.cc//a/3/What-is-Passive-Income-and-How-to-Earn-It_aHR0cHM6Ly9jbGsuc2gvZnVsbD9hcGk9MDM1MTUwOWQxYjljZGNkYTQ3NTAxZmI1ODgzYzhmZDJjODQ4MzM4MSZ1cmw9YUhSMGNITTZMeTkzZDNjdVptbHNaV055ZVhCMExtTmpMME52Ym5SaGFXNWxjaTlDUWpFNE1UY3dNelEwTG1oMGJXdz0mdHlwZT0y

### Version

Manifest-v2

### What browser(s) are you seeing the problem on?

Firefox browsers

### What platform are you seeing the problem on?

Computer (Windows, Linux, MacOS)

**Comment by lostdusty** [comment]
See https://github.com/FastForwardTeam/FastForward/issues/1504
