### ISSUE TITLE
try2link.com/

### ISSUE THREAD

**Issue by ahmed98Osama** [FastForwardTeam/FastForward#151]
### Domain

https://try2link.com

### Link

https://try2link.com/K4QlbuK/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
```js
domainBypass(/newforex\.online|world-trips\.net/, () => {
	ensureDomLoaded(() => {
	ifElement("a.submitBtn.btn.btn-primary[href]", a => {
		safelyNavigate(a.href)
	})
	})
})
```

**Comment by NotAProton** [comment]
Fixed, thanks for the report

**Comment by mustaqimM** [comment]
@NotAProton It doesn't work anymore. This is the fix I have:

```js
domainBypass("try2link.com", () => {
  ifElement("a.btn.btn-success.btn-lg.get-link.disabled", d => {
    awaitElement("a.btn.btn-success.btn-lg.get-link[href]:not(.disabled)", d => {
      d.click()
    })
  })
})
```

The countdown still needs to be taken care of though.
