### ISSUE TITLE
coinsurl.com

### ISSUE THREAD

**Issue by ahmed98Osama** [FastForwardTeam/FastForward#153]
### Domain

https://coinsurl.com

### Link

https://coinsurl.com/eBt24cD1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kammychan** [comment]
You could use below solution before CrowdBypass lanuch. It is supported CoinsUrl, Cryptoads, CoinsParty

//CoinsUrl, Cryptoads, CoinsParty
domainBypass(/coinsearns\.com|mcrypto\.club|luckydice\.net/,()=>{
     ifElement("#mdt",b=>b.click())
     ifElement("a#wpsafelinkhuman[onclick]",c=>c.onclick())
     ifElement("a[onclick^='window.open']",ao=>ao.onclick())  
})
