### ISSUE TITLE
Rodjulian.com, publicananker.com, ... aren't bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#154]
### Domain

Publicananker.com

### Link

https://rodjulian.com/disaster-or-deliciouskoreas-bizarre-meat-bbq/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Mirror sites of link1s.com aren't bypassed:
Publicananker.com, pennbookcenter.com, rodjulian.com, …
Original link: https://link1s.com/vmosromv7_64
Kiwi browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogachenko** [comment]
@Vojtak42 From which site (full URL) did you go to this site?

**Comment by NotAProton** [comment]
merging with #40
