### ISSUE TITLE
Link1s

### ISSUE THREAD

**Issue by dragondemon111311** [FastForwardTeam/FastForward#157]
### Domain

https://link1s.com

### Link

https://link1s.com/64BIT

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

how fastforward cant link1s is because after you open a link1s is direct you to another website 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
duplicate of #40
