### ISSUE TITLE
FilesSrc

### ISSUE THREAD

**Issue by Furionsama** [FastForwardTeam/FastForward#164]
### Domain

https://worldsrc.net/

### Link

https://worldsrc.net/games/detalis?Ty=2307

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
"We Will Be Retiring WorldSrc.Net On June 20th, 2022"
