### ISSUE TITLE
rdaenthusiast.com

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#165]
### Domain

rdaenthusiast.com

### Link
http://click.email.rdaenthusiast.com/?qs=da8244d635c2adee1f1c9bd5b227685a5795713a5b561f4416704d837a2a4f96f11d27b02c5780e63e07f755a4d508ae132277688649c2d1
`
### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Where is this supposed to take me?

**Comment by toyboatcash** [comment]
My bad grabbed the wrong link I updated it and here's where it redirects to https://www.familyhandyman.com/wp-content/uploads/2021/09/PP_HiLoTable_Final3.pdf?_cmp=FHWelcome_E7&_ebid=FHWelcome_E710152021&_mid=442100&ehid=196c18662ee328ed8700ffc3c4bbb9da9109dd93

**Comment by reashetyrr** [comment]
it seems to work fine for me?
