### ISSUE TITLE
cutdl.xyz is not bypassed

### ISSUE THREAD

**Issue by glencoe2004** [FastForwardTeam/FastForward#167]
### Domain

cutdl.xyz

### Link

https://cutdl.xyz/wim97EOL

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeF53** [comment]
It does attempt to bypass it, but it sometimes forgets to include the second half of the link
example case
https://cutdl.xyz/ongmHQt

FastForward caches https://1fichier.com/, while the link should be https://1fichier.com/?e9r2b4dpw8bjzhs9hbwi

**Comment by reashetyrr** [comment]
but the ?something is wrong and will be ignored due to no value 🤔

**Comment by CodeF53** [comment]
This issue is still relevant.

**Comment by CodeF53** [comment]
It still happens.

**Comment by MathiasDevelopes** [comment]
Issue still persists.

**Comment by aquuadrain** [comment]
still happens

**Comment by XmemphistoX** [comment]
Still going on.

**Comment by CodeF53** [comment]
https://cutdl.xyz/ is currently down for maintenance, so I can't test if this still applies

**Comment by CodeF53** [comment]
https://cutdl.xyz/ is still down for maintenance, so I would just close the issue or leave it stale

**Comment by kiraio-moe** [comment]
Work on the latest commit [f4c8bdb](https://github.com/FastForwardTeam/FastForward/commit/f4c8bdbbea6ab60ff031f63fd72ea52bdac3587e). Browser: Edge
