### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by k0ng1** [FastForwardTeam/FastForward#168]
## Context
> _generated_background_page.html
## Stack Trace
> _generated_background_page.html:1 (anonymous function)

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/44335195/138079557-749865f3-515d-4575-b254-5a9d3307a9fe.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Can't reproduce

**Comment by NotAProton** [comment]
Are you still facing the issue?

**Comment by lem6ns** [comment]
Closed due to inactivity.
