### ISSUE TITLE
Please add bypass for ouo.io

### ISSUE THREAD

**Issue by LiteItOn** [FastForwardTeam/FastForward#171]
### Domain

https://ouo.io/

### Link

https://ouo.io/mbPbaa

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TETYYS** [comment]
Already bypassed

**Comment by LiteItOn** [comment]
> Already bypassed

xdddddddddd this is fucking 7 months old bro

**Comment by TETYYS** [comment]
then close the issue

**Comment by feeas** [comment]
not working https://ouo.io/Q2sQlL

**Comment by TETYYS** [comment]
works on my machine
