### ISSUE TITLE
affstat.adro.co

### ISSUE THREAD

**Issue by DRSDavidSoft** [FastForwardTeam/FastForward#176]
### Domain

affstat.adro.co

### Link

https://affstat.adro.co/click/e0efee15-70de-42db-803a-75c56bd927f1/aHR0cHM6Ly93d3cuZGlnaWthbGEuY29tL3Byb2R1Y3QvZGtwLTEwMzY0MS8=

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

This is a base64 encoded URL:
```
https://affstat.adro.co/click/e0efee15-70de-42db-803a-75c56bd927f1/aHR0cHM6Ly93d3cuZGlnaWthbGEuY29tL3Byb2R1Y3QvZGtwLTEwMzY0MS8=
```

The format is: `/click/{UUID}/{base64}`

P.S.: There is another endpoint which doesn't have the base64-encoded destination in its URL, i.e. `/click/{UUID}`.  This is different and will require crowdsourcing, unlike the one above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DRSDavidSoft** [comment]
### Other example

Source
```
https://affstat.adro.co/click/e0efee15-70de-42db-803a-75c56bd927f1/aHR0cHM6Ly93d3cuZGlnaWthbGEuY29tL3Byb2R1Y3QvZGtwLTM3MzUxMzg=
```

destination (decoding the base64 segment of the url)
```
https://www.digikala.com/product/dkp-3735138
```

**Comment by DRSDavidSoft** [comment]
I'd still like this issue to be resolved

**Comment by DRSDavidSoft** [comment]
I'd still like this issue to be resolved

**Comment by abadawe-dev** [comment]
Seems to be working can you test again?
