### ISSUE TITLE
tinyurl.is

### ISSUE THREAD

**Issue by rigaz29** [FastForwardTeam/FastForward#177]
### Domain

https://tinyurl.is

### Link

https://tinyurl.is/cZbN?sport=american-football

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
Already bypassed.
