### ISSUE TITLE
un-byapssed website

### ISSUE THREAD

**Issue by imagineimagining** [FastForwardTeam/FastForward#182]
### Domain

https://link1s.com/

### Link

https://link1s.com/okeOf/?user=WDJwZ25la0RML25zM1hneHpWU2RpbmthWUNydisxMEhWcHhhNzhRL09DdFBKQktNaHZmQ1E3elpmUFVsZXdjeU1wTEFSZ2MzRllRWHZnYU9TK2JLMTNLY2x2bmVSVVRNVmVVSjErb0RPYVU9

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
duplicate of #40
