### ISSUE TITLE
drive.hollywoodtelugupedia.cf

### ISSUE THREAD

**Issue by sunilroyy007** [FastForwardTeam/FastForward#183]
### Domain

https://drive.hollywoodtelugupedia.cf/gp/?id=NWxrSU81Vkg

### Link

https://drive.hollywoodtelugupedia.cf/gp/?id=NWxrSU81Vkg

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

There is no kiwi version to select and no kiwi browser to select and no android os to select so saying here... Please add this site to bypass list. I need to click on that download button and wait 5 seconds then need to click on download. Please do fix

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sunilroyy007** [comment]
Any response?

**Comment by dhana-exe** [comment]
for this https://gplinks.co/5lkIO5VH already detected and works...
but for https://drive.hollywoodtelugupedia.cf itself... i think alot things need to be done...
maybe you can give another url from that sites....
