### ISSUE TITLE
adshnk.com isn't bypassed

### ISSUE THREAD

**Issue by BoscoFZ** [FastForwardTeam/FastForward#186]
### Domain

https://adshnk.com/

### Link

http://adshnk.com/Bj3jBO

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
it "redirects"  to the same website, just uses captcha...
