### ISSUE TITLE
Megaup bypass is .... almost working

### ISSUE THREAD

**Issue by LightBeamOvHe** [FastForwardTeam/FastForward#187]
### Domain

megaup.net

### Link

https://megaup.net/2lRlk?pt=Jy%2FGoW9Tj%2B3kGis%2FLPIlZV5NUEi1WM3pKncjO1ow6m4%3D

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I'm actually using Vivaldi. This problem was also occuring on Universal Bypass.
So the countdown is running fast, so it does looks like it's working, tho when I click on the Download button right after, it reset and I can't download the file. I still have to wait a few seconds in order to download, expect I have to make the countdown myself in my head. Is there any way to fix this behavior ?

Thanks a lot

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
This happens due to megaup having a serversided check to make sure that you actually waited. Nothing we can do to fix this. Sorry!
