### ISSUE TITLE
newforex.online

### ISSUE THREAD

**Issue by MohammedElsayad** [FastForwardTeam/FastForward#188]
### Domain

https://newforex.online/

### Link

https://newforex.online/can-forex-brokers-be-trusted/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
Please give the original site link.

**Comment by dhana-exe** [comment]
Proxy or VPN detected - Please disable to access this website!

i think this is pure from the sites due to miss setting... so this is bug from site itself... not from addons...
