### ISSUE TITLE
belinfo.my.id

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#189]
### Domain

https://anisub.my.id/stream/komi-san-wa-comyushou-desu-episode-4/

### Link

https://belinfo.my.id/sl/MjAyMS0xMC0yNyAxODowNzoyNQ==

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
anisub is a domain error and the belinfo returns a cloudflare ssl error
