### ISSUE TITLE
inafut.com NSFW

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#190]
### Domain

https://www.niihen.com/2021/11/yamitsuki-pheromone.html

### Link

https://www.inafut.com/p/ads.html?download=YUhSMGNITTZMeTkzZDNjdWJXbHljbTl5WldRdWRHOHZabWxzWlhNdk1VeFFUMEpKUlVzdlcwNWxhMjlRYjJsZFgxbGhiV2wwYzNWcmFWOVFhR1Z5YjIxdmJtVmZWR2hsWDBGdWFXMWhkR2x2Ymw4dFh6QXlYMXMzTWpCUVhWdHVaV3R2Y0c5cExtTmhjbVZkTG0xd05GOXNhVzVyY3c9PQ==

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
inafut seems to be a non existing site anymore?
