### ISSUE TITLE
Linkvertise.com is no longer bypassed

### ISSUE THREAD

**Issue by glencoe2004** [FastForwardTeam/FastForward#192]
### Domain

https://linkvertise.com

### Link

https://linkvertise.com/161996/Loledv11/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
![image](https://user-images.githubusercontent.com/62519659/140619137-33291aa6-3996-40dd-9c8d-0741a3c11577.png)
The /1 breaks the bypass. PR soon:tm:
![image](https://user-images.githubusercontent.com/62519659/140619181-067f99eb-c375-4d1e-a18e-2bcb103afa33.png)
