### ISSUE TITLE
The extension suddenly gets uninstalled. Please help.

### ISSUE THREAD

**Issue by TrappyPlayz** [FastForwardTeam/FastForward#197]
### Domain

https://github.com/FastForwardTeam/FastForward/

### Link

??

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhana-exe** [comment]
The solution is
extract the addons from rar/zip
and then drag and drop the files to chrome extension....


if you drag and drop the extension while it still on rar/zip... they will dissapear

**Comment by lem6ns** [comment]
@TrappyPlayz If this worked, please close the issue. Thanks! 👍
