### ISSUE TITLE
Tei.ai a.k.a Tii.Ai  and ckk.ai broke on chromium based browser and firefox for android all versions

### ISSUE THREAD

**Issue by kevin01523** [FastForwardTeam/FastForward#198]
### Domain

Tii.ai ckk.ai

### Link

https://tei.ai/gQZd
https://tei.ai/JPZFr
### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

Last merged commit broke it for me please test before merging

Tei.ai broke on the commits 10 days ago last 
Known working commit is 
a9ba4b3e4b51216f31781c8ac52603198a776ed8

More info:
Tii.ai links basically redirect or goes into tei.ai link
So that's why tii.ai and ckk.ai is bypassed by fast forward
Im not sure which commit broke it but fastforward doesn't recognize tei.ai links or loan2host links

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin01523** [comment]
This is still broken but works on previous definitions on firefox and kiwi
@NotAProton

**Comment by Tenome** [comment]
Broken for me as well. Latest Firefox version. Example:
https://tei.ai/xVDhCep
