### ISSUE TITLE
Starlink account login failure

### ISSUE THREAD

**Issue by Brettflan** [FastForwardTeam/FastForward#199]
### Body

Starlink recently overhauled their website's login and account portal, and something they've changed now triggers an authentication error (it specifically returns "INVALID CREDENTIALS") if FastForward or the older Universal Bypass is enabled. Similarly, their account recovery form fails to work with an "UNKNOWN ERROR" message returned.

Disabling FastForward / Universal Bypass allows login.

This is their login page:
https://api.starlink.com/auth-rp/auth/login?returnUrl=https%3A%2F%2Fwww.starlink.com%2Faccount

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
See: https://www.reddit.com/r/Starlink/comments/qr7c5z/comment/hlmnhoh/?utm_source=reddit&utm_medium=web2x&context=3
