### ISSUE TITLE
Add `out.reddit.com`

### ISSUE THREAD

**Issue by NatoBoram** [FastForwardTeam/FastForward#200]
### Domain

out.reddit.com

### Link

https://out.reddit.com/t3_qrrg2s?url=https%3A%2F%2Ftwitter.com%2Fpipipoko_%2Fstatus%2F1458801910945751040&token=AQAAAteNYYzuOVBwFbJ1q1SBlbyQfsHQtffCx5uuHAwAvjk-C1Jd&app_name=android

### Version

Version `0.1873` · Bypass definitions `1da582a`

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### (Optional) Anything else?

Reddit's mobile app have started to add a redirector to track outgoing links. I'm not exactly sure how FastForward works, but here's my solution using the template in the extension's settings.

```javascript
// https://out.reddit.com/t3_qrrg2s?url=https%3A%2F%2Ftwitter.com%2Fpipipoko_%2Fstatus%2F1458801910945751040&token=AQAAAteNYYzuOVBwFbJ1q1SBlbyQfsHQtffCx5uuHAwAvjk-C1Jd&app_name=android
domainBypass("out.reddit.com", () => {
    location.href = new URL(location.href).searchParams.get("url")
})
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
im not sure but i think that it works exactly the same, we bypass wait times and click requirements, none of those relate to the reddit out link which would potentially just makes it slower

**Comment by NatoBoram** [comment]
Is it possible to benchmark it?

Reddit's servers are very unstable and slow, sometimes it takes multiple seconds to get a first response out of `reddit.com`. I would be very surprised if something can make it slower...

**Comment by NatoBoram** [comment]
\*Sigh*

**Comment by NatoBoram** [comment]
Is it possible to benchmark it?

Reddit's servers are very unstable and slow, sometimes it takes multiple seconds to get a first response out of `reddit.com`. I would be very surprised if something can make it slower...

**Comment by NotAProton** [comment]
this can be a tracker bypass

**Comment by NatoBoram** [comment]
Oof, it's been a while.

Since the code is already provided, can we get it added somehow?

**Comment by aaronliu0130** [comment]
@NotAProton Can this be a trakcer bypass?

**Comment by NotAProton** [comment]
Yep
