### ISSUE TITLE
Akwam

### ISSUE THREAD

**Issue by ahmed98Osama** [FastForwardTeam/FastForward#201]
### Domain

https://go.akwam.cx/link/78668

### Link

https://go.akwam.cx/link/78668

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://akwam.cx/movie/4647/shang-chi-and-the-legend-of-the-ten-rings

orginal link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
```
ensureDomLoaded(() => {
	domainBypass(/go\.akwam\.(cc|cx|net|im)/, () => {
		awaitElement("a.download-link[href]", a => {
			safelyNavigate(a.href)
		})
	})
})
```
