### ISSUE TITLE
Re write build system in node.js

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#204]
### Body

Bash scripts are not cross-platform, and node has really good JSON support.

Use:
https://github.com/oncletom/crx
https://github.com/mozilla/web-ext

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
buiding the web ext works well without the web-ext package, i will check what that does

**Comment by reashetyrr** [comment]
i just checked, seems as if the chromium crx file is also just a zip named .crx, we can build that easily already
