### ISSUE TITLE
Add auto-updating for brave

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#205]
### Body

Should be possible, https://github.com/brave/brave-browser/issues/2457

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by untuned** [comment]
Now that this is on the Chrome webstore, this shouldn't be needed anymore?

**Comment by NotAProton** [comment]
yes

**Comment by rollingmoai** [comment]
> Now that this is on the Chrome webstore, this shouldn't be needed anymore?

Now that this is removed on the Chrome webstore, this is needed again

**Comment by NotAProton** [comment]
Now it is back on the webstore
