### ISSUE TITLE
threadbolts.com isn't bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#207]
### Domain

threadbolts.com

### Link

https://threadbolts.com/buy-car-insurance-online-affordable-car-insurance-best-car-insurance/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Linux

### (Optional) Anything else?

Original link: https://defaultfreeshort.in/DSqw

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Fixed, thanks for the report
