### ISSUE TITLE
ytsubme.com isn't bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#208]
### Domain

ytsubme.com

### Link

https://www.ytsubme.com/_/RrSjh/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vojtak42** [comment]
bypass?

**Comment by abadawe-dev** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/bc5e891e390174ed97246f45baaa25e06c79fe61, please close.
