### ISSUE TITLE
New bypass for vk.com

### ISSUE THREAD

**Issue by shifting-tides** [FastForwardTeam/FastForward#209]
### Domain

vk.com

### Link

https://vk.com/away.php?to=https%3A%2F%2Ftwitter.com%2FTwilledW%2Fstatus%2F1459919961628057600

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

vk.com, or VKontakte is the biggest social platform in Russia. A bypass could be used for bypassing their redirect system.

https://vk.com/away.php?to=https%3A%2F%2Ftwitter.com%2FTwilledW%2Fstatus%2F1459919961628057600

equals
https://twitter.com/TwilledW/status/1459919961628057600

![image](https://user-images.githubusercontent.com/63145386/142026975-af1fce74-fbc3-4aab-bd77-7bae96f3d664.png)

https://vk.com/away.php?to=https%3A%2F%2Fdiletant.media%2Farticles%2F45093108%2F&post=-142978854_219333&cc_key=

equals
https://diletant.media/articles/45093108/

![image](https://user-images.githubusercontent.com/63145386/142028140-e674da32-32e0-4c0b-af2c-a6ce461e24e8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by undeadjess** [comment]
Fixed in #900 
Sorry that took so long!
