### ISSUE TITLE
Can't Unistall Firefox Extension

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#21]
Installed from: https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/

Version: 0.1809

![image](https://user-images.githubusercontent.com/81463636/133110148-7280a453-41ad-42bf-988d-300851c06112.png)

### To reproduce:

1.  Install Addon from store
2.  Close Firefox and restart your computer
3. Open Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by undeadjess** [comment]
i cant reproduce this, i can still uninstall. whats the "Why?" button?

**Comment by lem6ns** [comment]
Cannot reproduce with steps provided

**Comment by NotAProton** [comment]
> i cant reproduce this, i can still uninstall. whats the "Why?" button?

https://support.mozilla.org/en-UK/kb/cannot-remove-add-on-extension-or-theme

**Comment by NotAProton** [comment]
Deleting the files locally from my profile folder solved it.
