### ISSUE TITLE
shorte.st

### ISSUE THREAD

**Issue by Jayyyson** [FastForwardTeam/FastForward#227]
### Domain

https://shorte.st

### Link

http://sh.st/qK5Km (NSFW ADS)

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Yes, you can click skip ad, but there is just so much NSFW content + I have to stare at it for 8 seconds before I can skip it. Also tons of scam ads and a download started without my permission.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xbjfk** [comment]
seems like the wait time is enforced server side, so crowd bypass is probably the only solution

**Comment by xbjfk** [comment]
Still seems present.

**Comment by lostdusty** [comment]
@NotAProton crowdbypass

**Comment by xbjfk** [comment]
not yet, stale bot.
