### ISSUE TITLE
FileDM

### ISSUE THREAD

**Issue by Cox-school** [FastForwardTeam/FastForward#229]
### Domain

https://filedm.com/

### Link

https://filedm.com/V8GTP

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

I'm using the latest version on Chrome Store, and it doesn't bypass.
Could someone please write a bypass for it?
It's very annoying as well as you need to download a file to get the link. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Download and run a suspicious exe to get a link?

**Comment by Cox-school** [comment]
Yes, like linkvertise again.

**Comment by kubuntuclaps** [comment]
I have a way to bypass filedm, will be awesome if they can add it into the extension.

https://github.com/kubuntuclaps/FileDM-Bypass

**Comment by lostdusty** [comment]
hey @kubuntuclaps could you make a PR to this repo with the bypass?

**Comment by kubuntuclaps** [comment]
> hey @kubuntuclaps could you make a PR to this repo with the bypass?

I'm bad at JS and i don't think this bypass still working, i erased the repo so if you want see the code another guy reuploaded it: https://github.com/Diego0918/FileDM-Bypass

**Comment by jaxp2** [comment]
Here's my custom one for fastforward

domainBypass("filedm.com",()=>{awaitElement("a#dlbutton",a=>{safelyNavigate("http://directdl.xyz/dm.php?id="+a.href.split("_")[1])})})
