### ISSUE TITLE
egao.in 

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#24]
### Domain

https://doronime.id/anime/tensei-shitara-slime-datta-ken-2nd-season-part-2/episode-23

### Link

https://egao.in/?id=eyJpdiI6IkhOVmpVNlNJa0JtVGJxWDNUMEFaMkE9PSIsInZhbHVlIjoibk5NWHNteUk4QWJheWdoZEZwMmRWdz09IiwibWFjIjoiZTI4NjIwMjMwZWQzNjkxMDdmZWU5OGI5N2Y1OGYzY2NlZGNiMjY3YmNiODQ4YTQxMzBkZTJjYTZhMDliMWFkOCJ9

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Would you test this please.

```
domainBypass("egao.in", () => {
    
    
	setTimeout(function (){
	    awaitElement("button#SafelinkChecker", a => {
        a.click();
        })
        
        setTimeout(function (){
            awaitElement("a#SafelinkGenerate", b => {
            safelyAssign(b.href);
        })}, 2000);

    }, 2500);
})
```

EDIT:
@lem6ns has a much better bypass in #33

**Comment by godra9** [comment]
> Would you test this please.

it worked well.

**Comment by NotAProton** [comment]
Fixed, thanks for the report
