### ISSUE TITLE
Report crowd bypass beta issues here

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#240]
Edit 10/12/2021: The beta has ended and we have started rolling out crowd bypass to everyone, thanks to everyone who participated. Please switch to the latest stable version here: https://github.com/FastForwardTeam/FastForward#readme

**Comment by SuperMarioMakerII** [comment]
crowd bypass not working
https://cararegistrasi.com/L9iAvEFx
https://cararegistrasi.com/z5wRX5H
