### ISSUE TITLE
 Official declaration of "I'm not done" and starting of crowd bypass service

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#241]
Edit 11/12/2021: The beta has ended and we have started rolling out crowd bypass to everyone, thanks to everyone who participated. Please switch to the latest stable version here: https://github.com/FastForwardTeam/FastForward#readme

**Comment by NotAProton** [comment]
lol

**Comment by FinderID** [comment]
is this beta version? and still can get update?

thanks before

**Comment by NotAProton** [comment]
@FinderID The beta has ended and we have started rolling out crowd bypass to everyone. Please switch to the latest stable version here: https://github.com/FastForwardTeam/FastForward#readme

**Comment by FinderID** [comment]
thank you @NotAProton
