### ISSUE TITLE
portsolect.org

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#242]
### Domain

portsolect.org

### Link

http://inpiyfo.portsolect.org/erec.php?nn=1o1561a7940cb27c7_1631.27f3977.A017grfg7581r020s9_n51515.05aybMDVmMHExazhvbjdj0x697l

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### (Optional) Anything else?

redirects from http://inpiyfo.portsolect.org/erec.php?nn=1o1561a7940cb27c7_1631.27f3977.A017grfg7581r020s9_n51515.05aybMDVmMHExazhvbjdj0x697l
to https://quotes.ecoverage.com/love-most-rdl/?src=88-6526-241&kw=Erec0112_153b6lm-&afid=88&subid=6526&trans_id=102b149c040ca062d915081cd02669&cid=241&offer_ref=eCover210618112723&creative_id=0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bogachenkove** [comment]
How did you get to this site `http://inpiyfo.portsolect.org/erec.php?nn=1o1561a7940cb27c7_1631.27f3977.A017grfg7581r020s9_n51515.05aybMDVmMHExazhvbjdj0x697l`?
