### ISSUE TITLE
codecomets.com

### ISSUE THREAD

**Issue by pikawee** [FastForwardTeam/FastForward#247]
### Domain

defaultfreeshort.in

### Link

https://m.defaultfreeshort.in/hW9dE

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Fixed, thanks for the report
