### ISSUE TITLE
mealob.com

### ISSUE THREAD

**Issue by FinderID** [FastForwardTeam/FastForward#249]
### Domain

https://www.mkvcinemas.pl/

### Link

https://www.mkvcinemas.pl/shang-chi-and-the-legend-of-the-ten-rings-2021-movie-bluray-hindi-dubbed-300mb-480p-1gb-720p-2gb-1080p-f/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

bypass at the download page, thanks 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
is it fixed?

**Comment by FinderID** [comment]
sorry, i think the website is not give the real link

i have try with use fastforward addon and not, the result is same

so, i think the problem come from the site "mkvcinemas.pl"


thanks @NotAProton :)

**Comment by FinderID** [comment]
the result always "bad request" when i'm not use the addon

but, if you think the shortlink is not yet listed from fastforward, i will reopen this issue
