### ISSUE TITLE
request pahe.ph bypass

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#25]
### Domain

https://pahe.ph/mortal-kombat-legends-battle-of-the-realms-2021/

### Link

https://intercelestial.com/?id=NEtLUW9ybmRNT0t0eDU5dUhzdXVreVQvaDlvc0F0ZENOMzJvVTNHMGF1UEpYWDljWFlLQWdUeVJ4YXN4MlZkdTJHbTRZK3cxT0pobTh0NWs4QXNtbUxhQlNURVVvNHVyNWZhby9ZaG93cEE1K1RpWURjVjZUSUNKZVhBQ2Nkc3MrSFhNQk5jWUxmeVVjV2FGeHVzOU1URHV4c1d5SlJaTmVEMDJ1aEtuSUlZUERLR0RGL3FoWG9SR0piWFZkRFRvY1pJQTZ3Ukp6T055ZHpBWHVNQW9EUT09

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Will be fixed when server is up.
