### ISSUE TITLE
Gestyy isn´t by pass

### ISSUE THREAD

**Issue by Juniorjoose** [FastForwardTeam/FastForward#259]
### Domain

http://gestyy.com/

### Link

http://gestyy.com/ep965w NSFW

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Juniorjoose** [comment]
shorte.st banner appear

**Comment by NotAProton** [comment]
Duplicate of #47
