### ISSUE TITLE
i98.info isn't bypass

### ISSUE THREAD

**Issue by mmtech2012** [FastForwardTeam/FastForward#27]
### Domain

https://i98.info

### Link

https://i98.info/648647_hidden_life.php

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

example : https://i98.info/648647_hidden_life.php
accessed from https://benameiran.com/dracula_series/dracula_s01e05/#
the green buttons

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
~~todo: add bypass for https://benameiran.com since if you click the button, it sends over "requested_download_link"~~

resolved in #32
