### ISSUE TITLE
paid4link.com not bypassed

### ISSUE THREAD

**Issue by mrpotensial** [FastForwardTeam/FastForward#270]
### Domain

https://paid4.link/dlGCuqL

### Link

https://paid4.link/dlGCuqL (NSFW)

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhana-exe** [comment]
no fix yet?

**Comment by dhana-exe** [comment]
https://paid4.link/ZAIc5ZW

**Comment by dhana-exe** [comment]
![image](https://user-images.githubusercontent.com/29838157/169497894-a05799fc-b08e-4c8f-9d0d-535950dc2c07.png)
maybe good if the fastforward click auto click "click here to continue" after we complete the captcha

and 1 other problem....
even though i already skip the link several times, when the captcha appear.... they didn't skip automatically to the destination....
https://paid4.link/BIb2q

also
need to automate this link...
![image](https://user-images.githubusercontent.com/29838157/169498430-69a5aa95-b2cf-4642-ab99-6fb6d43d47d1.png)
