### ISSUE TITLE
adtival.network not bypassed

### ISSUE THREAD

**Issue by abidjauhar17** [FastForwardTeam/FastForward#271]
### Domain

https://www.adtival.network

### Link

https://www.adtival.network/SjStyplR

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
New-bypass > Broken bypass

https://github.com/FastForwardTeam/FastForward/blob/c976c3f0aa097fbc16d051d287353cd040620dfd/src/js/injection_script.js#L504
