### ISSUE TITLE
[request] api.torob.com

### ISSUE THREAD

**Issue by DRSDavidSoft** [FastForwardTeam/FastForward#276]
Could you please also add rules for this domain to be bypassed server-side?  It's not a 30x redirect, there is an `<script>` in the response that manually changes `window.location.href`.

Using uBlock Origin and/or Pi-hole, the `api.torob.com` domain is blocked, so it'd be awesome if Fast Forward could allow bypassing this kind of redirection.  Thanks!
         
### Domain

https://api.torob.com/

### Link

https://api.torob.com/v4/product-page/redirect/?prk=321b2e7e-0f1d-488b-8aff-e6978b505f9b&source=next&uid=&discover_method=direct&_bt__experiment=direct&device=desktop&_url_referrer=&_http_referrer=&_ft__has_badge_desktop=True

### Expected result
https://www.texnoli.com/product/%d9%85%da%a9-%d8%a8%d9%88%da%a9-%d8%a7%db%8c%d8%b1-%db%b1%db%b3-%d8%a7%db%8c%d9%86%da%86-%db%b2%db%b0%db%b2%db%b0-%d9%85%d8%af%d9%84-mgn63/?utm_medium=PPC&utm_source=Torob

### Notes
- Originally posted at: https://github.com/Sainan/Universal-Bypass/issues/1775

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DRSDavidSoft** [comment]
I would like to ask for this to be resolved.

**Comment by DRSDavidSoft** [comment]
I would still like to ask for this to be resolved.

**Comment by abadawe-dev** [comment]
Seems to work, test again and close.
