### ISSUE TITLE
intipanime.com 

### ISSUE THREAD

**Issue by justaordinaryman** [FastForwardTeam/FastForward#279]
### Domain

https://safe.intipanime.com/

### Link

https://bakadame.com/?6b2053bcf2=cG50Z1NXN2JsLys0ODc5NS84cXlLYzBFcGh5ZEovdHc5NU9yTmxvbmwrSVZmUUFYdTBuYXZ4VGFHRWFodE5NcGIxZ3dNNitiTUIxWExtUkNzalRTQjFKWXFtQVJNSnpYbU9VN0N1U0k1aXhkeUhOUy9nZGR3NkdnRmJMVFZOTTJtcFdhV3Y5VjhXbjRYY2FsV3pGU3NRPT0=

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Linux

### (Optional) Anything else?

Fast Forward Vesion : Version 0.1880 · Bypass definitions c976c3f (up to date)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3xploiton3** [comment]
another example:
https://bakadame.com/?6b2053bcf2=M1ZIN0o1dnIvUVVHdUpOSktWV0ZLMlZnQ1JZbGtKeVIzRnF1NlREc3NTR0JHWmdYbzhDS2xMN0wyY2Y5bXA3aUNlUWRXSmx1MEw4dHJMeXBUK3lKSUhiN3YxT1IyRlMxYTRibzYrVjNneERudkpTeTRMRW1kNWhUMS9zSEZCZFY2SGRBT2M0V0xsZUMyV1RhSWVmWEVKMkt6M2FyaUpsek02WTluUXhiaENBSzJRYVBEeG1pM1g5MUVWUjhqVHBVdGx3MkFvU0g1Mlp4TldRSEdINUYyWk90OFNQZy8raUZiR2pJNmdyK0g3cz0=

reference:
https://bakadame.com/buddy-daddies-sub-indo/
