### ISSUE TITLE
techynroll.com is not bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#28]
### Domain

Techynroll.com

### Link

https://techynroll.com/does-refinancing-hurt-your-credit/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Original link: https://defaultfreeshort.in/DSqw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Done. Thanks for a good report  : ) 

```
domainBypass("techynroll.com", () => {
    awaitElement("a#enablebtn", a => {
        safelyAssign(a.href);
    })
})

```

Smaller:

`domainBypass("techynroll.com",()=>safelyAssign(document.getElementById("enablebtn").href))`
