### ISSUE TITLE
Bypass for Work.ink

### ISSUE THREAD

**Issue by LaTiquee** [FastForwardTeam/FastForward#284]
### Domain

Work.ink

### Link

https://work.ink/en/l/g4/pulsivedownload

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coreknee** [comment]
wait, i have the same thing RIP
