### ISSUE TITLE
[New Bypass] duckduckgo advertisements

### ISSUE THREAD

**Issue by WormChickenWizard** [FastForwardTeam/FastForward#285]
### Domain

duckduckgo.com

### Link

https://duckduckgo.com/y.js?ad_provider=bing&eddgt=CwThWqAjKQPSlL5wUBemyw%3D%3D&rut=02a93ca2f303f4e5b6f0f39d80908900f50e33d7e0362543852a8c85b57204c9&u3=https%3A%2F%2Fwww.bing.com%2Faclick%3Fld%3De8aQ7kkTT2Y%2DzFlRCj%2DPC6BDVUCUx03yr13d4OlEG_ark7MXvAxSY0VU3DDXDkIPx76iKZ_WqK0cdpq3I87FB4nvQEiXZXsxzE0BFmUiaIHd8xWrsiYjymUSCLsu4rPie4_x7%2DzU1fZ0NexK%2DP%2DDc5RhC4XiJGAAilb4_i5MZNd9sqvhh4mPlPgTnFpRjhybdKOxHBFg%26u%3DaHR0cHMlM2ElMmYlMmZjbGlja3NlcnZlLmRhcnRzZWFyY2gubmV0JTJmbGluayUyZmNsaWNrJTNmbGlkJTNkOTI3MDAwNjY0NzI0NDU2NDElMjZkc19zX2t3Z2lkJTNkNTg3MDAwMDc0MDkwODQyOTAlMjZkc19zX2ludmVudG9yeV9mZWVkX2lkJTNkOTc3MDAwMDAwMDg3ODg2MTklMjZkc19hX2NpZCUzZDU5MzI1MTU2NCUyNmRzX2FfY2FpZCUzZDE0Njc0NDY4MDI0JTI2ZHNfYV9hZ2lkJTNkMTI1MjMzMTUyNjE3JTI2ZHNfYV9saWQlM2RwbGEtMTQyNjYxODkyNDI1NyUyNiUyNmRzX2VfYWRpZCUzZDc4OTU4ODQ3NzcxNzA3JTI2ZHNfZV90YXJnZXRfaWQlM2RwbGEtNDU4MjU1ODMzMDU0OTUyNSUyNmRzX2VfcHJvZHVjdF9ncm91cF9pZCUzZDQ1ODI1NTgzMzA1NDk1MjUlMjZkc19lX3Byb2R1Y3RfaWQlM2Q1MjU0NzglMjZkc19lX3Byb2R1Y3RfY291bnRyeSUzZFVTJTI2ZHNfZV9wcm9kdWN0X2xhbmd1YWdlJTNkRU4lMjZkc19lX3Byb2R1Y3RfY2hhbm5lbCUzZE9ubGluZSUyNmRzX2VfbmV0d29yayUzZHMlMjZkc191cmxfdiUzZDIlMjZkc19kZXN0X3VybCUzZGh0dHBzJTNhJTJmJTJmd3d3LmdhbWVzdG9wLmNvbSUyZnZpZGVvLWdhbWVzJTJmcGMtZ2FtZXMlMmZwcm9kdWN0cyUyZnVucmVhbC1nb2xkJTJmNTI1NDc4Lmh0bWwlM2Z1dG1faWQlM2Q0MDI0MDUwMjUlMjZnY2xpZCUzZDg1MGIwMzk0MGJhMDEyZGIxODYyNjI1YzNkOTJmNWU2JTI2Z2Nsc3JjJTNkM3AuZHMlMjZtc2Nsa2lkJTNkODUwYjAzOTQwYmEwMTJkYjE4NjI2MjVjM2Q5MmY1ZTYlMjZ1dG1fc291cmNlJTNkYmluZyUyNnV0bV9tZWRpdW0lM2RjcGMlMjZ1dG1fY2FtcGFpZ24lM2QlMjUyNFBMQV8lMjUyNEJOR18lMjUyNE5CX0NhdGVnb3J5X0RpZ2l0YWxfR2FtZXNfRnJhbmNoaXNlJTI2dXRtX3Rlcm0lM2Q0NTgyNTU4MzMwNTQ5NTI1JTI2dXRtX2NvbnRlbnQlM2REaWdpdGFsX0dhbWVzX1RvcF9GcmFuY2hpc2VfQWxsX090aGVycw%26rlid%3D850b03940ba012db1862625c3d92f5e6&vqd=3-275724812813702216950189957987412199680-149161889907757588238746424526755342070&iurl=%7B1%7DIG%3D62E07EFC9F6B4AA6AFB683CC44C0BEA6%26CID%3D274DE8412F21631F36C7F9582EC76203%26ID%3DDevEx%2C5803.1

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Advertisements on duckduckgo have multiple redirects when clicked on. It starts with the https/duckduckgo.com/y.js* site then redirects to a https://clickserve.dartsearch.net/ then redirects to the actual site. (I think. Brave stopped it at the clickserve.dartsearch.net page asking if I wanted to continue citing that the domain may track me.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AliahX** [comment]
I would recommend using Ublock origin as well as fastforward, so you don't get any ads.
Also, the link you sent does no longer function so if you still want us make a bypass you need to try get another link
