### ISSUE TITLE
exe.io isn't passed

### ISSUE THREAD

**Issue by danteyc** [FastForwardTeam/FastForward#287]
### Domain

https://exe.io

### Link

http://exe.io/yVH9YH

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #117
