### ISSUE TITLE
Masteredutech.com is not bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#29]
### Domain

Masteredutech.com

### Link

https://masteredutech.com/3-ways-to-recover-deleted-photos-on-any-android-device#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Original link: https://defaultfreeshort.in/DSqw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
```
domainBypass("masteredutech.com", () => {
	ensureDomLoaded(() => {
		safelyAssign(document.querySelector('.btn-captcha').href)
	})
})

```

Smaller:
`domainBypass("masteredutech.com",()=>safelyAssign(document.querySelector('.btn-captcha').href))`

**Comment by undeadjess** [comment]
fixed. thanks for the report!
