### ISSUE TITLE
psarips changed url again (psa.pm)

### ISSUE THREAD

**Issue by mpottens** [FastForwardTeam/FastForward#290]
### Domain

https://psa.pm/

### Link

https://psa.pm/

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### Anything else?

```hrefBypass(/((psarips\.(com|net|org|eu|in|one|xyz|uk))|(psa\.one))\/exit\//,()=>ifElement("form[name='redirect']",f=>{```

should be:

```hrefBypass(/((psarips\.(com|net|org|eu|in|one|xyz|uk))|(psa\.(one|pm)))\/exit\//,()=>ifElement("form[name='redirect']",f=>{```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gabanders** [comment]
If you're still following this, I implemented this change in this PR:
https://github.com/FastForwardTeam/FastForward/pull/619

But FastForward still fails to bypass psa.pm exit links after the commit (3b9c441). Can you check whether there are further changes that we need to do to successfully bypass psa.pm?
