### ISSUE TITLE
MegaURL isn't bypassed

### ISSUE THREAD

**Issue by Pablo198989** [FastForwardTeam/FastForward#291]
### Domain

https://megaurl.in

### Link

http://megaurl.in/AloyUndergarment                                 NSFW

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Hi

ive wanna download something from this user
https://www.deviantart.com/dddkhakha1
But cannot bypass MegaURL links, his written soluctions not work for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by becauseimnoob** [comment]
+++++  @0xc60f 

@AliahX 

@BS-zombie

@lem6ns

@lem6ns

@NotAProton

@untuned

**Comment by lem6ns** [comment]
do not do that please
