### ISSUE TITLE
Icon still outdated

### ISSUE THREAD

**Issue by multiwastaken** [FastForwardTeam/FastForward#292]
### Body

well... what the title said

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/93272004/147850596-6d146103-989d-4ffe-9373-614d35da0c21.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AliahX** [comment]
This (to my knowledge) has been fixed. The only place on chrome that still uses the old logo is the branding on the chrome web store @BS-zombie
