### ISSUE TITLE
[REQ] usersdrive.com delay timer bypass

### ISSUE THREAD

**Issue by Pandoriaantje** [FastForwardTeam/FastForward#296]
### Domain

https://usersdrive.com/

### Link

https://usersdrive.com/tj8k1kazfjfg.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Site has a 17sec countdown/ delay timer and CAPTCHA.
Any way to bypass/remove the delay?
Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rutagoat** [comment]
```
domainBypass("usersdrive.com", () => {
	ensureDomLoaded(() => {
		document.getElementsByClassName('seconds')[0].innerHTML = 0;
	})
})
```
try adding this code in custom bypasses if it works tell me (works for me) and if somebody is good in js please modify this and share the stable code i am not that pro in JS

this code will reduce the seconds to 0 and enabled the download button and only thing to do is recaptcha solve
