### ISSUE TITLE
work.ink

### ISSUE THREAD

**Issue by coreknee** [FastForwardTeam/FastForward#299]
### Domain

https://work.ink/

### Link

https://work.ink/en/l/yU/VegaX

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coreknee** [comment]
i need this bypass rn

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #284.
