### ISSUE TITLE
fc-lc seems not be bypassed anymore

### ISSUE THREAD

**Issue by Darkmaster006** [FastForwardTeam/FastForward#300]
### Domain

https://fc-lc.com/

### Link

https://fc-lc.com/penl2aVI

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

I've done it already in here https://fc-lc.com/penl2aVI and I tried it again to see if it bypassed itself but it didn't, so it must not be working.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool22** [comment]
I noticed this too.
