### ISSUE TITLE
Tny.so

### ISSUE THREAD

**Issue by HectorThe** [FastForwardTeam/FastForward#309]
### Domain

https://tny.so/

### Link

https://tny.so/ju02mR9p?

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

![image](https://user-images.githubusercontent.com/97747985/149541700-b281529f-9b42-484b-98e3-0b4c99666df9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egypt00king** [comment]
I second this request
