### ISSUE TITLE
premads.com

### ISSUE THREAD

**Issue by akn19** [FastForwardTeam/FastForward#313]
### Domain

premads.com

### Link

https://www.premads.com/p/spxchantsr4p1md.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rahaaatul** [comment]
https://www.premads.com/p/spfl23320mg.html
