### ISSUE TITLE
Hola a todos ese lin lo frecuento y siempre no lo salta tengo que esperar los 10s siempre

### ISSUE THREAD

**Issue by esteveper** [FastForwardTeam/FastForward#321]
### Domain

https://exey.io/blog/2019/06/10/benefits-of-tunnel-based-transit-system/

### Link

https://exey.io/blog/2019/06/10/benefits-of-tunnel-based-transit-system/

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

_Ese_ link lo frecuento y siempre no lo salta tengo que esperar los 10s siempre

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #150
