### ISSUE TITLE
Please add a bypass for work.ink

### ISSUE THREAD

**Issue by Little-Night-Wolf** [FastForwardTeam/FastForward#326]
### Domain

https://work.ink/

### Link

https://work.ink/en/l/3w/XENOSX64

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

The website is similar to linkvertise and its ads are very annoying and abusive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #299
