### ISSUE TITLE
always redirected to wrong/dead link

### ISSUE THREAD

**Issue by mozozky** [FastForwardTeam/FastForward#330]
### Domain

https://linegee.net/

### Link

https://linegee.net/?link=54993c6be7&hash=5e75033e56d27e2cb6063adb06856d4a&sign=1c8e7a1b3d7d27bc479676791a2a4adb

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/29743624/151703012-3c884a49-964d-412f-8548-18cd10f0544b.png)
if i dont use bypass worked fine, but if use the bypass it'll look like this 
![image](https://user-images.githubusercontent.com/29743624/151703065-422e655f-0453-4aab-bab4-bd3056c485a5.png)

this is shortlink from pahe.ph if you're wondering 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AliahX** [comment]
This gives me a 404 without any extensions at all can you confirm it still works?

**Comment by mozozky** [comment]
The link still work, but it cannot be copied directly from url bar, you have to manually go to pahe.ph and click on the url from the wwebsite

Can you try it? Sorry if it's taking too much, it has been like this since last year

**Comment by AliahX** [comment]
Yes I've noticed that. The website is also being horrible and opening the debugger whenever i use dev console, but i will find a way.
Hopefully we can bypass this soon.

**Comment by mozozky** [comment]
Thanks for the response!
Hope the work goes well

GL
