### ISSUE TITLE
acortame.xyz

### ISSUE THREAD

**Issue by mandycuba** [FastForwardTeam/FastForward#331]
### Domain

acortame.xyz

### Link

https://acortame.xyz/#aHR0cHM6Ly9mYy1sYy5jb20vT0hwdA==

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tacohitbox** [comment]
```js
domainBypass("acortame.xyz", () => {
    if (window.location.hash) unsafelyNavigate(atob(window.location.hash.substr(1)))
})
```
Add this to your custom bypasses for now. I'll make a PR to add this.
