### ISSUE TITLE
linegee.net

### ISSUE THREAD

**Issue by rigaz29** [FastForwardTeam/FastForward#333]
### Domain

https://linegee.net

### Link

https://linegee.net/....

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

from : https://intercelestial.com/?id=UDdPTWFjQlpxS1RiRUFOMUVwbFdkZWtCVmJrSDhDNkQyU0xDd1lvaWZyL0F0MytQNldERldUamYvUVVJV1U2NGVucU5CSWhiV0RZeVpPKzFoSnF3dEN5eFVGSVpRVzlDWG0zcS92OUhhN05peVphdTRMZGl5RXNNVGFLaVN3NjUrZTYzMFZVcXR3U3pmQ04zTU5tWGZHWXlFK1ZmMzZzNE1JczVtb1hxUFo3eEkrM2lhcHJYVUtTRURyaHdOSC9UTG4rbXhEMkNKTFFicnArejRQWEQvUT09

not correct link : https://uptobox.com/A1fcaeaebb9839
correct link : https://uptobox.com/43jsrx4j9f2n

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnJust1ce** [comment]
Could you please send an example link for the website?
also what is the from link for? i cant see any relation
