### ISSUE TITLE
Leechall ad-sites

### ISSUE THREAD

**Issue by marcovecchione** [FastForwardTeam/FastForward#335]
### Domain

https://mdn.rest/

### Link

https://mdn.rest/the-biggest-mistakes-you-can-make-as-a-stocks-trader-in-2022/#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

It is non the exact link, in fact visiting it again it is different. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AliahX** [comment]
Hey i can't manage to access the site, can you make sure the link is correct?

**Comment by marcovecchione** [comment]
Visiting it again doesn't show the same result

Inviato da Yahoo Mail su Android 
 
  Il ven, 4 feb, 2022 alle 4:07, ***@***.***> ha scritto:   


Hey i can't manage to access the site, can you make sure the link is correct?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
