### ISSUE TITLE
Linkvertise Bypass giving 401 unauthorized and then redirecting to linkvertise.com

### ISSUE THREAD

**Issue by CodexScript** [FastForwardTeam/FastForward#336]
### Domain

https://linkvertise.com

### Link

https://linkvertise.com/252997/r4el1lb14ck/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Link is NSFW.

The GET request for the URL https://publisher.linkvertise.com/api/v1/redirect/link/static/252997/r4el1lb14ck returns 401 Unauthorized.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tacohitbox** [comment]
Seems to work fine for me. Might be based around the IP you're on currently.

**Comment by CodexScript** [comment]
After checking with a VPN I can confirm that it was my IP being limited.
