### ISSUE TITLE
Pls add https://shrinke.me/

### ISSUE THREAD

**Issue by Ironize97** [FastForwardTeam/FastForward#347]
### Domain

https://shrinke.me/

### Link

https://shrinke.me/FcSbG0m

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tenome** [comment]
+1

**Comment by IzzyDude** [comment]
I too have encountered this site.
