### ISSUE TITLE
Request - Fumacrom.com/Xervoo.net

### ISSUE THREAD

**Issue by unknowboy1991** [FastForwardTeam/FastForward#348]
### Domain

https://fumacrom.com/

### Link

https://fumacrom.com/1QEII

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Double redirect
1. Fumacrom.com (https://fumacrom.com/1QEII)
2. Xervoo.net (http://xervoo.net/-89918FWBO/1QEII?rndad=1959468642-1644327348)

At last it redirects to the link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknowboy1991** [comment]
The issue is not resolved

**Comment by abadawe-dev** [comment]
Seems to work, test again and close.
