### ISSUE TITLE
drivehub.ws

### ISSUE THREAD

**Issue by chirag127** [FastForwardTeam/FastForward#356]
### Domain

drivehub.ws

### Link

https://drivehub.ws/file/3458859455

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahsaassy** [comment]
I am not sure how exactly you're supposed to bypass this. 
First, it needs access to your drive, creates a folder inside, copies the file over then starts downloading
![drivehub](https://user-images.githubusercontent.com/86418323/156990659-dea6b1a8-0f4c-468d-9875-1bea264c340c.PNG)

**Comment by chirag127** [comment]
.

**Comment by chirag127** [comment]
> I am not sure how exactly you're supposed to bypass this. First, it needs access to your drive, creates a folder inside, copies the file over then starts downloading ![drivehub](https://user-images.githubusercontent.com/86418323/156990659-dea6b1a8-0f4c-468d-9875-1bea264c340c.PNG)

I want to automatically download the folder and bypass the download wall
