### ISSUE TITLE
intercelestial.com

### ISSUE THREAD

**Issue by abidjauhar17** [FastForwardTeam/FastForward#358]
### Domain

https://pahe.li/i-am-legend-2007-uhd-bluray-720p-1080p/

### Link

https://intercelestial.com/?id=OFNkb2M0RUdHNUN3MUhrQWhDOHg2cWk4eDZ0UUVEZk51TTFtd3N2V1BqM1p1dlo5QzVvdmtjRjhBalkyL2RhNHdQMHlIK2gwVlhrTmtyb3M3U2NBMm1wajRZZ1BCTWpCNEE2YlVOQXdHUmpOSW1GSnZNem9CRGYvWkt4OFo5ZlFLWTZnTXIyL01zWkphbHFQZm11aTA5bXVJazN6RHdlVkdnb2pLMTFuWDhwa1cwcllMZUJZMW9jVVk1N1pNVXdMNDhXQnJZZ2FZQWZ3SWhmSmlqVzJwUT09

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

the page is just a white blank when the FastForward extension is enabled, when disabled, the page runs flawlessly

![image](https://user-images.githubusercontent.com/37255346/153849043-f9a166b5-bc14-4233-8b72-12f60465bf07.png)
![image](https://user-images.githubusercontent.com/37255346/153849066-31bb9f31-6b0b-4d5d-99ec-4ea74ab56eb6.png)
![image](https://user-images.githubusercontent.com/37255346/153849293-8df41dbd-fc03-4902-a999-bff4d569378e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmed98Osama** [comment]
no solve yet ?

**Comment by princessmortix** [comment]
Fixed in #758.
