### ISSUE TITLE
linkpoi.me

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#36]
### Domain

https://nekopoi.care/uncensored-skyhd-087-sky-angel-blue-vol-87/

### Link

https://linkpoi.me/DLQ7yWb

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
captcha, use crowd bypass.

**Comment by 3xploitzer0** [comment]
no captcha

![image](https://user-images.githubusercontent.com/56762704/134967881-4ac8597b-bcb0-4ae2-a320-d0f6cad145cc.png)

**Comment by dhana-exe** [comment]
no fix until now?
any issue? the link clear no captcha...

**Comment by 3xploitzer0** [comment]
https://linkpoi.me/aZjI

**Comment by reashetyrr** [comment]
i only had 2 seconds delay?

**Comment by reashetyrr** [comment]
i think what you want bypassed being exey.io?

**Comment by dhana-exe** [comment]
> i think what you want bypassed being exey.io?

i think that's different story....
linkpoi isn't redirect automatically since they need us to click it....

how can you only had 2 second delay? do you use 3rd party script?

**Comment by reashetyrr** [comment]
no just a clean microsoft edge 🤔

**Comment by dhana-exe** [comment]
> no just a clean microsoft edge 🤔

are u click something?
that's not possible on chrome... lastest version....

if i leave it... nothing will do... 
if i click... then they will redirect to safelink... and of course i need to wait again....
especially if recaptcha appear.... the FF for some reason... didn't redirect the sites when the captcha is on....
even if they already know the destination link....

maybe this is new problem for new thread

**Comment by reashetyrr** [comment]
hmmm i will take a further look into it! :)

**Comment by dhana-exe** [comment]
> hmmm i will take a further look into it! :)

ok sure, i will be waiting for it
