### ISSUE TITLE
stfly.me

### ISSUE THREAD

**Issue by josesilveiraa** [FastForwardTeam/FastForward#365]
### Domain

https://stfly.me/

### Link

https://stfly.me/6Mrrrii

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #143
