### ISSUE TITLE
Dereferer.me

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#368]
### Domain

dereferer.me

### Link

https://dereferer.me/?https://bayfiles.com/X7kfPe91x0

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vojtak42** [comment]
Please add bypass, it is easy.

**Comment by lostdusty** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/bf5bab09e8bdd92735fc73a9ab3f9254cf68d705.

**Comment by Vojtak42** [comment]
No, it wasn't.

**Comment by Vojtak42** [comment]
It doen't work on newer type of links, but for my needs it's ok.
