### ISSUE TITLE
work.ink

### ISSUE THREAD

**Issue by jLn0n** [FastForwardTeam/FastForward#373]
### Domain

https://work.ink/

### Link

https://work.ink/en/l/12A/HorizonDownload

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

linkvertise ripoff

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #284.
