### ISSUE TITLE
Javascript required to bypass certain Websites

### ISSUE THREAD

**Issue by RyldSamu** [FastForwardTeam/FastForward#378]
### Body

Because of security and privacy reasons, I disable javascript by default. I figured out that it's only possible to bypass websites like sub2unlock or linkvertise by giving them the permission to run javascript.I think it isn't on purpose but I don't know it.

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
Link shorteners usually needs to run some background javascript code to get you to the final link. FastForward can take advantage of that and bypass websites. We can't really make websites to stop using javascript.
