### ISSUE TITLE
meostream.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#38]
### Domain

https://meostream.com/episodes/shaman-king-1x22/

### Link

https://meostream.com/links/2tybklpdlt/

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Thanks for the report

`domainBypass("meostream.com", () => ifElement("a#link", a => (safelyNavigate(a.href))))`

smaller:

```hrefBypass(/meostream\.com\/links\//,()=> ifElement("a#link",safelyNavigate))```

**Comment by NotAProton** [comment]
Fixed.
