### ISSUE TITLE
Sharemods.com reload loop

### ISSUE THREAD

**Issue by Lucas559-noob** [FastForwardTeam/FastForward#382]
### Domain

https://sharemods.com

### Link

https://sharemods.com/32uhkimztk0s/SA_-_SkyGfx_Extended.7z.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xCuri0** [comment]
seems like they added captcha. send html of the page with captcha so i can make it not try to bypass if theres a captcha since i can't get it to show me captcha
