### ISSUE TITLE
work.ink not bypassed

### ISSUE THREAD

**Issue by dinowars007** [FastForwardTeam/FastForward#384]
### Domain

https://work.ink/

### Link

https://work.ink/en/l/Xi/JailbreakProjectEvolution

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #284.
