### ISSUE TITLE
link1s.com

### ISSUE THREAD

**Issue by blazesprings** [FastForwardTeam/FastForward#394]
### Domain

https://link1s.com/

### Link

https://link1s.com/yDD4f7

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://link1s.com/yDD4f7
There  are 4 timers each of 10 sec. Please hellp bypass the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Duplicate of #40
