### ISSUE TITLE
Adfly/fumacrom not bypassing sometimes

### ISSUE THREAD

**Issue by Tenome** [FastForwardTeam/FastForward#397]
### Domain

Adfly

### Link

http://fumacrom.com/2LqzU

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I'm guessing this is because of crowd bypassing. Do crowd bypasses have to wait for an update from the server? How can I verify that I'm submitted new links to the server to be bypassed by others? Universal Bypass had a popup that told you when you submitted a new link.

Here are all the links. Some bypass immediately, others give me the 5 second Adfly countdown. It seems hit or miss, sometimes I'll click on a link that was bypassed instantly earlier and I'll get the adfly countdown. Any idea what could be causing the inconsistent behavior?

Volume 01: http://fumacrom.com/27dVC

Volume 02: http://fumacrom.com/2LqzU

Volume 03: http://fumacrom.com/2pW46

Volume 04: http://fumacrom.com/3Ca77

Volume 05: http://fumacrom.com/3VHDb

Volume 06: http://fumacrom.com/3vDT4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
There is a one in ten chance that you'll volunteer (read: be forced) to help verify the link you're visiting. We do this to weed out malicious link from the database.

Also the server is down at the moment, we're trying to get it back up.
