### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#4]
Results of vote on Discord.
Universal Bypass Renewed-1
FastFoward-11
U-Bypass-1
X-Bypass-1
(Excluding BS_Zombie)

Winner: FastFoward

![image](https://user-images.githubusercontent.com/81463636/132936557-19929c12-b3c8-4664-8d55-7c9463d6635e.png)

**Comment by kevin01523** [comment]
Lol remove the err

**Comment by Cyberavater** [comment]
8. X-Bypass

**Comment by NotAProton** [comment]
Logo concept, thoughts?

 <img src="https://user-images.githubusercontent.com/81463636/132813247-d9667826-c44d-4c52-a965-5e99f75e6455.png" width="250">
