### ISSUE TITLE
linkvertise

### ISSUE THREAD

**Issue by ChdoMiso** [FastForwardTeam/FastForward#412]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/75237/tara-babcock/2

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
Duplicate issue, see #51.
