### ISSUE TITLE
Intercelestial/Linegee Incorrect Redirection

### ISSUE THREAD

**Issue by oliver-queen16** [FastForwardTeam/FastForward#416]
### Domain

Linegee.net

### Link

linegee.net/?link=f8ec4cef0e&hash=42a06e9db02f1b25fba83714b0c64146&sign=964ee53e867 deff87ae8cf0848823dc7

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Hi!

First of all, this is not the same as the previous issues regarding intercelestial.com as that was fixed already. I only included it as it's coordinated on how the process has been executing in my situation.

Images uploaded below are the steps that I did with FastForward disabled. As you can see, I am being directed to the correct MEGA link.
![nff1](https://user-images.githubusercontent.com/90881932/160968507-19675752-0f88-4b19-b044-f3962ea6d00c.jpg)
![nff2](https://user-images.githubusercontent.com/90881932/160968512-46b0aa6c-6f62-46a3-9de7-4a5e84120423.jpg)
![nff3](https://user-images.githubusercontent.com/90881932/160968516-0241400d-fd0c-4af8-ba6a-c357df0781bd.jpg)
![nff4](https://user-images.githubusercontent.com/90881932/160968518-d62daf3b-85e9-473f-a4a3-1e880233d052.jpg)
![nff5](https://user-images.githubusercontent.com/90881932/160968524-2d1a9de4-efcf-417d-8973-7c3d71c964c5.jpg)

However, incorrect redirection is occuring when FastForward is enabled used as you can see from below:
![ff1](https://user-images.githubusercontent.com/90881932/160968124-028ec25f-48ba-485e-a5ff-0cd880887129.jpg)
![ff2](https://user-images.githubusercontent.com/90881932/160968131-9c334c1e-500c-466a-9fb7-b3a3bdcd9180.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
The link you added leads to a 404 error page. Also is it related crowd bypass FastForwardTeam/Server#15 ?

**Comment by oliver-queen16** [comment]
> The link you added leads to a 404 error page. Also is it related crowd bypass [FastForwardTeam/Server#15](https://github.com/FastForwardTeam/Server/issues/15) ?

Hi! I apologize for the late reply. The link is created by intercelestial.com which came from the website of Pahe.in so probably it's an expiring link. 

No, it's not related to the issue you linked above. The MEGA link is always the same, regardless of what file I access. It leads to mega.nz/A43abb...

**Comment by NotAProton** [comment]
Merging with #442
