### ISSUE TITLE
Error: <?>

### ISSUE THREAD

**Issue by SasanSistan** [FastForwardTeam/FastForward#419]
### Body

Show half link

https://clik.pw/f3KKA
https://freeltc.io/shortlinks.php?post_back=QLuAh2SracVCPDBW

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lostdusty** [comment]
should https://clik.pw/f3KKA lead to https://freeltc.io/login.php ?

**Comment by princessmortix** [comment]
should https://clik.pw/f3KKA lead to https://freeltc.io/login.php?
