### ISSUE TITLE
bit.ly/mega.nz link error

### ISSUE THREAD

**Issue by darkage2** [FastForwardTeam/FastForward#422]
### Body

When opening a bit.ly shortened link pointing to a mega.nz site, the extension changes the link and makes the actual content unreachable.
For example:
wxVCkDiC#PHoyTb0JBR9iqibO0HX1zQ is turned into wxVCkDiC#PHoyTb0JBR9iqibO0HX1zQ#PHoyTb0JBR9iqibO0HX1zQ

The problem is that the content after # is duplicated. When it's removed then the link is working again fine.

### Version

0.1952

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
We're working on this (see #442).
