### ISSUE TITLE
problem with adshort.co, infinite bypass loading

### ISSUE THREAD

**Issue by gabri25ele** [FastForwardTeam/FastForward#424]
### Domain

https://adshort.co/

### Link

https://adshort.co/exfD5

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

in https://adshort.co/ link, an infinite re-loop loading.
no captcha appears.

**Comment by lostdusty** [comment]
@reashetyrr sounds a easy fix

**Comment by reashetyrr** [comment]
on it

**Comment by reashetyrr** [comment]
i see, they added a recaptcha, so we are submitting the form without a valid captcha key

**Comment by reashetyrr** [comment]
the infinite redirect is because of crowd bypass

**Comment by reashetyrr** [comment]
![image](https://user-images.githubusercontent.com/6582364/169546611-a54e7fb8-1627-45bb-a73f-ea8e5e9cbac6.png)

**Comment by gabri25ele** [comment]
> the infinite redirect is because of crow bypass

is the last or the penultimate option in settings?

**Comment by reashetyrr** [comment]
yeah i was an idiot, the code just did a form submit whenever it found a submit, was not due to crowd bypass

**Comment by Dimar9** [comment]
Hi, it seems that there is still no solution to bypass this shortener?

**Comment by Lokotito** [comment]
Any news about this site and issue?

**Comment by ccddeee33333** [comment]
me have the same problem.

**Comment by lostdusty** [comment]
Nothing yet.

**Comment by lostdusty** [comment]
But we'll take a look very soon.

**Comment by 514guy** [comment]
This bug is inherited from Universal Bypass. Behavior is identical.

**Comment by reashetyrr** [comment]
time to pick this back up

**Comment by gabri25ele** [comment]
problem also with

https://gaminplay.com/

**Comment by nightnick** [comment]
Hi! No updates on this so far?
