### ISSUE TITLE
Sourceforge Infinite Loop on Download Page.

### ISSUE THREAD

**Issue by V3D4N7V2** [FastForwardTeam/FastForward#429]
### Domain

https://sourceforge.net

### Link

https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.2.22/xampp-portable-windows-x64-7.2.22-0-VC15.zip/download

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

the extension redirects (probably to the same page ? idk) resulting in a infinite loop , and the download doesn't start . The page just keeps refreshing several times every second ... until the server gives error "429 Too Many Requests" ... 
the page works as intended if i disable the extension.

**Comment by lostdusty** [comment]
Seems to be fixed, at least for me i don't get any infinite loops.
