### ISSUE TITLE
Incorrect bypass tinyurl.is

### ISSUE THREAD

**Issue by Blahx** [FastForwardTeam/FastForward#430]
### Domain

https://redi1.soccerstreams.net/event/manchester-city-liverpool-live-stream/824112

### Link

https://tinyurl.is/4iX9?sport=soccer

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

The link was suppose to go to http://givemenbastreams.com/nba/liverpool-live-stream?sport=soccer
but ends up automatically going to https://redditsoccerstreams.app/

**Comment by Write** [comment]
Can confirm the issue. 

I use my own ugly 'solution' to bypass tinyurl.is for now in a userscript

```javascript
/*
* Helper function that triggers when specific selector
* is available on the page.
*/
const checkElement = async selector => {
    while (document.querySelector(selector) === null) {
        await new Promise(resolve => requestAnimationFrame(resolve));
    }
    return document.querySelector(selector);
};

/*
* Tinyurl.is use 'count' var for countdown
* Instead of reverse engineer everything,
* just set the counter to -1 every 10ms
* ---
* Was useful back then the link were populated
* only when the countdown hit 0
* This doesn't seems to be the case anymore.
* ---
*/
window.count = -1;
function resetCountDown() {
    setTimeout(function () {
        window.count = -1;
        console.log(window.count);
        resetCountDown();
    }, 10);
}
resetCountDown();

/*
* As soon as there is an element that match `a[class*="btn"]` selector
* and doesn't contain 'tinyurl' as href value, follow it's link.
*/
checkElement('a[class*="btn"]:not([href^=http\\:\\/\\/tinyurl])').then((selector) => {
    var url = selector.href;
    console.log("LINK FOUND : " + url);
    window.location = url;
});
```


The site seem way less obfuscated than before, everything is just visible in the source code, wasn't the case before.
Right now they tricked FastForward by changing the id of the new skip-btn (id=newskip-btn-*) where * are some random numbers and using the old one (id="skip-btn") to redirect to the wrong site.

I used `a[class*="btn"]:not([href^=http\\:\\/\\/tinyurl])')` as a selector back then because the button contained a tinyurl link before being populated with the real url once the countdown hit 0. Which doesn't seem to be the case anymore.
Something like `a[id^=newskip-btn][class*="btn"]` work just great right now.

**Comment by bradenhilton** [comment]
```javascript
domainBypass("tinyurl.is",()=>awaitElement("a[id^='newskip-btn'][class*='btn']",safelyNavigate))
````
Works for me, thanks @Write

**Comment by nightzeyy** [comment]
> Can confirm the issue.
> 
> I use my own ugly 'solution' to bypass tinyurl.is for now in a userscript
> 
> ```js
> /*
> * Helper function that triggers when specific selector
> * is available on the page.
> */
> const checkElement = async selector => {
>     while (document.querySelector(selector) === null) {
>         await new Promise(resolve => requestAnimationFrame(resolve));
>     }
>     return document.querySelector(selector);
> };
> 
> /*
> * Tinyurl.is use 'count' var for countdown
> * Instead of reverse engineer everything,
> * just set the counter to -1 every 10ms
> * ---
> * Was useful back then the link were populated
> * only when the countdown hit 0
> * This doesn't seems to be the case anymore.
> * ---
> */
> window.count = -1;
> function resetCountDown() {
>     setTimeout(function () {
>         window.count = -1;
>         console.log(window.count);
>         resetCountDown();
>     }, 10);
> }
> resetCountDown();
> 
> /*
> * As soon as there is an element that match `a[class*="btn"]` selector
> * and doesn't contain 'tinyurl' as href value, follow it's link.
> */
> checkElement('a[class*="btn"]:not([href^=http\\:\\/\\/tinyurl])').then((selector) => {
>     var url = selector.href;
>     console.log("LINK FOUND : " + url);
>     window.location = url;
> });
> ```
> 
> The site seem way less obfuscated than before, everything is just visible in the source code, wasn't the case before. Right now they tricked FastForward by changing the id of the new skip-btn (id=newskip-btn-*) where * are some random numbers and using the old one (id="skip-btn") to redirect to the wrong site.
> 
> I used `a[class*="btn"]:not([href^=http\\:\\/\\/tinyurl])')` as a selector back then because the button contained a tinyurl link before being populated with the real url once the countdown hit 0. Which doesn't seem to be the case anymore. Something like `a[id^=newskip-btn][class*="btn"]` work just great right now.

It works but it breaks other sites for example  https://www.hotukdeals.com/

**Comment by Write** [comment]
> It works but it breaks other sites for example [hotukdeals.com](https://www.hotukdeals.com/)


If you want to use it as standalone userscript, you have to add a match rules that only match tinyurl.is of course !

**Comment by nightzeyy** [comment]
> If you want to use it as standalone userscript, you have to add a match rules that only match tinyurl.is of course !

Got it working thanks!
