### ISSUE TITLE
beta.applebee1558.com 15 seconds same as krnl.ca

### ISSUE THREAD

**Issue by Lucas559-noob** [FastForwardTeam/FastForward#432]
### Domain

https://beta.applebee1558.com

### Link

https://beta.applebee1558.com/bark/keyintro?pc_id=c4a36a0fbbe7a155adc03d2d855e45c750ff10748e3e6f8414b400f4dd1891c0

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by applebee1558** [comment]
I'm requesting the deletion/closure of this issue as the detection steps and cooldowns are intentionally made to prevent bypasses. Being the owner of that said website, the time-based check is from the encrypted cookie, so any form of client bypassing will not hop around this mandatory wait.
