### ISSUE TITLE
Soccerstreams misbehaving

### ISSUE THREAD

**Issue by vassilyzaitsev** [FastForwardTeam/FastForward#435]
### Domain

https://redi1.soccerstreams.net

### Link

https://redi1.soccerstreams.net/event/real-madrid-chelsea-live-stream/827773

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

This link and similar others:

![image](https://user-images.githubusercontent.com/35409978/163037688-fe47e558-5e40-4247-8aca-f043a2d44f43.png)

Instead of going to here: 
![image](https://user-images.githubusercontent.com/35409978/163037757-b48a20b8-efa2-488a-ad20-366f2f940799.png)

is going here: 
![image](https://user-images.githubusercontent.com/35409978/163037808-22200588-18e9-4280-963f-3d30e5da4739.png)

**Comment by rayshabh** [comment]
Yup Facing the same issue. To get to the actual side, we gotta disable fast forward and then click the link!

**Comment by rayshabh** [comment]
Please fix the issue!

**Comment by NotAProton** [comment]
Merging with #430
