### ISSUE TITLE
Add: adshort.co

### ISSUE THREAD

**Issue by MigelAngelEC** [FastForwardTeam/FastForward#437]
### Domain

https://adshort.co/

### Link

https://go.techgeek.digital/ucow

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

- Link: is NSFW 
- Also, Link keeps reloading while FastForward is activated

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #424.
