### ISSUE TITLE
link1s.com is not bypassed

### ISSUE THREAD

**Issue by hoainamvlm** [FastForwardTeam/FastForward#44]
### Domain

link1s.com

### Link

https://pennbookcenter.com/how-to-write-a-book-report/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### (Optional) Anything else?

Original link: https://link1s.com/ycs7ygc7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
captcha & bypassed by crowd bypass.
please do not make duplicate issues

**Comment by hoainamvlm** [comment]
I was trying to bypass link1s.com but it doesn't work, have crowd bypass enabled.

**Comment by lem6ns** [comment]
The crowd bypass server is currently down right now. It should be up soon.
