### ISSUE TITLE
Links to Mega with ecryption don't work correctly in Crowd bypass

### ISSUE THREAD

**Issue by r00teniy** [FastForwardTeam/FastForward#442]
### Domain

https://stfly.me/

### Link

https://stfly.me/WgkK14p

### Version

0.1952

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

It seems that Crowd bypass in this case (mega with password) cuts password part after #
Correct link: https://mega.nz/folder/3DQ03BhJ#sY56cHZItvYacP2DYFfsmg
link you get from crowd bypass:  https://mega.nz/folder/3DQ03BhJ

**Comment by NotAProton** [comment]
I guess this is causing it to drop the hash https://github.com/FastForwardTeam/Server/blob/d64da97f565dcd8b6cbf9dcf77e8d7f0f68af757/src/crowdHandlers.go#L132

**Comment by lostdusty** [comment]
Fixed on [this commit](https://github.com/FastForwardTeam/Server/commit/64d7f892e38a9916f1339e5c680ca0151fc38241) on crowdbypass server repo.
