### ISSUE TITLE
[New bypass] app.trangchu.news

### ISSUE THREAD

**Issue by BaSsAmMq** [FastForwardTeam/FastForward#443]
### Domain

https://app.trangchu.news

### Link

https://app.trangchu.news/7-best-joomla-security-extensions-to-protect-your-website.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

![image](https://user-images.githubusercontent.com/11368230/163734506-a7f2c498-74d6-40ad-9b95-b57c3f698f86.png)

**Comment by Vojtak42** [comment]
And travel.trangchu.news.

**Comment by Vojtak42** [comment]
original link: http://megafly.in/58dJ
