### ISSUE TITLE
Xervoo bypass

### ISSUE THREAD

**Issue by darkx239** [FastForwardTeam/FastForward#445]
### Domain

https://xervoo.net

### Link

http://xervoo.net/ad/locked?url=5R&t=s&subid=19962647&h=76651

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Please make a bypass for this site if possible

**Comment by lostdusty** [comment]
Closed due of being duplicate of #348.
