### ISSUE TITLE
FastForward doesn't properly bypass magicgen linkvertise

### ISSUE THREAD

**Issue by UltimateWishub** [FastForwardTeam/FastForward#447]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/95483/830.7422921497605/dynamic?r=aHR0cHM6Ly93d3cubWFnaWNnZW4ueHl6L2FjY291bnQucGhwP2lkPTUzODQ3MC03RDRGQTg%3D&o=sharing

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Duplicate issue, see #51.
