### ISSUE TITLE
Can you please add support for this website?

### ISSUE THREAD

**Issue by emzywastaken** [FastForwardTeam/FastForward#448]
### Domain

work.ink

### Link

https://work.ink/en/l/1n8/DarkHubKey1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by andranik1452** [comment]
A few days ago I opened the same link they should add support for work.ink cus it starting to be used a-lot now and it's annoying

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #284.
