### ISSUE TITLE
leasurepartment.xyz no bypass

### ISSUE THREAD

**Issue by 0chriis** [FastForwardTeam/FastForward#463]
### Domain

leasurepartment.xyz

### Link

https://leasurepartment.xyz/?h=1f02.net&tid=938968&cc=eyJ0aXRsZSI6IkhUVFBTJTNBJTJGJTJGUEFTVEVCSU4uQ09NJTJGQ1YwOFRDSVMiLCJjZCI6OTM4OTY4LCJkb21haW4iOiIlMkYlMkZkeWo4cGJjbmF0NHh2LmNsb3VkZnJvbnQubmV0IiwibGluayI6Imh0dHBzJTNBJTJGJTJGcGFzdGViaW4uY29tJTJGQ1YwOFRjaXMifQ%3D%3D

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #371.
