### ISSUE TITLE
Xervoo is not bypassed (You have to wait for the counter to run out)

### ISSUE THREAD

**Issue by BrightDarknessXX** [FastForwardTeam/FastForward#465]
### Domain

http://xervoo.net/

### Link

https://www.anime-loads.org/media/shingeki-no-kyojin?redirect

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

When you type http://xervoo.net/ it will lead you to https://adf.ly/?21.
Click the "Link" and go to the tab "Streams" and try to watch a video. It will open the adfly page that is not skippable.

**Comment by thatguy1943** [comment]
Hello, does this lead to "https://www.anime-loads.org/media/shingeki-no-kyojin?redirect"? Because on Firefox, at least, I am being redirected immediately. 

Also, please add this to your bookmarks for future use: [URL Redirect Checker](https://wheregoes.com/) is really handy to have at times

Using this, you can see that it is in fact the domain and not the extension that redirects you. Unless of course the URL Checker uses this extension to check the links....

**Comment by BrightDarknessXX** [comment]
> Hello, does this lead to "https://www.anime-loads.org/media/shingeki-no-kyojin?redirect"? Because on Firefox, at least, I am being redirected immediately.
> 
> Also, please add this to your bookmarks for future use: [URL Redirect Checker](https://wheregoes.com/) is really handy to have at times
> 
> Using this, you can see that it is in fact the domain and not the extension that redirects you. Unless of course the URL Checker uses this extension to check the links....

First time clicking on it will immediately redirect. Click it like 5 times and you wait 10 seconds for every other tab. Just checked on Chrome and Firefox.

**Comment by BrightDarknessXX** [comment]
> Hello, does this lead to "https://www.anime-loads.org/media/shingeki-no-kyojin?redirect"? Because on Firefox, at least, I am being redirected immediately.

No, it does not. The link probably expired. Go on this link you posted and go on the tab "Stream" and try to watch a video, it will redirect you to an adfly site that is not skippable.

**Comment by BrightDarknessXX** [comment]
EDIT: I updated my original post that should explain it better.

**Comment by lostdusty** [comment]
Closed due of being duplicate of #348.
