### ISSUE TITLE
click.redditmail.com

### ISSUE THREAD

**Issue by the-r3dacted** [FastForwardTeam/FastForward#466]
### Domain

https://click.redditmail.com

### Link

https://click.redditmail.com/CL0/https:%2F%2Fwww.reddit.com%2Fr%2FAmd%2Fcomments%2Fug2qvs%2Fjust_recreaed_the_amds_wraith_max_am4_cooler_in%2F%3F$deep_link=true%26correlation_id=426ca147-8727-492f-99c9-80bbf8715e5a%26post_fullname=t3_ug2qvs%26post_index=1%26ref=email_digest%26ref_campaign=email_digest%26ref_source=email%26utm_content=post_body/1/01000180827f032b-0ec4a85e-e249-4715-9617-4fb46f5ba3cc-000000/z_3Y0bCpZYu2ynaruOHnOchkq8yPmrH5Tv1FF_lsjNo=247

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

It looks like a basic redirect, all the information is there in the link.

**Comment by AliahX** [comment]
It's a redirect, not a link shortener, so it will literally redirect before fastforward can

**Comment by the-r3dacted** [comment]
It's blocked by most tracking/privacy lists, and fastforward redirects some redirects, so that's not a good answer.

**Comment by AliahX** [comment]
but it will literally be redirected by the thing before fastforward can redirect it

**Comment by legowerewolf** [comment]
Not always. Not if you have tools that block the DNS lookup.

**Comment by the-r3dacted** [comment]
> Not always. Not if you have tools that block the DNS lookup.

Exactly, however I just made a Redirector rule for my purposes.
![image](https://user-images.githubusercontent.com/77039240/204974007-c14d80eb-7541-4363-aaf2-f2fa424578b0.png)

**Comment by AliahX** [comment]
ok 🍍
