### ISSUE TITLE
https://thumb9.net/?dta=$/ptI6qoCL

### ISSUE THREAD

**Issue by Kosterc1** [FastForwardTeam/FastForward#469]
### Domain

https://thumb9.net

### Link

https://thumb9.net/?dta=$/ptI6qoCL

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

it forwards to the wrong location. is there a way to stop forwarding just 1 link

**Comment by reashetyrr** [comment]
this just leads to a rick roll

**Comment by Kosterc1** [comment]
It shouldn't. Is there a way to tick something when it directs forward
wrong.?

**Comment by reashetyrr** [comment]
when i go to any of above supplied urls i get:
![image](https://user-images.githubusercontent.com/6582364/169069874-6e87d3cd-d694-49ca-bc63-0477923c5237.png)
the button just leads to youtube rickroll

**Comment by Kosterc1** [comment]
It is for me like 10 diffrent start links

https://uniqueten.net/how-to-make-money-as-an-instacart-shopper/

Like I said, fast forward is seen and instantly directed Into bullshit
land. This is what it should look like.

**Comment by reashetyrr** [comment]
That screenshot is taken on a clean Microsoft edge....

**Comment by lostdusty** [comment]
![image](https://user-images.githubusercontent.com/47502554/169421221-88cb171e-8816-441c-81a6-8c7b7621d570.png)

Should i get redirect to this?
