### ISSUE TITLE
shorte.st

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#47]
### Domain

http://festyy.com/wM2dCY

### Link

http://gestyy.com/w7FxMx

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

```
http://gestyy.com/w7FxMx
http://ceesty.com/weC7bY
http://festyy.com/wM2dCY
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Looks like they have server side checks

```
domainBypass("festyy.com", () => {
	ensureDomLoaded(() => {
	    timer.classList.remove("show");
	    timer.remove();
	    skip_button.classList.add("show");
	})
})
```

@lem6ns, any ideas?
