### ISSUE TITLE
Sdarot.tv

### ISSUE THREAD

**Issue by GalCohenDev** [FastForwardTeam/FastForward#471]
### Domain

https://sdarot.tv

### Link

https://sdarot.tv/watch/31-%D7%94%D7%9E%D7%AA%D7%99%D7%9D-%D7%94%D7%9E%D7%94%D7%9C%D7%9B%D7%99%D7%9D-the-walking-dead/season/1/episode/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

![Example](https://user-images.githubusercontent.com/47279949/167251137-9f009be8-1477-4736-a010-f6d8a54f83a5.png)

**Comment by lostdusty** [comment]
Closed because it's a duplicate issue of #402.
