### ISSUE TITLE
[Broken bypass] FastForward is trimming :8080 on ShrinkUrl.org

### ISSUE THREAD

**Issue by Hyphonical** [FastForwardTeam/FastForward#472]
### Domain

http://shrinkurl.org

### Link

http://test.shrinkurl.org/OfTBkM

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Brave, Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
@NotAProton take a look

**Comment by lostdusty** [comment]
Fixed on [this commit](https://github.com/FastForwardTeam/Server/commit/64d7f892e38a9916f1339e5c680ca0151fc38241) on crowdbypass server repo.
