### ISSUE TITLE
[NSFW] Problem with Final Destination 

### ISSUE THREAD

**Issue by TindoJack** [FastForwardTeam/FastForward#474]
### Body

The Problem with extension is the final bypass link is should be like with final key. Here it's broken for mega.
Here's the example link 
https://gplinks.co/V4Hh
It's Bypass tho but without mega key. So it's uselss 
https://universal-bypass.org/navigate?target=https%3A%2F%2Fmega.nz%2Ffolder%2Fxp1lHZDQ&referer=https%3A%2F%2Fgplinks.co%2FV4Hh%3F20018737
That was I getting.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Issue seen on #442, and we are currently working on this. Also please NEVER open issues with NSFW links.
