### ISSUE TITLE
Misspelled word in _locales/cs/messages.json

### ISSUE THREAD

**Issue by KAJIKK** [FastForwardTeam/FastForward#477]
### Body

Line 66 is "message": "Otevřete croed-sourced cíl v nové záložce po % vteřinách."
and shoud be "message": "Otevřete cro**w**d-sourced cíl v nové záložce po % vteřinách."

Line 69 is "message": "zavřít záložku obsahující crow-sorced cíl po % vteřinách po jejím navštívení"
and shoud be "message": "zavřít záložku obsahující crow**d**-sorced cíl po % vteřinách po jejím navštívení"
### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Brave, Microsoft Edge

**Comment by lostdusty** [comment]
Could you make a pull request fixing that issue?

**Comment by KAJIKK** [comment]
Ok, done
