### ISSUE TITLE
[Request] note1s.com

### ISSUE THREAD

**Issue by dhana-exe** [FastForwardTeam/FastForward#478]
### Domain

note1s.com

### Link

https://note1s.com/notes/O1NWBW5

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
this appears to be a crowdbypass?

**Comment by dhana-exe** [comment]
> this appears to be a crowdbypass?

yes.... and maybe you can automate the "continue" click 
on second page after clicking the captcha and then stored into crowd bypass

**Comment by lostdusty** [comment]
> this appears to be a crowdbypass?

Probally not, there is some token on cookies.

**Comment by dhana-exe** [comment]
eh the site changed?
first time i share it here...
they had something like ?xxxx something after the link.....

which you can use everytime without opening captcha page....
now you can't :'(
