### ISSUE TITLE
disafelink.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#48]
### Domain

disafelink.com

### Link

https://disafelink.com/m/POCoMDm
https://disafelink.com/m/99Ba

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
I literally cannot get to the final link. Am I blind?

**Comment by NotAProton** [comment]
> 
> 
> I literally cannot get to the final link. Am I blind?

wait for 5 seconds then scroll down and click this tiny button
![image](https://user-images.githubusercontent.com/81463636/133936073-0d03a344-389f-4dc8-adbd-676988d6ed02.png)

**Comment by lem6ns** [comment]
Captcha, has to be bypassed with Crowd Bypass.

**Comment by NotAProton** [comment]
![image](https://user-images.githubusercontent.com/81463636/133936192-af3d2fca-91c8-49bf-ab0f-35e608b3214d.png)
another myFunction() bypass

**Comment by NotAProton** [comment]
> 
> 
> Captcha, has to be bypassed with Crowd Bypass.

thats the second one in the chain, the first one is a myFunction bypass
