### ISSUE TITLE
entitled looser has a tantrum

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#480]
### Body

bet you thought "no matter, it looks great that way", I wish from the bottom of my heart that failure of add-on is deleted from all the browsers' add-on stores too and I also wish you are banned from the whole internet
![Captura web_13-5-2022_01622_exey io](https://user-images.githubusercontent.com/105477255/168221872-bb02623e-35b0-48ec-8aa0-6bb9aff5e328.jpeg)

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by AliahX** [comment]
What the fuck is wrong with you

**Comment by AliahX** [comment]
It's not possible figure out the destination link of  some link shorteners, so what we do is we record the destination link you go to, then if anyone ever goes to that link again, it bypasses it.

**Comment by AliahX** [comment]
Also what do you even mean "no matter, it looks great that way"???

if your complaining about it not being in english, we cant change that because it copies your browsers language.

**Comment by ghost** [comment]
> It's not possible figure out the destination link of some link shorteners, so what we do is we record the destination link you go to, then if anyone ever goes to that link again, it bypasses it.

so installing this thing is almost as big a waste of time as having created it because it doesn't serve its purpose

**Comment by AliahX** [comment]
Lmao. It does serve its purpose. It automatically skips a huge portion of link shorteners, and has crowd bypassing for the ones it can't.

**Comment by AliahX** [comment]
I'm truly sorry we wasted 507 kilobytes of data and 10 seconds of your time. Do you want a refund?
