### ISSUE TITLE
Linkvertise Bypass appears to no longer work

### ISSUE THREAD

**Issue by MintOcha** [FastForwardTeam/FastForward#481]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/449204/tds-auto-farm-status-ud/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

*Expected result* --> Bypass the link
*Result* --> Refer to image below
![image](https://user-images.githubusercontent.com/88380103/168274993-49a7b111-2d5d-4c81-94d8-89fee5aee801.png)

I tried
-Reinstalling the extension
Same thing, nothing happened. This was not the case with the previous versions

Result after doing the captcha:
![image](https://user-images.githubusercontent.com/88380103/168275356-9748a4fe-63fa-4f04-a440-71b70b061634.png)

**Comment by eks28** [comment]
Same here it doesn't auto bypass but click free works (as in dont have to wait/install etc)

**Comment by lostdusty** [comment]
Duplicate issue, see #51.
