### ISSUE TITLE
When FastForward is enable WhatsApp Code Verify addon says "Validation Failure"

### ISSUE THREAD

**Issue by MuhammetEminCakir** [FastForwardTeam/FastForward#482]
### Domain

https://web.whatsapp.com/

### Link

https://web.whatsapp.com/

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

FastForward version:
Firefox->0.1943
Chrome->0.1952

WhatsApp Code Verify addon link:
for [Firefox](https://addons.mozilla.org/firefox/addon/code-verify/)
for [Chrome](https://chrome.google.com/webstore/detail/code-verify/llohflklppcaghdpehpbklhlfebooeog?hl)

**Comment by lostdusty** [comment]
Couldn't reproduce the issue, maybe you took to long to scan the qr code?

**Comment by MuhammetEminCakir** [comment]
Did you download "Code Verify" extension? (This extension is developed for WhatsApp code validation control from Meta. Also it is open source in [here](https://github.com/facebookincubator/meta-code-verify).)

FastForward enable (All other extensions disable):
![Ekran görüntüsü 2022-05-15 130123](https://user-images.githubusercontent.com/64583157/168468152-fed88909-7f6a-4cab-9658-2e005329e8e6.png)

FastForward disable (All other extensions disable):
![Ekran görüntüsü 2022-05-15 132354](https://user-images.githubusercontent.com/64583157/168468210-c1a0d760-e843-4c3e-a9d9-295e6a5295a5.png)

**Comment by lostdusty** [comment]
I've tested on my end, the issues exists, but doesnt seems to be related to Fast Forward end, but maybe on Code Verify end. Fast Forward doesn't modify web.whatsapp.com. If you found anything relevant, comment on this issue.

**Comment by PureOcean** [comment]
Thank you for reproduce and re-opening the issue.

Code Verify and FF's incompatibility have been [reported](https://github.com/facebookincubator/meta-code-verify/issues/161) to Meta/Facebook.

I don't think they will fix it. 

Instead of fixing this issue, wouldn't it be easier to add Exclude/Whitelist Websites support to FastForward?

**Comment by lostdusty** [comment]
FastForward doesn't modify *.whatsapp.com at all, but a whitelist feature is already on our to-do list.
