### ISSUE TITLE
mediafile.cc

### ISSUE THREAD

**Issue by gramenvir** [FastForwardTeam/FastForward#487]
### Domain

https://mediafile.cc/

### Link

https://mediafile.cc/4b20e11be4d95df9

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

**Comment by TETYYS** [comment]
Site generates you a token and ensures its at least 60 seconds old server-side, I don't think this bypass is possible.
