### ISSUE TITLE
work.ink not being bypassed

### ISSUE THREAD

**Issue by lostdusty** [FastForwardTeam/FastForward#488]
~~We already know that linkvertise is not being bypassed, and we are working on it. Please be patient while we found a fix for it.~~
Edit 5:50PM at 17/05/22 (BRT): Pull Request [498](https://github.com/FastForwardTeam/FastForward/pull/498) fixed Linkvertise bypass. Work.ink still not bypassed.

**Comment by lostdusty** [comment]
Same thing about work.ink, when the bypass is working we will give updates on this issue.

**Comment by reashetyrr** [comment]
they send the link back from the server when you finish the required steps, thats also verified before they send the link back, not sure we can bypass that anymore

**Comment by lostdusty** [comment]
crowdbypass then?

**Comment by ghost** [comment]
#942 has a bypass for work.ink, closing.

**Comment by lem6ns** [comment]
reopening, will link this to the PR

**Comment by lostdusty** [comment]
Moved to #967.
