### ISSUE TITLE
onsafelink.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#49]
### Domain

https://onsafelink.com/m/zqryhCTHb

### Link

https://onsafelink.com/m/v1O1MCbs

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
XD

```
domainBypass("metroupdate.biz", () => {
	ensureDomLoaded(() => {
		myFunction();		
})})
```

**Comment by NotAProton** [comment]
Fixed. Thanks for the report
