### ISSUE TITLE
Forward ibb.co to imgbb.com

### ISSUE THREAD

**Issue by MenacingPerson** [FastForwardTeam/FastForward#491]
### Domain

https://ibb.co

### Link

https://ibb.co

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### (Optional) Anything else?

Hi guys, please redirect ibb.co to imgbb.com as ibb.co is blocked in my isp but imgbb.com is not and they're the exact same. Thanks

**Comment by lostdusty** [comment]
ibb.co automatically redirects to imgbb.com, that not something we will cover. However you can add this code to your custom bypasses on Fast Forward settings:

```javascript
domainBypass("ibb.co", () => {
        var a = window.location.href
        var finalurl = a.replace("ibb.co", "imgbb.com")
        safelyNavigate(finalurl)
})
```

**Comment by MenacingPerson** [comment]
Still blocked
![image](https://user-images.githubusercontent.com/59611020/168966563-1c2fb818-361a-487b-9856-17b6648926ca.png)
