### ISSUE TITLE
Borked Redirrect

### ISSUE THREAD

**Issue by Sneethe** [FastForwardTeam/FastForward#494]
### Domain

https://www.thewoodworks.com.au

### Link

https://www.thewoodworks.com.au/

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### Anything else?

Navigating to any subpage redirects back to the homepage. Having a whitelist for domains would be a nice solution for these false positives.

**Comment by lostdusty** [comment]
@reashetyrr i haven't found ANYTHING about this on the extension, but the redirect exists when ff is enabled, any ideas?

**Comment by reashetyrr** [comment]
Is there perhaps a faulty/wrong one set in the database of crowd redirects?

**Comment by Sneethe** [comment]
Its very strange. To be honest I thought that it may just be due to a strange peculiarity pertinent to my setup. However if its redirecting for other people...
