### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by LucasBS1** [FastForwardTeam/FastForward#495]
### Body

I'm writing here, because when I click to write an issue, I'm redirected to https://github.com/FastForwardTeam/FastForward/issues/new/choose

Hope someone could move the topic to the right place

It's simple: all that I want is to change the language on the settings page.

How to do that ?

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by NotAProton** [comment]
Change your browser's language, FastForward automatically switches to whatever language the browser's using

**Comment by LucasBS1** [comment]
Not possible.

The browser is already in the right language (portuguese). And I'm not the only user: My girlfriend decapitates me every time I change languages.

Besides, the browser is well translated.
Only the Addon has a shitty translation. And even if it were good, english is more simple/better/original/precise/etc for the addons in general

I'll be happy with solutions even if it involves overwriting the translation file in use by the english one. IF that's how it works.

**Comment by lostdusty** [comment]
If you want, you can fix the translations yourself by creating a PR or going to our crowdin page. I'll be closing this issue, but feel free to contact me anytime for any further questions (just comment on this issue ;).

**Comment by LucasBS1** [comment]
No, I don't want to "fix the translation". I want to use the english language. Easy to understand.

If I "fix the translation", I'll make sure to convert it back to english, because that is the right "translation" for me. Unfortunately, I can't to that, because I would.

Why don't you guys focus on fixing the problem instead of closing topics as if open ones are a nuisance in some way !?

Close the whole goddam forum if we're not supposed to post problems on it

Serious. That a big favor ? Don't like to ask, so, if I'm asking, it's important to me...

Is the language file stored on the disk somewhere ? Can't I simply delete the portuguese one ? Replace it with the english ?

**Comment by NotAProton** [comment]
Sorry, we don't handle translations directly, the browser does. 
https://developer.chrome.com/docs/extensions/reference/i18n/

We provide the messages https://github.com/FastForwardTeam/FastForward/treemain/src/_locales and the browser is responsible for switching to the user's preferred language. If you have a problem ask chrome or Firefox to add support for your use case.

**Comment by AliahX** [comment]
> Only the Addon has a shitty translation. And even if it were good, english is more simple/better/original/precise/etc for the addons in general
If you think the Portuguese translation is shitty, suggest a better translation. 
Why do you want it to be in English if you have Portuguese as your browsers language??

Also, don't be a such a dick, this addon is free and we don't earn anything from it.

If you want to change the Portuguese translation to English, clone the extension, replace the Portuguese translation with the English one and then load the extension.

**Comment by reashetyrr** [comment]
hi @LucasBS1 ,

im sorry but as we stated we dont support setting your own language, the browser gives us the set language and we use that language as the "translation", if you really want to change from portugese to english you can do by following the following steps:

1. in your firefox go to: about:support
2. find the line that states "Profile Folder"
3. click on the button "Open Folder"
4. when the folder with your profile has opened up close firefox
5. double check that firefox is closed in your task manager(ctrl + shift + esc)
6. in the profile folder go to the extensions folder
7. find the xpi file that has fastforward in the name
8. open this file up using winrar or winzip or any zip application
9. in winrar/winzip/zip application go to the _locales folder
10. go into the shortcode of your firefox set language (pt-PT)
11. unzip the messages.json file
12. open up the extracted messages.json file and put the contents of: https://github.com/FastForwardTeam/FastForward/blob/main/src/_locales/en/messages.json inside
13. place the edited messages.json file back into the xpi zip
14. save the zip

now you should have changed the whole pt-PT translation to english

**NOTE: doing this will make it impossible to keep changes after updating, when you update the extension you have to redo all steps again!**


i hope this is sufficient information :)

**Comment by LucasBS1** [comment]
> (...) go to the _locales folder
> 10. go into the shortcode of your firefox set language (pt-PT)
> 11. unzip the messages.json file
> 12. open up the extracted messages.json file and put the contents of: https://github.com/FastForwardTeam/FastForward/blob/main/src/_locales/en/messages.json inside
> 13. place the edited messages.json file back into the xpi zip
> 14. save the zip

Thank you 
Thank you 
Thank you
Thank you

That is PRECISELY what I was looking for

Since these are easy steps, won't be a problem having to repeat it often.

Thank you again.
By me, this topic is effectively resolved.


Observation: how much would it cost for the developer to put an extra option on the settings ?

**Comment by reashetyrr** [comment]
pretty much alot, the whole translation strings are now being handled by the browser, if we were to implement an override style then we would have to make our very own translations module

**Comment by lostdusty** [comment]
Solved i guess.
