### ISSUE TITLE
wp.sekilastekno.com

### ISSUE THREAD

**Issue by andrizan** [FastForwardTeam/FastForward#496]
### Domain

https://wp.sekilastekno.com

### Link

https://wp.sekilastekno.com/household-finance-172#r/nXLxHAX2e

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
just curious.. but there is nothing like a redirection? the link https://wp.sekilastekno.com/household-finance-172#r/nXLxHAX2e points to a wordpress article?

**Comment by andrizan** [comment]
it turns out that there are two domains that are used. the below domain is used before the above domain.
https://apk.miuiku.com/nXLxHAX2e

**Comment by reashetyrr** [comment]
i would love to make a bypass, but the apk.miuiku.com link just keeps permanently loading for me :(

**Comment by andrizan** [comment]
disable adblocker

**Comment by dhana-exe** [comment]
> i would love to make a bypass, but the apk.miuiku.com link just keeps permanently loading for me :(

maybe you should using ublock origin
the blocker list update every day or even hour.....

i have no issue for testing the link above though.... so i hope you can test it with that
