### ISSUE TITLE
Schoology

### ISSUE THREAD

**Issue by yodaluca23** [FastForwardTeam/FastForward#499]
### Domain

schoology.com

### Link

https://schoology.kleinisd.net/link?a=2345837224&path=https%3A%2F%2Fquizizz.com%2Fjoin%3Fgc%3D22846925

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

The link will likely not work for you because you need to be logged in but I included it so you can see the formatting.

**Comment by reashetyrr** [comment]
i believe i can make something, jus not sure if it will work if i cant login >.<

**Comment by reashetyrr** [comment]
nope i was wrong, thers a hard redirect, doesnt seem to be bypassable without logging in

**Comment by z8512** [comment]
@yodaluca23 give the dev an account for testing
