### ISSUE TITLE
Hurirk.net is not bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#50]
### Domain

Hurirk.net

### Link

http://hurirk.net/ad/locked?rndad=635302387-1632050731&url=N0IE&t=s&subid=6943568&h=81198

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Can't reproduce, it is being bypassed. : /

**Comment by lem6ns** [comment]
Cannot reproduce.
