### ISSUE TITLE
I am already first encounter of the link but still have to wait when try acces again

### ISSUE THREAD

**Issue by Alberiansyah** [FastForwardTeam/FastForward#505]
### Domain

https://wp.sekilastekno.com/

### Link

https://wp.sekilastekno.com/whatis-business-1#r/a4oI15NCs0

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
dupicate of: https://github.com/FastForwardTeam/FastForward/issues/496
