### ISSUE TITLE
Intermediary Tab during bypass

### ISSUE THREAD

**Issue by akasaka99** [FastForwardTeam/FastForward#509]
### Body

Hi, when the extension encounters a url to be bypassed, the extension creates an intermediary blank page with the message: **"You are being navigated to https://...."** and then adds a new tab with the destination site. Is this intermediary page there by design or we can remove this page and just land on the destination page (I don't see any option to remove this page)?

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

MacOS

**Comment by reashetyrr** [comment]
hi do you have an example url for me? i have not seen this behaviour myself

**Comment by akasaka99** [comment]
yes it's this url: https://goo.gl/maps/8aeozY5jwVgoDbBfA?entry=yt

**Comment by reashetyrr** [comment]
thats just a google maps link....

**Comment by akasaka99** [comment]
Yep but I get: 
You are being navigated to https://www.google.com/maps/place/naat+restaurant+(%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AD%E0%B8%B2%E0%B8%AB%E0%B8%B2%E0%B8%A3%E0%B8%9B%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%B2%E0%B8%A3%E0%B8%96)/@7.7690077,98.3157604,17z/data=!3m1!4b1!4m5!3m4!1s0x305028a29dae629d:0xfb3edbc782a1239f!8m2!3d7.7690024!4d98.3179491?shorturl=1

And it shows the FastForward mozilla extension page on the url bar

**Comment by akasaka99** [comment]
Here is what I get on this intermediary page on the url bar:

moz-extension://957e4102-0bec-433b-b3c0-78b17200c3eb/html/before-navigate.html?target=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2Fnaat%2Brestaurant%2B(%25E0%25B8%25A3%25E0%25B9%2589%25E0%25B8%25B2%25E0%25B8%2599%25E0%25B8%25AD%25E0%25B8%25B2%25E0%25B8%25AB%25E0%25B8%25B2%25E0%25B8%25A3%25E0%25B8%259B%25E0%25B9%2589%25E0%25B8%25B2%25E0%25B8%2599%25E0%25B8%25B2%25E0%25B8%25A3%25E0%25B8%2596)%2F%407.7690077%2C98.3157604%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x305028a29dae629d%3A0xfb3edbc782a1239f!8m2!3d7.7690024!4d98.3179491%3Fshorturl%3D1&referer=tracker

**Comment by NotAProton** [comment]
There is an option to set the time to redirect you automatically, set it to zero
![image](https://user-images.githubusercontent.com/81463636/169657518-491c5d72-d5c9-4816-90ed-c200323fe41c.png)

**Comment by lostdusty** [comment]
Did we solved your problem?

**Comment by akasaka99** [comment]
Hello, 
Unfortunately the problem isn't solved.
I had already these options on

**Comment by lostdusty** [comment]
Are the secounds set to 0? I have tested in both browsers and I could'nt reproduce the issue.

**Comment by akasaka99** [comment]
Yes I have the same profile as you
