### ISSUE TITLE
101desire

### ISSUE THREAD

**Issue by munadutta** [FastForwardTeam/FastForward#510]
### Domain

101desire.com

### Link

https://vegamovies.cam/?732704aaba=R21NVENraTZnS1lnUFRSSFJMblh4S0hwd2lDQXBwTG96SWR0US9hbXlSQVpRVWpQYnZLWFlmcjNxOEI3NW1SdldGaTFUaG1QZGFwd3VHcExyL3BMVm5WRWRIT3BwY3JMM1VaZUJWSnZQQlJJcmp6OTlQK2xkSWNONUg3MVBtUmc=

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

please visit vegamovies.nl download a movie it will redirects to 101desire page, i want to bypass that
not able to copy the link.

**Comment by reashetyrr** [comment]
example: https://vegamovies.cam/?732704aaba=R21NVENraTZnS1lnUFRSSFJMblh4S0hwd2lDQXBwTG96SWR0US9hbXlSQVpRVWpQYnZLWFlmcjNxOEI3NW1SdldGaTFUaG1QZGFwd3VHcExyL3BMVm5WRWRIT3BwY3JMM1VaZUJWSnZQQlJJcmp6OTlQK2xkSWNONUg3MVBtUmc=

**Comment by munadutta** [comment]
> example: https://vegamovies.cam/?732704aaba=R21NVENraTZnS1lnUFRSSFJMblh4S0hwd2lDQXBwTG96SWR0US9hbXlSQVpRVWpQYnZLWFlmcjNxOEI3NW1SdldGaTFUaG1QZGFwd3VHcExyL3BMVm5WRWRIT3BwY3JMM1VaZUJWSnZQQlJJcmp6OTlQK2xkSWNONUg3MVBtUmc=

Yes... This one need to bypass

**Comment by dgbkn** [comment]
https://vegamovies.pages.dev/
SEE THIS

**Comment by dgbkn** [comment]
i made a bypass for it but it takes some time to load and bypass it about 10 to 15 seconds

**Comment by dgbkn** [comment]
if you want i will share the bypass but in private

**Comment by munadutta** [comment]
> if you want i will share the bypass but in private

i would love to use if you can share with me.

**Comment by undeadjess** [comment]
> if you want i will share the bypass but in private

if you would be ok sending it to one of the devs, or as a pull request, many other people would be able to use it...

**Comment by dgbkn** [comment]
> > if you want i will share the bypass but in private
> 
> if you would be ok sending it to one of the devs, or as a pull request, many other people would be able to use it...

But problem is that it takes 15 seconds to baypaass with is a very long time ,and Dev's would disagree with it as it very slow

**Comment by dgbkn** [comment]
when you click a download link wait it will load but as the bypass is hosted on a heroku server it takes time

**Comment by dgbkn** [comment]
https://github.com/dgbkn/bypass_vegamovies/blob/main/websocket.js For instance se this script that runs the bypass
