### ISSUE TITLE
linkvertise.com not working / because of new captcha system , also bypass not working on newly created linkvertises.

### ISSUE THREAD

**Issue by Ezekiel-Game** [FastForwardTeam/FastForward#522]
### Domain

linkvertise.com

### Link

https://linkvertise.com/48193/thekrnlkey/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

plz fix 
![image](https://user-images.githubusercontent.com/88566736/170635951-811f2d9d-35ed-4981-8d56-ebda350f3849.png)
is super annoying lel bc krnl system now i have to click 2 captchas now 
![image](https://user-images.githubusercontent.com/88566736/170636089-06738a26-ce64-4661-843c-2b4bee38069b.png)

**Comment by undeadjess** [comment]
fixed by #498
