### ISSUE TITLE
[New Bypass] l.facebook.com

### ISSUE THREAD

**Issue by 8227846265** [FastForwardTeam/FastForward#538]
### Domain

l.facebook.com

### Link

https://www.facebook.com/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

l.facebook.com is the URL that loads when you click an advertisement on Facebook.

**Comment by AntonioRedondo** [comment]
This would be a killer feature. [Facebook™ Direct Links](https://github.com/Mte90/facebook-direct-links/issues/39) doesn't work anymore.
