### ISSUE TITLE
h-gen.to bypass detected

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#54]
### Domain

https://h-gen.to/

### Link

https://h-gen.to/

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
Maybe cookie thing? It's not time-based from my testing.

**Comment by NotAProton** [comment]
example links?

**Comment by xAffan** [comment]
its detected based on the referrer link in headers

**Comment by lem6ns** [comment]
> 
> 
> its detected based on the referrer link in headers

👎, FastForward sends the original referrer (linkvertise.com)

**Comment by xAffan** [comment]
Well I arrived to this conclusion because a user script with tampermonkey
works fine as it has no redirection.

**Comment by lostdusty** [comment]
Looks like h-gen.to is not operating anymore, closing this issue.
