### ISSUE TITLE
mirrored.to auto click view

### ISSUE THREAD

**Issue by dhana-exe** [FastForwardTeam/FastForward#561]
### Domain

https://www.mirrored.to/

### Link

https://www.mirrored.to/files/1FFMW5HP/[NekoPoi]_[nekopoi.org]_Amakano_-_01_[720P].mp4_links?lang=en

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

Can you make this is automatically?
i mean first time before you download... you will see this page
![image](https://user-images.githubusercontent.com/29838157/175963345-e2c864e0-d59c-4303-8526-1c0da067c8a5.png)
what i think need to be bypassed is that button.... so we will directly see this page
![image](https://user-images.githubusercontent.com/29838157/175963716-2250f2ca-73ae-4dc1-af51-237932d85f73.png)
with this... i think all that FF need is to automatically click the button when first time visitor came.... (but didn't store any link, because after few hour... you will be redirected to first link if you saved the url....

i hope my broken english can be understand by someone who working for this....

**Comment by Bug-Cache** [comment]
another example link:

https://www.mirrored.to/files/1BWKHIL9/[NekoPoi]_Tsugou_no_Yoi_Sexfriend_-_04_[480P][nekopoi.care].mp4_links

**Comment by 3xploitzer0** [comment]
please fix this issues,
