### ISSUE TITLE
bypassing gaminplay.com causes forwarding to bad link.

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#572]
### Domain

gaminplay.com

### Link

https://gaminplay.com/xbox-game-studios-announces-age-of-empires-2-definitive-edition-dynasties-of-india-check-details/

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

I do not know where exactly is the problem but after bypassing [this website ](https://gaminplay.com/verify/?/mbHmoD) it forwards me to this link: https://go.adslinkfly.online/, instead of this: https://go.adslinkfly.online//mbHmoD.
I works without problem when I turn off fastforward.
original link: https://gaminplay.com/verify/?/mbHmoD

**Comment by ghost** [comment]
still the case for me
