### ISSUE TITLE
CUTY.IO ISNT BYPASSED

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#573]
### Domain

https://cuty.io/

### Link

https://cut-y.net/SZ3oBJW

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by Wykeless** [comment]
on firefox as well

**Comment by azizLIGHT** [comment]
Duplicate issue of #555
Also, cuty.io and cut-y.net can be substituted and links still work
