### ISSUE TITLE
linkerload.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [FastForwardTeam/FastForward#60]
### Domain

https://linkerload.com/in7XRr

### Link

https://linkerload.com/0LX7iVxFj

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
same bypass as duit.cc, doing https://duit.cc/0LX7iVxFj will bypass it. Regex?
