### ISSUE TITLE
Linkvertise: TXT files are blank

### ISSUE THREAD

**Issue by mjolnir870** [FastForwardTeam/FastForward#601]
### Domain

linkvertise.com

### Link

https://linkvertise.com/414421/ccrm/1

### Version

0.2025

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Some linkvertise links are showing a text file instead of redirecting to a link. This text file is blank when FastForward is enabled. Disabling it shows the text file's contents.

FF enabled, blank text:
![image](https://user-images.githubusercontent.com/35158449/178119438-b8a487ec-dec2-467d-bab9-2ee4bc6bfd2c.png)

**Comment by Srows** [comment]
me too

**Comment by mjolnir870** [comment]
just checked and this is still an issue with FastForward 0.2039 and Firefox 104.0b7.

**Comment by undeadjess** [comment]
fixed in later versions. if this is still an issue, please update.
