### ISSUE TITLE
MegaDB only reloads

### ISSUE THREAD

**Issue by Cannoner** [FastForwardTeam/FastForward#610]
### Domain

https://megadb.net

### Link

https://megadb.net/mdm6uy06nrp1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I get to this site through the site https://steamrip.com/
The actual issue is that the site keeps reloading and it says the countdown was skipped which is false

**Comment by ghost** [comment]
just saying I dont suggest using steamrip one person got a real trojan from it and now in r/piratedgames its in the untrusted list

**Comment by REVENGE977** [comment]
> just saying I dont suggest using steamrip one person got a real trojan from it and now in r/piratedgames its in the untrusted list

not true 
![image](https://user-images.githubusercontent.com/32039975/183098547-3979f469-5ef5-4d3a-8841-a7ac9f6386d7.png)

**Comment by ghost** [comment]
> > just saying I dont suggest using steamrip one person got a real trojan from it and now in r/piratedgames its in the untrusted list
> 
> not true ![image](https://user-images.githubusercontent.com/32039975/183098547-3979f469-5ef5-4d3a-8841-a7ac9f6386d7.png)

i made that comment months before u replied but anyway that time one guy got a virus and most believed that steamrip is a virus and it got removed from the megathread and it came back afterwards :)

**Comment by USLTD** [comment]
Can't we temporally block `megadb.net` bypassing until someone finds a working solution?

**Comment by USLTD** [comment]
Fixed by #924, at least temporarily. Please close this issue
