### ISSUE TITLE
https://go.techgeek.digital

### ISSUE THREAD

**Issue by PabloDM2** [FastForwardTeam/FastForward#611]
### Domain

https://go.techgeek.digital

### Link

https://go.techgeek.digital

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by PabloDM2** [comment]
The site enters an endless loop

**Comment by dhana-exe** [comment]
what you mean by endless loop... this is safelink or what? 
why you put the same link for domain and link '-' 

maybe you can close the thread if you didn't understand what you doing

**Comment by FabulousSpaceCat** [comment]
The extension attempts to bypass the page, but there is a captcha to complete, so the page reloads to tell you there is a captcha error, then the extension tries again, etc. 

Here is a link to see what is going on: https://go.techgeek.digital/gZQkA
