### ISSUE TITLE
A request to add support to bypass olamovies.click

### ISSUE THREAD

**Issue by pixelpiirate** [FastForwardTeam/FastForward#626]
### Domain

https://olamovies.click/

### Link

https://techmody.io/9-youtube-url-tricks-you-should-know-about/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

A request to bypass the links when you press on any link for a movie

**Comment by lostdusty** [comment]
Fixed in #762.

**Comment by UrTerrible** [comment]
I am having issues with olamovies.homes.
