### ISSUE TITLE
Bypass not working after latest commit (6f64a7)

### ISSUE THREAD

**Issue by RoganMatrivski** [FastForwardTeam/FastForward#629]
### Domain

stfly.me, tei.ai, but all website probably affected

### Link

https://tei.ai/49oIR, https://stfly.me/o5iI

### Version

0.2025

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Latest update redirects to a 404 page. Changing base URL to `universal-bypass.org` fixes the issue. Is the redirect site broken? (6f64a72cc4c11b7adcb419c45f23b50b640a1d62)
![image](https://user-images.githubusercontent.com/19743747/181043144-0f3f85ca-29cd-4912-b28f-e03f0beb163b.png)

**Comment by owolo** [comment]
![Screenshot_20220726-182404_Discord.png](https://user-images.githubusercontent.com/56605931/181046174-2f699c8a-ce91-4a89-8640-f661a982360f.png)
Just wait please
