### ISSUE TITLE
andianal.com

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#63]
### Domain

andianal.com

### Link

http://andianal.com/redirect.html?od=1syb61476cc4a932f_vl_weekvl_0zw1.11u3t3k.U0000rg2sz914qm00x_xf1292.g2sz9MHV5ZzdnLTJoOTBrZXI0o4tXc

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### (Optional) Anything else?

http://andianal.com/redirect.html?od=1syb614611e1e2307_vl_weekvl_0zw1.11u3t3k.U0000rg2rrn12in00x_xf1292.g2rrnMHV5ZzdnLTNhNTc4NTQ0j3dDX
http://andianal.com/redirect.html?od=1syb614612bfc290b_vl_weekvl_0zw1.11u3t3k.U0000rg2rrv15mx00x_xf1292.g2rrvMHV5ZzdnLTJocXBoOWg0z7eDn
http://andianal.com/redirect.html?od=1syb6146234e18ca7_vl_weekvl_0zw1.11u3t3k.U0000rg2s1p14qm00x_xf1292.g2s1pMHV5ZzdnLTJoOTBrZXI0q5Nfe
http://andianal.com/redirect.html?od=1syb6144ccf5194f1_vl_weekvl_0zw1.11u3t3k.U0000rg2qzk1blt00x_xf1292.g2qzkMHV5ZzdnLTI3MDg1MnI0b1cjP
http://andianal.com/redirect.html?od=1syb6144ca4bca0f0_vl_weekvl_0zw1.11u3t3k.U0000rg2qzg17gu00x_xf1292.g2qzgMHV5ZzdnLTJoOTBhcHU0v6dzj
http://andianal.com/redirect.html?od=1syb61476cc4a932f_vl_weekvl_0zw1.11u3t3k.U0000rg2sz914qm00x_xf1292.g2sz9MHV5ZzdnLTJoOTBrZXI0o4tXc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
Cannot get to final link manually, just all links to scam ads.
Can someone else verify?

**Comment by NotAProton** [comment]
> 
> 
> Cannot get to final link manually, just all links to scam ads.
> Can someone else verify?

same
