### ISSUE TITLE
Link to the changelog returns 404

### ISSUE THREAD

**Issue by savchenko** [FastForwardTeam/FastForward#630]
### Body

The big bright button...

![image](https://user-images.githubusercontent.com/300146/181045957-bb51d89e-ea8e-4750-bcab-818749882bf8.png)

...leads here:

![image](https://user-images.githubusercontent.com/300146/181046075-c2e90db9-1fc8-44ec-9aee-c2f06bf3dea3.png)

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

**Comment by TubaApollo** [comment]
Currently all references to Universal Bypass get changed to Fast Forward, it's only a temporary issue:
(Screenshot from the announcement channel in the FastForward Discord)
![image](https://user-images.githubusercontent.com/86665265/181046511-8999ec70-b068-454e-b906-9a510d4c9b10.png)

**Comment by Elnagy** [comment]
I have the same problem I am using Chrome and kiwi browser
