### ISSUE TITLE
forgytroies.com

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#64]
### Domain

forgytroies.com

### Link

http://forgytroies.com/redirect.html?od=1syq614519af29ec5_vl_weekvl_0z61.11u3t3k.O0000rg2riu1b670ij_xf1266.g2riuMHV5ZzdnLTFlcjJwOW80m4NPa

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

http://forgytroies.com/redirect.html?od=1syq614519af29ec5_vl_weekvl_0z61.11u3t3k.O0000rg2riu1b670ij_xf1266.g2riuMHV5ZzdnLTFlcjJwOW80m4NPa
http://forgytroies.com/redirect.html?od=1syq61461378774c3_vl_weekvl_0z61.11u3t3k.O0000rg2rsm16e90ij_xf1266.g2rsmMHV5ZzdnLTJocXBvNG80m4NPa

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
All 404s.
