### ISSUE TITLE
LINKVERSE

### ISSUE THREAD

**Issue by gevin456** [FastForwardTeam/FastForward#640]
### Domain

https://link-target.net/205379/sophie33

### Link

https://link-target.net/205379/sophie33

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

ITS WORKED BEFORE, BUT ITS CRASHED AND RE-ROUTING TO GITHUB PAGE

**Comment by reashetyrr** [comment]
hi there, we are currently in the process of making a new release that fixes this issue
