### ISSUE TITLE
Attempting to bypass any site redirects to "You aren't supposed to be here"

### ISSUE THREAD

**Issue by PopCat19** [FastForwardTeam/FastForward#641]
### Body

Attempting to bypass any site (ex. linkvertise) redirects to "You aren't supposed to be here" page.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/104473808/181220746-cb78428b-0c48-47dd-a643-63963730f273.png)

**Comment by lostdusty** [comment]
See #647.
