### ISSUE TITLE
website isn't bypass

### ISSUE THREAD

**Issue by Piyushnigam16** [FastForwardTeam/FastForward#644]
### Domain

https://adrinolinks.com

### Link

https://adrinolinks.com/WiGFiL

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
this should have been fixed, be sure to download the newest bypass definitions

**Comment by lostdusty** [comment]
See #647.
