### ISSUE TITLE
I tried to bypass mirrored and get some error.

### ISSUE THREAD

**Issue by muslimcyber26** [FastForwardTeam/FastForward#645]
### Domain

https://www.mirrored.to/files/1CANDLHU/?hash=f27b0c028ab8ad0aec1f3dfc41053368&dl=0

### Link

https://www.mirrored.to/files/1CANDLHU/?hash=f27b0c028ab8ad0aec1f3dfc41053368&dl=0

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
please check: https://github.com/FastForwardTeam/FastForward/issues/647

**Comment by reashetyrr** [comment]
this should have been fixed, be sure to download the newest bypass definitions
