### ISSUE TITLE
You aren't supposed to be here

### ISSUE THREAD

**Issue by oureveryday** [FastForwardTeam/FastForward#646]
### Domain

cshort.org

### Link

https://cshort.org/kCxvTKZTqy

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

After the countdown end it shows that:
https://fastforward.team/bypassed?target=https%3A%2F%2Fcshort.org%2FilA8AMxsM1%3Fu%3D1528f5bc-062d-4203-8605-a0bb63ff524e%3AilA8AMxsM1&referer=https%3A%2F%2Fcshort.org%2FilA8AMxsM1
![image](https://user-images.githubusercontent.com/20489787/181238924-ced078b1-20a0-4036-ab9c-648d050577a8.png)

**Comment by reashetyrr** [comment]
please check: https://github.com/FastForwardTeam/FastForward/issues/647

**Comment by reashetyrr** [comment]
This should now be fixed again, please download the latest bypass definitions

**Comment by oureveryday** [comment]
Thanks it works.
