### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by tdeek** [FastForwardTeam/FastForward#648]
### Body

""You aren't supposed to be here""  ...   what was there?   

version: 0.2025

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
please check: https://github.com/FastForwardTeam/FastForward/issues/647

**Comment by reashetyrr** [comment]
this should have been fixed, be sure to download the newest bypass definitions
