### ISSUE TITLE
Broken bypass at uprot.net

### ISSUE THREAD

**Issue by xlollomanx** [FastForwardTeam/FastForward#650]
### Domain

https://uprot.net

### Link

https://uprot.net/msf/0cmn25dav698

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by reashetyrr** [comment]
for me with the newest bypass definitions downloaded it works

**Comment by xlollomanx** [comment]
> for me with the newest bypass definitions downloaded it works

I've tried again just now and it works. Probably my definitions where not up to date. Thank you for your work and sorry for the disturb.

**Comment by reashetyrr** [comment]
its fine, when you inserted the issue the bypass definitions did not work properly
