### ISSUE TITLE
adpaylink it's not bypass

### ISSUE THREAD

**Issue by HM-BlueBird** [FastForwardTeam/FastForward#652]
### Domain

https://adpaylink.com/

### Link

https://adpaylink.com/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

please add this link to the list of extensions, thanks you.

**Comment by lostdusty** [comment]
Could you give an example link?

**Comment by HM-BlueBird** [comment]
> Could you give an example link?

Yeah sure, here's the link for example : https://adpaylink.com/full?api=1c5f7856959eae320c7b536d8eb273c28c3b6bab&url=aHR0cHM6Ly93d3c1OS56aXBweXNoYXJlLmNvbS92L0FQSTJMNTJpL2ZpbGUuaHRtbA==&type=2

**Comment by HM-BlueBird** [comment]
Aw! Thanks Man, its WORKING NOW!!!
Thanks For Contributor and Developers to add this, i closed this issue now.
![image](https://user-images.githubusercontent.com/79822926/182006210-fb4436d9-823f-4243-a434-bcde134a6d49.png)
