### ISSUE TITLE
Work.ink not bypassing

### ISSUE THREAD

**Issue by elo12344** [FastForwardTeam/FastForward#655]
### Domain

work.ink

### Link

https://work.ink/en/l/159/BeeSwarmSimulator2

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

fastforward for some reason bypass work.ink and site has pop ups and i need to do tasks to acess to site and it anoys me bc of pop ups and tasks so if u can bypass this site it would be great

**Comment by Luiaves** [comment]
Please fix this i need help too

**Comment by ghost** [comment]
Duplicate of #488.
