### ISSUE TITLE
https://pahe.li/

### ISSUE THREAD

**Issue by DanTheMobileComputerMan** [FastForwardTeam/FastForward#659]
### Domain

https://pahe.li/

### Link

https://intercelestial.com/#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

When clicking on any link at the domain, redirected eventually to a blank page with the message "no such file exists". Links on this domain work fine when FastForward is disabled, though.

**Comment by lostdusty** [comment]
Fixed in #758.
