### ISSUE TITLE
clg.am

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#66]
### Domain

clg.am

### Link

http://clg.am/GameFuelLinkus 

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://clg.am/ShopLinkus
http://clg.am/GameFuelLinkus 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lem6ns** [comment]
What is this for? Tracker Bypass?

**Comment by toyboatcash** [comment]
yes this is for a Tracker Bypass
