### ISSUE TITLE
https://eio.io/haEhx not working

### ISSUE THREAD

**Issue by Praveensenpai** [FastForwardTeam/FastForward#664]
### Domain

https://eio.io/haEhx

### Link

https://eio.io/haEhx

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### Anything else?

for some working and some not

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
