### ISSUE TITLE
 https://stfly.me/ is no-longer working

### ISSUE THREAD

**Issue by BoscoFZ** [FastForwardTeam/FastForward#667]
### Domain

 https://stfly.me/

### Link

https://stfly.me/EOETCrX

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by kevin01523** [comment]
i think its specific  to this url  since it direct into ouo url

oh i think it still works on kiwi but broken o edge it seems or chrome

**Comment by lostdusty** [comment]
Fixed in #758.
