### ISSUE TITLE
FastForward doesn't work with ckk.ai

### ISSUE THREAD

**Issue by FerdinandoPH** [FastForwardTeam/FastForward#668]
### Domain

ckk.ai

### Link

https://ckk.ai/SH37wF

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

The extension does nothing when entering this page. I have a special interest in bypassing this domain because I haven't found any way to get to the destination link manually (I get trapped in a maze of unavoidable ads).

Good luck fixing this, and thank you for making this extension!

**Comment by kevin01523** [comment]
yep same broken  on my side both tested from kiwi(mobile) and edge

**Comment by ghost** [comment]
same for me. I get redirected to Magybu.net.

Not sure if anyone else has this same problem

**Comment by kevin01523** [comment]
I guess crowdbypass is also down for this site

**Comment by kevin01523** [comment]
Still broken

**Comment by Tenome** [comment]
Still broken.

**Comment by ghost** [comment]
Keeping this open because I have a MV3 bypass for this site, so I can just translate that to the mv2 version.

**Comment by Tenome** [comment]
Damn, I didn't even notice that this site has been broken since at least August.

**Comment by Tenome** [comment]
Any luck?

**Comment by undeadjess** [comment]
i believe crowd-bypass fixes this

**Comment by kevin01523** [comment]
crowd bypass has been not working foir ages now i guess it got fixed 
but i think it can still bypassed like thw oldway without relying on crowd bypass or use crowdbypass as a backup or fallback

it still does have some problems though
ocggpihchhomkgodkjjejbajojamlbmi is blockedThis page has been blocked by Chrome
ERR_BLOCKED_BY_CLIENT

![image](https://user-images.githubusercontent.com/8380242/227754296-77b46b9c-4349-45af-9fc4-529e524e6c7e.png)

**Comment by undeadjess** [comment]
i saw that too, just after i sent this. im not sure why thats happening, ill ask the other devs. we will go back to a local bypass in the mv3 build which is coming in a few weeks.

**Comment by kevin01523** [comment]
now for me  the pop  up for the links hasn't been been visited does not show up and that error does not come.feels like sometime it works sometime it doesn't

**Comment by NotAProton** [comment]
You can try out the (experimental) mv3 version here: https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3

**Comment by kevin01523** [comment]
was looking for this but cant find it. yeah the mv3 version doesn't work for me only the edge version with crowd bypass whats the difference since its update that broke crowdbypass for me for the recent versions
i think it was some weird bug with the homepage etc when moved from sainans version and proper script indentation.

**Comment by Tenome** [comment]
Yeah, mv3 doesn't work for me either it seems. Oh well, I'll just forget about it and then be surprised when it works one day.

**Comment by kevin01523** [comment]
it was broke when the website changed a bit but i do think its still fixable

**Comment by nathanredblur** [comment]
same for tii.la domain

**Comment by kevin01523** [comment]
yeah still broken tested both on mv3 and mv2 both firefox and chrome and on arch linux and windows too

**Comment by Tenome** [comment]
Are we still waiting on the fabled mv3 1.0 release before FastForward actually starts working again? I was using it just fine like 6 months ago, but now my reason for installing this isn't functioning (crowd bypasses).

**Comment by kevin01523** [comment]
can we still use the mv2 version ?

**Comment by lostdusty** [comment]
> can we still use the mv2 version ?

Yes you can.
