### ISSUE TITLE
Elsticsearch's Kibana dashboard doesn't load when the extension is enabled [Version : 0.2039]

### ISSUE THREAD

**Issue by taoufix** [FastForwardTeam/FastForward#669]
### Body

Elsticsearch's Kibana dashboard doesn't load when the extension is enabled and gives the following error:
```
Please upgrade your browser
This Elastic installation has strict security requirements enabled that your current browser does not meet.
```
![image](https://user-images.githubusercontent.com/1518/183959619-a0166f76-9c51-40fa-906e-f7d48f836207.png)

When the extension is disabled, the dashboard loads correctly.

Demo dashboard
https://demo.elastic.co/app/kibana

**Version : 0.2039**

Meta Bug: the form to submit this bug doesn't list the versions and has only one option, 0.0.0.

### Version

0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
Seems to be working for me, try seeing if it is due to any other extensions.

Closing now due to inability to reproduce, but OP can open a new issue if they can replicate the issue.
