### ISSUE TITLE
Request to add domain http://ccl1.xyz/odr20

### ISSUE THREAD

**Issue by thanhbinhpv** [FastForwardTeam/FastForward#671]
### Domain

http://ccl1.xyz/odr20

### Link

http://ccl1.xyz/odr20

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

hope you add this web to the tool.

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
