### ISSUE TITLE
cutdl.xyz  not bypassing

### ISSUE THREAD

**Issue by ezn24** [FastForwardTeam/FastForward#672]
### Domain

cutdl.xyz

### Link

cutdl.xyz

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by SkilledAlpaca** [comment]
Same issue on Firefox v105.0.3 on Windows 10

**Comment by ghost** [comment]
Duplicate of #167.
