### ISSUE TITLE
Links redirecting to Magybu.net in Chrome

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#673]
### Domain

https://ckk.ai/V7x4eu57

### Link

https://ckk.ai/V7x4eu57

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

When clicking on the link, it would take you to a urlshortener, most likely by adf.ly, and after do a 'I'm not a robot' gatcha, you click 'Get Link' It would look like it is bypassing the rest but it take you do magybu.net stating that This page isn't working and that the site redirected you too many times.

Clicking reload does nothing. I have turn off FF and the same result happens. Not sure if it is on my end or not but this never happen before until yesterday when I went to download from the link.

Links works correctly with FF on in Edge but not with Google Chrome.

**Comment by kevin01523** [comment]
Also based on what type of bypass it makes i suggest that removing or at least make it work without crowdbypass enabled. As the current bypass doesn't rely on crowdbypass

**Comment by ghost** [comment]
Duplicate of #668.

However, @Dragoonity, I highly recommend you post the behavior of the site on that issue so that the developers can see everything in one issue,
