### ISSUE TITLE
https://mhma12.tech/

### ISSUE THREAD

**Issue by Nzzyme** [FastForwardTeam/FastForward#674]
### Domain

mhma12.tech

### Link

https://mhma12.tech/best-enterprise-account-management-program-in-the-arab-world-review-plus/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Hello,

I visit the following link: https://hoxiin.com/1D5pJKcj and then the redirection journey starts with the domain mhma12.tech hopping on to multiple sub-sites. Can you please address?

![image](https://user-images.githubusercontent.com/6959116/184590878-775a4090-3a18-47cf-b205-04c93eb6bac7.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
