### ISSUE TITLE
Captchas on PortableApps.com broken on Chrome

### ISSUE THREAD

**Issue by RuiNtD** [FastForwardTeam/FastForward#676]
### Body

The captcha on https://portableapps.com/user/register doesn't work with FastForward installed, telling me to "upgrade to a supported browser."

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

I'm currently running version 0.2086, but I only have the option to select 0.0.0
![](https://fayne-is.a-shitty.dev/i/hYrtdA)

**Comment by lostdusty** [comment]
Adding the page to whitelist makes the captcha work.
