### ISSUE TITLE
Not Bypassing this website https://push.bdnewsx.com/

### ISSUE THREAD

**Issue by rakitanc** [FastForwardTeam/FastForward#677]
### Body

10 second countdown is coming

### Version

0.2025

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Linux

**Comment by yo-honey** [comment]
Mine is stuck on 7 seconds & even i can't click after waiting 10-20 decs

**Comment by rakitanc** [comment]
Is this solved?

**Comment by rakitanc** [comment]
Hey there..Please update on this

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
