### ISSUE TITLE
shrinkme.io not getting bypass

### ISSUE THREAD

**Issue by Sahil12524** [FastForwardTeam/FastForward#678]
### Domain

shrinkme.io

### Link

https://shrinke.me/kGGDQ

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
