### ISSUE TITLE
cdn.krnl.place is detecting FastForward

### ISSUE THREAD

**Issue by localfossa** [FastForwardTeam/FastForward#679]
### Domain

https://cdn.krnl.place

### Link

https://cdn.krnl.place/getkey

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

This link redirects me to linkvertise but linkvertise redirects to https://cdn.krnl.place/getkey_somethingrandom then it shows suspicious code: 2

**Comment by lostdusty** [comment]
Won't fix, as we don't bypass krnl anymore. (Why we don't bypass? Because krnl is cheating, and we don't approve that)
