### ISSUE TITLE
MegaDB broken bypass

### ISSUE THREAD

**Issue by What-dev** [FastForwardTeam/FastForward#681]
### Domain

https://megadb.net/

### Link

https://megadb.net/download

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

It looks like it tries but MegaDB throws an error "skipped countdown". Only works after disabling FF and reloading the page.

**Comment by ghost** [comment]
Duplicate of #610.
