### ISSUE TITLE
Not Bypassing ier.ai - Health 2 Wealth

### ISSUE THREAD

**Issue by NicolasBse** [FastForwardTeam/FastForward#682]
### Domain

ier.ai

### Link

https://ier.ai/RiGH3twaW

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

The extension does nothing when entering this page. I have a special interest in bypassing this domain because I haven't found any way to get to the destination link manually (I get trapped in a maze of unavoidable ads).

Good luck fixing this, and thank you for making this extension!

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
