### ISSUE TITLE
bc.vc is not bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#684]
### Domain

bcvc.xyz

### Link

https://bcvc.xyz/vQesLIh

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by Ast3risk-ops** [comment]
I have the same issue, am on same browser and OS, and have crowd bypass on, still does not work
