### ISSUE TITLE
cshort.org is no longer bypassed

### ISSUE THREAD

**Issue by Vojtak42** [FastForwardTeam/FastForward#685]
### Domain

cshort.org

### Link

https://cshort.org/LPMNEEqK

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
