### ISSUE TITLE
Mega.nz Redirect Fail.

### ISSUE THREAD

**Issue by p0008874** [FastForwardTeam/FastForward#686]
### Body

https://user-images.githubusercontent.com/75534590/186170216-454cca97-48a2-4dee-a6b3-f93ff16738fd.mp4

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://user-images.githubusercontent.com/75534590/186170251-5d5bde36-d415-4444-98b2-cdcbf7f7829e.mp4

**Comment by ghost** [comment]
This seems like a problem with the person who created the file as they have password-protected it. You'll need to ask them for the password, as I saw FastForward work properly there.
