### ISSUE TITLE
FastForward notification stuck on file-upload.com files page

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#687]
### Domain

file-upload.com

### Link

https://www.file-upload.com/?op=my_files

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

I'm using file-upload.com for upload files. FastForward notification get stuck forever even you are not downloading file

![image](https://user-images.githubusercontent.com/70694330/186235881-6d455f1d-2a2b-478a-b337-b9e1cbb15582.png)

**Comment by undeadjess** [comment]
hi, you can click the notifications to make it magically vanish in a puff of smoke. the notification is intended behavior, as we have no way of knowing what uris might be used on the page.
