### ISSUE TITLE
Shrinke.me not bypassing

### ISSUE THREAD

**Issue by SimoCharhbili** [FastForwardTeam/FastForward#688]
### Domain

https://shrinke.me

### Link

https://shrinke.me/AP7l8B

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by K4Z3R0** [comment]
+1

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
