### ISSUE TITLE
https://stfly.me/XXXXX  no longer being able to bypassed

### ISSUE THREAD

**Issue by SilentOfChaos** [FastForwardTeam/FastForward#689]
### Domain

https://stfly.me/

### Link

https://stfly.me/6HSlNqW

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

FastForward unable to bypass shorten links from https://stfly.me/ (example: https://stfly.me/6HSlNqW).

**Comment by kaiji05** [comment]
https://buzzzfly.bid/w/XXXXXX

**Comment by lostdusty** [comment]
Fixed in #758.
