### ISSUE TITLE
Buzzzfly.bid not bypassing

### ISSUE THREAD

**Issue by kaiji05** [FastForwardTeam/FastForward#690]
### Domain

https://bitcotask.com

### Link

https://buzzzfly.bid/w/RM6nZeC

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
