### ISSUE TITLE
Curto.win counter bypass

### ISSUE THREAD

**Issue by mstromboli** [FastForwardTeam/FastForward#692]
### Domain

https://curto.win

### Link

https://curto.win/jGWzoC

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

There is a 120 second long counter.  It would be great if the counter could be negated, or at least shortened by this tool.

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
