### ISSUE TITLE
 problem with adshort.co, infinite bypass loading

### ISSUE THREAD

**Issue by gabri25ele** [FastForwardTeam/FastForward#693]
### Body

Domain

https://adshort.co/
Link

https://adshort.co/exfD5
Version

0.0.0
What browsers are you seeing the problem on?

Firefox
What OS are you seeing the problem on?

Windows
Anything else?

in https://adshort.co/ link, an infinite re-loop loading.
no captcha appears.

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
Duplicate of #424.
