### ISSUE TITLE
Mealob.com not bypassing

### ISSUE THREAD

**Issue by scrtdev** [FastForwardTeam/FastForward#694]
### Domain

https://185.53.88.204/

### Link

mealob.com/?id=VeryVeryVeryLongRandomIDHere

### Version

0.2025

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Version 0.2025 · Bypass definitions 0245857

pls fix it is not working on downloading links of https://185.53.88.204

**Comment by ghost** [comment]
Can you provide a working example link so that we can take a look?
