### ISSUE TITLE
https://informaxonline.com

### ISSUE THREAD

**Issue by ghost** [FastForwardTeam/FastForward#695]
### Domain

informaxonline.com

### Link

https://informaxonline.com/?link=Tk2mYil

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Fastforward redirects me to dead home pages of the site and sometimes I finish at the fast forward error page. In the second screenshot it looks like this error is caught due to the installed addons, but I have tried this also on  incognito mode with only this addon and on other browsers

![Knipsel](https://user-images.githubusercontent.com/57501353/188290315-fc4bea87-fdb3-44f6-80b6-7df0d27960ab.PNG)
![Knipsel123](https://user-images.githubusercontent.com/57501353/188290347-70b02104-a33c-4313-8e34-1966a2caa42f.PNG)

**Comment by ghost** [comment]
There has been made a bug report about this before but that got closed automatically

**Comment by blazesprings** [comment]
@erik9012 I had opened the issue few months ago but the problem still persists. Please check on your side and fix it.

**Comment by ghost** [comment]
How can i fix something on my side? You had opened a issue a few months
ago, I have the same issue and with opening a new issue I mention that
indeed the issue is still active and needs a fix

Op zo 4 sep. 2022 om 19:43 schreef blazesprings ***@***.***>:

**Comment by undeadjess** [comment]
heya, this will be solved when you update the version of the addon that you use. please follow the guide here: https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md
