### ISSUE TITLE
FastForward breaks National Australia Bank banking website

### ISSUE THREAD

**Issue by keatit71** [FastForwardTeam/FastForward#696]
### Body

When trying to access https://ib.nab.com.au/nabib/index.jsp?browser=correct nothing loads except some text with this addon enabled and without it disabled the website loads properly.

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

I saw there was a whitelist feature being developed so maybe before that you could tell me how to whitelist nab so it works with this addon.

**Comment by abadawe-dev** [comment]
Seems to work, please test again.

**Comment by ghost** [comment]
Closing this as OP has not responded in a while; if you can find evidence to reproduce this error, please make another issue (disable all other extensions).
