### ISSUE TITLE
linkvertise bypass not working??

### ISSUE THREAD

**Issue by gigachadUltraShaggy100X** [FastForwardTeam/FastForward#699]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/473298/demonrpgscript/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

i am using opera GX browser but i said chrome because thats the browser i used to download the extension

**Comment by reashetyrr** [comment]
Does this link direct to a linkvertise paste or file?

**Comment by reashetyrr** [comment]
I just checked this on my phone with the latest bypass definitions and it worked for me...

**Comment by lostdusty** [comment]
It also worked here just fine, closing this issue
