### ISSUE TITLE
httpslink.com

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#70]
### Domain

httpslink.com

### Link

https://httpslink.com/2dollars

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
These shorteners are mostly harmless, this project is more focused on bypassing annoying captchas. We will try to bypass these, but please post link shorteners that are annoying rather than every link shortener in existence.

**Comment by lostdusty** [comment]
Domain expired, closing this issue.
