### ISSUE TITLE
can't bypass 

### ISSUE THREAD

**Issue by RvJames26** [FastForwardTeam/FastForward#700]
### Domain

https://linkspy.cc

### Link

https://linkspy.cc/tr/aHR0cHM6Ly9hZHBheWxpbmsuY29tL2Z1bGw/YXBpPTMwMmYzMWRmOTdiMDQ2MWRkMjhkODcxZjlmZTVjODA3YTQzNTViNmMmdXJsPWFIUjBjSE02THk5M2QzY3VabWxzWldOeWVYQjBMbU5qTDBOdmJuUmhhVzVsY2k5Q01ERXhORUpHUmpJM0xtaDBiV3c9JnR5cGU9Mg==

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by abadawe-dev** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/6b4d060d21f7a4580a46dd2fed246082bc1814f3, please colse.

**Comment by ghost** [comment]
Closed at request of @N0-0NE-Dev.
