### ISSUE TITLE
MegaDB downloads

### ISSUE THREAD

**Issue by Kingkiller690** [FastForwardTeam/FastForward#701]
### Domain

MegaDB.net

### Link

https://megadb.net/1kihmrrf3izw

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Yeah, this link and every other megaDB download (ignore the steamrip)

**Comment by ghost** [comment]
Duplicate of #610.
