### ISSUE TITLE
Chrome Store version is gone?

### ISSUE THREAD

**Issue by dnet890** [FastForwardTeam/FastForward#704]
### Body

I tried to open the url (https://chrome.google.com/webstore/detail/fastforward/icallnadddjmdinamnolclfjanhfoafe) and the extension is gone. 

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/29157187/189598246-2b745663-2c10-4796-80d1-e1e9bc1a4f99.png)

**Comment by sjain882** [comment]
The extension just got disabled in Chrome for me due to "being marked as malware"

**Comment by ErbiumStrike** [comment]
MS edge disabled the extension now calling it malware!

**Comment by dnet890** [comment]
Is this false positive or real malware?

**Comment by reashetyrr** [comment]
This is definitely a false positive, you can check the complete source on main

**Comment by dnet890** [comment]
yeah the Firefox and the Edge page is still live too. But, I hope MS or Mozilla does not follow the same path as well.

**Comment by sjain882** [comment]
> This is definitely a false positive, you can check the complete source on main

Correct me if I'm wrong, but isn't it possible for the web store build to differ from the git? Such was the case with the extension "Nano Defender" a while ago. I guess it's best to wait for a statement from the developers

**Comment by JunkiEDM** [comment]
It seems they're aware of the issue as they've modified the readme with changes to the [Chromium based browsers](https://github.com/FastForwardTeam/FastForward/blob/main/README.md#chromium-based-browsers) section, removing the link to CWS and pointing you in the direction of installing the extension manually on browsers other than edge and firefox. 

On Kiwi Browser it disables the extension with the warning: "This extension violates the Chrome Web Store policy." with no mention of malware, which might be closer to the truth in this case.

Just to be safe though, you can always compare your [installed version's source code](https://www.howtogeek.com/198964/HOW-TO-VIEW-THE-SOURCE-CODE-OF-A-CHROME-EXTENSION/) with the code in this git repo.

**Comment by JunkiEDM** [comment]
It could have been removed in reference to [this section](https://developer.chrome.com/docs/webstore/program_policies/#prohibited-products) of the policy, although it isn't super clear. 
![Screenshot of Chrome's Web Store Policy](https://user-images.githubusercontent.com/8350274/189610731-5c6fe85a-2f6c-4911-812a-af1c8142912e.jpg)

**Comment by JunkiEDM** [comment]
Google has also been known to block extensions which don't violate any policies, but don't align with their business interests, [such as is the case with AdNauseum](https://adnauseam.io/free-adnauseam.html), which in this case could be that it skips Google's link tracking on search results.

**Comment by undeadjess** [comment]
Google has removed the extension, they said it violates the chrome web store polices as it bypasses paywalls. this is not true, and we have asked google to reconsider the decision. more information of this is available on our discord (https://discord.gg/RSAf7b5njt)

For now, you can manually install the extension with instructions [here](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md)

We can assure you that it is not malicious, and that what you have come across is a false positive.

To be clear, both Microsoft and Mozilla still list the extension, and will probably not remove it.

**Comment by SofiaRedmond** [comment]
> MS edge disabled the extension now calling it malware!

Download it from [Edge Extensions Store](https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl)

**Comment by iznawh** [comment]
if its already installed via chrome store does it still work or do i need to install it the manual way ?

**Comment by undeadjess** [comment]
you should simply be able to turn it on in [the extensions page](chrome://extentions), and that will re enable it. this is also good because if we get it back onto the chrome web store, it will automatically update

**Comment by 0x11DFE** [comment]
We need a release for chromium!

**Comment by undeadjess** [comment]
> We need a release for chromium!

you can install the extension on any chromium browser with the instructions [here](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md)

**Comment by agret** [comment]
> MS edge disabled the extension now calling it malware!

Nope, Google did. The Edge version is still available and working.

https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl

> yeah the Firefox and the Edge page is still live too. But, I hope MS or Mozilla does not follow the same path as well.

Mozilla is a lot better about this than Google. Google has a vested interest in advertising / paid web content.

For instance, the bypass paywall extension is still available on the Mozilla store for some years now, Chrome doesn't allow it on the web store.

https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean/

> you should simply be able to turn it on in the extensions page, and that will re enable it. this is also good because if we get it back onto the chrome web store, it will automatically update

No can do, when they are flagged for malware you can't turn them back on. I've seen a bunch of my extensions get marked as malware, I think it's a generic thing that Google are marking old extensions as malware to try and force the developer to release an update.

![image](https://user-images.githubusercontent.com/568523/190065781-d7113704-e531-40d5-824b-06f9640a901f.png)

**Comment by Lamby777** [comment]
that's some real bullshit, man. hopefully everyone's gonna see this from search engines like I did.

**Comment by g-k-m** [comment]
idk why everyone is making such a fuss. just use this https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon does the same job, prob there's another 100 extensions that do the same thing

**Comment by dnet890** [comment]
I saw the chrome store reviews that alternative have some flaws compare to Fastforward (like some sites does not worked).

**Comment by Doc-4** [comment]
> idk why everyone is making such a fuss. just use this https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon does the same job, prob there's another 100 extensions that do the same thing

Having used both extensions, these in no way do the same job, one is not a replacement for the other. Beyond that, this extension was removed unjustly, there being a replacement is irrelevant.

**Comment by amaanq** [comment]
I noticed after manually installing, chrome removes the extension by itself after a restart, why in the world is that and how can I prevent that? :)

**Comment by Lamby777** [comment]
> I noticed after manually installing, chrome removes the extension by itself after a restart, why in the world is that and how can I prevent that? :)

Brave Browser :)

**Comment by amaanq** [comment]
> Brave Browser :)

haha good joke, if I had to pick between 2 evils I'm going with google, thanks

**Comment by Doc-4** [comment]
> > Brave Browser :)
> 
> haha good joke, if I had to pick between 2 evils I'm going with google, thanks

Chromium and ungoogled chromium are available if you don't want someone else's version of chrome, they're just chrome with less, and even less unwanted junk respectively. Both are open source, as is Firefox.

**Comment by amaanq** [comment]
> Chromium and ungoogled chromium are available if you don't want someone else's version of chrome, they're just chrome with less, and even less unwanted junk respectively. Both are open source, as is Firefox.

Hmm yeah, I might just switch to Chromium then - thanks for the reminder

**Comment by Pdzly** [comment]
Bruh Chrome Moment

**Comment by waldens** [comment]
After installing it manually (either in unpacked mode or crx mode), will it update automatically in my browser when a new version is released? (or at least, remind me that a new version has been released, will it?)

**Comment by rafalohaki** [comment]
when brave store?

**Comment by AkuStranger** [comment]
Is only me or everyone too? MS edge blocking it.

![crowdbypassblocked](https://user-images.githubusercontent.com/81702563/212207870-8ac01eee-653d-4578-b057-149d6cfc7e64.png)

Bitdefender also blocking because of untrusted certificate

![BitdefenderBlockedconnection](https://user-images.githubusercontent.com/81702563/212208057-ad34fd25-772b-4e81-9507-3cd547fca0ca.png)

**Comment by Lamby777** [comment]
> ![BitdefenderBlockedconnection](https://user-images.githubusercontent.com/81702563/212208057-ad34fd25-772b-4e81-9507-3cd547fca0ca.png)

when the content is sus! 😳

**Comment by undeadjess** [comment]
Our Crowd Bypass server is currently down and doesnt have a valid SSL certificate. Its nothing to worry about and will be fixed soon!

**Comment by Rusenche** [comment]
I followed the steps from here [https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#chrome-chromium-kiwi-opera-opera-gx-vivaldi-brave-etc](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#chrome-chromium-kiwi-opera-opera-gx-vivaldi-brave-etc) and manually installed it in Chromium (I even I packaged and installed it as crx).

But I have a question.

According to [https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl](https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl) - the version is 0.2086. But my Chromium version is 0.2219.

Nowhere on the site - [https://github.com/FastForwardTeam/FastForward/](https://github.com/FastForwardTeam/FastForward/) is there any information on which version is current. Respectively, as soon as the extension is installed manually in Chromium, there will be no update on its own. And here is the question - where exactly on the site should we check which version is the current, up-to-date one, so that I can check periodically if there is a new version?! I'm surprised there's no public coverage for the current version.

**Comment by undeadjess** [comment]
heya
we version by the commit number, the latest is 2221, but any of the recent ones should be fine. the microsoft store stopped allowing us to upload new versions so its a bit behind.

**Comment by Rusenche** [comment]
It's just that you didn't tell me where to look for new versions?! Orient me.

Because basically, there should be new versions here, but you don't have them: https://github.com/FastForwardTeam/FastForward/releases/

**Comment by undeadjess** [comment]
we dont distribute from releases, you can get the latest here:
[chromium](https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/FastForward_chromium.zip)
[firefox](https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/FastForward_firefox.zip)

**Comment by Rusenche** [comment]
The Chromium link is known to me, thanks to it I subsequently installed the crx extension. But how do I know there is a new version by looking at the link?! How do I know it's the latest when it doesn't say what version it is anywhere to tell me if I should update?! That's my question?! :}

**Comment by ilike2burnthing** [comment]
New builds are created after each commit. If there's a new commit, there's a new build to download shortly after.

As for working out if what you have downloaded is a new version, the file name (once unzipped) is the most obvious way (e.g. `FastForward_firefox_0.2222.xpi`), but the `manifest.json` within the addon/extension file also contains the version number.

**Comment by Rusenche** [comment]
`the file name (once unzipped) is the most obvious way`

I had thought of that myself a few hours ago. But the question is: This archive should be downloaded and checked once a week, twice a month?! It is not convenient at all when it is not reflected anywhere which is the current version and so on.

**Comment by ilike2burnthing** [comment]
If you want to stay on the bleeding edge then save https://github.com/FastForwardTeam/FastForward as a bookmark and check every couple of days for the current commit total.

Currently it is `2222` and therefore the version number of the extension is `v0.2222`. If the commit total is greater than your current version number, you can update.

**Comment by ilike2burnthing** [comment]
A quick and dirty batch file updater for Windows:

<details>
<summary>update.bat</summary>

```bat
@ECHO OFF
set URL=https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/
set FILE=FastForward_firefox.zip
:: set FILE=FastForward_chromium.zip
set FOLDER=Update
for /F "delims=" %%i in (LATEST_CHANGE) do set LATEST_CHANGE=%%i

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                         Checking for new version ...                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

if exist %FILE% del %FILE%
if exist %FOLDER% rmdir /s /q %FOLDER%
wget --no-check-certificate %URL%%FILE%
7za e %FILE% -o%FOLDER%
dir /b %FOLDER% > CHECK
for /F "delims=" %%j in (CHECK) do set CHECK=%%j
if not "%LATEST_CHANGE%"=="%CHECK%" goto Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I   You already have the latest FastForward - %LATEST_CHANGE%   I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE%
rmdir /s /q %FOLDER%

goto eof

:Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I      Downloaded the latest FastForward - %CHECK%      I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE%
copy /y CHECK LATEST_CHANGE

:eof

timeout 5
```
</details>

Requires [Wget](https://eternallybored.org/misc/wget/) (wget.exe) and [7-Zip's standalone console](https://7-zip.org/download.html) (7za.exe) in the same directory as the script.

The above downloads the Firefox addon. To download the Chromium extension, move the comment (`:: `) from before the Chromium `FILE` to before the Firefox `FILE`. Only use one. While the script could be rewritten to update both together, it would just be a lot of duplicated lines with `_FIREFOX` and `_CHROMIUM` variants. Much easier to just have 2 update scripts if you need both.

The download `FOLDER` is set as a folder named `Update`, a subdirectory of the folder the script is in. This can be changed to wherever you want, but the folder should be used exclusively by the script. DO NOT use a common folder such as your Downloads or Desktop, as the folder and its contents are deleted on each run.

You can automate this to run on startup with a scheduled task, either checking the folder regularly or adding a line to the end of the script to copy the new addon/extension to somewhere obvious (e.g. Downloads or Desktop).

The script could be made less redundant if devs want to add a `version.txt` file with the version number in it to the main.yml workflow. Not really vital though, we're only talking about 0.5MB anyway.

**Comment by ilike2burnthing** [comment]
I said it would be kinda pointless, so of course then I had to do it. This is what I'm now using, with a scheduled task for startup and midnight, and the updated addon and extension files copied to the Downloads folder:

<details>
<summary>update.bat</summary>

```bat
@ECHO OFF
set URL=https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/
set FILE_FIREFOX=FastForward_firefox.zip
set FILE_CHROMIUM=FastForward_chromium.zip
set FOLDER=Update
set FOLDER_NEW=%UserProfile%\Downloads
for /F "delims=" %%i in (LATEST_CHANGE) do set LATEST_CHANGE=%%i

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                         Checking for new version ...                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

if exist %FILE_FIREFOX% del %FILE_FIREFOX%
if exist %FILE_CHROMIUM% del %FILE_CHROMIUM%
if exist %FOLDER% rmdir /s /q %FOLDER%
wget --no-check-certificate %URL%%FILE_FIREFOX% %URL%%FILE_CHROMIUM%
7za e *.zip -o%FOLDER%
dir /b %FOLDER% > CHECK
for /F "delims=" %%j in (CHECK) do set CHECK=%%j
if not "%LATEST_CHANGE%"=="%CHECK%" goto Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I   You already have the latest FastForward - %LATEST_CHANGE%   I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM%
rmdir /s /q %FOLDER%

goto eof

:Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I      Downloaded the latest FastForward - %CHECK%      I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM%
copy /y CHECK LATEST_CHANGE
copy %FOLDER% %FOLDER_NEW%

:eof

timeout 5
```
</details>

**Comment by Rusenche** [comment]
> I said it would be kinda pointless, so of course then I had to do it. This is what I'm now using, with a scheduled task for startup and midnight, and the updated addon and extension files copied to the Downloads folder:
> 
> update.bat

**This comment with the bat file was helpful.** Accordingly, I immediately packed it into a crx file and installed it that way.

Turns out there was an update since I wrote two days ago because I think I was on v.0.2219. So there were new versions, but that was the ambiguity - there was a new version, but we don't know about the new version anywhere. ;)

It turned out that the RSS reader didn't help either.

For now, the inconvenience is in two cases:
1. Periodically enter the site and watch for a new number above 2222;
2. Periodically run the bat file.

As in both cases "periodically" means subjectively unclear after how many days/weeks.

**Comment by ilike2burnthing** [comment]
Scheduled task solves that.

**Comment by Rusenche** [comment]
> You can automate this to run on startup with a scheduled task, either checking the folder regularly or adding a line to the end of the script to copy the new addon/extension to somewhere obvious (e.g. Downloads or Desktop).


In principle, it can also with every reboot or with every OS start, but what's the use, as the folder will be jammed with downloads or with a change v.2222 1; v.2222 2 or similar accumulation I suppose. ;)

This is the first time I've come across something that offers new versions but doesn't make them public to show that there's a new version. :D

**Comment by ilike2burnthing** [comment]
No, the Upload folder is deleted on each run, so you're not going to end up with multiple addon/extension files.

With the second version of the script and a scheduled task you never need to go checking for updates again, they'll just appear on your Desktop or in your Downloads folder whenever one is available. That's the closest thing you're getting to auto-updates for now.

**Comment by Rusenche** [comment]
> No, the Upload folder is deleted on each run, so you're not going to end up with multiple addon/extension files.
> 
> With the second version of the script and a scheduled task you never need to go checking for updates again, they'll just appear on your Desktop or in your Downloads folder whenever one is available. That's the closest thing you're getting to auto-updates for now.

It sounds good. With this bat file it is better than nothing or than it was before.

I have a request for this script.

It would be nice for those of us using Chromium to have a Chromium window at the bottom of the script after it ends.

I circle it in red to show what I mean. My thought is that under that circled in red there is the same information under it, but for Chromium. Yes, you will write that the information is there, but it is hidden, and the script quickly shuts down (well, for myself I made it 20 seconds). But it would be good if you implement my idea. :}

**Comment by ilike2burnthing** [comment]
Was there supposed to be a screenshot with your comment?

I think I get what you mean, so I'll rustle something up.

**Comment by Rusenche** [comment]
> Was there supposed to be a screenshot with your comment?
> 
> I think I get what you mean, so I'll rustle something up.

You are absolutely right that I forgot to attach a picture. :}

https://i.postimg.cc/bNqr9CcY/Ahh.png

**Comment by ilike2burnthing** [comment]
Probably could be cleaner, but it's working:

<details>
<summary>update.bat</summary>

```bat
@ECHO OFF
set URL=https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/
set FILE_FIREFOX=FastForward_firefox.zip
set FILE_CHROMIUM=FastForward_chromium.zip
set FOLDER=Update
set FOLDER_NEW=%UserProfile%\Downloads
for /F "delims=" %%i in (LATEST_CHANGE_FIREFOX) do set LATEST_CHANGE_FIREFOX=%%i
for /F "delims=" %%j in (LATEST_CHANGE_CHROMIUM) do set LATEST_CHANGE_CHROMIUM=%%j

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                         Checking for new version ...                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

if exist %FILE_FIREFOX% del %FILE_FIREFOX%
if exist %FILE_CHROMIUM% del %FILE_CHROMIUM%
if exist %FOLDER% rmdir /s /q %FOLDER%
wget --no-check-certificate %URL%%FILE_FIREFOX% %URL%%FILE_CHROMIUM%
7za e FastForward_firefox.zip -o%FOLDER%\Firefox
7za e FastForward_chromium.zip -o%FOLDER%\Chromium
dir /b %FOLDER%\Firefox > CHECK_FIREFOX
dir /b %FOLDER%\Chromium > CHECK_CHROMIUM
for /F "delims=" %%k in (CHECK_FIREFOX) do set CHECK_FIREFOX=%%k
for /F "delims=" %%l in (CHECK_CHROMIUM) do set CHECK_CHROMIUM=%%l
if not "%LATEST_CHANGE_FIREFOX%"=="%CHECK_FIREFOX%" goto Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                   You already have the latest FastForward:                   I
echo I                                                                              I
echo I                       %LATEST_CHANGE_CHROMIUM%                        I
echo I                       %LATEST_CHANGE_FIREFOX%                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM%
rmdir /s /q %FOLDER%

goto eof

:Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                      Downloaded the latest FastForward:                      I
echo I                                                                              I
echo I                       %CHECK_CHROMIUM%                        I
echo I                       %CHECK_FIREFOX%                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM%
copy /y CHECK_FIREFOX LATEST_CHANGE_FIREFOX
copy /y CHECK_CHROMIUM LATEST_CHANGE_CHROMIUM
copy %FOLDER%\Firefox %FOLDER_NEW%
copy %FOLDER%\Chromium %FOLDER_NEW%

:eof

timeout 5
```
</details>

Now displays:

```bat
--------------------------------------------------------------------------------
I                                                                              I
I                   You already have the latest FastForward:                   I
I                                                                              I
I                       FastForward_chromium_0.2224.zip                        I
I                       FastForward_firefox_0.2224.xpi                         I
I                                                                              I
--------------------------------------------------------------------------------
```

```bat
--------------------------------------------------------------------------------
I                                                                              I
I                      Downloaded the latest FastForward:                      I
I                                                                              I
I                       FastForward_chromium_0.2224.zip                        I
I                       FastForward_firefox_0.2224.xpi                         I
I                                                                              I
--------------------------------------------------------------------------------
```

You can manually delete the `CHECK` and `LATEST_CHANGE` files, they're no longer used.

**Comment by Rusenche** [comment]
It's better that way. Well done.

Do these files make sense:
- CHECK_CHROMIUM;
- CHECK_FIREFOX;
- LATEST_CHANGE_CHROMIUM;
- LATEST_CHANGE_FIREFOX.

I mean - it's better if the bat file doesn't create them at all.

I mean - to create only these two files FastForward_chromium_0.2224.zip and FastForward_firefox_0.2224.xpi directly in the same folder. I think there is no need for the bat file to put these two files in new folders - Chromium and Firefox?

To be cleaner. :}

**Comment by ilike2burnthing** [comment]
The `LATEST_CHANGE_` files are used as a way to carry across the last downloaded version number to a different instance of the script being run hours or days later. These are then compared against the `CHECK_` files, which are copied over the `LATEST_CHANGE_` files when there's a new update. I don't really see a way of doing this without persistent files.

The easiest way to display both files names in that summary was to put them in a separate folder. Given that the files are then copied elsewhere it doesn't really seem all that important that they're in 2 separate folders.

Best I can do (only the `LATEST_CHANGE_` files should be left over, and you can delete the `.wget-hsts` file, it will no longer be created):

<details>
<summary>update.bat</summary>

```bat
@ECHO OFF
set URL=https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/
set FILE_FIREFOX=FastForward_firefox.zip
set FILE_CHROMIUM=FastForward_chromium.zip
set FOLDER=Update
set FOLDER_NEW=%UserProfile%\Downloads
for /F "delims=" %%i in (LATEST_CHANGE_FIREFOX) do set LATEST_CHANGE_FIREFOX=%%i
for /F "delims=" %%j in (LATEST_CHANGE_CHROMIUM) do set LATEST_CHANGE_CHROMIUM=%%j

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                         Checking for new version ...                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

if exist %FILE_FIREFOX% del %FILE_FIREFOX%
if exist %FILE_CHROMIUM% del %FILE_CHROMIUM%
if exist %FOLDER% rmdir /s /q %FOLDER%
wget --no-check-certificate --no-hsts %URL%%FILE_FIREFOX% %URL%%FILE_CHROMIUM%
7za e FastForward_firefox.zip -o%FOLDER%\Firefox
7za e FastForward_chromium.zip -o%FOLDER%\Chromium
dir /b %FOLDER%\Firefox > CHECK_FIREFOX
dir /b %FOLDER%\Chromium > CHECK_CHROMIUM
for /F "delims=" %%k in (CHECK_FIREFOX) do set CHECK_FIREFOX=%%k
for /F "delims=" %%l in (CHECK_CHROMIUM) do set CHECK_CHROMIUM=%%l
if not "%LATEST_CHANGE_FIREFOX%"=="%CHECK_FIREFOX%" goto Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                   You already have the latest FastForward:                   I
echo I                                                                              I
echo I                       %LATEST_CHANGE_CHROMIUM%                        I
echo I                       %LATEST_CHANGE_FIREFOX%                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM% CHECK_*
rmdir /s /q %FOLDER%

goto eof

:Downloaded

echo --------------------------------------------------------------------------------
echo I                                                                              I
echo I                      Downloaded the latest FastForward:                      I
echo I                                                                              I
echo I                       %CHECK_CHROMIUM%                        I
echo I                       %CHECK_FIREFOX%                         I
echo I                                                                              I
echo --------------------------------------------------------------------------------

del %FILE_FIREFOX% %FILE_CHROMIUM%
move /y CHECK_FIREFOX LATEST_CHANGE_FIREFOX
move /y CHECK_CHROMIUM LATEST_CHANGE_CHROMIUM
copy %FOLDER%\Firefox %FOLDER_NEW%
copy %FOLDER%\Chromium %FOLDER_NEW%
rmdir /s /q %FOLDER%

:eof

timeout 5
```
</details>

Always open to alternative methods if they're available.

**Comment by Rusenche** [comment]
> The `LATEST_CHANGE_` files are used as a way to carry across the last downloaded version number to a different instance of the script being run hours or days later. These are then compared against the `CHECK_` files, which are copied over the `LATEST_CHANGE_` files when there's a new update. I don't really see a way of doing this without persistent files.
> 
> The easiest way to display both files names in that summary was to put them in a separate folder. Given that the files are then copied elsewhere it doesn't really seem all that important that they're in 2 separate folders.
> 
> Best I can do (only the `LATEST_CHANGE_` files should be left over, and you can delete the `.wget-hsts` file, it will no longer be created):
> 
> update.bat
> Always open to alternative methods if they're available.

Strange. I ran the bat file in a new folder from scratch. It says that the two files FastForward_chromium_0.2224.zip and FastForward_firefox_0.2224.xpi have been created, but they are not in the folder where the bat file is?!


It actually creates them and in less than a second - those two files disappear, self-delete?!


_____________________________

I see them being created in a "Downloaded" folder. Can you make them only be created in the current folder where the bat file is so that they can be seen and used from there.

**Comment by ilike2burnthing** [comment]
That's been the case since https://github.com/FastForwardTeam/FastForward/issues/704#issuecomment-1484429648, but now we're deleting the originals. Just change the value of `FOLDER_NEW` from the current `%UserProfile%\Downloads` to whatever folder you want.

**Comment by Rusenche** [comment]
> That's been the case since [#704 (comment)](https://github.com/FastForwardTeam/FastForward/issues/704#issuecomment-1484429648), but now we're deleting the originals. Just change the value of `FOLDER_NEW` from the current `%UserProfile%\Downloads` to whatever folder you want.

My idea is not to specify a specific folder, but to have it be the current folder. How is this supposed to happen?!

___________________________________

I changed to: set FOLDER=%FOLDER%

______________

Actually - no, that doesn't work. Can I have a solution?



```
> @ECHO OFF
> set URL=https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/
> set FILE_FIREFOX=FastForward_firefox.zip
> set FILE_CHROMIUM=FastForward_chromium.zip
> set FOLDER=Update
> for /F "delims=" %%i in (LATEST_CHANGE_FIREFOX) do set LATEST_CHANGE_FIREFOX=%%i
> for /F "delims=" %%j in (LATEST_CHANGE_CHROMIUM) do set LATEST_CHANGE_CHROMIUM=%%j
> 
> echo --------------------------------------------------------------------------------
> echo I                                                                              I
> echo I                         Checking for new version ...                         I
> echo I                                                                              I
> echo --------------------------------------------------------------------------------
> 
> if exist %FILE_FIREFOX% del %FILE_FIREFOX%
> if exist %FILE_CHROMIUM% del %FILE_CHROMIUM%
> if exist %FOLDER% rmdir /s /q %FOLDER%
> wget --no-check-certificate --no-hsts %URL%%FILE_FIREFOX% %URL%%FILE_CHROMIUM%
> 7za e FastForward_firefox.zip -o%FOLDER%\Firefox
> 7za e FastForward_chromium.zip -o%FOLDER%\Chromium
> dir /b %FOLDER%\Firefox > CHECK_FIREFOX
> dir /b %FOLDER%\Chromium > CHECK_CHROMIUM
> for /F "delims=" %%k in (CHECK_FIREFOX) do set CHECK_FIREFOX=%%k
> for /F "delims=" %%l in (CHECK_CHROMIUM) do set CHECK_CHROMIUM=%%l
> if not "%LATEST_CHANGE_FIREFOX%"=="%CHECK_FIREFOX%" goto Downloaded
> 
> echo --------------------------------------------------------------------------------
> echo I                                                                              I
> echo I                   You already have the latest FastForward:                   I
> echo I                                                                              I
> echo I                       %LATEST_CHANGE_CHROMIUM%                        I
> echo I                       %LATEST_CHANGE_FIREFOX%                         I
> echo I                                                                              I
> echo --------------------------------------------------------------------------------
> 
> del %FILE_FIREFOX% %FILE_CHROMIUM% CHECK_*
> rmdir /s /q %FOLDER%
> 
> goto eof
> 
> :Downloaded
> 
> echo --------------------------------------------------------------------------------
> echo I                                                                              I
> echo I                      Downloaded the latest FastForward:                      I
> echo I                                                                              I
> echo I                       %CHECK_CHROMIUM%                        I
> echo I                       %CHECK_FIREFOX%                         I
> echo I                                                                              I
> echo --------------------------------------------------------------------------------
> 
> del %FILE_FIREFOX% %FILE_CHROMIUM%
> move /y CHECK_FIREFOX LATEST_CHANGE_FIREFOX
> move /y CHECK_CHROMIUM LATEST_CHANGE_CHROMIUM
> copy %FOLDER%\Firefox %FOLDER_NEW%
> copy %FOLDER%\Chromium %FOLDER_NEW%
> rmdir /s /q %FOLDER%
> 
> :eof
> 
> timeout 25
```

**Comment by ilike2burnthing** [comment]
Again, you should change the value of `FOLDER_NEW`, not `FOLDER`. In your example above you appear to have removed `FOLDER_NEW` completely.

If you want the files to be copied to the folder you're running the script from, just leave the value for `FOLDER_NEW` blank.

**Comment by Rusenche** [comment]
> Again, you should change the value of `FOLDER_NEW`, not `FOLDER`. In your example above you appear to have removed `FOLDER_NEW` completely.
> 
> If you want the files to be copied to the folder you're running the script from, just leave the value for `FOLDER_NEW` blank.

I followed your advice. Thanks.

I think your efforts on this bat file will be helpful to others reading this thread who have encountered the same problem.

**Comment by rollingmoai** [comment]
> If you want to stay on the bleeding edge then save [FastForwardTeam/FastForward](https://github.com/FastForwardTeam/FastForward) as a bookmark and check every couple of days for the current commit total.
> 
> Currently it is `2222` and therefore the version number of the extension is `v0.2222`. If the commit total is greater than your current version number, you can update.

A CRX file would be more convenient, it auto-updates itself and there would be no need for a complicated batch script. I used to use the CRX file from the releases until I noticed it had disappeared. Please consider bringing it back (for nightly).

**Comment by NotAProton** [comment]
Google removed the ability for update_url to be anything other than the Chrome Web Store link. Edge supports it but we are already on the Edge store so there's no point.
https://developer.chrome.com/docs/extensions/mv3/external_extensions/

**Comment by rollingmoai** [comment]
Since when? Other extensions still work for me, though:
https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v9.7.0.3/TWP.9.7.0.3.crx
https://github.com/libredirect/libredirect/releases/download/v2.5.4/libredirect-2.5.4.crx

**Comment by JunkiEDM** [comment]
Installing extensions via CRX is still possible in Chrome, Edge, Brave, and Vivaldi, but require registry edits to not be forcibly disabled. 
Some examples of extensions I've found that provide `*.reg` files with their CRX for automatic updates are [libredirect](https://libredirect.github.io/download_chromium.html), [Translate Web Pages](https://github.com/FilipePS/Traduzir-paginas-web/#chrome-edge-and-brave-with-crx-and-auto-update), and [TTV LOL PRO](https://github.com/younesaassila/ttv-lol-pro#with-automatic-updates-windows--linux). 
Other chromium browsers I'm not sure about, but from what I've read, it seems like no registry edits are needed, but the extensions might not auto-update. 
chromium-web-store also has some examples for auto-update support [on their repo](https://github.com/NeverDecaf/chromium-web-store#if-you-are-a-chrome-extension-developer). 
Google also provides some documentation about this, targeting enterprise use cases: [Windows](https://support.google.com/chrome/a/answer/7532015) | [Mac](https://support.google.com/chrome/a/answer/7517624) | [Linux](https://support.google.com/chrome/a/answer/7517525)

**Comment by AliahX** [comment]
Its back finally with the mv3 release!!!!

**Comment by ilike2burnthing** [comment]
Website's link is working fine, but GH readme needs updated.

**Comment by ilike2burnthing** [comment]
Forgot to ask earlier, no custom bypasses in MV3?

**Comment by AliahX** [comment]
> Forgot to ask earlier, no custom bypasses in MV3?

Nope, the webstores don't like that for some reason. Anyways not many people used the custom bypasses, and you can still just build your own version of the extension with custom bypasses.
