### ISSUE TITLE
Microsoft Edge marks chrome store version as malware

### ISSUE THREAD

**Issue by kittybwained** [FastForwardTeam/FastForward#705]
### Body

I just got a popup saying that Microsoft Edge has removed the fast forward extenstion due to malware. I had the chrome store version, i have now installed the microsoft edge store version and it works fine. Is this a false positive?

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by Hazmi35** [comment]
Related with #704

**Comment by SofiaRedmond** [comment]
You can download it from [Edge Extensions Store](https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl)

**Comment by kittybwained** [comment]
> You can download it from [Edge Extensions Store](https://microsoftedge.microsoft.com/addons/detail/fastforward/ldcclmkclhomnpcnccgbgleikchbnecl)

I already did, and the JS files seem to match the hashes of the ones from the source code, so thats safe.

**Comment by Droyk** [comment]
same here! Just got the pop up!
![image](https://user-images.githubusercontent.com/15848350/189667701-7a92b704-6fa1-408d-8c76-e8ef6611efc8.png)
![image](https://user-images.githubusercontent.com/15848350/189667738-c52d2a80-2630-42a3-9df8-eb704a25d967.png)

**Comment by kittybwained** [comment]
> same here! Just got the pop up! ![image](https://user-images.githubusercontent.com/15848350/189667701-7a92b704-6fa1-408d-8c76-e8ef6611efc8.png) ![image](https://user-images.githubusercontent.com/15848350/189667738-c52d2a80-2630-42a3-9df8-eb704a25d967.png)

yeah, just get the one from the edge store.

**Comment by q-temp** [comment]
@avriii @Droyk 
That is not the official FastForward extension.

It has a different ID, logo, and version number. Looks like you guys installed a copycat version.

**Comment by kittybwained** [comment]
> @avriii @Droyk That is not the official FastForward extension.
> 
> It has a different ID, logo, and version number. Looks like you guys installed a copycat version.

Are you saying the one in the microsoft edge store is a copycat? I just replied, that is not my screenshot, also it has actually been taken down, its on the discord server. And there are no other extensions by that name, so pretty sure its the official one.

**Comment by q-temp** [comment]
My FastForward extension on Edge has the ID "**ldcclmkclhomnpcnccgbgleikchbnecl**".

Works on my Edge browser and hasn't been disabled for me, neither in Edge nor the Add-on store.

![msedge_JB0OmCqaG1](https://user-images.githubusercontent.com/92174998/189693805-52c31201-ad43-4112-8113-748b7df86481.png)

**Comment by kittybwained** [comment]
> My FastForward extension on Edge has the ID "**ldcclmkclhomnpcnccgbgleikchbnecl**".
> 
> Works on my Edge browser and hasn't been disabled for me, neither in Edge nor the Add-on store.
> 
> ![msedge_JB0OmCqaG1](https://user-images.githubusercontent.com/92174998/189693805-52c31201-ad43-4112-8113-748b7df86481.png)

Yes, because we are talking about the Chrome version. Chrome extensions work in Edge, as a result of edge using Chromium. The edge version is still up, we are talking about the Chrome version being taken down.

**Comment by q-temp** [comment]
> we are talking about the Chrome version being taken down

Sorry for the misunderstanding.

I doubt it will come back to the Chrome Web Store since Google is cracking down on these type of extensions that interfere with their ad business.

**Comment by kittybwained** [comment]
> > we are talking about the Chrome version being taken down
> 
> Sorry for the misunderstanding.
> 
> I doubt it will come back to the Chrome Web Store since Google is cracking down on these type of extensions that interfere with their ad business.

Its okay. Even if it doesn't come back you can still manually install it

**Comment by lostdusty** [comment]
See this comment for more details: https://github.com/FastForwardTeam/FastForward/issues/704#issuecomment-1243433256
