### ISSUE TITLE
Registry key for Chrome policy is wrong, should be "ExtensionInstallAllowlist"

### ISSUE THREAD

**Issue by Brawl345** [FastForwardTeam/FastForward#706]
### Body

FYI: The registry "hack" for allowing the extension in Chrome does not work. It uses `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallWhitelist` but this was changed in Chrome 86 to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallAllowlist`. Using this, it works.

EDIT: Also be aware that this disabled Secure DNS...

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

See: https://chromeenterprise.google/policies/?policy=ExtensionInstallAllowlist

**Comment by undeadjess** [comment]
Thanks, fixed!
