### ISSUE TITLE
Cannot bypass teknoku.me

### ISSUE THREAD

**Issue by luhdewi** [FastForwardTeam/FastForward#709]
### Domain

https://teknoku.me/telegram-update-there-are-new-features-like-clubhouse/#

### Link

https://teknoku.me/telegram-update-there-are-new-features-like-clubhouse/#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### Anything else?

![Screenshot_2022-09-17-09-32-55-547_com kiwibrowser browser](https://user-images.githubusercontent.com/26851162/190835392-de1ab0a2-c4a5-4b9b-a718-7be1ea5ddb7c.jpg)
![Screenshot_2022-09-17-09-33-31-236_com kiwibrowser browser](https://user-images.githubusercontent.com/26851162/190835394-0eced2ca-a02b-44cb-9439-b55e04c7402d.jpg)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
