### ISSUE TITLE
rb.gy

### ISSUE THREAD

**Issue by toyboatcash** [FastForwardTeam/FastForward#71]
### Domain

rb.gy

### Link

https://rb.gy/u2gaox

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

part of https://free-url-shortener.rb.gy/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
i got transfered immediately?
