### ISSUE TITLE
exe.app bypass broken

### ISSUE THREAD

**Issue by INify** [FastForwardTeam/FastForward#710]
### Domain

exe.app

### Link

https://exe.app/JMrT8

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://user-images.githubusercontent.com/61307591/190864986-bde09217-7dfc-4bd6-a225-0c26b2d432ed.mp4

**Comment by antonio8909** [comment]
Hello,

I'm also affected by this issue. Is a fix coming anytime soon?

Thanks
