### ISSUE TITLE
can not bypass site

### ISSUE THREAD

**Issue by luhdewi** [FastForwardTeam/FastForward#713]
### Domain

https://lifesurance.info/benefits-of-azelaic-acid-for-acne-face/#

### Link

https://lifesurance.info/benefits-of-azelaic-acid-for-acne-face/#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by ghost** [comment]
Can you please provide a link where FastForward is meant to work?

**Comment by lostdusty** [comment]
Inactive, also closing this one.
