### ISSUE TITLE
Cannot Bypass

### ISSUE THREAD

**Issue by alpdmrel** [FastForwardTeam/FastForward#714]
### Domain

https://adbs.uab.gov.tr

### Link

https://adbs.uab.gov.tr

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

doesn't bypass

**Comment by abadawe-dev** [comment]
Please add an example link.

**Comment by lostdusty** [comment]
Inactive, closing this.
