### ISSUE TITLE
this extension might be the source of my "browser is managed" policy issue. 

### ISSUE THREAD

**Issue by hatter1888** [FastForwardTeam/FastForward#716]
### Body

alright i realized "browser is managed" on my chome settings page. after some research, and some walkthroughs suggesting possible solutions, i couldn't fix the issue and tried to figure out what exactly hijacked my browser. it lead me to my broswers policy settings. these two policies, ExtensionInstallWhitelist, and ExtensionInstallSources had this extensions id. ilcacnomdmddpohoakmgcboiehclpkmj listed, which is what lead me to reason this extentions is doing something it probably shouldn't be. deleting the policy via regedit solved the issue, but i wanted to make sure i spoke up cus if it was the problem, i dont think it was intentionally malicious. i could be completely wrong, and just misunderstood the information presented to me. or maybe i had the version listed on the store, and thats a reason it was taken down. either way, i'd like to hear more info, if im wrong i want to know what i got wrong, or if im right, how this addon decided to promote itself to manager lol 

ExtensionInstallWhitelist
ExtensionInstallSources

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by undeadjess** [comment]
we use the .reg file that you open when you install the extension to add it to the chrome extension whitelist, but that should make the browser say its managed. ill take a look so and get back to you maybe tmr

**Comment by ViperYS** [comment]
Could you fix the issue?

**Comment by lostdusty** [comment]
This behaviour is normal, due of the registry changes
