### ISSUE TITLE
Due to copyright reasons we are not bypassing linkvertise stored content (paste, download etc) :c

### ISSUE THREAD

**Issue by illegalsolutions** [FastForwardTeam/FastForward#717]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/156939/epicmod/1

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/47225461/191130486-35d8ac27-67f7-46d3-8829-91bc6a8f87ac.png)
Due to copyright reasons we are not bypassing linkvertise stored content (paste, download etc)

:c

**Comment by undeadjess** [comment]
as you can see from the message, Due to copyright reasons we are not bypassing linkvertise stored content.

**Comment by aidan-walden** [comment]
Try this custom bypass:

```
domainBypass("linkvertise.com", () => {
    fetch('https://api.bypass.vip/', {
        method: 'POST',
        body: new URLSearchParams({
            url: window.location.href //URL to be bypassed
        })
    })
    .then(response => {
        response.json()
        .then(json => [response, json])
            .then(data => {
                if (data[1]['success'] === true) {
                    window.location.replace(data[1]['destination'])
                } else {
                    alert("Bypassing failed: " + data[1]['response'] + "\nHTTP Status: " + data[0].status + " " + data[0].statusText + "\nOK: " + data[0].ok)
                }
        })
    })
})
```

**Comment by lostdusty** [comment]
We won't fix this, as the message says.
