### ISSUE TITLE
no longer working bypass

### ISSUE THREAD

**Issue by MzoxM** [FastForwardTeam/FastForward#721]
### Domain

Bluemediafiles.com

### Link

http://bluemediafiles.eu/url-generator.php?url=onAhF5ZLCDGjfP3AAUIv/b2DJLi0YBRL/g/VlBQbxQSPGnQBRxGG80khFImQU29iGYxdbHBqXwQHwhk5wnQhX1Qutn0n+JTYyO1e+3OrUiYx0MSVc0d/WSlMfS5IdA55

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/bf5bab09e8bdd92735fc73a9ab3f9254cf68d705.
