### ISSUE TITLE
Breaks dashdot / dash. selfhosted app

### ISSUE THREAD

**Issue by Linx-ESP** [FastForwardTeam/FastForward#724]
### Domain

https://getdashdot.com/

### Link

https://getdashdot.com/docs/install/docker-compose

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

In my case is a selfhosted private instance of dashdot, that show all white page and the next error in console:
`runtime.37bfc31cd171f5de.esm.js:1 
        
       Uncaught Error: Automatic publicPath is not supported in this browser
    at runtime.37bfc31cd171f5de.esm.js:1:2129
    at runtime.37bfc31cd171f5de.esm.js:1:2271
    at runtime.37bfc31cd171f5de.esm.js:1:3064`
Disabling the extension works

**Comment by undeadjess** [comment]
are you sure FastForward is causing this?

**Comment by Linx-ESP** [comment]
Pretty sure, I tested recently only with that extension and happened too.
With that said, might be a incompatibility between different things as Edge, my reverse proxy and more.
