### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Khotyz** [FastForwardTeam/FastForward#725]
### Body

is it possible to add whitelist in bypass? because there are some links that I open like bit.ly and some others that instead of jumping it closes the tab in firefox

https://user-images.githubusercontent.com/74627161/191888527-d3052df6-e894-4c48-8df3-ad5270e03678.mp4

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

https://user-images.githubusercontent.com/74627161/191888688-8dd85b7d-dd00-4c31-968e-92f13213abb3.mp4

![firefox_q9jRwpn95b](https://user-images.githubusercontent.com/74627161/191888790-77f78105-f155-47f7-a5a2-bd1be98d5586.gif)

**Comment by lostdusty** [comment]
See #656
