### ISSUE TITLE
fc-lc seems not be bypassed anymore

### ISSUE THREAD

**Issue by Darkmaster006** [FastForwardTeam/FastForward#730]
### Domain

https://fc-lc.com/

### Link

https://fc-lc.com/penl2aVI

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

I've done it already in here https://fc-lc.com/penl2aVI and I tried it again to see if it bypassed itself but it didn't, so it must not be working.
Thank you, hope this can be fixed!

**Comment by wernser412** [comment]
link: https://fc-lc.com/7kGqrX
Bug.
![Video_2022-10-12_162634](https://user-images.githubusercontent.com/53667212/195459670-9dd07f88-2cf3-4647-9de6-e13273ba1590.gif)

**Comment by ghost** [comment]
Site brought me to the final destination after waiting for 5 seconds. If you get stuck on the next.php page, I suggest copying the link and trying it again, making sure not to click anything on the page.
