### ISSUE TITLE
Sub2Unlock not working

### ISSUE THREAD

**Issue by Xeimyn** [FastForwardTeam/FastForward#731]
### Domain

https://sub2unlock.com

### Link

https://sub2unlock.com/5aa1438d84b19

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I wanna mention that the Site i linked is the example linked in the FAQ.

**Comment by lostdusty** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/bf5bab09e8bdd92735fc73a9ab3f9254cf68d705.
