### ISSUE TITLE
A request to add support to bypass  https://themoviesverse.co/

### ISSUE THREAD

**Issue by Baggabilla** [FastForwardTeam/FastForward#732]
### Domain

https://themoviesverse.co/

### Link

https://themoviesverse.co/download-the-sea-beast-2022-hindi-english-480p-720p-1080p/

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### Anything else?

Dear Sir,
A request to add support to bypass https://themoviesverse.co/ and https://bollyverse.site/

**Comment by lostdusty** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/bf5bab09e8bdd92735fc73a9ab3f9254cf68d705.
