### ISSUE TITLE
Broken final link when clicking on a Twitter link "t.co"

### ISSUE THREAD

**Issue by Olfdev** [FastForwardTeam/FastForward#733]
### Domain

t.co

### Link

https://t.co/1v2xnVfF8d?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Escreen-name%3Abeepboxco%7Ctwcon%5Es1_c14

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Hello,

There is an issue when FastForward is ON with t.co links.
As an example, you can click on some beepbox.co links in the embedded twitter window and the link created is "doubled" leading in a non working link.

Here is a diff between without (left) and with (right) FastForward.
![hbdLO9](https://user-images.githubusercontent.com/80658604/193278863-099a0406-b593-4847-8ad0-a9794e4329d0.jpg)

Repro:
1. Activate FastForward
2. Go to beepbox.co
3. Click on a beepbox link in the embedded twitter window that uses t.co
4. Observe the black window
5. Disable FastForward
6. Click again on the link
7. Observe the working window
8. Do the diff between both links
9. Observe the "doubled" link when FastForward is ON

**Comment by lostdusty** [comment]
See #784.

**Comment by Murazaki** [comment]
Not sure I get how this works, but t.co `<a>` tags actually contains the complete link, separated by useless span tags. Why not try something like this ?

```js
hrefBypass("t.co", () => {
	ifElement("a", a => {
	    const realLink = a.innerHTML.replace(/<.*?>/, '');
		safelyNavigate(realLink)
	}, () => {
	})
})
```
