### ISSUE TITLE
megadb.net skipped countdown

### ISSUE THREAD

**Issue by Yurie13** [FastForwardTeam/FastForward#734]
### Domain

https://megadb.net/

### Link

https://megadb.net/download

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

megadb knows you have a timer skipper
the page will keep reloading with text of "Skipped countdown"
turning off the add-on "fixes" the problem

**Comment by ghost** [comment]
Duplicate of #610.
