### ISSUE TITLE
Lona2Host and (ShrinkMe.io) Worked at one point but no longer do

### ISSUE THREAD

**Issue by iSupakilla** [FastForwardTeam/FastForward#735]
### Domain

https://shrinke.me/

### Link

https://shrinke.me/L4LcHcW

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

These bypassed at one point but now they don't skip me forward anymore and the adding your own doesn't have outright make enough sense to me to try and make one myself

**Comment by ghost** [comment]
Duplicate of #678.
