### ISSUE TITLE
dropgalaxy.com not bypassing

### ISSUE THREAD

**Issue by rakitanc** [FastForwardTeam/FastForward#736]
### Body

https://dropgalaxy.com

Please fix it

### Version

0.2025 

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Linux

**Comment by abadawe-dev** [comment]
Nothing to bypass here, can you provide another example link please?

**Comment by lostdusty** [comment]
Looks like just another clone of uploadrar.com family.

**Comment by lostdusty** [comment]
> Nothing to bypass here, can you provide another example link please?

https://dgdrive.xyz/gjyk8kcrd1wj

**Comment by adsdestroyer** [comment]
dropgalaxy file sharing site cannot be bypassed i have tried everything.

**Comment by ghost** [comment]
While this is a new bypass, it shares the same bypass as another site, so it'll stay open.

**Comment by blazesprings** [comment]
@adsdestroyer Could you please bypass this timer? It's not server side. It's user side.
![image](https://github.com/FastForwardTeam/FastForward/assets/80951522/21d7a581-7126-4c35-b459-2a3265505c76)

**Comment by Asrum** [comment]
> @adsdestroyer Could you please bypass this timer? It's not server side. It's user side. ![image](https://user-images.githubusercontent.com/80951522/257055243-21d7a581-7126-4c35-b459-2a3265505c76.png)

Thank, for loginning!
