### ISSUE TITLE
Fast forward extension did not work on this indonesian websites

### ISSUE THREAD

**Issue by dedman23444** [FastForwardTeam/FastForward#738]
### Domain

https://game.downloadtanku.org/

### Link

https://moddroid.id/pk-xd-apk-download/

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

This is an indonesian website for downloading 3rd party games or software

**Comment by abadawe-dev** [comment]
Honestly, I would highly recommend you check [this.](https://rentry.org/pgames-mega-thread)

**Comment by lostdusty** [comment]
FastForward does not encourage cheating in games online, therefore, this issue will be closed.
