### ISSUE TITLE
Not working on FileCrypt

### ISSUE THREAD

**Issue by levilawliet7** [FastForwardTeam/FastForward#740]
### Domain

https://filecrypt.cc/

### Link

https://filecrypt.cc/Container/C8DE506D23.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

If site ask for password type "744". Site asking for finding the open circle.

**Comment by abadawe-dev** [comment]
I don't think this is what FastForward is for, maybe try using a download manager like [pyload](https://github.com/pyload/pyload) or [JDownloader](https://jdownloader.org/).

**Comment by levilawliet7** [comment]
So it's not possible to bypass first part. I will close this issue then.
