### ISSUE TITLE
Not working on this site

### ISSUE THREAD

**Issue by levilawliet7** [FastForwardTeam/FastForward#741]
### Domain

https://linkspy.cc

### Link

https://linkspy.cc/tr/aHR0cHM6Ly9hZHBheWxpbmsuY29tL2Z1bGw/YXBpPTMwMmYzMWRmOTdiMDQ2MWRkMjhkODcxZjlmZTVjODA3YTQzNTViNmMmdXJsPWFIUjBjSE02THk5bWFXeGxZM0o1Y0hRdVkyTXZRMjl1ZEdGcGJtVnlMMEk0TmtGRlJEVkROVUl1YUhSdGJBPT0mdHlwZT0y

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by abadawe-dev** [comment]
Fixed in https://github.com/FastForwardTeam/FastForward/commit/6b4d060d21f7a4580a46dd2fed246082bc1814f3, please colse.
