### ISSUE TITLE
FastForward

### ISSUE THREAD

**Issue by Dieguis1985** [FastForwardTeam/FastForward#743]
### Body

No funciona. Chrome pone problema. Ustedes son unos cabrones al comprar universal bypass.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
First, describe your issue before complaning, what is not working?
Also, we didn't bought Universal Bypass, it was abondoned by Sainan, so we continued it.
