### ISSUE TITLE
manifest file is missing or unreadable could not load manifest

### ISSUE THREAD

**Issue by LunaXRedo** [FastForwardTeam/FastForward#744]
### Body

ok so i enter developer mode and try to select the file and when i press select it says manifest file is missing or unreadable could not load manifest

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![manifest file is missing or unreadable could not load manifest](https://user-images.githubusercontent.com/115378990/194731159-6aeec320-5d95-402a-b10b-ac88403e2b5d.png)

**Comment by dckrell** [comment]
i am having this problem as well, hope the devs fix it i guess

**Comment by lostdusty** [comment]
https://github.com/FastForwardTeam/FastForward/issues/745#issuecomment-1273965402
