### ISSUE TITLE
crx header invalid on chrome dev

### ISSUE THREAD

**Issue by 3xploitzer0** [FastForwardTeam/FastForward#745]
### Body

![image](https://user-images.githubusercontent.com/56762704/194741803-d8711b9b-694e-4aed-8ca0-9a7d7c31c75e.png)

crx header invalid

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by zakiyys** [comment]
Try to open the .crx file with WinRar first, 
after that you can see the files inside that crx,
extract the files into new folder then click the "Load Unpacked" and choose the folder where you extract the files.

**Comment by lostdusty** [comment]
The comment says what you need to do. Also its explained on the install instructions

**Comment by 3xploitzer0** [comment]
> Try to open the .crx file with WinRar first, after that you can see the files inside that crx, extract the files into new folder then click the "Load Unpacked" and choose the folder where you extract the files.

![Program_Manager_18-10-2022-(-)](https://user-images.githubusercontent.com/56762704/196417135-bfa8967e-6850-47cb-9999-7c2b2995b7f5.gif)

doesn't work

**Comment by zakiyys** [comment]
You need to extract that .crx file first bro. (Use WinRar or WinZip)

**Comment by zakiyys** [comment]
![Install FF](https://user-images.githubusercontent.com/77758375/196421250-1b894f27-446f-4ecc-b9af-f4664d37b78d.gif)
Here how to do it.

**Comment by zakiyys** [comment]
> > Try to open the .crx file with WinRar first, after that you can see the files inside that crx, extract the files into new folder then click the "Load Unpacked" and choose the folder where you extract the files.
> 
> ![Program_Manager_18-10-2022-(-)](https://user-images.githubusercontent.com/56762704/196417135-bfa8967e-6850-47cb-9999-7c2b2995b7f5.gif)
> 
> doesn't work



![Install FF](https://user-images.githubusercontent.com/77758375/196421502-47a7e7b9-214f-4c4a-87a3-85ed2f56c899.gif)
Here how to do it.

**Comment by 3xploitzer0** [comment]
i see, nice, it work bro,

thank you

little error

![image](https://user-images.githubusercontent.com/56762704/196431671-6e35d2dd-fa0f-4e8a-995b-3716e32d5faf.png)

**Comment by zakiyys** [comment]
I also got that types of error, Someone in discord said to ignore that one 
![image](https://user-images.githubusercontent.com/77758375/196441485-92583f2a-7571-4bf4-b009-681157534c5d.png)
