### ISSUE TITLE
All bypasses no longer working

### ISSUE THREAD

**Issue by Ultimatron** [FastForwardTeam/FastForward#752]
### Domain

ouo.io

### Link

https://ouo.io/cqHVFY

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

MacOS

### Anything else?

Was working yesterday, but my laptop updated to Montery overnight. May have something to do with the issue.

**Comment by abadawe-dev** [comment]
Working here, maybe try reinstalling and updating the bypass definitions?

**Comment by Ultimatron** [comment]
Will do.

**Comment by Ultimatron** [comment]
Never mind, it's working now. I was using the "load-unpacked" version, which seemed to stop working after a reboot. The crx whitelist version fixed the issue. Closing.
