### ISSUE TITLE
not by passing ad.fly

### ISSUE THREAD

**Issue by nammminn2** [FastForwardTeam/FastForward#756]
### Domain

adly

### Link

http://neexulro.net/ad/locked?rweasy=1&user_id=63984&_adflyurl_=https%3A%2Fgoplay.ml%2Fdownloadcode%2F&folder_id=&dl=ZzHNdsdSO%2F0IYRUxcXlwOlJh4wxxZBMr6wrPIziEcyvaoGWlX6iyVEb5FUYkPX7GkQ8E9fpBPD4pUrdj4N17XtKUMgkylDKO8hrUkfpKsno%3D&rndad=1626999353-1666768687&url=https%3A%2F%2Fgoplay.ml%2Fdownloadcode%2F%3Fdl%3DZzHNdsdSO%2F0IYRUxcXlwOlJh4wxxZBMr6wrPIziEcyvaoGWlX6iyVEb5FUYkPX7GkQ8E9fpBPD4pUrdj4N17XtKUMgkylDKO8hrUkfpKsno%3D&t=e&subid=63984&h=1

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

MacOS

### Anything else?

not skipping

**Comment by lostdusty** [comment]
You probably have a broken link, has it returned 404.
