### ISSUE TITLE
itscybertech.com

### ISSUE THREAD

**Issue by HarshRaj-I** [FastForwardTeam/FastForward#76]
### Domain

itscybertech.com

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### (Optional) Anything else?

for example:
https://tinyurl.com/yk3yh6jg
https://tinyurl.com/yh7d6w43
https://tinyurl.com/ygt32pta
https://tinyurl.com/yzj58uv3

(by clicking on these links it is redirected to itscybertech.com)

**Comment by lostdusty** [comment]
Already bypassed.
