### ISSUE TITLE
Unable to install in chrome

### ISSUE THREAD

**Issue by pruebark9** [FastForwardTeam/FastForward#760]
### Body

I was using this extension without problems since 1 year ago I think and now my Chrome restarted and I lost several extensions that were not synchronized. Now when I try to install it again it always gives me an error.

If I drag the .crx file it says "crx_header_invalid".
If I drag the zip or the unzipped folder it tells me "
The manifest file is missing or cannot be read".
Could not load manifest file."

I have even installed the .reg that it says to update automatically and nothing, there is no way to reinstall it and it was one of my favorite extensions.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Please follow https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md for the correct install instructions

**Comment by pruebark9** [comment]
That is what I do and nothing, when I load the folder I get the error "The manifest file is missing or cannot be read.
The manifest file could not be loaded."

**Comment by pruebark9** [comment]
> Please follow https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md for the correct install instructions


That is what I do and nothing, when I load the folder I get the error "The manifest file is missing or cannot be read.
The manifest file could not be loaded."

**Comment by pruebark9** [comment]
I have been able to fix it. You have to use 7zip to do step 4.
