### ISSUE TITLE
sh.st bypass doesnt work

### ISSUE THREAD

**Issue by iwongiwongwongiwong** [FastForwardTeam/FastForward#761]
### Domain

https://google.com

### Link

https://google.com

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

im just try the example link that available in fast forward page and the sh.st seems doesn't work and i can't even skip the ad
![image](https://user-images.githubusercontent.com/113374991/198881261-f4c80005-c17b-47e2-80d4-12bb31d5c7d0.png)

**Comment by lostdusty** [comment]
Duplicate of #663.
