### ISSUE TITLE
cutin.it

### ISSUE THREAD

**Issue by kodiakhub** [FastForwardTeam/FastForward#764]
### Domain

cutin.it

### Link

https://cutin.it/anRa?sport=soccer

### Version

0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by stanleylhs** [comment]
Domain
cutin.it

Link
https://cutin.it/anRa?sport=soccer

Version
0.2039

What browsers are you seeing the problem on?
Firefox

What OS are you seeing the problem on?
MacOS

**Comment by Write** [comment]
They obfuscated their js lol.

For now they simply rely on window.count being set to -1 to fill the href in the button.

Quite ugly but for personal use, I made an userscript just for me.

```
        const checkElement = async selector => {
            while (document.querySelector(selector) === null) {
                await new Promise(resolve => requestAnimationFrame(resolve));
            }
            return document.querySelector(selector);
        };

      
        checkElement('a[class*="btn"][class*=sadsad]:not([href^=\\#])').then((selector) => {
            var url = selector.href;
            console.log("LINK FOUND : " + url);
            location.assign(url);
        });

        setTimeout(function () {
            console.log("resetting count")
            window.count = -1;
        }, 100)
```

Not sure when window.count is set or anything and i'm way to lazy to find more so I just set window.count to -1 every 100ms.

You guys can try my userscript if you'd like for soccer's streaming site : https://github.com/Write/AutoPlaySoccerStreams
I'm not heavily maintaining it though.

**Comment by Write** [comment]
The JS is encoded with this method : https://scriptasylum.com/tutorials/encode-decode.html

Pretty trivial to decode. 

```
var rawHTML;
window.dF = function(s) {
    var s1=unescape(s.substr(0,s.length-1));
    var t='';
    for(i=0;i<s1.length;i++)t+=String.fromCharCode(s1.charCodeAt(i)-s.substr(s.length-1,1));
    var unescappedHTML = unescape(t);
    rawHTML = unescappedHTML;
    return unescappedHTML;
}
```

and call the original dF('longstring') from the original site by copy / pasting it.

Not sure how to do get the raw string from dF programmatically.

JS Obtained from the code link above is then : 

![Screenshot du 2022-11-02 à 00 31 02](https://user-images.githubusercontent.com/541722/199361324-33e4e043-b52f-4645-ac03-d2f79b8c689e.png)

Countdown that contains our url.


EDIT : 

Here's how to decode the JS and get original JS src : 

```js
        var rawHTML;
        function decode(s) {
            var s1=unescape(s.substr(0,s.length-1));
            var t='';
            for(i=0;i<s1.length;i++)t+=String.fromCharCode(s1.charCodeAt(i)-s.substr(s.length-1,1));
            var unescappedHTML = unescape(t);
            rawHTML = unescappedHTML;
            return unescappedHTML;
        }
		var scripts = document.querySelectorAll('script');

        scripts.forEach(function (e) {
            var regex = /dF\('(.*)'\)/

            if (e.innerText.match(regex)) {
				var encodedJS = e.innerText.match(regex)[1]
                console.log(decode(encodedJS))
            }			
        });
```

Just copy and paste in the console and it should work.

**Comment by Write** [comment]
Full Working POOC Userscript using MutationObserver's API : 

https://gist.github.com/Write/d76f028279d9777873f051f8c9f04e1d

Tested and working on Firefox / Chrome.

**Comment by lostdusty** [comment]
Done in #766.
