### ISSUE TITLE
blogspot with snacklink cant bypassed

### ISSUE THREAD

**Issue by ikhoeyZX** [FastForwardTeam/FastForward#767]
### Domain

https://teknosimple.com/

### Link

https://teknosimple.com/jl5sYTj

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### Anything else?

Stuck at "please wait...10"

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
