### ISSUE TITLE
carapedi.id not bypassing or not added

### ISSUE THREAD

**Issue by Ezekiel-Game** [FastForwardTeam/FastForward#774]
### Domain

https://carapedi.id

### Link

https://carapedi.id/selalu-aman-inilah-5-antivirus-terbaik-untuk-android

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

version 0.08 and browseris opera gx.

**Comment by abadawe-dev** [comment]
Where did you get this link from?

**Comment by Ezekiel-Game** [comment]
i was gonna download but it send me here and i had to download button but it was ridden with ads and i needed to get something to redirect me here i thought i t was gonna go ez peacy bc fast forward has a great bypass database but it didnt work sooo yeah.

**Comment by abadawe-dev** [comment]
What website were you trying to download from?

**Comment by Ezekiel-Game** [comment]
carapedi.id

**Comment by abadawe-dev** [comment]
You don't understand me, this website is just articles, what website forwarded you to carapedi.id?

**Comment by ghost** [comment]
We do not currently bypass carapedi.id based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
