### ISSUE TITLE
Megaurl not Bypassing!!

### ISSUE THREAD

**Issue by NVT223** [FastForwardTeam/FastForward#778]
### Domain

http://megaurl.in/A2QU

### Link

https://app.trangchu.news/how-to-become-a-professional-ethical-hacker.html#A2QU

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
We do not currently bypass megaurl.in based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
