### ISSUE TITLE
Registry hack for Windows - using id #1 may break other allowed installations

### ISSUE THREAD

**Issue by a10kiloham** [FastForwardTeam/FastForward#779]
### Body

In the reg file, I'd recommend adding bypasses for HKCU and using the number 9 or something instead of 1. If there are other extensions installed they may be overwritten by using the same id number (like Anti-Captcha for example). 

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Please install the unpacked version.
