### ISSUE TITLE
Work.ink not bypassing

### ISSUE THREAD

**Issue by SparkEden** [FastForwardTeam/FastForward#781]
### Domain

https://work.ink

### Link

https://work.ink/14c/FurkUltraDownload

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
See #488.

**Comment by MindMurderer** [comment]
got the same issue

**Comment by swinowz** [comment]
pretty sure you can't bypass it bec they keep the final link in their own servers or smthg

**Comment by cupidkev10** [comment]
its either an extension you have, or the built in chrome ad block, you can disable it by looking it up
