### ISSUE TITLE
Nexus Mods no longer bypassing

### ISSUE THREAD

**Issue by XarisZ** [FastForwardTeam/FastForward#783]
### Domain

https://www.nexusmods.com/

### Link

https://www.nexusmods.com/skyrimspecialedition/mods/77779?tab=files&file_id=331352&nmm=1

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Doesnt work on Chrome either.

**Comment by Daemonrat** [comment]
still an issue

**Comment by BitGrub** [comment]
Still an issue, actually got worse now

**Comment by BitGrub** [comment]
unstale
