### ISSUE TITLE
Trackers bypasses not working

### ISSUE THREAD

**Issue by thiaguinho4** [FastForwardTeam/FastForward#784]
### Domain

https://bit.ly

### Link

https://bit.ly/3tpucsF

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

when I enter a bit.ly link, FastForward doesn't bypass it. (continues with "bypassed 11 sites for you")

![a](https://user-images.githubusercontent.com/101910294/201705854-1554c0a3-85ec-42fa-bfb8-1a1d6bba29e7.png)

**Comment by purple512** [comment]
The apimon.de API that was used for that has been taken offline. This probably affects lots of sites.

![image](https://user-images.githubusercontent.com/79816784/201729185-32a7c233-c5b4-4f6c-9eb7-d574b94c19f2.png)

**Comment by lostdusty** [comment]
I'm still redirected to youtube... But yes, the API has been discontinued, this is currently out of our hands.

If anyone knows a similar api that we could use, replacing apimon.de

**Comment by 1fexd** [comment]
Maybe unshorten.me could be used? https://unshorten.me/api

**Comment by GITHUBTRASHACCOUNT** [comment]
https://bypass.vip/

**Comment by NotAProton** [comment]
> Maybe unshorten.me could be used? https://unshorten.me/api

Doesn't seem to resolve new URLs anymore

**Comment by 1fexd** [comment]
> > Maybe unshorten.me could be used? https://unshorten.me/api
> 
> Doesn't seem to resolve new URLs anymore

What do you mean? It works fine for me?

**Comment by NotAProton** [comment]
try https://t.co/BJCe4w8BPR which is a new one and isn't stored in their database
![image](https://github.com/FastForwardTeam/FastForward/assets/81463636/de873c97-4945-430b-8af6-0328ef48b660)

**Comment by ghost** [comment]
> try https://t.co/BJCe4w8BPR which is a new one and isn't stored in their database ![image](https://user-images.githubusercontent.com/81463636/251962381-de873c97-4945-430b-8af6-0328ef48b660.png)

It works with other websites, twitter links probably don't work because of Musk's dumbass view restrictions.
My personal website with a bit.ly link:
![image](https://github.com/FastForwardTeam/FastForward/assets/45770865/a791aa1c-1acc-4033-a9e1-a15f98700fb6)

**Comment by 1fexd** [comment]
> > try https://t.co/BJCe4w8BPR which is a new one and isn't stored in their database ![image](https://user-images.githubusercontent.com/81463636/251962381-de873c97-4945-430b-8af6-0328ef48b660.png)

You know what the funniest thing about twitter short urls is? Their internal API which the website uses serves them, as well as the unshortened url itself

**Comment by NotAProton** [comment]
So we drop support for t.co and use unshorten.me ?

**Comment by NotAProton** [comment]
Does anyone know where I can get a full list of domains bypassed by unshorten.me?

edit: mailed them, no reply. Just checked all the ones that apimon used to bypass https://github.com/FastForwardTeam/FastForward/pull/983/commits/453e6baf31c456a11a259be5bd894aae6d84c6ae

**Comment by lostdusty** [comment]
Unpinning since this is done.

**Comment by NotAProton** [comment]
Unshorten.me now requires users to login for api requests

**Comment by NotAProton** [comment]
Merging with #1297
