### ISSUE TITLE
sharemods.com infinite loop again

### ISSUE THREAD

**Issue by RoonMoonlight** [FastForwardTeam/FastForward#789]
### Domain

https://sharemods.com

### Link

https://sharemods.com/lplzm001rt1a/early_autumn_ats_v3_1.scs.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Red 'Skipped countdown' text now appears when FastForward tries to bypass the site... Guess they added mitigation against the bypass extensions like FastForward. This needs to be addressed fast if possible

**Comment by thiaguinho4** [comment]
![i](https://user-images.githubusercontent.com/101910294/203857579-68ffea30-00a4-4612-abb8-bbea64eefb0c.png)

**Comment by boat666** [comment]
![image](https://user-images.githubusercontent.com/72342344/204093714-74b7034d-d682-4040-83a5-3cb0e85f47e8.png)
