### ISSUE TITLE
https://adshort.live

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#79]
### Domain

https://adshort.live

### Link

https://adshort.live/dN3dD

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
this redirects me immediately to go.techgeek.digital, is that the one that needs to be bypassed?, please update the issue if thats the case
