### ISSUE TITLE
13.15.2

### ISSUE THREAD

**Issue by K4T4STR0S8392** [FastForwardTeam/FastForward#792]
### Domain

https://fc-lc.com/TmkQL7

### Link

https://mega.nz/folder/cF0AHLaZ#GMsrNLzd8lZuo7vmT9EYOA

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://fc-lc.com/TmkQL7
pwd: GMsrNLzd8lZuo7vmT9EYOA

**Comment by ghost** [comment]
Duplicate of #730.
