### ISSUE TITLE
ufacw.com not bypassing 

### ISSUE THREAD

**Issue by titosalah** [FastForwardTeam/FastForward#794]
### Domain

https://ufacw.com/

### Link

https://exee.app/CKr4R

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Hi bro 
ufacw.com not bypassing successfully
i must disable fastforward extension and press continue on ufacw.com page to redirect to next step page on  exee.app/CKr4R
if not disable fastforward extension bypassing keep loading first page exee.app/CKr4R

thanxx

**Comment by rwdsji** [comment]
I second this

**Comment by ghost** [comment]
Duplicate of #710
