### ISSUE TITLE
I can't delate the folder of the installation

### ISSUE THREAD

**Issue by TonyTrapper** [FastForwardTeam/FastForward#795]
### Body

When i deleted the folder , i lost the extension on chrome

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

thanks for your attention

**Comment by ghost** [comment]
This is a normal side effect, unlike extensions that are installed straight from the store, sideloaded extensions require the core files to always be intact (meaning you can't delete the folder).

I recommend downloading the extension again and saving it in a place where you don't need to delete it, then load the unpacked extension through the extensions page.
