### ISSUE TITLE
won.pe not a shortener anymore - it's listed on example-links page 

### ISSUE THREAD

**Issue by shepherdlewis000** [FastForwardTeam/FastForward#797]
### Domain

https://won.pe

### Link

https://won.pe/k1Xwj

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

At your convenience I'd think.... I was trying some of the example links give here:
https://fastforward.team/example-links

There's the below link is listed. I'm thinking that won.pe is not a link shortening service any more. Just a parked domain I think.
https://won.pe/k1Xwj

**Comment by lostdusty** [comment]
Will be fixed soon.
