### ISSUE TITLE
Stfly Bypass Broken

### ISSUE THREAD

**Issue by Linden10** [FastForwardTeam/FastForward#799]
### Domain

https://stfly.me/

### Link

https://stfly.me/4SwkZ

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

I'm using Opera v93.0.4585.21 (Chrome in a sense).

Using the latest version of FastForward (Version 0.2161.0), Bypass Definitions 42216c1, I'm no longer able to skip and bypass stfly links as I used to.

Instead getting these errors in console:
`[FastForward] Couldn't define blurred
ODP @ VM35:32`

and

`Uncaught TypeError: Cannot read properties of null (reading 'submit')
    at FastForwardBypassDefinition.execution (<anonymous>:2028:41)
    at domainBypass (<anonymous>:158:27)
    at <anonymous>:2027:2`

Please help and thank you!

**Comment by Pizzy23** [comment]
Same problem

**Comment by gudarks** [comment]
+1

**Comment by Tenome** [comment]
Seems to be broken for me as well, doesn't ask if I want to skip or offer to let others skip next time.

**Comment by kevin01523** [comment]
yeah this is still broken

**Comment by kevin01523** [comment]
i guess some devs are busy with the main  extention instead of bypasses i dont see any bypasses working for the ones i encounter
