### ISSUE TITLE
https://short.toptap.website

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#80]
### Domain

https://short.toptap.website

### Link

https://short.toptap.website/NaWAjCi0

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
uses cloudflare captcha.... annoying might look into later
