### ISSUE TITLE
Bypass not working on soccerstreams

### ISSUE THREAD

**Issue by joebligblog** [FastForwardTeam/FastForward#800]
### Domain

https://worldcup.soccerstreams.net/

### Link

https://tinyurl.so/rZTj?sport=soccer

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

**Comment by Write** [comment]
Not sure about why it doesn't work.
Right now I just called window.location two times to fix it (??).
https://github.com/Write/AutoPlaySoccerStreams/blob/main/Autoplay.user.js#L227

While waiting, You can always use my userscript if you want.

**Comment by lem6ns** [comment]
soccerstreams goes to seized message and tinyurl.is/.co is dead from what I've seen
closed
