### ISSUE TITLE
Downloaded from Firefox Add-ons Store and it's in development mode, not functioning

### ISSUE THREAD

**Issue by ChishaWolf** [FastForwardTeam/FastForward#802]
### Body

Downloaded fresh from Add-ons Store and it says it's in development mode. I reinstalled it and it's still the same.
![firefox_LFkdtQs5CB](https://user-images.githubusercontent.com/78742042/204211944-9c14b29d-54ac-4efe-b05a-5be13c08ead4.png)
Fastfoward function is not working.
![firefox_n78gW7oagC](https://user-images.githubusercontent.com/78742042/204212186-ecbb938f-a5e2-4fce-882a-bc26fbfe2830.png)
No such file as `injection_script.js` and `rules.json` is found on my local drive.
![Everything_lUcP11EIaD](https://user-images.githubusercontent.com/78742042/204212688-ef6bc62a-ef50-4250-8677-ee63963071fe.png)
![Everything_gXIMH37NPK](https://user-images.githubusercontent.com/78742042/204212694-ff548993-9740-4da5-8112-4868da49df34.png)
![firefox_gam0e2qoog](https://user-images.githubusercontent.com/78742042/204213275-23c360f9-32f4-4eb1-90f1-80ce9e676e73.png)

Version: 0.1992 Firefox version: 107.0

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

**Comment by lostdusty** [comment]
Could you try manually installing it?

**Comment by ChishaWolf** [comment]
> Could you try manually installing it?

I tried to install it from Firefox Add-ons Store just now and it functions normally. Maybe an update fixed it. Case solved? It's an amazing addon btw

**Comment by lostdusty** [comment]
Nice to hear it's fixed for you now!
