### ISSUE TITLE
https://tny.so

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#81]
### Domain

https://tny.so

### Link

https://tny.so/NNj9W

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
stupid website that opens up sites on click anywhere.... even downloaded an sketchy .iso file....
