### ISSUE TITLE
Azmath not bypassed anymore!!

### ISSUE THREAD

**Issue by NVT223** [FastForwardTeam/FastForward#813]
### Domain

https://hamieu1.online/34f2f497-6c76-49cd-bcd7-f12da750f8af

### Link

https://azmath.info/kaspersky-virus-protection-review-superior-computer-security-program-with-user-friendly-interface.html

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot (19)](https://user-images.githubusercontent.com/114287428/205534274-b3b52d35-ba64-42f6-9948-453f5b44f850.png)

**Comment by ghost** [comment]
We do not currently bypass both sites listed based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
