### ISSUE TITLE
unable download Bypass definitions

### ISSUE THREAD

**Issue by Bug-Cache** [FastForwardTeam/FastForward#814]
### Body

![image](https://user-images.githubusercontent.com/98657967/205679141-0be80e4e-326e-4008-869f-e975bc4b6c6e.png)

Chrome Dev Latest Version

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
This is a known issue, see [this guide](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md). We plan on fixing it soon, but unfortunately no ETA on that.
