### ISSUE TITLE
Pahe.li (intercelestial.com)

### ISSUE THREAD

**Issue by azripon** [FastForwardTeam/FastForward#816]
### Domain

https://intercelestial.com

### Link

https://pahe.li/scrooge-a-christmas-carol-2022-web-dl-480p-720p/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by SamadXYZ** [comment]
same problem faceing in latest ver

**Comment by wiknew1** [comment]
Yup. Not working on anything related to Pahe.

**Comment by ghost** [comment]
We have a bypass for this site but it's based on a outdated domain. We'll make sure to fix this bypass soon.

**Comment by arifyilmaz-hb** [comment]
I guess they updated the version and FastForward doesn't function.

**Comment by OmiChrome** [comment]
anyone please fix it
