### ISSUE TITLE
Pop-up that i need to solve captcha when there is no captcha

### ISSUE THREAD

**Issue by Superwheat** [FastForwardTeam/FastForward#817]
### Body

Happens on linkvertise.com, there is no captcha and yet it still says i need to solve one, the pop-up text upon opening any url is: "FastForward requires you to complete the captcha before we can bypass this site for you. after you do this, we can skip the annoying steps!"

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Chrome version: 108.0.5359.73

**Comment by lostdusty** [comment]
There _is_ a captcha, you need to first click on "Free access with ads" or just "Free access".
