### ISSUE TITLE
https://blogginglass.com

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#82]
### Domain

https://blogginglass.com

### Link

https://blogginglass.com/?getlink=NeWMM6I

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Fixed, thanks for the report
