### ISSUE TITLE
Techtnet not bypassed error!!

### ISSUE THREAD

**Issue by NVT223** [FastForwardTeam/FastForward#820]
### Domain

https://linkneverdie.net

### Link

https://techtnet.com/news/laptops/how-techtnet-reviews-checks-tests-and-rankings-laptops-and-desktops-71

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
We do not currently bypass techtnet.com based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
