### ISSUE TITLE
IGG-games.com, interstitial page between IGG and the file lockers no longer skips the count or auto-forwards

### ISSUE THREAD

**Issue by boomercore** [FastForwardTeam/FastForward#827]
### Domain

igg-games.com

### Link

https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+KS3sMYpKpWVXA9+Fii3bg+vdisBs7aMOXpDfv76036+Vx5uro/skk7BYpXISgOo3A==

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

As per the ticket subject, any link to megaup, mega.nz, google drive, etc for any of the games now has the 6-count with the FFXV picture and doesn't bypass like it used to.  Thanks in advance.

**Comment by creeperita09** [comment]
don't use igg games they distribute viruses, please delete the games you have downloaded from them and do a full scan of your sistem

**Comment by ghost** [comment]
IGG-Games is a website commonly known within the pirating community to contain viruses. Follow what @creeperita09 has said to keep your system clean. Closing as not planned.

**Comment by boomercore** [comment]
I never caught a virus from there.  If you don't feel like doing it it's your show, though.
