### ISSUE TITLE
Add instant bypass to sites which sre eligble

### ISSUE THREAD

**Issue by ccuser44** [FastForwardTeam/FastForward#828]
Currently what Fastforward does that it's bypasses run after the HTML dom has been loaded.

Now for some websites this is unnecessary and redundant (for example because the destination URL can be derived from the middle URL). Infact this is what the bit.ly bypass does, however unfortunately this cannot be used for sny other bypasses.

How this should function that before the browser even makes a connection to the website it's already redirected to the destination.

This would make the user experience much better. Oftentimes there is annoying load times and the intermediate page appears for a few seconds.
It would save unnecessary bandwith usage, not to mention improve privacy and prevent potential malicious javascript from running.

(Now of course this should only be enabled on sites which it can work on and be a feature for custom bypasses)

**Comment by ghost** [comment]
This actually looks like something we could integrate into the MV3 extension, but I think moving this issue to Discussions would allow us to gather feedback and understand how to implement this.
