### ISSUE TITLE
no funciona

### ISSUE THREAD

**Issue by nrgl2002** [FastForwardTeam/FastForward#832]
### Domain

https://m.kongutoday.com/2022/12/best-cloud-hosting-for-wordpress.html#?o=8ef40286975acc976736f54e72b5e4cab1fc1caf9e1296682a31a661ce4d6c08d1813cff64a87eea

### Link

https://m.kongutoday.com/2022/12/best-cloud-hosting-for-wordpress.html#?o=8ef40286975acc976736f54e72b5e4cab1fc1caf9e1296682a31a661ce4d6c08d1813cff64a87eea

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://m.kongutoday.com/2022/12/best-cloud-hosting-for-wordpress.html#?o=8ef40286975acc976736f54e72b5e4cab1fc1caf9e1296682a31a661ce4d6c08d1813cff64a87eea

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
