### ISSUE TITLE
Downloading Bypass definitions takes forever

### ISSUE THREAD

**Issue by heismauri** [FastForwardTeam/FastForward#833]
### Body

When deleting the `injection_script.js` to always receive the latest script it takes forever and it just does not download the update.

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome, Brave

### What OS are you seeing the problem on?

MacOS

### Anything else?

![Screen Shot 2022-12-15 at 11 55 51 AM](https://user-images.githubusercontent.com/47569205/207892858-443633f6-d0b2-4484-8885-6addaed0b7df.png)

**Comment by ghost** [comment]
Known issue, will be fixed in a future release.

**Comment by anzenchitai** [comment]
Version 0.2200.0 and still haven't fixed.

**Comment by ghost** [comment]
We know why this happens (issue with pulling the injection script from Github), but we still don't know how to fix it.
