### ISSUE TITLE
not work with megaurl.in  ( Copyright © megaurl.in 2021 ) 

### ISSUE THREAD

**Issue by sadtango289** [FastForwardTeam/FastForward#834]
### Domain

megaurl.in

### Link

NSFW https://upvideo.to/v/mzpabi5fo0cf/JasmineJ9966_-_Shower_You_With_Love_-_Full_Ver.mp4

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot 2022-12-16 052440](https://user-images.githubusercontent.com/45529026/207980208-b1808e09-107c-440a-9684-fbf5d140b1d5.png)

**Comment by ghost** [comment]
Closed due to website being NSFW
