### ISSUE TITLE
MegaDB refresh issue

### ISSUE THREAD

**Issue by HYDRADOESJS** [FastForwardTeam/FastForward#838]
### Domain

https://megadb.net/

### Link

https://megadb.net/download

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

It keeps refreshing the page over & over.

**Comment by elementt1** [comment]
Hi!
Could you resend a new download link? 
The one you sent is broken. 
Thanks!

**Comment by NekoAlosama** [comment]
Duplicate of #610 (it has a link which demonstrates this)

**Comment by lostdusty** [comment]
Duplicate of #610.
