### ISSUE TITLE
http://www.crazyblog.in

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#84]
### Domain

http://www.crazyblog.in

### Link

http://www.crazyblog.in/?postid=https://cblink.crazyblog.in/c2gkVkED

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TETYYS** [comment]
The link is broken, no button to click, no redirects
