### ISSUE TITLE
Bypass is not working on enit.in

### ISSUE THREAD

**Issue by Bamboozul** [FastForwardTeam/FastForward#844]
### Domain

https://enit.in

### Link

https://enit.in/QEXQV?#

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot 2022-12-27 173718](https://user-images.githubusercontent.com/101983929/209688641-7403fa96-a212-4c2d-b715-5ead71cddc12.png)

**Comment by ghost** [comment]
We do not currently bypass enit.in based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
