### ISSUE TITLE
Bypass is not working on forex-gold.net

### ISSUE THREAD

**Issue by Bamboozul** [FastForwardTeam/FastForward#845]
### Domain

https://try2link.net/

### Link

https://try2link.net/PbDee4U4/

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by ghost** [comment]
Try2link redirects to forex-gold.net, but the issue will stay open because there are websites with the same name that have existing bypasses, so we can just add this site to that specific domain bypass.
