### ISSUE TITLE
not bypassing oko.sh

### ISSUE THREAD

**Issue by gototheskinny** [FastForwardTeam/FastForward#846]
### Domain

oko.sh

### Link

https://oko.sh/iqDHLGD0

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

after r u robot its not bypassing the 10 sec waiting. this link i think could be crowd bypassed i don't know why its not already.

**Comment by ghost** [comment]
We do not currently bypass oko.sh based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
