### ISSUE TITLE
Bypass is not working on exeo.app

### ISSUE THREAD

**Issue by SanujaNS** [FastForwardTeam/FastForward#851]
### Domain

https://exeo.app/

### Link

https://exeo.app/0inKj

### Version

0.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Brave

### What OS are you seeing the problem on?

Linux

### Anything else?

This is previously known as exe.io

**Comment by ghost** [comment]
We do not currently bypass exeo.app based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read #656 for more details.

Once we have finished with the project, you are free to reopen the issue.

**Comment by ghost** [comment]
Duplicate of #769
