### ISSUE TITLE
Please add bypass to fc-lc

### ISSUE THREAD

**Issue by BerserkSoul1989** [FastForwardTeam/FastForward#854]
### Domain

https://fc-lc.com

### Link

https://fc-lc.com/zScs

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Please add bypass function to fc-lc or if you have some tutorial to make my own script it could be really helpful

**Comment by ghost** [comment]
It bypasses for me, you may have been the first person to access the link, leading to you having to wait.
