### ISSUE TITLE
s

### ISSUE THREAD

**Issue by kantoj0** [FastForwardTeam/FastForward#856]
### Domain

https://1shortlink.com/l/KhcDGBx

### Link

https://1shortlink.com/l/KhcDGBx

### Version

0.0.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

s

**Comment by MichaelEpicA** [comment]
Update your version. https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md

**Comment by ghost** [comment]
Working for me, please update your extension. Keep in mind that you may have been the first person to encounter that link, so it may not have bypassed for you.
