### ISSUE TITLE
Create A Bypass For This Site

### ISSUE THREAD

**Issue by gigachaand** [FastForwardTeam/FastForward#859]
### Domain

https://hubcloud.work/drive/4qby1t46ci9ytyv

### Link

https://www-google-com.cdn.ampproject.org/c/s/bloggingvector.com/re/aHR0cHM6Ly93d3ctZ29vZ2xlLWNvbS5jZG4uYW1wcHJvamVjdC5vcmcvYy9zL3RlY2hub3JvemVuLmNvbS9nbz9pZD0zT2ZwM2R5dW9xVFYzdGJXNGR6ZTJLSHMzTnZmb3RuZjB1cllwS0hhMXV5bTRaMnExdDZtNHVqczY2emQ0OTdhMjZiS3Bkam55cm5YcDlHWnBLWFgyTC9vd04rdjJ0aktwcksycDhYSHdyL0pwY3l6MmNEWDRMUFMxOG5nMzd6TDErYTh3TWJNMTluUnBjakpuYVk9

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

None

### Anything else?

![Screenshot_2023-01-09-12-16-22-478_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/96541364/211253577-cc55a3a0-1a06-413d-b1b0-ca2d623bb926.jpg)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
