### ISSUE TITLE
https://sevenjournals.com

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#86]
### Domain

https://sevenjournals.com

### Link

https://sevenjournals.com/?go=QhtWBIC

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
i just get to the 7journals website?
