### ISSUE TITLE
bluemediafile.sbs not working like it used to

### ISSUE THREAD

**Issue by h1ghju1ce** [FastForwardTeam/FastForward#860]
### Domain

bluemediafile.sbs

### Link

https://bluemediafile.sbs/url-generator.php?url=+F30sKVGya5zG++539sIDeknUvP7uCWirMMYS0undWjwizvZTIxdeCQywNXUvAupkYoMa6QvLZJo07Fpj9DKtRJs64+8n32yBxvXjAdzH08=

### Version

Version 0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

there is a 5 second countdown, to the download button

but after that, even clicking the download button doesn't go to the destination , you have to click it about 5-6 times (that opens new AD tabs) THEN it finally goes to the destination site/page

**Comment by lostdusty** [comment]
Should be fixed in #876.
