### ISSUE TITLE
Broken Bypass platinmods.com

### ISSUE THREAD

**Issue by wernser412** [FastForwardTeam/FastForward#863]
### Domain

https://platinmods.com/threads/18-camgirls-inc-nutaku-ver-0-78-mod-apk-menu-cost-energy.152999/

### Link

https://apkadmin.com/e3ismrk8ehhn/camgirls-inc_314_modfix.apk.html

### Version

0.2165.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

**Comment by dhana-exe** [comment]
same
https://apkadmin.com/14aezxpndeza/ML_FREE_NINO_JOKERART_PMT_signed_signed.apk.html
they seems to be looping since they implemented the captcha....
need to fix it

**Comment by ghost** [comment]
> same https://apkadmin.com/14aezxpndeza/ML_FREE_NINO_JOKERART_PMT_signed_signed.apk.html they seems to be looping since they implemented the captcha.... need to fix it

It most likely uses backend verification, so we'd have to resort to a crowd bypass.

However, apkadmin,com is not a site we currently bypass according to [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md). Please read #656 for more information. After we're done with the project, you are free to repoen the issue.
