### ISSUE TITLE
intercelestial not working and exclude segment[REQUEST]

### ISSUE THREAD

**Issue by BedBug2479** [FastForwardTeam/FastForward#864]
### Domain

https://intercelestial.com/

### Link

https://intercelestial.com/evening-star

### Version

0.2025

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

for this site FF removes the timer and continue buttons and I am unable to move forward.

If cannot be fixed plz add an option in the extension to exclude a few custom websites that can be added by us

**Comment by ghost** [comment]
Duplicate of #816
