### ISSUE TITLE
https://faucet.100count.net/clickit

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#87]
### Domain

https://faucet.100count.net

### Link

https://faucet.100count.net/clickit/sh/Ac4Swzw

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### (Optional) Anything else?

https://faucet.100count.net/fo/linko/vXu5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Place in ensureDomLoaded

```js
domainBypass("100count.net", () => {
	awaitElement("button#mdt", a => (a.click()))
	awaitElement("div#cl1", d => (safelyNavigate(d.getElementsByTagName("a")[0].href)))
})
```

**Comment by NotAProton** [comment]
Fixed, thanks for the report
