### ISSUE TITLE
Shrinke Bypass Broken

### ISSUE THREAD

**Issue by NVT223** [FastForwardTeam/FastForward#870]
### Domain

https://shrinke.me

### Link

https://shrinke.me/tk7bCdyJ

### Version

0.2200.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Plz fix that!!!

**Comment by ghost** [comment]
Not directly on [this list of bypassed sites](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), but keeping it open because it seems that it redirects to a domain we already bypass.
