### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'T', "The Redire"... is not valid JSON

### ISSUE THREAD

**Issue by serial02** [FastForwardTeam/FastForward#871]
### Body

Uncaught SyntaxError: Unexpected token 'T', "The Redire"... is not valid JSON
Context
_generated_background_page.html
stack trace
_generated_background_page.html:1 (anonymous function)

### Version

0.2200.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Linux

### Anything else?

Uncaught SyntaxError: Unexpected token 'T', "The Redire"... is not valid JSON
Context
_generated_background_page.html
stack trace
_generated_background_page.html:1 (anonymous function)

**Comment by ghost** [comment]
1. Does uninstalling and reinstalling the extension fix the issue?
2. If 1 doesn't work, would you mind providing more context about when this issue occurs and possible steps to reproduce it?

**Comment by serial02** [comment]
> 1. Desinstalar e reinstalar a extensão corrige o problema?
> 2. Se 1 não funcionar, você se importaria de fornecer mais contexto sobre quando esse problema ocorre e as possíveis etapas para reproduzi-lo?

1. Não
2. Apenas copiei o texto que estava na cx de erros e depois apaguei. Caso apareça novamente irei printar a tela e enviar novamente.
3. Existe um log deixado por esta extensão para que eu possa enviar?

**Comment by lostdusty** [comment]
Tem uma print de onde o erro apareceu?

**Comment by serial02** [comment]
> Tem uma print de onde o erro apareceu?

Hi

 Yes I do, by the way I just updated to version 2201 and it keeps the same error.  But now with some details.  Messages are appearing in Opera browser for Linux Fedora 37

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

> {
>     "manifest_version": 2,
>     "icons": {
>         "48": "icon/48.png",
>         "128": "icon/128.png",
>         "150": "icon/150.png",
>         "176": "icon/176.png",
>         "512": "icon/512.png"
>     },
>     "default_locale": "en",
>     "name": "FastForward",
>     "description": "__MSG_appDesc__",
>     "homepage_url": "https://fastforward.team",
>     "version": "0.2201.0",
>     "author": "FastForward Team",
>     "incognito": "split",
>     "permissions": [
>         "alarms",
>         "storage",
>         "webRequest",
>         "webRequestBlocking",
>         "<all_urls>"
>     ],
>     "options_ui": {
>         "page": "html/options.html",
>         "open_in_tab": true
>     },
>     "browser_action": {
>         "default_icon": {
>             "48": "icon/48.png",
>             "128": "icon/128.png",
>             "150": "icon/150.png",
>             "176": "icon/176.png",
>             "512": "icon/512.png"
>         },
>         "default_popup": "html/popup.html"
>     },
>     "background": {
>         "scripts": [
>             "background.js"
>         ]
>     },
>     "content_scripts": [
>         {
>             "matches": [
>                 "<all_urls>"
>             ],
>             "js": [
>                 "content_script.js"
>             ],
>             "run_at": "document_start"
>         }
>     ],
>     "web_accessible_resources": [
>         "html/before-navigate.html",
>         "html/blocked.html",
>         "html/crowd-bypassed.html",
>         "html/firstrun.html",
>         "html/firstrun-noscript.html",
>         "html/options.html",
>         "icon/48.png"
>     ]
> }
> 

![Captura de tela de 2023-01-28 11-07-13](https://user-images.githubusercontent.com/32621790/215271225-5e0dcded-59ff-412f-a9dc-ef5346bc3855.png)

**Comment by ghost** [comment]
Isso é apenas um aviso e não um erro. Você pode continuar usando a extensão normalmente.

**Comment by lostdusty** [comment]
Pequena curiosidade mas eu sou brasileira, por isso te respondi em português. ^^
