### ISSUE TITLE
New Adfly domain not being bypassed

### ISSUE THREAD

**Issue by MrRorls12** [FastForwardTeam/FastForward#872]
### Domain

oaxyteek.net

### Link

http://bit.ly/S04E41_Star-Wars_1080p

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

It's link this:
I want to download a Phineas and Ferb episode, and I have to go through Adfly. I think it's gonna be "neexulro.net" or something but then, in the bottom left hand corner, I see "oaxyteek". Please help me out.

**Comment by ghost** [comment]
I made a mitigation for this in the MV3 version, but adf.ly changes links constantly, probably as a safeguard against extensions like this. My only solution right now would be to freeze the page since the destination link is in the URL, but I'm unsure of how that would affect the redirection.
