### ISSUE TITLE
streamcheck.link not bypassing

### ISSUE THREAD

**Issue by kuskusxyren** [FastForwardTeam/FastForward#873]
### Domain

streamcheck.link

### Link

https://streamcheck.link/BWi7?sport=basketball

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

this happens when I try to watch a basketball stream

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
