### ISSUE TITLE
ckk.ai don't working

### ISSUE THREAD

**Issue by smileyface24** [FastForwardTeam/FastForward#875]
### Domain

ckk.ai

### Link

https://ckk.ai/ZQSM44d4h3L

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Hello there!

I can't bypass everything on this shorten: Loan2host aka: ckk.ai

Any help is appreciated it.

Thanks.

**Comment by Tenome** [comment]
https://github.com/FastForwardTeam/FastForward/issues/668

**Comment by ghost** [comment]
Duplicate of #668
