### ISSUE TITLE
howifx.com Bypss broken

### ISSUE THREAD

**Issue by Void2258** [FastForwardTeam/FastForward#878]
### Domain

https://howifx.com/

### Link

https://howifx.com/how-do-i-fix-an-unresponsive-iphone-12-screen/#getlink

### Version

Version 0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/6126362/217561493-0f554297-70a4-4921-a1be-7c66b6841932.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
