### ISSUE TITLE
enit.in not bypassed

### ISSUE THREAD

**Issue by Void2258** [FastForwardTeam/FastForward#879]
### Domain

https://enit.in/

### Link

https://enit.in/4gb5gm2?token=bfe05abf9cc0ad12a3feb5279de2faaf55b18d62c33c9dfd4ab4750416cdba82#

### Version

Version 0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/6126362/217561859-b9cbc402-9268-4e52-8d91-53d323753a02.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
