### ISSUE TITLE
https://mcrypto.club

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#88]
### Domain

https://mcrypto.club

### Link

https://mcrypto.club/?link=4HUJ

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
i just get to the mcrypto.club website?
