### ISSUE TITLE
techmody.io not bypassing

### ISSUE THREAD

**Issue by Void2258** [FastForwardTeam/FastForward#880]
### Domain

https://techmody.io/

### Link

https://techmody.io/linux-vs-bsd-everything-you-need-to-know/

### Version

Version 0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/6126362/217582607-43cc0dc6-f09a-4b93-a8e8-849b750b1bb6.png)
![image](https://user-images.githubusercontent.com/6126362/217582654-f272ec02-589b-4b3f-8aa4-e12134b38d69.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
