### ISSUE TITLE
https://mobi2c.com/ outright stops cold with VPN

### ISSUE THREAD

**Issue by Void2258** [FastForwardTeam/FastForward#881]
### Domain

https://mobi2c.com/

### Link

https://mobi2c.com/?p=381&k=aHR0cHM6Ly93b3JsZDJvdXIuY29tLz9wPTc4Jms9YUhSMGNITTZMeTlvWldGc2RHaDVOSEJsY0c5c1pTNWpiMjB2UDNBOU16TTRKbXM5WVVoU01HTklUVFpNZVRrd1kyNXJlV0pIYkhWaGVUVnFZakl3ZGs1c2FIQlVhVGd2V2tRd2VFNXFZekZQVkZsM1RsUlplQ1pzUFUxNU9Ib21aRDFOVkZrelRsUnJNazFFVlRKTlVUMDlKbXhsZG1Wc1BXeGxkbVZzTXc9PSZsPU1pOHomZD1NVFkzTlRrMk1EVTJNUT09JmxldmVsPWxldmVsMw==&l=MS8z&d=MTY3NTk2MDU2MQ==&level=level3#

### Version

Version 0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/6126362/217877098-3bbe5d8c-8960-4b2c-aee1-411e45ea506d.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
