### ISSUE TITLE
https://krnl.place/getkey detects bypass

### ISSUE THREAD

**Issue by Damian-11** [FastForwardTeam/FastForward#884]
### Domain

https://krnl.place

### Link

https://krnl.place/getkey

### Version

0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

The site started detecting after the "please wait 15 seconds so the site won't detect you" feature got added to the extension today. If you wait the 15 seconds like the extension tells you to, it will redirect you and the site detects the bypass. However, if you copy the target link just before the 15 seconds have passed, the site will not detect you.

**Comment by irgjeoirtj** [comment]
The bypass worked fine just before this. If you could maybe reverse the bypass back to the way it used to be done for this website specifically, that would be great.

**Comment by ghost** [comment]
Wontfix: The FastForward developers do not support cheating in games.
