### ISSUE TITLE
Browser Redirects too much

### ISSUE THREAD

**Issue by bruhger12** [FastForwardTeam/FastForward#885]
### Domain

linkvertise.com

### Link

https://linkvertise.com/152666/fluxus-windows-check-1/1

### Version

37fd375 

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

I'm pretty sure its getting detected because its redirecting to your browser site(with the timer before it redirects you to the target site) before it bypasses the site(as in remove the downloads off linkvertise) I think a fix would be to add a switch to turn off redirecting to the browser site.
PS: krnl is doing the same thing aswell

**Comment by ghost** [comment]
Wontfix: The FastForward developers do not condone cheating in games.
