### ISSUE TITLE
ud.toolxox.com

### ISSUE THREAD

**Issue by beakwood** [FastForwardTeam/FastForward#886]
### Domain

ud.toolxox.com

### Link

https://ud.toolxox.com/nmmghgjgjhgjcvbcfbcbcvbfggjhjghjgjhgdfsfrrtryrtaisxmzxvocsdwzzxvbnmdkaoeokgkkgkfkkdkvgndhdhcnnbjgjjkdkskskskffjfjaaal.php?nznmtm=https://toolxox.com/dl/2/dlgrab_1/tmp/grab_im/dl.beatsnoop.com-3000-PY8gjtIWNC.jpg

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

The domain is ud.toolxox.com, but on the website of the timer/countdown, it says 'askingtips'. 

<img width="1340" alt="Screenshot 2023-02-14 155026" src="https://user-images.githubusercontent.com/43938224/218889000-6d5a3f25-fc91-4667-8c09-b7d0e8d16a2a.png">

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
