### ISSUE TITLE
clink1.com: does not bypass countdown and link from yesterday

### ISSUE THREAD

**Issue by gabri25ele** [FastForwardTeam/FastForward#887]
### Domain

clink1.com

### Link

https://www.clink1.com/hz9I

### Version

0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

blocked here, 
![click](https://user-images.githubusercontent.com/33927879/218982655-8ac340e6-6818-4228-a3fc-07c06cb3e0f6.png)

manual click is needed, 
but until two days ago it was bypassed immediately without even waiting for the 10-second countdown

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.

**Comment by gabri25ele** [comment]
currently not, but previously yes.
:-/
