### ISSUE TITLE
Support for mgnetu.com

### ISSUE THREAD

**Issue by namkazt** [FastForwardTeam/FastForward#888]
### Domain

mgnetu.com

### Link

https://mgnetu.com/lMSBO4

### Version

0.2201.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Support for mgnetu.com

**Comment by Sayaniku** [comment]
That aren't an broken-bypass, that normal because you need to click on the green thing when that good

**Comment by namkazt** [comment]
> That aren't an broken-bypass, that normal because you need to click on the green thing when that good

is it supposed to be automatic?

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
