### ISSUE TITLE
linkvertise not working

### ISSUE THREAD

**Issue by LuciferxR** [FastForwardTeam/FastForward#889]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/414000/riini/1

### Version

1

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

please fix asap

**Comment by ghost** [comment]
Works for me, make sure that you follow the [the instructions here](https://github.com/FastForwardTeam/FastForward/wiki/Adding-the-Linkvertise-Custom-Bypass) to make sure that Linkvertise will work.
