### ISSUE TITLE
FastForward break the Douban website

### ISSUE THREAD

**Issue by JinxAgain** [FastForwardTeam/FastForward#890]
### Body

If I turn fastforward on, then I can not commit a comment about movies on Douban

Normally URL like this
https://movie.douban.com/subject/1297737/

But if I turn on and visit a movie that I never opened before
The URL will add extra something (I dont even know how to call it)
https://movie.douban.com/subject/1300106/?from=subject-page

and I can not hit the star button and save the comment.

### Version

0.2212

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Normally
![image](https://user-images.githubusercontent.com/64463709/219950553-24490b06-fa85-4589-a232-52995ecf287e.png)

### Turn on
![image](https://user-images.githubusercontent.com/64463709/219951282-a69d6c77-7177-4fd3-87c1-4db687071223.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
