### ISSUE TITLE
link1s.com bypass not working

### ISSUE THREAD

**Issue by k3lvinmitnick** [FastForwardTeam/FastForward#891]
### Domain

https://link1s.com

### Link

https://link1s.com/AAQiLt

### Version

0.2212

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

link1s.com Pls Add hurry up !
P/S: How to manual add any website that I want ? I saw injection_script.js guide, but I don't see any detail guide, need a Video guide on YouTube

**Comment by ghost** [comment]
We have a wiki which helps with making bypasses, so if you know Javascript, you could make your own bypass.

**Comment by ghost** [comment]
You are welcome to make your own bypass @k3lvinmitnick, but we will not make it at the moment; check #656 for more details.

**Comment by NotAProton** [comment]
https://github.com/bogachenko/fuckfuckadblock

**Comment by NotAProton** [comment]
see #40

**Comment by ghost** [comment]
Duplicate of #40
