### ISSUE TITLE
sieuthuthuat.com

### ISSUE THREAD

**Issue by phatnt634** [FastForwardTeam/FastForward#892]
### Domain

https://sieuthuthuat.com/

### Link

https://redirect.sieuthuthuat.com/2022/05/playing-pokemon-go-game-helps-relieve.html#?o=d4a101e5607ada137de7ba18f76db629e7af5495c9c508f769e68408c48ee770534c41eedd065f464d13a6738caa65a475bd198aa00282f1

### Version

0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

https://prnt.sc/mRbQ0ZE_uKJ8
https://prnt.sc/V4dlHYQK4tMx

**Comment by ghost** [comment]
We don't bypass this site currently, check #656 for more details.
