### ISSUE TITLE
Deferer.me not working

### ISSUE THREAD

**Issue by digitaldelboy** [FastForwardTeam/FastForward#893]
### Domain

http://www.thetvdb.com

### Link

https://dereferer.me/?http://www.thetvdb.com/?tab=series&id=395029

### Version

0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

It does actually bypass the problem is that it jumps straight to the homepage (https://thetvdb.com/) instead of the correct url.

**Comment by undeadjess** [comment]
fixed, thanks for reporting!
