### ISSUE TITLE
Linvertise link issue

### ISSUE THREAD

**Issue by rololo88** [FastForwardTeam/FastForward#895]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/profile/621022

### Version

0.2212

### What browsers are you seeing the problem on?

Brave, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Only link on this page (login10) doesn't work other works.

**Comment by lostdusty** [comment]
Could you provide more information? Like screenshots.

**Comment by undeadjess** [comment]
This is a linkvertise profile, not a shortened link, so it does not have a destination. if the other links on your page "login10" work, this is just a dead link, if not you may have to [add the custom linkvertise bypass](https://github.com/FastForwardTeam/FastForward/wiki/Adding-the-Linkvertise-Custom-Bypass)
