### ISSUE TITLE
Bypass Fail

### ISSUE THREAD

**Issue by Cosm-o** [FastForwardTeam/FastForward#896]
### Domain

linktervise.com

### Link

https://file-link.net/129289/V2USTP2

### Version

0.2212

### What browsers are you seeing the problem on?

Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/114190046/222918942-e2728308-161c-446a-be05-3b691b4cafb7.png)

**Comment by lostdusty** [comment]
Have you added the custom linkvertise bypass?

**Comment by Cosm-o** [comment]
On Wed, Mar 8, 2023 at 2:07 PM Princess Mortix ***@***.***>
wrote:

> Have you added the custom linkvertise bypass?
>
im a unsure but i have found a new website that gives me the link for media
fire so i’m good but thank you
