### ISSUE TITLE
Viralfeed.xyz

### ISSUE THREAD

**Issue by XriTW** [FastForwardTeam/FastForward#897]
### Domain

https://https://viralfeed.xyz/

### Link

https://viralfeed.xyz/top-7-ways-the-medicinal-world-has-been-influenced-by-technology/

### Version

0.2212

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

no lo bypaseea ;c

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
