### ISSUE TITLE
comohoy.com (ExternalLink) not working

### ISSUE THREAD

**Issue by aetherjyan** [FastForwardTeam/FastForward#898]
### Domain

https://comohoy.com/

### Link

https://comohoy.com/grab/out.html?url=aHR0cHM6Ly9jdXR5LmlvL1E3Nk9BVDQ=

### Version

0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

The website is full of ads and pop-ups everywhere, very annoying to access to the destination link.
The "real" name of the service seems to be External Link

![image](https://user-images.githubusercontent.com/124942756/222924761-b9d9e95a-4e23-4878-8246-a76ed2787011.png)

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
