### ISSUE TITLE
https://porofly.xyz

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#90]
### Domain

https://porofly.xyz

### Link

https://porofly.xyz/kW6XZy

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kammychan** [comment]
Below code is working for MoroFly, PoroFly, WoroFly, ZoroFly, Fameen, Gameen, Yameen
```js

domainBypass("adsy.pw",()=>{
	ifElement("button",b=>b.click())
	ifElement("a[href*='shortlinks']",safelyAssign)
	ifElement("a[href*='checksl']",safelyAssign)
})
domainBypass("girls-like.me",()=>{
	awaitElement("form>input[name='shorted']",i=>safelyAssign(i.value))
})
domainBypass("yalla-shoot-now.us",()=>{
	awaitElement("form>input[name='shorted']",i=>safelyAssign(i.value))
})
```

**Comment by reashetyrr** [comment]
this gives me a very tall website with a gif of how to supposedly continue without anythink to click
