### ISSUE TITLE
megadropz.com no longer working

### ISSUE THREAD

**Issue by upsetllama16** [FastForwardTeam/FastForward#901]
### Domain

megadropz.com

### Link

https://megadropz.com/s?ug8 NSFW

### Version

0.2201.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

None

### Anything else?

It used to work but doesn't anymore

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
