### ISSUE TITLE
Shorte.st bypass does not work (never worked for me)

### ISSUE THREAD

**Issue by HGStyle** [FastForwardTeam/FastForward#902]
### Domain

https://shorte.st

### Link

http://sh.st/wVGYZ

### Version

be2f32f

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

I tried the test link from the official FastForward website (https://fastforward.team/example-links) and the Shorte.St does not work. Can anyone explain me why or tell me a solution please ?

**Comment by lostdusty** [comment]
Duplicate of #227
