### ISSUE TITLE
Once it tries to bypass, it just says that it skipped countdown

### ISSUE THREAD

**Issue by Veki34** [FastForwardTeam/FastForward#903]
### Domain

https://megadb.net/

### Link

https://megadb.net/download

### Version

0.2039

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot_5](https://user-images.githubusercontent.com/110414283/223441175-8ce4f269-189f-4ea6-960f-a8af67c98060.png)

**Comment by lostdusty** [comment]
Duplicate of #610.
