### ISSUE TITLE
Megadb.net

### ISSUE THREAD

**Issue by Felzow47** [FastForwardTeam/FastForward#904]
### Domain

https://megadb.net

### Link

https://megadb.net/download

### Version

0.2159.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://user-images.githubusercontent.com/49567056/224113905-827d935a-cea0-4901-9f9f-998e33e0107a.mp4

**Comment by USLTD** [comment]
Duplicate of #610

**Comment by UltraStudioLTD** [comment]
Duplicate of #610

**Comment by ghost** [comment]
> Duplicate of #610

Closing this, please have all discussion there.
