### ISSUE TITLE
Rocklinks.net not redirect properly

### ISSUE THREAD

**Issue by thanioruvanben10** [FastForwardTeam/FastForward#908]
### Domain

rocklinks.net

### Link

https://rocklinks.net/1pLCZf

### Version

Latest

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Android

### Anything else?

Just ad few modifications to the script

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
