### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND Glitch

### ISSUE THREAD

**Issue by Princeton25** [FastForwardTeam/FastForward#910]
### Domain

https://filedm.com/GpvWg
### Link

https://fastforward.team/

### Version

Newest

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

So for some reason, fastforward won't work entirely and there was this problem that said Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by ghost** [comment]
Works on my end, try uninstalling and reinstalling FastForward.

**Comment by Princeton25** [comment]
It wont work.
