### ISSUE TITLE
will not bypass this web.

### ISSUE THREAD

**Issue by afat123** [FastForwardTeam/FastForward#911]
### Domain

https://tii.la/

### Link

https://tii.la/KpO60N7

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

it will not automatically directs to the destination website

**Comment by Tenome** [comment]
Same.

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
