### ISSUE TITLE
Why does fastward in Firefox stick to old version 0.1946

### ISSUE THREAD

**Issue by serial02** [FastForwardTeam/FastForward#912]
### Domain

https://www.google.com.br/

### Link

https://www.google.com.br/

### Version

0.1946

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

Olá pessoal

Hey guys

 Why does Firefox have version 0.1946, while on the official page the application available has FastForward version 0.2219?

![Captura de tela de 2023-03-20 08-44-49](https://user-images.githubusercontent.com/32621790/226330504-b382b401-927e-4994-8892-b3c326f36ed5.png)

**Comment by lostdusty** [comment]
Olá :wave:,
O Firefox suspendeu a nossa extensão temporariamente, mas em breve ela voltará a ser atualizada na loja de extensões do Firefox.

A extensão, mesmo em uma versão antiga, vai funcionar corretamente, ja que o script para pular os sites é obtido pelo Github, e é atualizado automaticamente.

**Comment by gh0sti** [comment]
@princessmortix why did FF remove the extension? Same response as Google? 
¿Por qué FF eliminó la extensión? ¿Misma respuesta que Google?

**Comment by cRu572Vltn** [comment]
> O Firefox suspendeu a nossa extensão temporariamente, mas em breve ela voltará a ser atualizada na loja de extensões do Firefox.

Yeah, well, it's been deleted for more than 4 days and it's still not back in the addon shop. I don't think that's exactly "_soon_". I have the same doubt as gh0sti.

**Comment by ghost** [comment]
Firefox is not a fan of the auto-updating script because (according the them) it's code not bundled within the extension, which isn't exactly allowed under their guidelines. The hypocrisy is that extensions like uBO have similar designs and are still on there.

**Comment by serial02** [comment]
It is not being allowed to install the extension manually on FF, as described on the website:

https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#troubleshooting

See attached error message:

![Captura de tela de 2023-03-24 12-55-48](https://user-images.githubusercontent.com/32621790/227577647-8e7d5cc1-388a-418c-b885-72ec5e18fe7c.png)

**Comment by ghost** [comment]
Firefox does not allow unsigned extensions; you can use Firefox Nightly or Developer Edition until we fix the issue with Mozilla.
