### ISSUE TITLE
Cannot Bypass

### ISSUE THREAD

**Issue by The-Ellimst-17** [FastForwardTeam/FastForward#914]
### Domain

https://fc-lc.com/

### Link

https://fc-lc.com/eB61M

### Version

0.2086

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![Untitled 2](https://user-images.githubusercontent.com/128522036/226708854-7ac31d75-ebbe-45e5-b942-52915236e445.png)
![Untitled](https://user-images.githubusercontent.com/128522036/226708864-1ffcfa44-5a64-4161-8b68-dc6a513cc47d.png)

**Comment by The-Ellimst-17** [comment]
Often redirects to a blank page.

**Comment by ghost** [comment]
Duplicate of #861
