### ISSUE TITLE
FileCR.com

### ISSUE THREAD

**Issue by zekecarter** [FastForwardTeam/FastForward#915]
### Domain

https://filecr.com

### Link

https://filecr.com/windows/yamicsoft-windows10manager?id=231266165184

### Version

N/A

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

the web page loads fine but when we click on direct download it shows a message that we must disable adblock, can you add a bypass to prevent that from happening and take us to the download page?

I hope you can help us

https://user-images.githubusercontent.com/83554130/227072366-ac66ba4b-e21e-4c43-952c-7636ba60c6c6.mp4

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
