### ISSUE TITLE
bakenor.com not working

### ISSUE THREAD

**Issue by GauravMohla** [FastForwardTeam/FastForward#917]
### Domain

https://bakenor.com/

### Link

https://bakenor.com/what-is-the-best-health-insurance-for-senior-citizens/

### Version

0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/12412497/227696712-d145e168-5caf-4682-b683-28d8d546cb65.png)

**Comment by undeadjess** [comment]
Do you know where you got this like from? could you give me a link to that website?

**Comment by ghost** [comment]
This is not something that FastForward can bypass. Try using an adblocker to remove the elements that are blocking the page.

**Comment by NotAProton** [comment]
use https://github.com/bogachenko/fuckfuckadblock
