### ISSUE TITLE
Linkvertise bypass doesnt work.

### ISSUE THREAD

**Issue by coreknee** [FastForwardTeam/FastForward#918]
### Domain

https://linkvertise.com/

### Link

https://linkvertise.com/152666/fluxus-windows-check-1/2

### Version

 0.2221

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Does not even try to bypass. it seems like it doesnt see the link.

**Comment by undeadjess** [comment]
This appears to be a detection system of something called "fluxus". Do you know what that is?

The linkvertise bypass is still working fine.

**Comment by ghost** [comment]
As Fluxus is a cheating tool and because the FF developers do not support cheating in video games, we will not provide support.

**Comment by ghost** [comment]
As fluxus is a cheating tool and because the FF developers don't support cheating in video games, we will not provide support.
