### ISSUE TITLE
FastForward breaks if you disable and enable it again

### ISSUE THREAD

**Issue by kevin01523** [FastForwardTeam/FastForward#919]
### Body

Fastforward seems to break randomly as in the warning that a link has not been visited doesn't appear or wont even forward links and the downloading bypass definitions would be stuck at that status
the only way i found to make it consistent was to disable it and re enable it and it breaks 

![image](https://user-images.githubusercontent.com/8380242/227759527-7eeaa261-eb9c-40fe-a684-9b3be0f19aee.png)
this has happened before and it only works without error earlier when the there was  a crx auto update when FF was still not on the store 

im using chrome right now

also just noticed                 did firefox just nuke the add on from the store i swear i still managed to install it few days ago

### Version

2222

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

n/a

**Comment by ghost** [comment]
Usually uninstalling and reinstalling the extension fixes most of these issues.
