### ISSUE TITLE
Loan to host not working

### ISSUE THREAD

**Issue by Johanfer12** [FastForwardTeam/FastForward#922]
### Domain

https://tii.la/

### Link

https://tii.la/ProTools12Full

### Version

 0.2086

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

Keeps saying I'm the first using the link, and I opened it multiple times

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.

We're pretty close to finish, so you won't need to wait long.
