### ISSUE TITLE
Crowd bypass blocked by edge

### ISSUE THREAD

**Issue by Xenos4th** [FastForwardTeam/FastForward#923]
### Body

Crowd Bypass blocked by microsoft page in exe.io

### Version

0.2086 ·

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/113509256/228098768-58b04a6a-a097-43cd-94be-eb38a9e647a7.png)

**Comment by kevin01523** [comment]
its not only edge its all chromium my kiwi browser also shows this
and it was the only version of FF that was stable for me and reliably use crowd bypass or bypass some shortlinks

**Comment by kevin01523** [comment]
not sure but this might be a similar case as the edge version is  an older build over a year ago
https://stackoverflow.com/questions/68038854/chrome-blocking-redirect-to-extension-page 

![image](https://user-images.githubusercontent.com/8380242/229956283-d28d47c2-f018-4059-afd6-5e816f44e007.png)
after messing with the manifest file i guess just a bit more

**Comment by Xenos4th** [comment]
Still not working in Microsoft Edge
Version 112.0.1722.48

**Comment by kevin01523** [comment]
> Still not working in Microsoft Edge Version 112.0.1722.48

i think the extention is not updated on edge store
