### ISSUE TITLE
Add infoBox method to let people know that we don't bypass cheating sites

### ISSUE THREAD

**Issue by NotAProton** [FastForwardTeam/FastForward#926]
We definitely should use the infoBox method to let people know that we don't bypass this website because it's video game cheating,

_Originally posted by @0xc60f in https://github.com/FastForwardTeam/FastForward/pull/921#discussion_r1151354672_

**Comment by Apep-the-snek** [comment]
I smell forks where it bypasses to cheating sites. Weird how it allows pirating sites (which is what i use it for lol) but not cheating, when cheating software isn't really even illegal, lol.

**Comment by NotAProton** [comment]
Feel free to fork :)

**Comment by ghost** [comment]
Closing this since we changed our stance: we will not develop fixes to these sites, but we will accept changes that someone else makes.
