### ISSUE TITLE
the extension makes some sites go blank

### ISSUE THREAD

**Issue by vhtNov17** [FastForwardTeam/FastForward#935]
### Body

example: https://genshin.hoyoverse.com/en/, https://frzyc.github.io/genshin-optimizer/

i tried disabling all my extensions (except for FF) then accessed those sites and saw no problem. reloading helps but not always

### Version

0.2224 

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/81290839/229447833-045b2590-8365-44e7-bd12-129dd7369bd5.png)

**Comment by NotAProton** [comment]
Can you reproduce this with the mv3 version? https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3

**Comment by vhtNov17** [comment]
yes no problem. take a look!

normal version:
https://user-images.githubusercontent.com/81290839/229681982-1ecdc68e-3816-4dbd-8563-8e396c4f5766.mp4

mv3 version:
https://user-images.githubusercontent.com/81290839/229682067-48c394fd-ed36-4401-b2b2-dae92a5415e2.mp4

the version you gave me works flawlessly

**Comment by ghost** [comment]
> yes no problem. take a look!
> 
> normal version: https://user-images.githubusercontent.com/81290839/229681982-1ecdc68e-3816-4dbd-8563-8e396c4f5766.mp4
> 
> mv3 version: https://user-images.githubusercontent.com/81290839/229682067-48c394fd-ed36-4401-b2b2-dae92a5415e2.mp4
> 
> the version you gave me works flawlessly

If that's the case, I'm going to close this as completed. We're close to finishing the MV3 version of the extension, so there's not a reason to fix a soon-to-be-deprecated version if the updated version works fine.
