### ISSUE TITLE
1link.vip broken bypass

### ISSUE THREAD

**Issue by Allusionsss** [FastForwardTeam/FastForward#936]
### Domain

1link.vip

### Version

0.2157.0

### What browsers are you seeing the problem on?

Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/105530085/229527210-71ef4624-1dee-4cc5-b0b8-fe7385a31b11.png)

**Comment by Allusionsss** [comment]
Issue solved by disable crowd bypass

**Comment by NotAProton** [comment]
duplicate of #923
