### ISSUE TITLE
Bypass not working in acortalink

### ISSUE THREAD

**Issue by C6548** [FastForwardTeam/FastForward#946]
### Domain

https://acortalink.me/

### Link

https://acortalink.me/s.php?i=VTJGc2RHVmtYMThmQWV6c2czWENUNk5QL0NuRmxxVHZhWUsrK1phUUJTWmZhajFPamVac3hNSTdkejFVSnZXUEVRTUkxTWlLUnVmRVNFRzNQdm5sOW5NaUwrMlV1VGIyR2I2ZEZ1MXd1Mld5Zk53SDdvbml1QW9tdGZxakFqdWRCbzhPcnpXV3JiN1VWNUF3UGlRVDBBPT0=

### Version

0.2230

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

I was trying to use fastfoward to skip acortalink in hackstore.re, it was working at  the first times but for some reason stopped working and it is not skipping the url.

**Comment by yagovago2** [comment]
Second that!
