### ISSUE TITLE
I can't manually install the .XPI file using the provided instructions.

### ISSUE THREAD

**Issue by Apep-the-snek** [FastForwardTeam/FastForward#947]
### Body

xpinstall.signatures.required pref does not work, i manually added it to prefs.js using a user.js and user-overrides.js, i checked that it was set to false in about:config with bold text, indicating it is set to a non-default value. when i try to either click on install addon from file or drag the properly extracted .xpi file from my file system, it gives off the same error saying that it doesn't allow unsigned addons as it always did. i suppose this is an issue with firefox and not with fast forward, but the instructions shouldn't be promoting something that does not work either.

### Version

https://nightly.link/FastForwardTeam/FastForward/workflows/main/main/FastForward_firefox.zip

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Linux

### Anything else?

no that's all, idk why i HAVE to write something here, when there is a Body right over....

**Comment by Tenome** [comment]
Vanilla Firefox doesn't allow unsigned. You have to use Developer or Nightly Edition (which the instructions explicitly say).

**Comment by SpaceMageWhatever** [comment]
try this one, i downloaded it from the firefox store
 https://www.mediafire.com/file/t6buj51h07g7bu1/addon%2540fastforward.team.xpi/file

**Comment by NotAProton** [comment]
See https://github.com/FastForwardTeam/FastForward/releases/tag/0.2237
