### ISSUE TITLE
https://topcryptoz.net

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#95]
### Domain

https://topcryptoz.net

### Link

https://topcryptoz.net/?link=2lE9R

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
this is just leading to a rickroll
