### ISSUE TITLE
Turns it self Off

### ISSUE THREAD

**Issue by Reqon** [FastForwardTeam/FastForward#950]
### Body

Title says it all whenever i restard my pc and open chrome addon is turned off 

### Version

0.2224

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

nope

**Comment by dhana-exe** [comment]
i had this issue also....

**Comment by ghost** [comment]
Make sure you follow the instructions exactly on [our installation page](https://fastforward.team/instructions).
