### ISSUE TITLE
Bypass not working on The Sims Resource

### ISSUE THREAD

**Issue by ramsestone** [FastForwardTeam/FastForward#961]
### Domain

thesimsresource.com

### Link

https://www.thesimsresource.com/downloads/thankyou/id/1609148

### Version

0.2025

### What browsers are you seeing the problem on?

Opera

### What OS are you seeing the problem on?

Windows

### Anything else?

All download links are behind a 15 secs countdown.

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
