### ISSUE TITLE
Linkvertise bypass

### ISSUE THREAD

**Issue by SadlekAski** [FastForwardTeam/FastForward#963]
### Domain

https://linkvertise.com

### Link

https://linkvertise.com/256968/soul-cultivation-gui1/1

### Version

0.2249

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

it takes me to there 
![image](https://user-images.githubusercontent.com/129619951/233123027-62e3501c-4018-4fc7-86f1-724286dc406d.png)
when it bypasses

**Comment by Grohax** [comment]
I'm having the same problem with Linkvertise. Just used it days ago and was fine.
I'm using version 0.2251 on Edge/Windows.

**Comment by NotAProton** [comment]
I cannot reproduce the issue, it seems to bypass it just fine. Try clearing you cookies

**Comment by SadlekAski** [comment]
> I cannot reproduce the issue, it seems to bypass it just fine. Try clearing you cookies

ok I'll try

**Comment by SadlekAski** [comment]
> I cannot reproduce the issue, it seems to bypass it just fine. Try clearing you cookies

My fastforward deleted itself second time already (at first time I installed it, it was bypassing normally)

**Comment by lostdusty** [comment]
I could reproduce
@0xc60f add your PR here.

**Comment by SadlekAski** [comment]
Who and what's PR

**Comment by The420Boss** [comment]
What is this?????

**Comment by ghost** [comment]
> I could reproduce
> 
> @0xc60f add your PR here.

Once I get back on Discord I will, shit blew over IRL and I'm having some trouble with my peers.

**Comment by lostdusty** [comment]
No more Linkvertise bypass.
