### ISSUE TITLE
Bypass dont work on megaup (NSFW)

### ISSUE THREAD

**Issue by Manidarean5** [FastForwardTeam/FastForward#965]
### Domain

https://megaup.net

### Link

https://megaup.net

### Version

Last

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Anything

**Comment by NotAProton** [comment]
Please provide an example link

**Comment by Manidarean5** [comment]
Example link: https://megaup.net/1TAzt/The_bot.png
but when i wait: https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbeswkcyY8BAN%2BwO2I0DGIPkOSdArt%2Bnk0DNkgT1vgbt%2BolX%2FcKYgLNoasii3YQX0Oq4zGpDA0iZ%2BnmmQzQaGZYPk%3D&idfilename=The+bot.png&idfilesize=35.00+KB
