### ISSUE TITLE
Bypass not working on work.ink

### ISSUE THREAD

**Issue by ExperimentalDiva00000001** [FastForwardTeam/FastForward#967]
### Domain

Work.ink

### Link

https://work.ink/1jn/zosamuraiv1

### Version

0.2025

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://user-images.githubusercontent.com/131543228/233794201-7ecc002a-292e-47c4-b8c8-c36612be20a4.png)

**Comment by NotAProton** [comment]
can you reproduce this with the mv3 version https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3 ?

**Comment by ghost** [comment]
We have a working bypass, but we are deciding how to implement it so that it will not be patched again.

**Comment by Vojtak42** [comment]
Any news?😇
