### ISSUE TITLE
Stops working after a few days

### ISSUE THREAD

**Issue by pruebark9** [FastForwardTeam/FastForward#968]
### Domain

ouo.io

### Link

ouo.io

### Version

0.2256

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Whenever I install it, it works without problems for the first few days, but after the second or third day it stops working. When I go to the extension options, it always comes out like this and the only solution is to reinstall it again.

![Captura de pantalla (82)](https://user-images.githubusercontent.com/92517051/233808358-5afc6954-6caf-4592-85a2-49845dad2f88.png)

**Comment by sus2790** [comment]
same

**Comment by pruebark9** [comment]
It has stopped working again and now I get the following error in the chrome extensions log


Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details

{
	"manifest_version": 2,
	"icons": {
		"48": "icon/48.png",
		"128": "icon/128.png",
		"150": "icon/150.png",
		"176": "icon/176.png",
		"512": "icon/512.png"
	},
	"default_locale": "en",
	"name": "FastForward",
	"description": "__MSG_appDesc__",
	"homepage_url": "https://fastforward.team",
  "version": "0.2256",
	"author": "FastForward Team",
	"incognito": "split",
	"permissions": [
		"alarms",
		"storage",
		"webRequest",
		"webRequestBlocking",
		"<all_urls>"
	],
	"options_ui": {
		"page": "html/options.html",
		"open_in_tab": true
	},
	"browser_action": {
		"default_icon": {
			"48": "icon/48.png",
			"128": "icon/128.png",
			"150": "icon/150.png",
			"176": "icon/176.png",
			"512": "icon/512.png"
		},
		"default_popup": "html/popup.html"
	},
	"background": {
		"scripts": [
			"background.js"
		]
	},
	"content_scripts": [
		{
			"matches": [
				"<all_urls>"
			],
			"js": [
				"content_script.js"
			],
			"run_at": "document_start"
		}
	],
	"web_accessible_resources": [
		"html/before-navigate.html",
		"html/blocked.html",
		"html/crowd-bypassed.html",
		"html/firstrun.html",
		"html/firstrun-noscript.html",
		"html/options.html",
		"icon/48.png"
	]
}

**Comment by darthvorr** [comment]
For me, the extension seems to get removed automatically every few days, too.

**Comment by ghost** [comment]
#999
