### ISSUE TITLE
https://uniqueten.net

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#97]
### Domain

https://uniqueten.net

### Link

https://uniqueten.net/?link=KXNyT5

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by reashetyrr** [comment]
this is just leading to a rickroll
