### ISSUE TITLE
Cannot install extension in firefox

### ISSUE THREAD

**Issue by rezadk56** [FastForwardTeam/FastForward#971]
### Body

I've switched the value in config from true to false, but i still cannot install the extensions (see my ss), how can it happen? any solution?

### Version

FastForward_firefox_0.2256

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot_1](https://user-images.githubusercontent.com/65821032/233845626-5e3b56bb-54b8-489c-bbe5-a9a7c04468c1.png)

**Comment by AppTesterMC** [comment]
I am confirming this happens to me too.

### Version
FastForward_firefox_0.2256
### What browsers are you seeing the problem on?
Firefox 112.0.1 (64-bit)
### What OS are you seeing the problem on?
Windows 10

**Comment by Write** [comment]
Hello,

You can only install unsigned extension on ESR, Nightly and Dev version of Firefox as stated [here](https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md#troubleshooting)

![Screenshot du 2023-04-25 à 15 00 01](https://user-images.githubusercontent.com/541722/234284079-17f0438b-a62d-4de2-9347-1a56dc6c9baf.png)

However, you can install the one from the [release](https://github.com/FastForwardTeam/FastForward/releases) page, click on the "**Assets**" dropdown to reveal "**FastForward_Firefox**". If you click on it, Firefox will finally ask you if you want to install it.

![Screenshot du 2023-04-25 à 15 01 11](https://user-images.githubusercontent.com/541722/234284589-cd54097f-1dd9-4cad-8447-15e38d3cedfc.png)


Have a great day.

**Comment by NotAProton** [comment]
Thanks @Write
