### ISSUE TITLE
WebSite https://suaurl.com

### ISSUE THREAD

**Issue by NicMarco12** [FastForwardTeam/FastForward#973]
### Domain

https://suaurl.com

### Link

https://suaurl.com/LastTokyoRevengersRP

### Version

Version 0.2256

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Not working in https://suaurl.com

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
