### ISSUE TITLE
clicksfly.com and shrinkearn.com bypass broken

### ISSUE THREAD

**Issue by zekecarter** [FastForwardTeam/FastForward#976]
### Domain

clicksfly.com

shrinkearn.com

### Link

https://clicksfly.com/st?api=9a5ce7425d5bcd40f9fa14870c4184e9cb63a31d&url=http://mwpaste.com/index.php?v=jPX

https://shrinkearn.com/st?api=e504d153c7a3baa895093ff41aa947915db0b6e2&url=http://mwpaste.com/index.php?v=jPX

### Version

0.2161.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

these web pages redirect to web pages that have a lot of captchas and countdowns

https://user-images.githubusercontent.com/83554130/235057645-d0f5147e-5e5d-4a20-8021-a450de4c8b07.mp4

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.

**Comment by artiomborovinskii** [comment]
echo "aHR0cHM6Ly9tZWdhLm56L2ZpbGUvWmRoeEJSaEojVUVZU1dSQXdRclJhZm93ckFDM2lKRDlKVVlKU1dJZ3RJcDFlOHliZ20xcw==" | base64 -s    base64: invalid option -- 's'                                     Try 'base64 --help' for more information.
   ~ echo "aHR0cHM6Ly9tZWdhLm56L2ZpbGUvWmRoeEJSaEojVUVZU1dSQXdRclJhZm93ckFDM2lKRDlKVVlKU1dJZ3RJcDFlOHliZ20xcw==" | base64 -d
https://mega.nz/file/ZdhxBRhJ#UEYSWRAwQrRafowrAC3iJD9JUYJSWIgtIp1e8ybgm1s%                                                             ~ https://shrinkearn.com/full\?api\=00ca8e6e4054c7078d72481fc3b69790035f9b86\&url\=aHR0cHM6Ly9tZWdhLm56L2ZpbGUvWmRoeEJSaEojVUVZU1dSQXdRclJhZm93ckFDM2lKRDlKVVlKU1dJZ3RJcDFlOHliZ20xcw\=\=\&type\=2
