### ISSUE TITLE
disheye/rocklinks bypass is misbehaving

### ISSUE THREAD

**Issue by astaadleo** [FastForwardTeam/FastForward#977]
### Domain

toonworld4all.me

### Link

https://toonworld4all.me/redirect/main.php?url=KSwycP1PDamlOYL0VQUIzTamU87rLu+wxVokmN3y2DRGfTP0WWlcVLm6CXk7

### Version

0.2256

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

I don't know exactly whether it is disheye link or rocklinks one. So please do check and make it possible to bypass through your extention. I'm leaving a link as an example so that you can check why bypass is misbehaving. TYSM

https://toonworld4all.me/redirect/main.php?url=KSwycP1PDamlOYL0VQUIzTamU87rLu+wxVokmN3y2DRGfTP0WWlcVLm6CXk7

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
