### ISSUE TITLE
will not bypass this website

### ISSUE THREAD

**Issue by afat123** [FastForwardTeam/FastForward#979]
### Domain

https://aoutoqw.xyz

### Link

https://aoutoqw.xyz/landing-page/?fbclid2=111

### Version

0.1992 

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

will not bypass that web, at all.

**Comment by ghost** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
