### ISSUE TITLE
https://blog.bshopme.site

### ISSUE THREAD

**Issue by oq1u7o5f14** [FastForwardTeam/FastForward#98]
### Domain

https://blog.bshopme.site

### Link

https://blog.bshopme.site/?link=rDQrwpg6n

### Version

0.0.0

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
Fixed, thanks for the report
