### ISSUE TITLE
cshort link on main website

### ISSUE THREAD

**Issue by kylr1516** [FastForwardTeam/FastForward#980]
### Domain

cshort.org

### Link

https://cshort.org/LPMNEEqK

### Version

0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

it shows the actual countdown that you need to wait 10 seconds

**Comment by ghost** [comment]
It redirected after 2 seconds for me.
