### ISSUE TITLE
Cannot update version

### ISSUE THREAD

**Issue by Kats132** [FastForwardTeam/FastForward#981]
### Body

can not update code

### Version

 0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

![Screenshot 2023-05-02 202948](https://user-images.githubusercontent.com/93334061/235681246-448798eb-d7b9-453c-a98e-0ffec80abe70.png)

**Comment by eks28** [comment]
Same here

**Comment by ghost** [comment]
#999
