### ISSUE TITLE
some websites STILL go blank :/

### ISSUE THREAD

**Issue by vhtNov17** [FastForwardTeam/FastForward#982]
### Body

old problem. help! see video below :)

### Version

0.2256 

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://user-images.githubusercontent.com/81290839/236107146-d5234278-9f3b-4d25-94a0-4bb5b50ef721.mp4

**Comment by mashirochan** [comment]
I have the same issue on Firefox 113.0.1 (64-bit) on Windows 10. It won't let me access my Keeper password vault, it just loads a blank white page like in the video.

**Comment by ghost** [comment]
Can you reproduce this with the [mv3 version](https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3)?

**Comment by vhtNov17** [comment]
ive tested with the version you gave me. the site works so well. i remember the last time we did this, the problem went away when using the beta version but still happened to the released versions. i hope u guys could find a solution soon. ty

https://github.com/FastForwardTeam/FastForward/assets/81290839/71c9a9f1-340f-47c3-9e84-0a338e5e279c
