### ISSUE TITLE
Linkvertise not being bypassed

### ISSUE THREAD

**Issue by Dictator6938** [FastForwardTeam/FastForward#985]
### Domain

linkvertise.com

### Link

https://linkvertise.com/

### Version

idk

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

When downloading mods specifically Minecraft, fast forward should be able to bypass linkvertise

**Comment by NotAProton** [comment]
Duplicate of #963
