### ISSUE TITLE
Libbyapp.com 

### ISSUE THREAD

**Issue by sammytoesis** [FastForwardTeam/FastForward#987]
### Domain

https://libbyapp.com

### Link

https://libbyapp.com/?repair=1683644233029

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

![image](https://github.com/FastForwardTeam/FastForward/assets/68130102/9663470e-74d9-4458-845a-0b507d439dd5)
Image of the particular issue. Turning off the extension has the redirect work without a hitch. 

![image](https://github.com/FastForwardTeam/FastForward/assets/68130102/94dfa97d-6e1c-4b72-a532-c3e366a1838a)
Example of the settings I have enabled.

**Comment by ghost** [comment]
I have Libby and didn't have this issue, this doesn't seem like an issue on our end; as suggested in your screenshot, try contacting Libby.
