### ISSUE TITLE
ouo.io Infinit Loop

### ISSUE THREAD

**Issue by Skates1616** [FastForwardTeam/FastForward#989]
### Domain

https://ouo.io/

### Link

https://ouo.io/Tl6E77

### Version

0.0.8

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

https://github.com/FastForwardTeam/FastForward/assets/23196661/58c271b5-0242-45b8-ba58-c9d05a88cf3a

**Comment by ghost** [comment]
Can you reproduce this with the [mv3 version](https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3)?

**Comment by Taimuna** [comment]
Have the same problem with ouo.io

**Comment by Tenome** [comment]
I tried OP's link and it worked as intended on mv3 Firefox.

**Comment by ghost** [comment]
> I tried OP's link and it worked as intended on mv3 Firefox.

Closed since working on Mv3
