### ISSUE TITLE
Cannot login onto medium.com

### ISSUE THREAD

**Issue by Obspogon** [FastForwardTeam/FastForward#990]
### Domain

https://medium.com

### Link

https://medium.com/m/signin

### Version

0.1992

### What browsers are you seeing the problem on?

Firefox

### What OS are you seeing the problem on?

Windows

### Anything else?

Anywhere I signin i get logged out and get sent to the homepage. Twitter login gives an error. Google signin logs me in, then out again.

**Comment by NotAProton** [comment]
can you reproduce this with the [mv3 version](https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3)?

**Comment by ghost** [comment]
Closing since OP hasn't responded.
