### ISSUE TITLE
[NSFW]: link1s hasn't bypassed yet.

### ISSUE THREAD

**Issue by MankMeo** [FastForwardTeam/FastForward#992]
### Domain

Web1s

### Link

https://web1s.info/squirt3

### Version

 0.2251

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you seeing the problem on?

Windows

### Anything else?

I think link1s(.com, info) hasn't bypassed yet. Is it an issue? Can you also help me to add websites manually? I really want to add more website by my own in the future :<

**Comment by ghost** [comment]
You can use [our wiki](https://github.com/FastForwardTeam/FastForward/wiki) to learn how to make bypasses for the extension.

However, we do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
