### ISSUE TITLE
work.ink bypasser isn't working

### ISSUE THREAD

**Issue by ddenis0** [FastForwardTeam/FastForward#993]
### Domain

https://work.ink

### Link

https://work.ink/38Z/New-DW-Job-AutoFarm

### Version

Version 0.2256

### What browsers are you seeing the problem on?

Brave

### What OS are you seeing the problem on?

Windows

### Anything else?

I don't think this needs more reasoning...

**Comment by ghost** [comment]
Duplicate of #967
