### ISSUE TITLE
Broken Bypass

### ISSUE THREAD

**Issue by Gialong2107** [FastForwardTeam/FastForward#994]
### Domain

https://www.haymod.top/2023/02/key-lien-quan-all-sever.html

### Link

https://mneylink.com/1qslamm

### Version

0.2256

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Anything else?

Broken Bypass

**Comment by 0xc60f** [comment]
We do not currently bypass this site based on [this list](https://github.com/FastForwardTeam/FastForward/blob/manifest-v3/Bypassed.md), please read https://github.com/FastForwardTeam/FastForward/issues/656 for more details.

Once we have finished with the project, you are free to reopen the issue.
